import type { StrandhootPack } from "../engine/types"

export const balanceCritA: StrandhootPack = {
  slug: "balance-crit-a",
  title: "Chemical Balance & Equations",
  subject: "MYP Chemistry",
  criterion: "A",
  topic: "Balancing equations & equilibrium",
  accent: "#1b7888",
  icon: "⚖️",
  statementOfInquiry: "Imbalanced relationships affect finite resources, both locally and globally.",
  estMinutes: 25,
  intro:
    "Master the language of chemistry — from reading formulae and state symbols to balancing equations and applying Le Chatelier's principle. Each strand targets a core concept from Chapter 1: Balance, levelling up from recall to analysis.",
  badges: [
    { id: "formula", label: "Formula Fluent", icon: "🔣", description: "Reach Level 8 on Chemical formulae", strandId: "formulae", atLevel: 8 },
    { id: "balancer", label: "Equation Balancer", icon: "⚖️", description: "Reach Level 8 on Balancing equations", strandId: "balancing", atLevel: 8 },
    { id: "equilib", label: "Equilibrium Expert", icon: "🔁", description: "Reach Level 8 on Chemical equilibrium", strandId: "equilibrium", atLevel: 8 },
    { id: "master", label: "Chemistry Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 1: Balance", blurb: "Formulae, equations, equilibrium and Le Chatelier", icon: "⚗️" }],
  strands: [
    {
      id: "formulae",
      name: "Chemical formulae & state symbols",
      descriptor: "Read and interpret chemical formulae, subscripts and state symbols.",
      guided: [
        { level: 2, body: "H₂O is the formula for water — the subscript 2 means two hydrogen atoms bonded to one oxygen. State symbols (s), (l), (g), (aq) describe the physical state of each substance in a reaction." },
        { level: 4, body: "Subscripts show the ratio of atoms. H₂SO₄ contains 2 H, 1 S, and 4 O atoms. The state symbol (aq) means dissolved in water. Brackets matter: Ca(OH)₂ has 2 OH groups — one Ca, two O, and two H atoms." },
        { level: 6, body: "H₂O₂ (hydrogen peroxide) and H₂O (water) both contain H and O but have very different subscripts and completely different properties. The formula encodes both composition and connectivity. Changing a subscript creates a different substance — you can never 'fix' an unbalanced equation by altering subscripts." },
        { level: 8, body: "In Fe₂O₃, the 2:3 Fe:O ratio tells you each Fe must have an oxidation state of +3 (iron(III)) to balance the charge of O²⁻. Compare FeO (iron(II), +2 state): entirely different stability and reactivity. The formula is the compressed record of both atomic composition and oxidation state, and changing it changes the substance entirely." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "f-l2",
            level: 2,
            prompt: "What does the subscript 2 in H₂O represent?",
            options: [
              { id: "a", text: "Two oxygen atoms" },
              { id: "b", text: "Two hydrogen atoms", correct: true },
              { id: "c", text: "Two water molecules" },
              { id: "d", text: "The charge on the molecule" },
            ],
            explanation: "The subscript 2 follows H, so it applies to hydrogen: two hydrogen atoms are bonded to one oxygen atom.",
          },
          {
            type: "fill",
            id: "f-l4",
            level: 4,
            prompt: "The state symbol for a substance dissolved in water is ▁.",
            answers: ["(aq)", "aq"],
            explanation: "From the Latin 'aqua' (water), (aq) means the substance is dissolved in water — an aqueous solution.",
          },
          {
            type: "short",
            id: "f-l6",
            level: 6,
            prompt: "Explain the difference between H₂O and H₂O₂. What do the subscripts tell us about the atoms in each molecule?",
            keywords: ["subscript", "atoms", "oxygen", "hydrogen", "two", "peroxide", "ratio", "different"],
            minKeywords: 3,
            sample: "H₂O has 2 hydrogen atoms and 1 oxygen atom; H₂O₂ has 2 hydrogen and 2 oxygen atoms. The different subscripts show a different ratio of atoms, producing completely different compounds — water and hydrogen peroxide — with very different properties.",
          },
          {
            type: "short",
            id: "f-l8",
            level: 8,
            prompt: "Iron forms two oxides: FeO and Fe₂O₃. Explain what each formula reveals about the oxidation state of iron, and why a chemist cannot simply change a subscript to 'balance' an equation.",
            keywords: ["oxidation", "state", "iron(ii)", "iron(iii)", "electrons", "ratio", "different", "subscript", "formula", "identity"],
            minKeywords: 3,
            sample: "In FeO, iron has oxidation state +2 (iron(II)) — each Fe loses 2 electrons to bond with O²⁻. In Fe₂O₃, iron is +3 (iron(III)), losing 3 electrons. Changing a subscript changes the substance itself — FeO and Fe₂O₃ are different compounds with different properties. To balance an equation, only coefficients (numbers in front of formulae) can be changed.",
          },
        ],
      },
    },
    {
      id: "balancing",
      name: "Balancing chemical equations",
      descriptor: "Apply the law of conservation of mass to balance equations using coefficients.",
      guided: [
        { level: 2, body: "A balanced equation has the same number of atoms of each element on both sides. We add coefficients (whole numbers in front of formulae) to balance — we never change subscripts. The law of conservation of mass states that matter cannot be created or destroyed." },
        { level: 4, body: "Balancing rule: do the metal element first, then elements in only one formula, then the rest. For Fe(s) + O₂(g) → Fe₂O₃(s): balance Fe first (need 4 Fe on left since 2Fe₂O₃ has 4 Fe), then O (3O₂ gives 6 O = 2Fe₂O₃). Result: 4Fe(s) + 3O₂(g) → 2Fe₂O₃(s)." },
        { level: 6, body: "Haber process: N₂(g) + H₂(g) → NH₃(g). Step 1 — N: 1 N₂ gives 2 N, so need 2 NH₃ on right. Step 2 — H: 2 NH₃ has 6 H atoms, need 3 H₂ on left. Balanced: N₂(g) + 3H₂(g) → 2NH₃(g). Check: 2N, 6H on each side. ✓" },
        { level: 8, body: "Methane combustion: CH₄(g) + O₂(g) → CO₂(g) + H₂O(g). Balance C (1 each, done), H (4 left → 2H₂O right), O (2+1=3 right → need 1.5 O₂). Multiply all by 2 to clear fraction: CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(g). Check: 1C, 4H, 4O each side. ✓ Fractional coefficients are valid intermediate steps; always clear fractions in the final answer." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "b-l2",
            level: 2,
            prompt: "What does a balanced chemical equation guarantee?",
            options: [
              { id: "a", text: "The same number of atoms of each element on both sides", correct: true },
              { id: "b", text: "The same number of compounds on each side" },
              { id: "c", text: "The same energy on each side" },
              { id: "d", text: "The same physical states on each side" },
            ],
            explanation: "Conservation of mass requires the same number of atoms of each element on both sides. Coefficients achieve this without altering the formulae.",
          },
          {
            type: "fill",
            id: "b-l4",
            level: 4,
            prompt: "To balance Fe(s) + O₂(g) → Fe₂O₃(s), the coefficient of Fe on the left is ▁.",
            answers: ["4"],
            explanation: "4Fe(s) + 3O₂(g) → 2Fe₂O₃(s). Balance Fe first: 2Fe₂O₃ contains 4 Fe atoms, so we need 4 Fe on the left. Then balance O: 2Fe₂O₃ has 6 O atoms → 3 O₂ on the left.",
          },
          {
            type: "short",
            id: "b-l6",
            level: 6,
            prompt: "Balance the Haber process equation: N₂(g) + H₂(g) → NH₃(g). Show your reasoning step by step.",
            keywords: ["n2", "3h2", "2nh3", "nitrogen", "hydrogen", "ammonia", "coefficients", "atoms", "balanced"],
            minKeywords: 3,
            sample: "Balance N: N₂ gives 2 N atoms, so need 2 NH₃ on the right. Balance H: 2 NH₃ contains 6 H atoms, so need 3 H₂ on the left. Balanced: N₂(g) + 3H₂(g) → 2NH₃(g). Check: 2N, 6H on each side. ✓",
          },
          {
            type: "short",
            id: "b-l8",
            level: 8,
            prompt: "Balance the methane combustion equation: CH₄(g) + O₂(g) → CO₂(g) + H₂O(g). Show full working and explain why subscripts cannot be used to balance equations.",
            keywords: ["2o2", "2h2o", "balanced", "subscripts", "formula", "conservation", "identity", "coefficient", "atoms"],
            minKeywords: 3,
            sample: "Balance C (1 each, done), H (4→2H₂O), O (need 4 O right → 2O₂ left). Balanced: CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(g). Check: 1C, 4H, 4O each side. ✓ Subscripts cannot be changed because changing a subscript changes the identity of the substance (H₂O₃ is not water). Only coefficients can be adjusted while preserving conservation of mass.",
          },
        ],
      },
    },
    {
      id: "equilibrium",
      name: "Chemical equilibrium",
      descriptor: "Describe and explain dynamic equilibrium in reversible reactions.",
      guided: [
        { level: 2, body: "Some reactions are reversible — they can go forwards and backwards. The symbol ⇌ shows a reversible reaction. At equilibrium, both the forward and reverse reactions are still occurring, but no overall change is visible." },
        { level: 4, body: "At dynamic equilibrium: (1) forward and reverse reaction rates are equal, (2) concentrations of reactants and products are constant (not necessarily equal), (3) the reaction appears static but is not — it is dynamic (still occurring in both directions) in a closed system." },
        { level: 6, body: "The equilibrium constant Kc gives the ratio of product to reactant concentrations at equilibrium. For N₂ + 3H₂ ⇌ 2NH₃: Kc = [NH₃]² / ([N₂][H₂]³). A large Kc means products are favoured; a small Kc means reactants are favoured. Kc only changes with temperature." },
        { level: 8, body: "Kc is temperature-dependent only — changing concentration or pressure shifts the equilibrium position but leaves Kc unchanged at constant temperature. If Kc decreases as temperature rises, the forward reaction must be exothermic (Le Chatelier: adding heat shifts equilibrium left, opposing the change). This principle connects the numerical value of Kc to the thermodynamics of the reaction." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "e-l2",
            level: 2,
            prompt: "In a reversible reaction at equilibrium, which statement is correct?",
            options: [
              { id: "a", text: "Both forward and reverse reactions have stopped" },
              { id: "b", text: "Only the forward reaction is occurring" },
              { id: "c", text: "The forward and reverse reaction rates are equal", correct: true },
              { id: "d", text: "The concentrations of reactants and products are equal to each other" },
            ],
            explanation: "At dynamic equilibrium, both reactions still occur at equal rates. The concentrations stay constant — but they are not necessarily equal to each other.",
          },
          {
            type: "fill",
            id: "e-l4",
            level: 4,
            prompt: "At dynamic equilibrium, the concentrations of reactants and products remain ▁, even though the reaction is still occurring in both directions.",
            answers: ["constant", "unchanged", "the same"],
            explanation: "The forward and reverse rates are equal, so concentrations stop changing and remain constant — but the system is dynamic (still reacting in both directions).",
          },
          {
            type: "short",
            id: "e-l6",
            level: 6,
            prompt: "Explain what is meant by 'dynamic equilibrium'. Why is it described as both 'dynamic' and 'equilibrium'?",
            keywords: ["forward", "reverse", "rate", "equal", "concentration", "constant", "dynamic", "occurring", "both"],
            minKeywords: 3,
            sample: "Dynamic equilibrium means the forward and reverse reactions are both occurring at equal rates — 'dynamic' because reactions are still happening. 'Equilibrium' because the concentrations of reactants and products remain constant with no net change. The system appears static from the outside but molecules are continuously reacting in both directions.",
          },
          {
            type: "short",
            id: "e-l8",
            level: 8,
            prompt: "The equilibrium constant Kc for N₂(g) + 3H₂(g) ⇌ 2NH₃(g) decreases as temperature increases. What does this tell you about the enthalpy change of the forward reaction? Use Le Chatelier's principle to justify your answer.",
            keywords: ["exothermic", "decreases", "temperature", "le chatelier", "forward", "enthalpy", "reverse", "favoured", "heat"],
            minKeywords: 3,
            sample: "A decreasing Kc with rising temperature means the equilibrium shifts left at higher temperatures. By Le Chatelier's principle, the system opposes the added heat — the endothermic reverse reaction is favoured. Therefore the forward reaction (N₂ + 3H₂ → 2NH₃) must be exothermic (ΔH < 0). This matches the known value of ΔH = −92 kJ mol⁻¹.",
          },
        ],
      },
    },
    {
      id: "lechatelier",
      name: "Le Chatelier's principle",
      descriptor: "Predict how temperature, pressure and concentration changes shift an equilibrium.",
      guided: [
        { level: 2, body: "Le Chatelier's principle: if a system at equilibrium is disturbed, it shifts to oppose the change and restore balance. Adding more reactant → the equilibrium shifts right, producing more product." },
        { level: 4, body: "For N₂(g) + 3H₂(g) ⇌ 2NH₃(g) (exothermic): increase [N₂] or [H₂] → shift right (more NH₃); remove NH₃ → shift right; increase pressure → shift toward fewer moles of gas (right: 2 mol vs 4 mol) → more NH₃; increase temperature → shift left (reverse is endothermic) → less NH₃, Kc decreases." },
        { level: 6, body: "Pressure only affects gas-phase equilibria. Moles comparison: 1N₂ + 3H₂ = 4 mol gas on left; 2NH₃ = 2 mol gas on right. Higher pressure → fewer moles side favoured → right shift → more yield. A catalyst speeds up both reactions equally — it does not change equilibrium position or Kc, only the time to reach equilibrium." },
        { level: 8, body: "Industrial compromise: thermodynamically, very low T and very high P give the highest yield. But low T gives an unacceptably slow rate even with an iron catalyst. High P (>200 atm) requires expensive, energy-intensive equipment. The Haber process uses ~450°C (sufficient rate) and ~200 atm (economic optimum): yield ≈ 15%, with unreacted N₂/H₂ recycled. Kc is unchanged by pressure or catalyst — only temperature moves it." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "lc-l2",
            level: 2,
            prompt: "According to Le Chatelier's principle, what happens when more reactant is added to a system at equilibrium?",
            options: [
              { id: "a", text: "The equilibrium shifts to the left" },
              { id: "b", text: "The equilibrium shifts to the right, making more product", correct: true },
              { id: "c", text: "The equilibrium constant Kc increases" },
              { id: "d", text: "The reaction stops until the extra reactant is used up" },
            ],
            explanation: "Adding reactant disturbs the equilibrium. The system opposes this by consuming the extra reactant — shifting right toward products. Kc itself does not change.",
          },
          {
            type: "fill",
            id: "lc-l4",
            level: 4,
            prompt: "In the exothermic Haber process N₂(g) + 3H₂(g) ⇌ 2NH₃(g), increasing the temperature shifts the equilibrium to the ▁, decreasing the yield of ammonia.",
            answers: ["left", "left-hand side", "reverse side"],
            explanation: "The forward reaction is exothermic. Adding heat is like adding a product of the forward reaction. Le Chatelier's principle predicts the reverse (endothermic) reaction is favoured — left shift, Kc decreases.",
          },
          {
            type: "short",
            id: "lc-l6",
            level: 6,
            prompt: "Explain why increasing pressure in the Haber process increases the yield of ammonia. Compare the moles of gas on each side.",
            keywords: ["moles", "gas", "fewer", "pressure", "forward", "shift", "4 mol", "2 mol", "le chatelier", "right"],
            minKeywords: 3,
            sample: "In N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the reactant side has 4 moles of gas and the product side has 2 moles. By Le Chatelier's principle, increasing pressure shifts the equilibrium toward the side with fewer moles of gas — the right (product) side. More NH₃ is produced, increasing yield.",
          },
          {
            type: "short",
            id: "lc-l8",
            level: 8,
            prompt: "The Haber process uses ~450°C and ~200 atm. Thermodynamically, lower temperature and higher pressure give greater yield. Explain why these more extreme conditions are not used industrially.",
            keywords: ["rate", "slow", "catalyst", "compromise", "yield", "economic", "pressure", "energy", "cost", "recycle", "450"],
            minKeywords: 4,
            sample: "Lower temperature gives higher yield (exothermic reaction favours products at low T) but makes the rate too slow to be economical, even with an iron catalyst. Higher pressure (above 200 atm) would increase yield further but requires expensive high-pressure equipment and consumes much more energy — the cost outweighs the benefit. 450°C and 200 atm represent an industrial compromise: acceptable rate and yield, with unused N₂ and H₂ recycled to improve overall efficiency.",
          },
        ],
      },
    },
  ],
}
