import type { StrandhootPack } from "../engine/types"

export const cellStructureCritA: StrandhootPack = {
  slug: "cell-structure-crit-a",
  title: "Cell Structure & Classification",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Organelles, tissues and taxonomy",
  accent: "#1b7888",
  icon: "🔬",
  statementOfInquiry: "Relationships between organisms are revealed by similarities and differences between the myriad of forms.",
  estMinutes: 25,
  intro:
    "From the organelles inside a single cell to the kingdoms of life, Form in biology is about understanding structure and its relationship to function. Each strand levels up from recall to analysis — covering organelles, prokaryote vs eukaryote cells, levels of organisation, and the classification of living things.",
  badges: [
    { id: "organelle", label: "Organelle Expert", icon: "🔬", description: "Reach Level 8 on Cell organelles", strandId: "organelles", atLevel: 8 },
    { id: "prokaryote", label: "Cell Classifier", icon: "🦠", description: "Reach Level 8 on Prokaryote vs eukaryote", strandId: "prokaryote", atLevel: 8 },
    { id: "taxonomy", label: "Taxonomy Master", icon: "🌳", description: "Reach Level 8 on Classification", strandId: "classification", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 3: Form", blurb: "Organelles, cell types, levels of organisation, and taxonomy", icon: "🔬" }],
  strands: [
    {
      id: "organelles",
      name: "Cell organelles",
      descriptor: "Identify and explain the function of key organelles in animal and plant cells.",
      guided: [
        { level: 2, body: "All cells contain a nucleus (contains DNA, controls the cell), mitochondria (release energy by aerobic respiration, producing ATP), ribosomes (make proteins), and a cell membrane (controls what enters and leaves). Plant cells additionally have a cell wall (made of cellulose for support) and chloroplasts (for photosynthesis)." },
        { level: 4, body: "The nucleus controls all cell activities because it contains DNA — the instructions for making proteins. Mitochondria carry out aerobic respiration: glucose + oxygen → CO₂ + water + ATP energy. Ribosomes are tiny structures attached to rough endoplasmic reticulum (RER) or free in the cytoplasm; they assemble amino acids into proteins using mRNA instructions. The cell membrane is selectively permeable — it allows some molecules through but not others." },
        { level: 6, body: "Plant cells have three structures absent from animal cells: (1) a rigid cellulose cell wall outside the membrane — gives shape and prevents the cell bursting; (2) chloroplasts — contain the green pigment chlorophyll and carry out photosynthesis; (3) a large central vacuole — contains cell sap, maintains turgor pressure which keeps the plant upright. Some plant cells also contain amyloplasts, colourless plastids that store starch (e.g. in potato tubers)." },
        { level: 8, body: "Form and function are tightly linked: the mitochondrion's double membrane (inner membrane folded into cristae) dramatically increases surface area for ATP synthesis via the electron transport chain — the more active the cell, the more mitochondria it has (e.g. cardiac muscle cells have >5 000). Chloroplasts similarly have stacked thylakoid membranes (grana) to maximise light-harvesting surface area. The endoplasmic reticulum network connects nucleus to cell membrane, enabling coordinated protein and lipid transport. Every ultrastructural feature directly reflects its specific biochemical function." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "org-l2",
            level: 2,
            prompt: "Which organelle is responsible for protein synthesis in all living cells?",
            options: [
              { id: "a", text: "Nucleus" },
              { id: "b", text: "Mitochondria" },
              { id: "c", text: "Ribosome", correct: true },
              { id: "d", text: "Chloroplast" },
            ],
            explanation: "Ribosomes are the sites of protein synthesis in all living cells. They read mRNA instructions from the nucleus and assemble amino acids into proteins.",
          },
          {
            type: "fill",
            id: "org-l4",
            level: 4,
            prompt: "The cell membrane is described as selectively ▁ because it controls which substances enter and leave the cell.",
            answers: ["permeable", "semi-permeable", "semipermeable"],
            explanation: "Selective permeability means the cell membrane allows some molecules through (e.g. oxygen, glucose) while preventing others from passing. This is essential for controlling the cell's internal environment.",
          },
          {
            type: "short",
            id: "org-l6",
            level: 6,
            prompt: "Explain three ways in which a plant cell differs from an animal cell. For each difference, describe the function of the additional structure.",
            keywords: ["cell wall", "cellulose", "chloroplast", "photosynthesis", "vacuole", "turgor", "support", "pressure", "chlorophyll", "plant"],
            minKeywords: 2,
            sample: "Plant cells have: (1) a cell wall made of cellulose — provides rigid support and prevents the cell from bursting by osmosis; (2) chloroplasts containing chlorophyll — carry out photosynthesis to convert light energy into glucose; (3) a large central vacuole filled with cell sap — maintains turgor pressure which keeps the plant upright. Animal cells lack all three structures.",
          },
          {
            type: "short",
            id: "org-l8",
            level: 8,
            prompt: "Explain how the internal structure of the mitochondrion is adapted to maximise ATP production. Why do cells with high energy demands have more mitochondria?",
            keywords: ["cristae", "inner membrane", "surface area", "atp", "electron transport", "aerobic respiration", "energy", "folded", "cardiac", "active"],
            minKeywords: 3,
            sample: "The mitochondrion has a double membrane; the inner membrane is folded into cristae, dramatically increasing surface area for the enzymes and proteins of the electron transport chain (ETC). A larger surface area allows more ATP synthase complexes to operate simultaneously, increasing ATP production rate. Cells with high energy demands (e.g. cardiac muscle, liver cells, sperm cells) have hundreds to thousands of mitochondria to meet their ATP requirements. This is a clear example of how organelle ultrastructure is directly adapted to cellular function.",
          },
        ],
      },
    },
    {
      id: "prokaryote",
      name: "Prokaryote vs eukaryote",
      descriptor: "Compare the structural features of prokaryotic and eukaryotic cells.",
      guided: [
        { level: 2, body: "Prokaryotic cells (e.g. bacteria) are smaller and simpler than eukaryotic cells (e.g. animal, plant, fungal cells). The key difference: prokaryotes do NOT have a nucleus — their DNA is free in the cytoplasm. Eukaryotes have a true nucleus surrounded by a nuclear membrane." },
        { level: 4, body: "Prokaryotes: no nucleus, no membrane-bound organelles, circular DNA (not in chromosomes), 70S ribosomes, cell wall made of peptidoglycan (not cellulose), size ~1–10 μm. Eukaryotes: true nucleus with nuclear envelope, membrane-bound organelles (mitochondria, ER, Golgi), linear chromosomes in the nucleus, 80S ribosomes, size ~10–100 μm. Both types have ribosomes and a cell membrane." },
        { level: 6, body: "The size difference has consequences: bacteria with diameter ~1 μm have a very high surface-area-to-volume ratio, allowing rapid absorption of nutrients. Eukaryotic cells (~10–100 μm) are larger and compartmentalise reactions in different organelles — mitochondria for respiration, rough ER for protein synthesis, Golgi for packaging. The 70S vs 80S ribosome difference is clinically important: antibiotics like streptomycin target 70S ribosomes specifically, killing bacteria without harming human (80S) cells." },
        { level: 8, body: "The endosymbiotic theory (Lynn Margulis, 1967) proposes that mitochondria and chloroplasts originated as free-living prokaryotes engulfed by ancestral eukaryotic cells. Evidence: mitochondria and chloroplasts have their own circular DNA (like bacteria), their own 70S ribosomes, divide by binary fission (not mitosis), and have double membranes (outer from engulfment, inner from the original prokaryote). This evolutionary link between prokaryote and eukaryote cell types is supported by DNA sequence evidence — mitochondrial DNA is most similar to α-proteobacteria." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "pro-l2",
            level: 2,
            prompt: "Which feature is found in prokaryotic cells but NOT in eukaryotic cells?",
            options: [
              { id: "a", text: "Cell membrane" },
              { id: "b", text: "Ribosomes" },
              { id: "c", text: "Circular DNA with no nuclear membrane", correct: true },
              { id: "d", text: "Cytoplasm" },
            ],
            explanation: "Prokaryotes have circular DNA floating freely in the cytoplasm — there is no nucleus or nuclear membrane. Eukaryotes have linear chromosomes enclosed within a nuclear envelope.",
          },
          {
            type: "fill",
            id: "pro-l4",
            level: 4,
            prompt: "Prokaryotic cells have ▁ ribosomes, while eukaryotic cells have 80S ribosomes. This difference is exploited by antibiotics that target bacteria without harming human cells.",
            answers: ["70S", "70s"],
            explanation: "The 70S vs 80S ribosome difference is clinically important. Antibiotics such as streptomycin and erythromycin target 70S ribosomes in bacteria, selectively killing them without affecting human cells which use 80S ribosomes.",
          },
          {
            type: "short",
            id: "pro-l6",
            level: 6,
            prompt: "Compare the cell wall composition of prokaryotes and plant cells. Why is this difference clinically significant?",
            keywords: ["peptidoglycan", "cellulose", "bacteria", "plant", "cell wall", "antibiotic", "target", "different", "composition"],
            minKeywords: 2,
            sample: "Prokaryote (bacterial) cell walls are made of peptidoglycan, a mesh-like polymer unique to bacteria. Plant cell walls are made of cellulose, a polysaccharide. This compositional difference is clinically significant: antibiotics such as penicillin target peptidoglycan synthesis enzymes, destroying the bacterial cell wall without affecting plant or animal cells, which do not use peptidoglycan. This selectivity is what makes such antibiotics safe for humans.",
          },
          {
            type: "short",
            id: "pro-l8",
            level: 8,
            prompt: "Describe the evidence that supports the endosymbiotic theory for the origin of mitochondria. What does this tell us about the evolutionary relationship between prokaryotes and eukaryotes?",
            keywords: ["circular dna", "70s ribosomes", "binary fission", "double membrane", "endosymbiosis", "margulis", "prokaryote", "alpha-proteobacteria", "evidence", "evolutionary"],
            minKeywords: 3,
            sample: "The endosymbiotic theory proposes mitochondria were once free-living bacteria engulfed by ancestral eukaryotes. Evidence: (1) mitochondria have their own circular DNA, similar to bacteria; (2) they have 70S ribosomes, not the 80S type found in the eukaryotic cytoplasm; (3) they divide by binary fission independently of the cell cycle; (4) they have a double membrane — the outer from the phagocytic vesicle, the inner from the original bacterium. Sequence analysis shows mitochondrial DNA is most similar to α-proteobacteria. This reveals that eukaryotes evolved in part by incorporating prokaryotes, blurring the boundary between the two cell types.",
          },
        ],
      },
    },
    {
      id: "organisation",
      name: "Levels of organisation",
      descriptor: "Describe the hierarchy of biological organisation and explain cell specialisation.",
      guided: [
        { level: 2, body: "Living things are organised from smallest to largest: cell → tissue → organ → organ system → organism. Example: epithelial cell → epithelial tissue → stomach → digestive system → human. Each level is built from the level below it." },
        { level: 4, body: "A tissue is a group of similar cells working together. An organ is made of different tissues working together. An organ system is several organs that cooperate. Example: red blood cells form blood tissue (with plasma, platelets, white blood cells) → blood, heart, vessels form the circulatory system → all systems make up the organism. Each level has emergent properties not present at lower levels." },
        { level: 6, body: "Cell specialisation means cells develop specific structures to carry out specific functions efficiently. Red blood cells: biconcave shape maximises surface area; no nucleus — more space for haemoglobin (Hb) molecules to carry oxygen; contain ~270 million Hb molecules each. Root hair cells: long extensions increase surface area for absorbing water and mineral ions from soil. Both cells start from a fertilised egg with identical DNA — gene expression differences determine their final form." },
        { level: 8, body: "Differentiation is controlled by differential gene expression — all cells contain the same DNA but only specific genes are switched on in each cell type. Stem cells (undifferentiated) can give rise to multiple cell types; their differentiation is triggered by chemical signals (morphogens, hormones, transcription factors). The level of organisation at which a function is performed determines its efficiency: diffusion alone suffices for single cells, but multicellular organisms need circulatory, respiratory, and digestive systems to supply cells deep in their tissues — this is why organisation levels themselves are an evolutionary adaptation." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "org2-l2",
            level: 2,
            prompt: "Which correctly shows the order of levels of organisation from smallest to largest?",
            options: [
              { id: "a", text: "Organ → tissue → cell → organ system → organism" },
              { id: "b", text: "Cell → tissue → organ → organ system → organism", correct: true },
              { id: "c", text: "Tissue → cell → organ → organism → organ system" },
              { id: "d", text: "Cell → organ → tissue → organism → organ system" },
            ],
            explanation: "The correct hierarchy is cell → tissue → organ → organ system → organism. Each level is composed of the level below, with increasing complexity and emergent properties.",
          },
          {
            type: "fill",
            id: "org2-l4",
            level: 4,
            prompt: "Red blood cells have no ▁, which allows them to contain more haemoglobin and carry more oxygen.",
            answers: ["nucleus", "nuclei"],
            explanation: "During development, red blood cells lose their nucleus (and mitochondria). This adaptation provides extra space for haemoglobin molecules — each red blood cell can carry approximately 270 million haemoglobin molecules, maximising its oxygen-carrying capacity.",
          },
          {
            type: "short",
            id: "org2-l6",
            level: 6,
            prompt: "Compare how red blood cells and root hair cells are each specialised for their function. What structural features allow each cell to work efficiently?",
            keywords: ["biconcave", "haemoglobin", "surface area", "nucleus", "root hair", "extension", "absorption", "water", "ions", "oxygen"],
            minKeywords: 2,
            sample: "Red blood cells: biconcave disc shape increases surface area for gas exchange; no nucleus means more space for haemoglobin molecules to carry oxygen; lack of mitochondria means they do not consume the oxygen they carry. Root hair cells: long, thin hair-like extensions dramatically increase the surface area in contact with soil water; this maximises absorption of water by osmosis and mineral ions by active transport. Both specialisations are the result of differential gene expression from the same DNA.",
          },
          {
            type: "short",
            id: "org2-l8",
            level: 8,
            prompt: "Explain why multicellular organisms need organised systems (tissues, organs) when single-celled organisms survive without them. Link your answer to diffusion distances and surface-area-to-volume ratio.",
            keywords: ["diffusion", "surface area", "volume", "ratio", "distance", "multicellular", "circulatory", "oxygen", "nutrients", "organisation"],
            minKeywords: 3,
            sample: "Single-celled organisms are small enough that oxygen, nutrients, and waste can diffuse to and from all parts of the cell quickly — the short diffusion distance and high surface-area-to-volume ratio make specialised transport systems unnecessary. As organisms grow, volume increases faster than surface area (SA:V ratio decreases), so diffusion alone cannot supply inner cells with oxygen and nutrients fast enough. Multicellular organisms therefore evolved hierarchical organisation — circulatory systems to transport substances, respiratory systems for gas exchange, digestive systems to absorb nutrients — to overcome the diffusion distance problem. Each level of organisation exists because it solves a transport or function problem that cannot be solved at the cellular level alone.",
          },
        ],
      },
    },
    {
      id: "classification",
      name: "Classification",
      descriptor: "Describe the principles of biological classification and construct dichotomous keys.",
      guided: [
        { level: 2, body: "Classification groups living things by similarities. The main groups from largest to smallest are: Kingdom → Phylum → Class → Order → Family → Genus → Species. A memory tool: 'King Philip Came Over For Good Soup.' Every species has a two-part scientific name — binomial nomenclature — written in Latin (e.g. Homo sapiens)." },
        { level: 4, body: "There are 5 kingdoms: Animalia (multicellular, no cell wall, heterotrophic), Plantae (multicellular, cellulose cell wall, photosynthetic), Fungi (cell wall of chitin, decomposers, e.g. mushrooms), Protoctista (mainly unicellular eukaryotes, e.g. Amoeba, Euglena), Prokaryotae (bacteria, no nucleus, e.g. Escherichia coli). Binomial nomenclature: genus capitalised, species lowercase, both in italics (e.g. Homo sapiens)." },
        { level: 6, body: "Dichotomous keys are identification tools: at each step, two mutually exclusive options lead to the next step or to an organism's name. They use observable features. Phylogenetic trees show evolutionary relationships (relatedness) based on shared characteristics — and increasingly on DNA evidence. Two organisms sharing more DNA sequences are more closely related. The three-domain system (Archaea, Bacteria, Eukarya) has largely replaced the 5-kingdom system in modern biology, based on molecular evidence." },
        { level: 8, body: "Traditional morphological classification (by form) can mislead — dolphins look like fish but are classified as mammals (Mammalia) because they share derived characteristics: warm-blooded, breathe air, give birth to live young, produce milk. DNA and molecular phylogenetics have revolutionised classification by revealing evolutionary relationships invisible to the naked eye. For example, fungi are now known to be more closely related to animals than to plants. The species concept itself is problematic: the biological species concept (reproductive isolation) breaks down for asexually reproducing organisms and fossils — alternative concepts (morphological, phylogenetic) apply in different contexts." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "class-l2",
            level: 2,
            prompt: "In binomial nomenclature, the scientific name Homo sapiens refers to which two ranks of classification?",
            options: [
              { id: "a", text: "Kingdom and Phylum" },
              { id: "b", text: "Order and Family" },
              { id: "c", text: "Genus and Species", correct: true },
              { id: "d", text: "Class and Order" },
            ],
            explanation: "Binomial nomenclature uses two names: the genus (Homo, capitalised) and the species (sapiens, lowercase), both written in italics. This system was devised by Carl Linnaeus in the 18th century.",
          },
          {
            type: "fill",
            id: "class-l4",
            level: 4,
            prompt: "Fungi have cell walls made of ▁, which distinguishes them from plant cell walls made of cellulose.",
            answers: ["chitin"],
            explanation: "Fungal cell walls are made of chitin, the same material found in insect exoskeletons. This is a key feature that places fungi in their own kingdom, separate from plants (cellulose cell walls) and bacteria (peptidoglycan cell walls).",
          },
          {
            type: "short",
            id: "class-l6",
            level: 6,
            prompt: "Explain what a dichotomous key is and how it is used to identify an unknown organism. Give an example of one step in a key.",
            keywords: ["dichotomous", "two", "options", "mutually exclusive", "identification", "feature", "observable", "key", "step", "organism"],
            minKeywords: 2,
            sample: "A dichotomous key is a step-by-step identification tool. At each step, two mutually exclusive options based on observable features direct the user to the next step or to an organism's name. Example: Step 1 — Does the organism have wings? (a) Yes → go to step 2; (b) No → go to step 4. Each question splits organisms into two groups until the unknown organism is identified. Dichotomous keys can be used in the field without specialist knowledge as long as the features can be observed.",
          },
          {
            type: "short",
            id: "class-l8",
            level: 8,
            prompt: "Explain why dolphins are classified as mammals and not fish, even though they live in water and have a similar body shape. What does this tell us about the limitations of classifying by appearance alone?",
            keywords: ["morphology", "mammal", "warm-blooded", "live young", "milk", "breathe air", "dna", "derived characteristics", "appearance", "phylogenetic"],
            minKeywords: 3,
            sample: "Dolphins share the body form (streamlined shape, fins) of fish due to convergent evolution — similar environments produce similar shapes. However, dolphins are classified as mammals (Mammalia) because they share derived characteristics unique to mammals: they are warm-blooded, breathe air through lungs, give birth to live young, and produce milk to feed them. These features reveal their evolutionary history from land mammals that returned to the sea. This shows that classifying by appearance alone (morphological classification) can mislead — dolphins and fish independently evolved similar body shapes. DNA and molecular phylogenetics now provide stronger evidence of evolutionary relationships, revealing the true ancestry that morphology can obscure.",
          },
        ],
      },
    },
  ],
}
