import type { StrandhootPack } from "../engine/types"

export const cellStructureCritC: StrandhootPack = {
  slug: "cell-structure-crit-c",
  title: "Seedling Growth Analysis",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Cell division and growth dataset",
  accent: "#0984b5",
  icon: "🔬",
  statementOfInquiry: "Relationships between organisms are revealed by similarities and differences between the myriad of forms.",
  estMinutes: 30,
  intro:
    "A student tracked the height of a bean seedling every 2 days after germination. Use the data tool to plot, transform, and analyse the growth data — then draw a conclusion about cell division rate and evaluate the method. The ln(height) vs time transform reveals whether growth is exponential.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Growth Analyst", icon: "🌱", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "evaluator", label: "Method Critic", icon: "⚖️", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Seedling growth dataset", blurb: "Height of a bean seedling over 14 days after germination", icon: "🌱" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the seedling height data clearly and apply a ln(y) linearising transform.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with the data but missing headings or units. A rough graph without axis labels." },
        { level: 4, body: "Level 3–4: A clear table with headings 'Days after germination' and 'Seedling height (mm)'. A graph with both axes labelled including units, plotted points connected by a smooth curve." },
        { level: 6, body: "Level 5–6: Axes labelled with units, a sensible scale that fills the grid, points accurately plotted with a smooth curve of best fit — showing the increasing growth rate characteristic of exponential growth. The graph should clearly show that the height increase per 2 days gets larger over time (not constant)." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised graph of ln(height) vs time. If growth is exponential (height = H₀ × eʳᵗ), then ln(height) = ln(H₀) + rt — a straight line with gradient r (the growth rate constant). This transform tests whether growth is truly exponential and makes the rate easy to calculate from the gradient." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Height of bean seedling over time after germination",
        xLabel: "Days after germination",
        yLabel: "Seedling height (mm)",
        editable: true,
        initialRows: [
          { x: 0, y: 2 },
          { x: 2, y: 3.2 },
          { x: 4, y: 5.1 },
          { x: 6, y: 8.2 },
          { x: 8, y: 13.1 },
          { x: 10, y: 20.5 },
          { x: 12, y: 31.0 },
          { x: 14, y: 40.2 },
        ],
        transforms: [
          { id: "raw", label: "Seedling height vs time", x: "x", y: "y", xLabel: "Days", yLabel: "Height (mm)" },
          { id: "ln", label: "ln(height) vs time (exponential growth model)", x: "x", y: "ln(y)", xLabel: "Days", yLabel: "ln(height)" },
        ],
        derive: { kind: "gradient", label: "Growth rate constant (r)", unit: "per day" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted height on the y-axis against days on the x-axis because...",
          "The graph shows a... trend because the height increase per 2 days...",
          "I linearised the data by plotting ln(height) vs time because...",
          "The straight line on the ln(height) plot confirms...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or a graph.", keywords: ["table", "graph", "data", "height", "days", "time"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "mm", "days", "height"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve; increasing rate described as exponential or accelerating.", keywords: ["curve", "best fit", "increases", "exponential", "smooth", "accelerating", "rate", "faster"], minKeywords: 2 },
          { level: 8, descriptor: "Linearised ln(height) vs time plot described and justified.", keywords: ["ln", "ln(height)", "straight line", "linear", "gradient", "transform", "exponential", "r", "growth rate"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient of the ln(height) vs time graph to find the growth rate constant r.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('the seedling grew taller every 2 days')." },
        { level: 4, body: "Level 3–4: Notes the height doubled several times over the 14 days and that the increase per 2-day interval grew larger — suggesting the growth rate is not constant." },
        { level: 6, body: "Level 5–6: From the ln(height) vs time graph, draws a line of best fit and reads off two widely-spaced points to calculate gradient = Δln(height) / Δdays. States the unit of gradient as per day (day⁻¹). Applies the formula: actual size = image size / magnification is not relevant here — the gradient of the ln plot gives r." },
        { level: 8, body: "Level 7–8: Full calculation shown. Using Day 0 (ln 2 = 0.693) and Day 14 (ln 40.2 = 3.693): gradient = (3.693 − 0.693) / (14 − 0) = 3.000 / 14 ≈ 0.214 per day (students may read slightly differently from their graph; accepted range ~0.17–0.22/day). Interpretation: r ≈ 0.17–0.21 per day means the seedling increased in height by ~17–21% per day during this exponential growth phase. Linking to biology: r reflects the net rate of cell division by mitosis minus cell death; the faster cells divide, the higher r." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Height of bean seedling over time after germination",
        xLabel: "Days after germination",
        yLabel: "Seedling height (mm)",
        editable: true,
        initialRows: [
          { x: 0, y: 2 },
          { x: 2, y: 3.2 },
          { x: 4, y: 5.1 },
          { x: 6, y: 8.2 },
          { x: 8, y: 13.1 },
          { x: 10, y: 20.5 },
          { x: 12, y: 31.0 },
          { x: 14, y: 40.2 },
        ],
        transforms: [
          { id: "raw", label: "Seedling height vs time", x: "x", y: "y", xLabel: "Days", yLabel: "Height (mm)" },
          { id: "ln", label: "ln(height) vs time (exponential growth model)", x: "x", y: "ln(y)", xLabel: "Days", yLabel: "ln(height)" },
        ],
        derive: { kind: "gradient", label: "Growth rate constant (r)", unit: "per day" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the ln(height) vs time graph and interpret it as the growth rate constant r.",
        scaffolds: [
          "The trend shows that the seedling height...",
          "From the ln(height) vs time plot, I chose two points: (day, ln height) = ... and ...",
          "Gradient r = Δln(height) / Δdays = ... / ... = ... per day",
          "This means the seedling increased in height by approximately ___ % per day.",
          "This rate is linked to cell division because...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes height increases over time.", keywords: ["increases", "taller", "grows", "height", "days", "time"], minKeywords: 1 },
          { level: 4, descriptor: "Notes the rate of increase itself increases; non-constant growth described.", keywords: ["faster", "accelerating", "doubling", "increase", "non-linear", "rate", "not constant"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated from ln(height) vs time graph with working shown.", keywords: ["gradient", "ln", "delta", "slope", "two points", "best fit", "per day", "day⁻¹"], minKeywords: 2 },
          { level: 8, descriptor: "Full gradient calculation with values; r interpreted as % growth per day; linked to cell division.", keywords: ["0.693", "3.693", "0.17", "0.21", "gradient", "r", "mitosis", "cell division", "% per day", "exponential"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about growth pattern and link to cell division by mitosis.",
      guided: [
        { level: 2, body: "Level 1–2: 'The seedling grew taller every day.'" },
        { level: 4, body: "Level 3–4: 'The seedling height increased from 2 mm to 40.2 mm over 14 days. The rate of increase was not constant — it increased over time, suggesting exponential growth.'" },
        { level: 6, body: "Level 5–6: 'The ln(height) vs time plot is approximately linear (R² close to 1), confirming exponential growth. The gradient r ≈ 0.17–0.21 per day is the growth rate constant. This is consistent with mitosis driving exponential growth early in seedling development — each cell division doubles the number of cells, and initially cell division rate exceeds differentiation rate.'" },
        { level: 8, body: "Level 7–8: Full conclusion with data: Height increased from 2 mm (Day 0) to 40.2 mm (Day 14) — a 20-fold increase. The ln(height) vs time graph is linear (gradient r ≈ 0.21 day⁻¹), confirming exponential growth (H = H₀ × e⁰·²¹ᵗ). This exponential phase reflects rapid mitotic cell division in the apical meristem — the region of actively dividing cells at the shoot tip. As the seedling matures, growth rate typically slows as cells differentiate and resource availability limits division. The growth constant r matches literature values for early bean seedling growth (0.15–0.25 day⁻¹), providing confidence in the data quality." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Height of bean seedling over time after germination",
        xLabel: "Days after germination",
        yLabel: "Seedling height (mm)",
        editable: true,
        initialRows: [
          { x: 0, y: 2 },
          { x: 2, y: 3.2 },
          { x: 4, y: 5.1 },
          { x: 6, y: 8.2 },
          { x: 8, y: 13.1 },
          { x: 10, y: 20.5 },
          { x: 12, y: 31.0 },
          { x: 14, y: 40.2 },
        ],
        transforms: [
          { id: "raw", label: "Seedling height vs time", x: "x", y: "y", xLabel: "Days", yLabel: "Height (mm)" },
          { id: "ln", label: "ln(height) vs time (exponential growth model)", x: "x", y: "ln(y)", xLabel: "Days", yLabel: "ln(height)" },
        ],
        derive: { kind: "gradient", label: "Growth rate constant (r)", unit: "per day" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. Is seedling growth exponential? Use data values from your graph and link to cell division by mitosis.",
        scaffolds: [
          "The seedling height increased from ___ mm on Day 0 to ___ mm on Day 14...",
          "The ln(height) vs time graph shows a... trend, which confirms the growth is...",
          "The growth rate constant r ≈ ___ per day means...",
          "This is consistent with mitosis because...",
          "The growth rate is expected to slow later because...",
        ],
        rubric: [
          { level: 2, descriptor: "States the seedling grew taller over time.", keywords: ["grew", "taller", "increased", "height", "days", "14"], minKeywords: 1 },
          { level: 4, descriptor: "Exponential growth stated; non-constant rate noted with values.", keywords: ["exponential", "not constant", "increases", "faster", "40.2", "2 mm", "20-fold"], minKeywords: 2 },
          { level: 6, descriptor: "ln(height) vs time linearity cited as evidence for exponential growth; r stated.", keywords: ["ln", "linear", "gradient", "r", "exponential", "confirmed", "0.17", "0.21", "mitosis", "cell division"], minKeywords: 3 },
          { level: 8, descriptor: "Full data-based conclusion; exponential equation cited; meristem linked; literature comparison.", keywords: ["0.21", "apical meristem", "mitosis", "exponential", "h = h₀", "differentiation", "literature", "0.15", "0.25", "20-fold", "confidence"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the seedling growth measurement and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could have been better.'" },
        { level: 4, body: "Level 3–4: 'Only one seedling was measured, which reduces reliability. If that seedling was unusually large or small, the results would not be representative.'" },
        { level: 6, body: "Level 5–6: Key limitations: (1) Only one seedling — results may not be representative; grow at least 5 seedlings and calculate the mean. (2) Height may be difficult to measure precisely if the seedling is curved — use a ruler held vertically, or photograph with a scale bar. (3) Measurements taken every 2 days — finer resolution (daily) would improve the accuracy of the gradient calculation." },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses: (1) Single seedling — one outlier would invalidate the trend; n=5 with mean and standard deviation would show variability. (2) Height measurement — a seedling that is not perfectly straight will give an underestimate if measured in a straight line; measure along the stem arc or photograph for consistency. (3) 2-day intervals — the ln(height) vs time graph assumes continuous exponential growth, but growth may be diurnal (faster in daytime); daily measurements reduce this error. (4) Environmental CVs not mentioned — temperature, light, water, soil composition all affect growth rate; controlled growth chamber needed. (5) Germination date — seedlings may have germinated at slightly different times, so 'Day 0' should be defined as the day the shoot first emerges above the soil, not the date of planting." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Height of bean seedling over time after germination",
        xLabel: "Days after germination",
        yLabel: "Seedling height (mm)",
        editable: true,
        initialRows: [
          { x: 0, y: 2 },
          { x: 2, y: 3.2 },
          { x: 4, y: 5.1 },
          { x: 6, y: 8.2 },
          { x: 8, y: 13.1 },
          { x: 10, y: 20.5 },
          { x: 12, y: 31.0 },
          { x: 14, y: 40.2 },
        ],
        transforms: [
          { id: "raw", label: "Seedling height vs time", x: "x", y: "y", xLabel: "Days", yLabel: "Height (mm)" },
          { id: "ln", label: "ln(height) vs time (exponential growth model)", x: "x", y: "ln(y)", xLabel: "Days", yLabel: "ln(height)" },
        ],
        derive: { kind: "gradient", label: "Growth rate constant (r)", unit: "per day" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect this seedling growth data. What are the main weaknesses and how would you improve them?",
        scaffolds: [
          "A key weakness is...",
          "This affects the result because...",
          "To improve this, I would...",
          "Reliability could be improved by growing ___ seedlings and calculating...",
          "A systematic error in measuring height might occur if...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem", "reliable"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned with a matching improvement.", keywords: ["one seedling", "repeat", "reliable", "more seedlings", "representative", "mean"], minKeywords: 1 },
          { level: 6, descriptor: "Two or more specific weaknesses with reasoned improvements.", keywords: ["one seedling", "curved", "2 days", "daily", "representative", "photograph", "mean", "5 seedlings", "resolution"], minKeywords: 3 },
          { level: 8, descriptor: "Multiple specific weaknesses with reasoned improvements, environmental CVs mentioned, Day 0 definition addressed.", keywords: ["n=5", "standard deviation", "diurnal", "temperature", "light", "controlled", "day 0", "germination", "arc", "measurement error", "environmental"], minKeywords: 4 },
        ],
      },
    },
  ],
}
