import type { StrandhootPack } from "../engine/types"

export const conditionsCritB: StrandhootPack = {
  slug: "conditions-crit-b",
  title: "Designing a Rate of Reaction Investigation",
  subject: "MYP Chemistry",
  criterion: "B",
  topic: "Investigating factors affecting reaction rate",
  accent: "#c0392b",
  icon: "🧪",
  statementOfInquiry:
    "Scientific innovations advance a scientist's ability to monitor changes in conditions and the effect they have on the rate of a chemical reaction.",
  estMinutes: 28,
  intro:
    "Design a full investigation into how temperature affects the rate of the sodium thiosulfate + hydrochloric acid reaction — the textbook 'disappearing cross' experiment. Each strand takes you one step further: from a sharp research question to a safe, step-by-step method.",
  badges: [
    {
      id: "questioner",
      label: "Sharp Question",
      icon: "❓",
      description: "Reach Level 8 on Research question",
      strandId: "rq",
      atLevel: 8,
    },
    {
      id: "predictor",
      label: "Bold Predictor",
      icon: "🔮",
      description: "Reach Level 8 on Hypothesis",
      strandId: "hypothesis",
      atLevel: 8,
    },
    {
      id: "controller",
      label: "Variable Master",
      icon: "🎛️",
      description: "Reach Level 8 on Variables",
      strandId: "variables",
      atLevel: 8,
    },
    {
      id: "safe",
      label: "Safe Scientist",
      icon: "🥼",
      description: "Reach Level 6+ on all strands",
      atLevel: 6,
    },
  ],
  paths: [
    {
      id: "default",
      label: "Disappearing cross experiment",
      blurb: "Sodium thiosulfate + HCl: design a temperature investigation",
      icon: "❌",
    },
  ],
  strands: [
    {
      id: "rq",
      name: "Research question",
      descriptor:
        "Write a focused, testable research question for the sodium thiosulfate + HCl disappearing-cross experiment.",
      guided: [
        {
          level: 2,
          body: "Level 1–2: A vague question names the reaction but not what is being tested: 'Does temperature affect the reaction between sodium thiosulfate and hydrochloric acid?' — This is too broad and does not specify a measurable outcome.",
        },
        {
          level: 4,
          body: "Level 3–4: A stronger question names the independent variable (IV) and the dependent variable (DV): 'How does the temperature of the reaction mixture affect the time taken for the black cross to disappear?' IV = temperature; DV = time for cross to disappear.",
        },
        {
          level: 6,
          body: "Level 5–6: A specific, testable question includes a range and the reaction: 'How does the temperature of the sodium thiosulfate solution (25°C, 35°C, 45°C, 55°C, 65°C) affect the time taken for a black cross to disappear when 10 cm³ of 2.0 mol dm⁻³ Na₂S₂O₃ is mixed with 5 cm³ of 1.0 mol dm⁻³ HCl?' This names IV, DV, and the range of temperatures.",
        },
        {
          level: 8,
          body: "Level 7–8: An operationalised question specifies how the DV is measured and with what precision: 'How does the temperature of the Na₂S₂O₃ solution (25–65°C ±1°C, measured with a calibrated thermometer) affect the rate of reaction (measured as 1/time in s⁻¹ to 3 significant figures) when 10 cm³ of 2.0 mol dm⁻³ Na₂S₂O₃ reacts with 5 cm³ of 1.0 mol dm⁻³ HCl at constant total volume?' Measurement technique and precision are fully specified.",
        },
      ],
      response: {
        kind: "design",
        prompt:
          "Write a research question for an investigation into how temperature affects the rate of the sodium thiosulfate + hydrochloric acid reaction. The endpoint is when a black cross beneath the flask can no longer be seen.",
        scaffolds: [
          "How does the temperature of the reaction mixture (__ to __°C)...",
          "...affect the time taken for the black cross to disappear...",
          "...when 10 cm³ of 2.0 mol dm⁻³ sodium thiosulfate reacts with...",
          "...5 cm³ of 1.0 mol dm⁻³ hydrochloric acid?",
        ],
        rubric: [
          {
            level: 2,
            descriptor: "Names the reaction or one variable vaguely.",
            keywords: [
              "temperature",
              "sodium thiosulfate",
              "hydrochloric",
              "rate",
              "cross",
              "reaction",
            ],
            minKeywords: 1,
          },
          {
            level: 4,
            descriptor: "IV (temperature) and DV (time/cross) clearly named.",
            keywords: [
              "temperature",
              "time",
              "cross",
              "disappear",
              "how does",
              "affect",
              "rate",
            ],
            minKeywords: 2,
          },
          {
            level: 6,
            descriptor: "Range of temperatures stated; both reagents named with concentrations.",
            keywords: [
              "25",
              "65",
              "°c",
              "na2s2o3",
              "sodium thiosulfate",
              "hcl",
              "2.0 mol",
              "1.0 mol",
              "10 cm",
              "5 cm",
            ],
            minKeywords: 3,
          },
          {
            level: 8,
            descriptor: "Measurement technique and precision specified; rate expressed as 1/time.",
            keywords: [
              "1/time",
              "s⁻¹",
              "calibrated",
              "thermometer",
              "±1",
              "significant figures",
              "3 sf",
              "operationalised",
              "precision",
              "total volume",
            ],
            minKeywords: 2,
          },
        ],
      },
    },
    {
      id: "hypothesis",
      name: "Hypothesis",
      descriptor: "Predict how temperature affects the rate of the disappearing-cross reaction, with collision-theory reasoning.",
      guided: [
        {
          level: 2,
          body: "Level 1–2: A directional prediction without reasoning: 'If the temperature is higher, the reaction will be faster and the cross will disappear sooner.' — Correct direction but no scientific explanation.",
        },
        {
          level: 4,
          body: "Level 3–4: If/then with IV and DV named: 'If the temperature of the sodium thiosulfate solution increases, then the time for the cross to disappear will decrease, because the reaction is faster at higher temperatures.' — names IV and DV with a direction, but lacks collision-theory explanation.",
        },
        {
          level: 6,
          body: "Level 5–6: Justified with collision theory: 'If the temperature increases from 25°C to 65°C, the time for the cross to disappear will decrease (rate will increase), because increasing temperature raises the average kinetic energy of the Na₂S₂O₃ and HCl particles. A greater proportion of particles will exceed the activation energy, increasing the frequency of successful collisions and therefore the rate of sulfur formation.'",
        },
        {
          level: 8,
          body: "Level 7–8: A quantitative prediction using the Arrhenius relationship: 'If temperature increases from 25°C to 65°C, the rate (1/time) will approximately double for every 10°C rise (a rule of thumb based on the Arrhenius equation). At 65°C, rate should be roughly 2⁴ = 16 times faster than at 25°C. This is because a greater proportion of molecules exceed the activation energy barrier at higher temperatures (Maxwell–Boltzmann distribution), increasing the frequency of successful collisions exponentially with temperature.'",
        },
      ],
      response: {
        kind: "design",
        prompt:
          "Write a hypothesis predicting how temperature affects the rate of the sodium thiosulfate + HCl reaction. Include scientific reasoning using the collision theory.",
        scaffolds: [
          "If the temperature increases, then the time for the cross to disappear will...",
          "because increasing temperature raises the average kinetic energy of the particles...",
          "A greater proportion of particles will exceed the activation energy, so...",
          "The frequency of successful collisions will...",
        ],
        rubric: [
          {
            level: 2,
            descriptor: "States a prediction about temperature and the cross or rate.",
            keywords: [
              "temperature",
              "faster",
              "cross",
              "disappear",
              "rate",
              "increase",
              "decrease",
            ],
            minKeywords: 1,
          },
          {
            level: 4,
            descriptor: "If/then structure with IV and DV; direction correct.",
            keywords: [
              "if",
              "then",
              "temperature",
              "time",
              "decrease",
              "rate",
              "increase",
              "faster",
            ],
            minKeywords: 2,
          },
          {
            level: 6,
            descriptor: "Collision theory applied: kinetic energy, activation energy, frequency of successful collisions.",
            keywords: [
              "kinetic energy",
              "activation energy",
              "frequency",
              "successful collisions",
              "proportion",
              "collision theory",
              "sulfur",
              "exceed",
            ],
            minKeywords: 3,
          },
          {
            level: 8,
            descriptor: "Quantitative prediction; Arrhenius or doubling rule; Maxwell–Boltzmann cited.",
            keywords: [
              "doubles",
              "10°c",
              "arrhenius",
              "16 times",
              "maxwell",
              "boltzmann",
              "exponential",
              "quantitative",
              "2^4",
            ],
            minKeywords: 2,
          },
        ],
      },
    },
    {
      id: "variables",
      name: "Variables",
      descriptor: "Classify all variables for the sodium thiosulfate + HCl disappearing-cross investigation.",
      guided: [
        {
          level: 2,
          body: "Level 1–2: Three types: independent variable (IV — what you change), dependent variable (DV — what you measure), controlled variables (CVs — what you keep constant to make it a fair test).",
        },
        {
          level: 4,
          body: "Level 3–4: IV = temperature of the sodium thiosulfate solution (°C). DV = time taken for the black cross to disappear (s), used to calculate rate = 1/time (s⁻¹). CVs include: volume and concentration of Na₂S₂O₃, volume and concentration of HCl.",
        },
        {
          level: 6,
          body: "Level 5–6: IV: temperature of Na₂S₂O₃ solution (25°C, 35°C, 45°C, 55°C, 65°C, ±1°C, measured with a thermometer). DV: time for cross to disappear (s ±0.5 s, using a stopwatch); rate = 1/time (s⁻¹). CVs with values: volume of Na₂S₂O₃ (10 cm³, using a measuring cylinder), concentration of Na₂S₂O₃ (2.0 mol dm⁻³), volume of HCl (5 cm³), concentration of HCl (1.0 mol dm⁻³), same black-cross paper, same observer.",
        },
        {
          level: 8,
          body: "Level 7–8: As L6, plus: each CV includes how it is controlled and why — 'Volume of Na₂S₂O₃ controlled by measuring 10 cm³ with a graduated pipette (±0.05 cm³) because changing volume changes concentration and therefore frequency of collisions.' Also names a possible systematic error: 'The endpoint (cross just disappearing) is subjective — different observers may stop the stopwatch at slightly different times. To minimise this, the same person should judge the endpoint in all trials.'",
        },
      ],
      response: {
        kind: "design",
        prompt:
          "Identify and classify all variables for the sodium thiosulfate + HCl disappearing-cross experiment investigating the effect of temperature on reaction rate.",
        scaffolds: [
          "Independent variable (IV): the temperature of the Na₂S₂O₃ solution (__ to __°C)",
          "Dependent variable (DV): the time taken for the black cross to disappear (s); rate = 1/time",
          "Controlled variables (CVs): volume of Na₂S₂O₃ = __ cm³; concentration of Na₂S₂O₃ = __ mol dm⁻³",
          "I will control [CV] by... because...",
          "A possible systematic error is...",
        ],
        rubric: [
          {
            level: 2,
            descriptor: "Names one type of variable.",
            keywords: [
              "independent",
              "dependent",
              "controlled",
              "temperature",
              "time",
              "cross",
            ],
            minKeywords: 1,
          },
          {
            level: 4,
            descriptor: "IV and DV named with units; at least one CV identified.",
            keywords: [
              "independent variable",
              "dependent variable",
              "temperature",
              "time",
              "°c",
              "seconds",
              "1/time",
              "controlled",
            ],
            minKeywords: 3,
          },
          {
            level: 6,
            descriptor: "IV, DV and 4+ CVs named with values/units.",
            keywords: [
              "10 cm³",
              "2.0 mol",
              "1.0 mol",
              "5 cm³",
              "25°c",
              "65°c",
              "±",
              "stopwatch",
              "measuring cylinder",
              "black cross",
            ],
            minKeywords: 4,
          },
          {
            level: 8,
            descriptor: "CVs with control method and reason; systematic error identified.",
            keywords: [
              "graduated pipette",
              "±0.05",
              "why",
              "frequency",
              "subjective",
              "observer",
              "systematic error",
              "endpoint",
              "same person",
              "concentration",
            ],
            minKeywords: 3,
          },
        ],
      },
    },
    {
      id: "method",
      name: "Method",
      descriptor:
        "Write a safe, numbered method for the sodium thiosulfate + HCl disappearing-cross experiment.",
      guided: [
        {
          level: 2,
          body: "Level 1–2: Lists materials but gives only 1–2 vague steps: 'Add the thiosulfate and acid together and time how long until the cross disappears.' — No volumes, no safety, no temperature control.",
        },
        {
          level: 4,
          body: "Level 3–4: Logical sequence: (1) Measure 10 cm³ of sodium thiosulfate. (2) Heat to 25°C using a water bath. (3) Place flask on black cross paper. (4) Add 5 cm³ of HCl and start stopwatch. (5) Stop when cross disappears. (6) Repeat at 35°C, 45°C, 55°C, 65°C.",
        },
        {
          level: 6,
          body: "Level 5–6: Numbered steps with volumes, concentrations, safety (eye protection; perform in fume hood or well-ventilated area as SO₂ product can cause asthma). Steps specify: 10 cm³ of 2.0 mol dm⁻³ Na₂S₂O₃ in a 250 cm³ conical flask, 40 cm³ distilled water added to dilute, check temperature with thermometer until it matches the water bath, add 5 cm³ of 1.0 mol dm⁻³ HCl, swirl, start stopwatch, observe from above and stop when cross is no longer visible, record time.",
        },
        {
          level: 8,
          body: "Level 7–8: Adds repeats (3 trials at each temperature for reliability; calculate mean and exclude anomalous values), states that rate = 1/mean time (s⁻¹), includes the ionic equation S₂O₃²⁻(aq) + 2H⁺(aq) → H₂O(l) + SO₂(g) + S(s) to confirm yellow sulfur precipitate is the endpoint indicator, specifies rinsing the flask between trials to remove sulfur residue that would affect the path length and endpoint judgement.",
        },
      ],
      response: {
        kind: "design",
        prompt:
          "Write a numbered, step-by-step method for the sodium thiosulfate + HCl disappearing-cross experiment investigating how temperature affects rate. Include safety precautions.",
        scaffolds: [
          "1. Measure 10 cm³ of 2.0 mol dm⁻³ sodium thiosulfate solution using a measuring cylinder...",
          "2. Place the conical flask in the water bath set at 25°C. Check the temperature with a thermometer...",
          "3. Draw a black cross on a white sheet of paper and place the flask directly on top...",
          "4. Measure 5 cm³ of 1.0 mol dm⁻³ hydrochloric acid. Add it to the flask, swirl, and start the stopwatch...",
          "5. Observe the cross from above. Stop the stopwatch when the cross can no longer be seen...",
          "Safety: wear eye protection; perform in a well-ventilated area as sulfur dioxide (SO₂) is produced.",
        ],
        rubric: [
          {
            level: 2,
            descriptor: "Lists materials or gives 1–2 vague steps.",
            keywords: [
              "thiosulfate",
              "acid",
              "cross",
              "stopwatch",
              "time",
              "flask",
            ],
            minKeywords: 1,
          },
          {
            level: 4,
            descriptor: "Logical sequence with 4+ steps including temperature control.",
            keywords: [
              "measure",
              "water bath",
              "temperature",
              "add",
              "start stopwatch",
              "disappear",
              "repeat",
              "35°c",
            ],
            minKeywords: 3,
          },
          {
            level: 6,
            descriptor: "Volumes and concentrations given; safety precautions included; endpoint described.",
            keywords: [
              "10 cm³",
              "2.0 mol",
              "5 cm³",
              "1.0 mol",
              "eye protection",
              "fume hood",
              "ventilated",
              "so2",
              "swirl",
              "observe from above",
            ],
            minKeywords: 4,
          },
          {
            level: 8,
            descriptor: "3 repeats; mean calculated; rate = 1/time stated; rinse flask between trials; ionic equation cited.",
            keywords: [
              "3 trials",
              "repeat",
              "mean",
              "anomalous",
              "1/time",
              "rate",
              "rinse",
              "sulfur",
              "s2o3",
              "ionic equation",
            ],
            minKeywords: 3,
          },
        ],
      },
    },
  ],
}
