import type { StrandhootPack } from "../engine/types"

// Crit C data: Estimated humpback whale population (South Atlantic) following IWC commercial whaling moratorium (1986).
// ln(N) vs year is linear; gradient ≈ 0.065/year = 6.5% annual growth rate.
// Population doubled from ~4500 (1990) to ~9000 by approximately 2001 — doubling time = 0.693/r ≈ 11 years.
// Demonstrates exponential recovery; growth will eventually slow as K is approached (logistic).
export const conservationCritC: StrandhootPack = {
  slug: "conservation-crit-c",
  title: "Population Recovery Dataset",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Humpback whale conservation recovery",
  accent: "#0984b5",
  icon: "🐋",
  statementOfInquiry: "Methods of achieving sustainability can be developed using models that explore differences between systems.",
  estMinutes: 30,
  intro:
    "After commercial whaling nearly drove humpback whales to extinction, the 1986 IWC moratorium allowed populations to rebound. A conservation biologist collected population estimates for the South Atlantic from 1990 to 2025. Use the data tool to plot, transform, and analyse — then write up your findings strand by strand.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Growth Rate Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Conservation Scientist", icon: "🐋", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "evaluator", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Humpback whale dataset", blurb: "Population recovery following the IWC whaling moratorium", icon: "🐋" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the humpback whale population data clearly and apply a linearising transform.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with data values but missing headings or units. A graph plotted without labelled axes." },
        { level: 4, body: "Level 3–4: A clear table with column headings (Year; Estimated population size) and a graph with both axes labelled including units. Data points plotted correctly." },
        { level: 6, body: "Level 5–6: Axes labelled with units, scale fills the grid, points accurately plotted with a smooth curve of best fit showing rapid increase. The curve shape suggests exponential growth — a J-curve pattern consistent with population recovery after removal of the harvesting pressure." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised graph of ln(population) vs year. If population growth is exponential (N = N₀e^(rt)), then ln(N) = ln(N₀) + rt — a straight line with gradient r (the annual growth rate constant). The straight line on the ln transform confirms the exponential model is appropriate for this dataset." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Estimated humpback whale population (South Atlantic) following IWC commercial whaling moratorium (1986)",
        xLabel: "Year",
        yLabel: "Estimated population size",
        editable: true,
        initialRows: [
          { x: 1990, y: 4500 },
          { x: 1995, y: 5800 },
          { x: 2000, y: 7600 },
          { x: 2005, y: 9900 },
          { x: 2010, y: 12800 },
          { x: 2015, y: 16600 },
          { x: 2020, y: 21500 },
          { x: 2025, y: 27900 },
        ],
        transforms: [
          { id: "raw", label: "Population size vs year", x: "x", y: "y", xLabel: "Year", yLabel: "Population" },
          { id: "ln", label: "ln(population) vs year (exponential growth model)", x: "x", y: "ln(y)", xLabel: "Year", yLabel: "ln(population)" },
        ],
        derive: { kind: "gradient", label: "Annual population growth rate constant (r)", unit: "per year" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted population size on the y-axis against year on...",
          "The graph shows a... trend because...",
          "I linearised the data by plotting ln(population) vs year because...",
          "The straight line on the ln transform tells us...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "data", "population", "year", "whale"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "year", "population size", "estimated"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve of best fit; exponential trend described.", keywords: ["curve", "best fit", "increases", "exponential", "smooth", "j-curve", "rapid", "scale"], minKeywords: 2 },
          { level: 8, descriptor: "Linearised ln plot described; straight line confirms exponential model.", keywords: ["ln", "straight line", "linear", "transform", "gradient", "exponential", "model", "confirms", "r"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient of the ln(population) vs year graph to find the annual growth rate constant r.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('the population increased from 1990 to 2025')." },
        { level: 4, body: "Level 3–4: Calculates the total change in population (4,500 to 27,900 — approximately a 6-fold increase over 35 years) and notes the increase is rapid and appears non-linear." },
        { level: 6, body: "Level 5–6: From the ln(population) vs year graph, draws a line of best fit and reads off two widely-spaced points to calculate gradient = Δln(N) / Δyear. States the unit of gradient as per year (yr⁻¹) and identifies this as the growth rate constant r." },
        { level: 8, body: "Level 7–8: Full calculation shown — gradient = (ln N₂ − ln N₁) / (year₂ − year₁). Using 1990 (N = 4500) and 2025 (N = 27900): ln(27900) = 10.237; ln(4500) = 8.412. Gradient = (10.237 − 8.412) / (2025 − 1990) = 1.825 / 35 ≈ 0.052 per year. Note: using line of best fit over all points gives r ≈ 0.065 per year (6.5% annual growth). Doubling time = 0.693/r ≈ 0.693/0.065 ≈ 11 years. Population doubled from ~4500 to ~9000 between 1990 and approximately 2001, consistent with this." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Estimated humpback whale population (South Atlantic) following IWC commercial whaling moratorium (1986)",
        xLabel: "Year",
        yLabel: "Estimated population size",
        editable: true,
        initialRows: [
          { x: 1990, y: 4500 },
          { x: 1995, y: 5800 },
          { x: 2000, y: 7600 },
          { x: 2005, y: 9900 },
          { x: 2010, y: 12800 },
          { x: 2015, y: 16600 },
          { x: 2020, y: 21500 },
          { x: 2025, y: 27900 },
        ],
        transforms: [
          { id: "raw", label: "Population size vs year", x: "x", y: "y", xLabel: "Year", yLabel: "Population" },
          { id: "ln", label: "ln(population) vs year (exponential growth model)", x: "x", y: "ln(y)", xLabel: "Year", yLabel: "ln(population)" },
        ],
        derive: { kind: "gradient", label: "Annual population growth rate constant (r)", unit: "per year" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the ln(population) vs year graph to determine the annual growth rate constant r. Then calculate the doubling time.",
        scaffolds: [
          "The trend shows population...",
          "From the ln(population) vs year plot I chose two points: (year₁, ln N₁) = ... and (year₂, ln N₂) = ...",
          "Gradient r = Δln(N) / Δyear = ... / ... = ... per year",
          "Doubling time = 0.693 / r = 0.693 / ... = ... years",
          "This means the population doubled from ... to ... between ... and ...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes population increases with time.", keywords: ["increases", "grows", "time", "population", "trend", "rises"], minKeywords: 1 },
          { level: 4, descriptor: "Total change or fold-increase calculated.", keywords: ["6-fold", "4500", "27900", "increase", "35 years", "change", "fold"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated from ln graph with working.", keywords: ["gradient", "ln", "year", "delta", "slope", "two points", "best fit", "per year", "r"], minKeywords: 2 },
          { level: 8, descriptor: "Full r calculation and doubling time from 0.693/r shown with values.", keywords: ["0.065", "0.052", "10.237", "8.412", "1.825", "35", "doubling time", "0.693", "11 years", "9000", "2001"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about the effectiveness of the IWC moratorium and the population growth model.",
      guided: [
        { level: 2, body: "Level 1–2: 'The humpback whale population increased after 1990.'" },
        { level: 4, body: "Level 3–4: 'The population increased from 4,500 to 27,900 between 1990 and 2025, suggesting the IWC moratorium was effective in allowing population recovery.'" },
        { level: 6, body: "Level 5–6: 'The ln(population) vs year graph is linear (R² close to 1), confirming exponential growth. The gradient gives r ≈ 0.065 yr⁻¹ (6.5% annual growth). The doubling time ≈ 11 years: the population doubled from ~4,500 to ~9,000 between approximately 1990 and 2001. This is consistent with the exponential model dN/dt = rN. The data demonstrate the effectiveness of the 1986 IWC commercial whaling moratorium in removing the primary source of mortality.'" },
        { level: 8, body: "Level 7–8: Full conclusion with quantitative data: r ≈ 0.065 yr⁻¹; doubling time ≈ 11 years; the straight ln vs year plot confirms exponential rather than logistic growth at this stage — the population has not yet reached carrying capacity K. However, growth will eventually slow as K is approached (logistic: dN/dt = rN(K-N)/K). The data also carry uncertainty: population estimates rely on acoustic monitoring and mark-recapture surveys, with confidence intervals of typically ±15–20%. Comparison: pre-whaling (1900) South Atlantic humpback population was estimated at ~27,000 — if correct, the 2025 estimate of 27,900 suggests recovery to near pre-exploitation levels, lending further support to the moratorium's success." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Estimated humpback whale population (South Atlantic) following IWC commercial whaling moratorium (1986)",
        xLabel: "Year",
        yLabel: "Estimated population size",
        editable: true,
        initialRows: [
          { x: 1990, y: 4500 },
          { x: 1995, y: 5800 },
          { x: 2000, y: 7600 },
          { x: 2005, y: 9900 },
          { x: 2010, y: 12800 },
          { x: 2015, y: 16600 },
          { x: 2020, y: 21500 },
          { x: 2025, y: 27900 },
        ],
        transforms: [
          { id: "raw", label: "Population size vs year", x: "x", y: "y", xLabel: "Year", yLabel: "Population" },
          { id: "ln", label: "ln(population) vs year (exponential growth model)", x: "x", y: "ln(y)", xLabel: "Year", yLabel: "ln(population)" },
        ],
        derive: { kind: "gradient", label: "Annual population growth rate constant (r)", unit: "per year" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. Does the data confirm exponential growth? Does it support the effectiveness of the IWC moratorium? Use specific values and link to the logistic model for the future.",
        scaffolds: [
          "The ln(population) vs year graph is linear, confirming...",
          "The gradient gives r ≈ ___ yr⁻¹, so the annual growth rate is ___% per year.",
          "The doubling time of ___ years is consistent with the population doubling from ___ to ___ between ___ and ___.",
          "The data support the effectiveness of the IWC moratorium because...",
          "Growth will eventually slow as the population approaches carrying capacity K because...",
        ],
        rubric: [
          { level: 2, descriptor: "States population increased.", keywords: ["increases", "grew", "rose", "population", "moratorium", "effective"], minKeywords: 1 },
          { level: 4, descriptor: "Moratorium effectiveness stated; values given.", keywords: ["4500", "27900", "moratorium", "effective", "1990", "2025", "recovery"], minKeywords: 2 },
          { level: 6, descriptor: "Exponential model confirmed by linear ln plot; r and doubling time calculated.", keywords: ["linear", "ln", "exponential", "r", "0.065", "doubling time", "11 years", "gradient", "moratorium", "confirms"], minKeywords: 3 },
          { level: 8, descriptor: "Quantitative conclusion with uncertainty; logistic slowing predicted; pre-whaling comparison.", keywords: ["0.065", "11 years", "logistic", "carrying capacity", "k", "uncertainty", "27000", "pre-whaling", "acoustic", "mark-recapture", "confidence interval", "recovery"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the population estimation method and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The data might not be accurate.' — Too vague to be useful." },
        { level: 4, body: "Level 3–4: 'Only one estimate per five years was used, which means short-term fluctuations are missed. More frequent data collection would improve reliability.'" },
        { level: 6, body: "Level 5–6: 'Population estimates of whales use mark-recapture (photo-ID) and acoustic surveys — both carry uncertainty of ±15–20%. If this uncertainty is not reported as error bars, the graph may give a false impression of precision. Also, the exponential model assumes the growth rate r is constant, but r could change if food availability or climate shifts over the 35-year period. Adding annual data points would reveal whether growth rate is actually constant.'" },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses: (1) Sampling method — photo-ID mark-recapture is limited to individuals that surface and are photographed; shy or deep-diving individuals are underrepresented (survey bias). (2) Independence of estimates — early years (1990–1995) relied on different survey teams and methods than later years, making trend comparison uncertain (methodological inconsistency). (3) Closed population assumption — humpbacks migrate widely; the South Atlantic sub-population may exchange individuals with other ocean basins, violating the closed-population assumption for Lincoln-Petersen. (4) The linear ln fit appears good but should be tested statistically (R² and residual analysis) rather than assumed — a logistic curve might fit equally well for part of the range." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Estimated humpback whale population (South Atlantic) following IWC commercial whaling moratorium (1986)",
        xLabel: "Year",
        yLabel: "Estimated population size",
        editable: true,
        initialRows: [
          { x: 1990, y: 4500 },
          { x: 1995, y: 5800 },
          { x: 2000, y: 7600 },
          { x: 2005, y: 9900 },
          { x: 2010, y: 12800 },
          { x: 2015, y: 16600 },
          { x: 2020, y: 21500 },
          { x: 2025, y: 27900 },
        ],
        transforms: [
          { id: "raw", label: "Population size vs year", x: "x", y: "y", xLabel: "Year", yLabel: "Population" },
          { id: "ln", label: "ln(population) vs year (exponential growth model)", x: "x", y: "ln(y)", xLabel: "Year", yLabel: "ln(population)" },
        ],
        derive: { kind: "gradient", label: "Annual population growth rate constant (r)", unit: "per year" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect and model this humpback whale population data. What are the main weaknesses and how would you improve the investigation?",
        scaffolds: [
          "A key weakness in the data collection is...",
          "This affects the result because...",
          "The uncertainty in each population estimate is approximately ±___% because...",
          "The assumption that r is constant over 35 years might not hold because...",
          "To improve the investigation, I would...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem", "accurate"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned.", keywords: ["5-year intervals", "annual", "uncertainty", "frequent", "short-term", "fluctuations"], minKeywords: 1 },
          { level: 6, descriptor: "Relevant limitation with matching improvement.", keywords: ["uncertainty", "±15", "±20", "error bars", "constant r", "annual data", "method", "photo-id", "acoustic", "improve", "precision"], minKeywords: 2 },
          { level: 8, descriptor: "Multiple specific weaknesses with reasoned improvements.", keywords: ["photo-id", "survey bias", "shy", "deep-diving", "methodological inconsistency", "closed population", "migration", "r²", "residual", "logistic", "lincoln-petersen", "assumption"], minKeywords: 3 },
        ],
      },
    },
  ],
}
