import type { StrandhootPack } from "../engine/types"

export const consequencesCritB: StrandhootPack = {
  slug: "consequences-crit-b",
  title: "Designing an Acid Rain Investigation",
  subject: "MYP Chemistry",
  criterion: "B",
  topic: "Investigating acid deposition & SO₂ pollution",
  accent: "#c0392b",
  icon: "🌧️",
  statementOfInquiry:
    "Change as a consequence of human development can be identified within all environments on our planet.",
  estMinutes: 27,
  intro:
    "The chapter's summative assessment asks you to simulate acid rain formation using sulfur powder, a Bunsen burner and universal indicator. This pack takes you through every design step — from writing a focused research question to building a safe, step-by-step method — mirroring the real investigation from Chapter 3.",
  badges: [
    {
      id: "sharp-question",
      label: "Sharp Question",
      icon: "❓",
      description: "Reach Level 8 on Research question",
      strandId: "rq",
      atLevel: 8,
    },
    {
      id: "bold-predictor",
      label: "Bold Predictor",
      icon: "🔮",
      description: "Reach Level 8 on Hypothesis",
      strandId: "hypothesis",
      atLevel: 8,
    },
    {
      id: "variable-master",
      label: "Variable Master",
      icon: "🎛️",
      description: "Reach Level 8 on Variables",
      strandId: "variables",
      atLevel: 8,
    },
    {
      id: "safe-scientist",
      label: "Safe Scientist",
      icon: "🥼",
      description: "Reach Level 6+ on all strands",
      atLevel: 6,
    },
  ],
  paths: [
    {
      id: "default",
      label: "Acid rain simulation",
      blurb: "Design an investigation into SO₂ dissolving in water to lower pH",
      icon: "🌧️",
    },
  ],
  strands: [
    {
      id: "rq",
      name: "Research question",
      descriptor:
        "Write a focused, testable research question for the acid rain simulation investigation.",
      guided: [
        {
          level: 2,
          body: "Level 1–2: A research question names the investigation topic. Vague example: 'Does acid rain affect the environment?' — this is too broad and cannot be tested in a single controlled experiment.",
        },
        {
          level: 4,
          body: "Level 3–4: A stronger question identifies an independent variable (IV) and dependent variable (DV): 'How does dissolving sulfur dioxide gas in distilled water affect the pH of the water?' IV = presence of dissolved SO₂; DV = pH of the water.",
        },
        {
          level: 6,
          body: "Level 5–6: A specific, testable question with a range: 'How does the volume of sulfur dioxide gas dissolved in 50 cm³ of distilled water (0–500 cm³ of SO₂) affect the pH of the resulting solution, as measured by universal indicator?' This names the IV, DV, a range, the controlled volume of water, and the measurement technique.",
        },
        {
          level: 8,
          body: "Level 7–8: An operationalised question specifies the measurement technique and precision: 'How does the volume of sulfur dioxide gas (generated by burning sulfur powder in a gas jar and measured by water displacement, 0–500 cm³ ± 10 cm³) dissolved in 50.0 cm³ (± 0.5 cm³) of distilled water affect the pH of the resulting solution as measured by a calibrated pH meter (± 0.01 pH units)?'",
        },
      ],
      response: {
        kind: "design",
        prompt:
          "Write a research question to investigate how dissolving sulfur dioxide in water changes the pH of the solution — simulating the formation of acid rain.",
        scaffolds: [
          "How does...",
          "...the volume of sulfur dioxide gas dissolved in...",
          "...distilled water affect the pH...",
          "...as measured by universal indicator / a pH meter?",
        ],
        rubric: [
          {
            level: 2,
            descriptor: "Names the topic or one variable vaguely.",
            keywords: [
              "sulfur",
              "acid rain",
              "ph",
              "water",
              "dissolve",
              "so2",
              "investigate",
            ],
            minKeywords: 1,
          },
          {
            level: 4,
            descriptor: "Names IV and DV with clear direction.",
            keywords: [
              "sulfur dioxide",
              "ph",
              "water",
              "how does",
              "affect",
              "independent",
              "dependent",
              "dissolve",
            ],
            minKeywords: 2,
          },
          {
            level: 6,
            descriptor:
              "Specific and testable; range stated; controlled variable (volume of water) identified; measurement technique named.",
            keywords: [
              "volume",
              "50 cm",
              "range",
              "universal indicator",
              "distilled",
              "controlled",
              "so2",
              "ph",
            ],
            minKeywords: 3,
          },
          {
            level: 8,
            descriptor:
              "Operationalised: measurement technique, precision and units specified for both IV and DV.",
            keywords: [
              "calibrated",
              "ph meter",
              "±",
              "precision",
              "water displacement",
              "0.01",
              "50.0 cm",
              "operationalised",
              "measure",
            ],
            minKeywords: 2,
          },
        ],
      },
    },
    {
      id: "hypothesis",
      name: "Hypothesis",
      descriptor:
        "Predict how dissolving SO₂ in water will change its pH, with chemical reasoning.",
      guided: [
        {
          level: 2,
          body: "Level 1–2: A hypothesis makes a directional prediction: 'Dissolving sulfur dioxide in water will make the water more acidic.' This gives a direction but no scientific reasoning.",
        },
        {
          level: 4,
          body: "Level 3–4: An if/then hypothesis: 'If more sulfur dioxide is dissolved in distilled water, then the pH of the water will decrease.' This names the IV and DV and gives a direction, but lacks a chemical explanation.",
        },
        {
          level: 6,
          body: "Level 5–6: A justified hypothesis: 'If sulfur dioxide is dissolved in distilled water, the pH will decrease below 7 because SO₂ reacts with water to form sulfurous acid, H₂SO₃: SO₂(g) + H₂O(l) ⇌ H₂SO₃(aq). This acid partially dissociates to produce H⁺ ions, lowering the pH. The greater the volume of SO₂ dissolved, the lower the pH will be.'",
        },
        {
          level: 8,
          body: "Level 7–8: A quantitative hypothesis with a mechanism: 'If 500 cm³ of SO₂ is dissolved in 50 cm³ of distilled water, the pH will fall from 7.0 to approximately 3–4. SO₂(g) + H₂O(l) ⇌ H₂SO₃(aq), and H₂SO₃ is a weak acid (partially dissociates). This is the same reaction responsible for acid rain, which typically reaches pH 4.2–4.4 in heavily polluted areas. The equilibrium shifts right as more SO₂ dissolves, continuously producing H₂SO₃ and increasing [H⁺]. Kc is unchanged at constant temperature — only the equilibrium position shifts.'",
        },
      ],
      response: {
        kind: "design",
        prompt:
          "Write a hypothesis predicting how dissolving SO₂ gas in distilled water will change its pH. Include a chemical equation and a scientific explanation.",
        scaffolds: [
          "If sulfur dioxide is dissolved in distilled water, then the pH will...",
          "because SO₂ reacts with water to form...",
          "The equation for this reaction is: SO₂(g) + H₂O(l) ⇌...",
          "This produces H⁺ ions, which means...",
          "A greater volume of SO₂ dissolved will cause...",
        ],
        rubric: [
          {
            level: 2,
            descriptor:
              "States a prediction about SO₂/acid rain and pH direction.",
            keywords: [
              "ph",
              "decrease",
              "acidic",
              "lower",
              "sulfur",
              "so2",
              "acid rain",
            ],
            minKeywords: 1,
          },
          {
            level: 4,
            descriptor: "If/then structure with IV and DV named; direction given.",
            keywords: [
              "if",
              "then",
              "sulfur dioxide",
              "ph",
              "decrease",
              "lower",
              "dissolved",
            ],
            minKeywords: 2,
          },
          {
            level: 6,
            descriptor:
              "Chemical equation for SO₂ + H₂O cited; H⁺ production explained; link to weak acid.",
            keywords: [
              "h2so3",
              "sulfurous acid",
              "h+",
              "so2",
              "h2o",
              "weak acid",
              "dissociate",
              "equilibrium",
              "equation",
            ],
            minKeywords: 3,
          },
          {
            level: 8,
            descriptor:
              "Quantitative prediction with approximate pH range; Kc unchanged noted; mechanism linked to real acid rain pH.",
            keywords: [
              "3",
              "4",
              "ph 4.2",
              "kc",
              "unchanged",
              "equilibrium position",
              "500 cm",
              "quantitative",
              "mechanism",
              "acid rain",
            ],
            minKeywords: 2,
          },
        ],
      },
    },
    {
      id: "variables",
      name: "Variables",
      descriptor:
        "Identify and classify all variables for the acid rain simulation experiment.",
      guided: [
        {
          level: 2,
          body: "Level 1–2: Variables are classified as independent (what you change), dependent (what you measure), and controlled (what you keep constant). In this experiment you change the amount of SO₂ and measure the pH.",
        },
        {
          level: 4,
          body: "Level 3–4: IV: volume of SO₂ gas dissolved (cm³); DV: pH of the water measured using universal indicator. CVs include: volume of distilled water (50 cm³), temperature of water, source of water (distilled not tap), mass of sulfur powder burned.",
        },
        {
          level: 6,
          body: "Level 5–6: IV: volume of SO₂ collected by water displacement (cm³ ± 10 cm³); DV: pH of solution measured with universal indicator colour chart (± 1 pH unit) — or better, a pH electrode (± 0.01 pH units). CVs: volume of distilled water (50.0 cm³ ± 0.5 cm³), measured with a measuring cylinder; temperature (20°C ± 2°C), controlled using a water bath; type of indicator solution (universal indicator, same batch); mass of sulfur powder (0.5 g, measured on a balance).",
        },
        {
          level: 8,
          body: "Level 7–8: As Level 5–6, plus: each CV stated with control method and reason. Volume of water: measured with 50 cm³ measuring cylinder (± 0.5 cm³) — 'because varying the volume of water would change the concentration of H₂SO₃ and therefore the pH, making comparisons invalid.' Temperature: controlled in a 20°C water bath — 'because temperature affects the equilibrium position of SO₂(g) + H₂O(l) ⇌ H₂SO₃(aq) and therefore the pH.' Systematic error: universal indicator gives only approximate pH values (± 1 unit); a calibrated pH electrode is more precise.",
        },
      ],
      response: {
        kind: "design",
        prompt:
          "Identify and classify all variables for an experiment investigating how the volume of SO₂ gas dissolved in distilled water affects the pH of the resulting solution.",
        scaffolds: [
          "Independent variable (IV): volume of SO₂ gas dissolved (cm³)",
          "Dependent variable (DV): pH of the solution, measured by...",
          "Controlled variables (CVs):",
          "I will control [CV] by... because...",
          "A possible systematic error is...",
        ],
        rubric: [
          {
            level: 2,
            descriptor: "Names one type of variable correctly.",
            keywords: [
              "independent",
              "dependent",
              "controlled",
              "so2",
              "ph",
              "volume",
            ],
            minKeywords: 1,
          },
          {
            level: 4,
            descriptor: "IV and DV named with units; at least one CV stated.",
            keywords: [
              "independent variable",
              "dependent variable",
              "ph",
              "volume",
              "cm",
              "temperature",
              "water",
              "controlled",
            ],
            minKeywords: 2,
          },
          {
            level: 6,
            descriptor:
              "IV, DV and 3+ CVs named with values and units; measurement tool stated.",
            keywords: [
              "50 cm",
              "universal indicator",
              "temperature",
              "20°c",
              "distilled",
              "mass",
              "sulfur",
              "measuring cylinder",
              "water bath",
              "ph electrode",
            ],
            minKeywords: 3,
          },
          {
            level: 8,
            descriptor:
              "CVs each with control method, reason and precision; systematic error identified.",
            keywords: [
              "water bath",
              "equilibrium",
              "calibrated",
              "±",
              "systematic error",
              "concentration",
              "invalid",
              "precision",
              "control method",
              "reason",
            ],
            minKeywords: 3,
          },
        ],
      },
    },
    {
      id: "method",
      name: "Method",
      descriptor:
        "Write a safe, numbered method to simulate acid rain formation using burning sulfur.",
      guided: [
        {
          level: 2,
          body: "Level 1–2: Lists materials only, or gives 1–2 vague steps: 'Burn the sulfur powder and add water, then test the pH.' No volumes, no safety, no detail on collecting the gas.",
        },
        {
          level: 4,
          body: "Level 3–4: Logical steps: (1) Place 0.5 g of sulfur powder on a deflagration spoon. (2) Ignite with a Bunsen burner. (3) Lower into a gas jar. (4) Add 50 cm³ of distilled water and seal with the lid. (5) Shake and test pH with universal indicator solution.",
        },
        {
          level: 6,
          body: "Level 5–6: Clear numbered steps including safety. (1) Measure 50 cm³ of distilled water into a gas jar with a measuring cylinder. (2) Add 5 drops of universal indicator solution and record the starting colour/pH. (3) Weigh 0.5 g of sulfur powder on a deflagration spoon. (4) Light the sulfur over a Bunsen burner until it burns with a blue flame. (5) Immediately lower the deflagration spoon into the gas jar and seal it with the lid. (6) Wait 30 seconds; remove the spoon and re-seal. (7) Shake the jar to dissolve the SO₂. (8) Observe the colour of the indicator and record the pH using the colour chart. Safety: work in a fume hood — SO₂ is a toxic gas that irritates the respiratory system; wear safety glasses at all times.",
        },
        {
          level: 8,
          body: "Level 7–8: Adds quantitative detail — repeat each volume 3 times to calculate a mean pH and assess reliability; include a control (50 cm³ distilled water with indicator, no SO₂) to confirm the starting pH is 7; state how to vary the IV (e.g. burn different masses of sulfur: 0.1, 0.2, 0.3, 0.4, 0.5 g); cite the equation SO₂(g) + H₂O(l) ⇌ H₂SO₃(aq) to justify measuring pH rather than another quantity; identify how to neutralise the acidic solution in the gas jar after use (add sodium hydrogencarbonate until fizzing stops) — this is both a safety measure and an example of the environmental solution: liming acidic soil.",
        },
      ],
      response: {
        kind: "design",
        prompt:
          "Write a numbered, step-by-step method to simulate the formation of acid rain by burning sulfur powder and dissolving the SO₂ produced in distilled water. Include safety precautions.",
        scaffolds: [
          "1. Measure 50 cm³ of distilled water into a gas jar using a measuring cylinder...",
          "2. Add 5 drops of universal indicator solution and record the starting colour/pH...",
          "3. Weigh 0.5 g of sulfur powder on a deflagration spoon...",
          "4. Ignite the sulfur with a Bunsen burner until it burns with a blue flame...",
          "5. Lower the deflagration spoon into the gas jar and seal with the lid...",
          "Safety: work in a fume hood because SO₂ is a toxic gas that...",
        ],
        rubric: [
          {
            level: 2,
            descriptor: "Lists materials only or gives 1–2 vague steps.",
            keywords: [
              "sulfur",
              "burn",
              "water",
              "ph",
              "indicator",
              "gas jar",
            ],
            minKeywords: 1,
          },
          {
            level: 4,
            descriptor: "Logical sequence with 4+ steps; gas collection mentioned.",
            keywords: [
              "deflagration",
              "bunsen",
              "gas jar",
              "seal",
              "shake",
              "indicator",
              "50 cm",
              "test",
            ],
            minKeywords: 2,
          },
          {
            level: 6,
            descriptor:
              "Numbered steps with volumes; indicator colour recorded; safety in fume hood; SO₂ toxicity mentioned.",
            keywords: [
              "50 cm",
              "0.5 g",
              "fume hood",
              "toxic",
              "safety glasses",
              "universal indicator",
              "colour",
              "seal",
              "shake",
              "30 seconds",
            ],
            minKeywords: 4,
          },
          {
            level: 8,
            descriptor:
              "Repeats 3× for reliability; control included; disposal of acidic solution; equation cited to justify measurement.",
            keywords: [
              "repeat",
              "3 times",
              "control",
              "reliable",
              "mean",
              "sodium hydrogencarbonate",
              "neutralise",
              "equation",
              "h2so3",
              "mass of sulfur",
            ],
            minKeywords: 3,
          },
        ],
      },
    },
  ],
}
