import type { StrandhootPack } from "../engine/types"

export const conservationCritA: StrandhootPack = {
  slug: "conservation-crit-a",
  title: "Models & Sustainability",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Population models and conservation biology",
  accent: "#1b7888",
  icon: "🐋",
  statementOfInquiry: "Methods of achieving sustainability can be developed using models that explore differences between systems.",
  estMinutes: 25,
  intro:
    "From bacteria doubling in a flask to humpback whales recovering from near-extinction, population models reveal the mathematics behind survival. Each strand levels up from recall to analysis — covering exponential and logistic growth, the collapse of overexploited fisheries, and the biotechnologies shaping conservation's future.",
  badges: [
    { id: "modeller", label: "Population Modeller", icon: "📈", description: "Reach Level 8 on Population models", strandId: "population-models", atLevel: 8 },
    { id: "ecologist", label: "Overexploitation Expert", icon: "🎣", description: "Reach Level 8 on Overexploitation", strandId: "overexploitation", atLevel: 8 },
    { id: "strategist", label: "Mitigation Strategist", icon: "🛡️", description: "Reach Level 8 on Mitigation strategies", strandId: "mitigation", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 12: Models", blurb: "Population dynamics, conservation, and biotechnology for sustainability", icon: "🐋" }],
  strands: [
    {
      id: "population-models",
      name: "Population models",
      descriptor: "Describe and compare exponential and logistic population growth models.",
      guided: [
        { level: 2, body: "Populations can grow in two main ways. Exponential growth (J-curve) happens when resources are unlimited — the population keeps doubling. Logistic growth (S-curve) happens when resources run out and limit growth — the population levels off at the carrying capacity (K)." },
        { level: 4, body: "Exponential growth is described by dN/dt = rN, where N = population size and r = intrinsic growth rate. Because there are no limits, each individual reproduces at the same rate and the population doubles at a constant doubling time (e.g., bacteria can double every 20 minutes). Logistic growth adds a braking term: dN/dt = rN(K-N)/K. As N approaches K, growth rate falls to zero." },
        { level: 6, body: "The S-curve shape arises because limiting factors (food, space, disease) increase as population density rises. At N = K/2, the population grows fastest (the inflection point). European human populations historically followed logistic patterns, but the global human population may overshoot K before stabilising — causing a crash rather than a smooth plateau. r-strategists (bacteria, insects) have many offspring with low parental care and high r; K-strategists (elephants, humans) have few offspring with high parental care and low r, adapting to live close to K." },
        { level: 8, body: "Comparing model assumptions: the logistic model assumes a constant K, which is rarely true in nature (K shifts with climate, disease, habitat change). r-selection favours rapid colonisation of unstable environments (short lifespan, early reproduction, high r); K-selection favours competitive efficiency in stable, saturated environments (long lifespan, delayed reproduction, high investment per offspring). Real populations often show oscillations around K due to time lags in density-dependent regulation. Predator–prey cycles (Lotka–Volterra model) emerge when two populations interact — prey grows exponentially until predators limit it, then predators decline as prey declines, creating out-of-phase cycles." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "pm-l2",
            level: 2,
            prompt: "Which graph shape describes exponential population growth?",
            options: [
              { id: "a", text: "S-curve (logistic)" },
              { id: "b", text: "Bell curve (normal distribution)" },
              { id: "c", text: "J-curve (exponential)", correct: true },
              { id: "d", text: "Flat line (no change)" },
            ],
            explanation: "Exponential growth produces a J-shaped curve because each new individual also reproduces, causing the rate of increase to accelerate without limit.",
          },
          {
            type: "fill",
            id: "pm-l4",
            level: 4,
            prompt: "In the logistic growth equation dN/dt = rN(K-N)/K, the letter K represents the population's ▁.",
            answers: ["carrying capacity", "k", "carrying capacity (k)"],
            explanation: "K is the carrying capacity — the maximum population size the environment can sustainably support. When N = K, growth rate falls to zero.",
          },
          {
            type: "short",
            id: "pm-l6",
            level: 6,
            prompt: "Explain the difference between r-strategists and K-strategists. Give one example of each and describe how their reproductive strategies relate to the logistic growth model.",
            keywords: ["r-strategist", "k-strategist", "offspring", "parental care", "carrying capacity", "logistic", "density", "bacteria", "insects", "elephant", "human", "unstable"],
            minKeywords: 2,
            sample: "r-strategists (e.g. bacteria, insects) produce many offspring with little parental care and high intrinsic growth rate r — they excel when resources are abundant and population density is low, far below K. K-strategists (e.g. elephants, humans) produce few offspring with high parental care, investing heavily in each individual to compete effectively near K. In the logistic model, r-strategists dominate the early, steep part of the S-curve; K-strategists are adapted to live near the plateau.",
          },
          {
            type: "short",
            id: "pm-l8",
            level: 8,
            prompt: "The logistic model predicts a smooth S-curve to carrying capacity K. Evaluate one limitation of this model and explain how predator–prey interactions (Lotka–Volterra) challenge the idea of a stable K.",
            keywords: ["logistic", "assumption", "constant k", "oscillations", "time lag", "lotka-volterra", "predator", "prey", "cycle", "density-dependent", "climate", "overshoot"],
            minKeywords: 3,
            sample: "The logistic model assumes K is constant, but in nature K changes with climate, habitat quality and disease — so real populations rarely plateau smoothly. A key limitation is time lag in density-dependent responses: populations often overshoot K before crashing back. Lotka–Volterra dynamics show that when a predator and prey interact, the two populations oscillate out of phase — as prey grows, predators increase and depress prey; falling prey causes predator decline, allowing prey to recover. This cycling around an average contradicts the simple stable equilibrium at K.",
          },
        ],
      },
    },
    {
      id: "overexploitation",
      name: "Overexploitation",
      descriptor: "Explain the causes and consequences of overexploitation of wild populations.",
      guided: [
        { level: 2, body: "Overexploitation means harvesting a species faster than it can reproduce. Famous examples include the Grand Banks cod collapse (Canada) and deforestation of the Amazon. The tragedy of the commons (Garrett Hardin, 1968) explains why shared resources are overexploited without regulation." },
        { level: 4, body: "Maximum sustainable yield (MSY) is the largest harvest that can be taken without reducing future stocks. MSY occurs at N = K/2 — the point on the logistic curve where the population grows fastest. Cod on the Grand Banks collapsed in 1992 after decades of overfishing; 40,000 jobs were lost and stocks have only partially recovered after 30 years. The Amazon has lost 17% of its forest since 1970 at approximately 11,000 km²/year net." },
        { level: 6, body: "The tragedy of the commons (Hardin 1968): when a resource (ocean fish, shared pasture) is owned by no one, each individual's rational choice to maximise their own harvest leads collectively to over-exploitation and resource collapse. Regulation (quotas, property rights, international agreements) is needed to overcome this. Bushmeat hunting and illegal wildlife trade threaten large mammals — the bushmeat crisis in Central Africa is driving populations of primates, forest elephants, and pangolins below viable thresholds. Amazon deforestation could trigger a tipping point: at 20–25% clearance, the forest may convert to savanna (Amazon dieback) as rainfall recycling breaks down." },
        { level: 8, body: "The cod collapse illustrates the lag between ecological warning signs and political action: scientists recommended cuts in catch limits through the 1980s, but lobbying delayed action until stocks crashed. This is a systemic failure of governance — the same pattern seen in whaling, Atlantic bluefin tuna, and Atlantic salmon. Allee effects compound the problem: below a critical population threshold, reproductive success falls because individuals cannot find mates or group defences break down. This creates an extinction vortex — decline accelerates non-linearly. Quantitative data: Amazon threshold is modelled at 20–25% clearance (currently 17%); crossing it is predicted to destabilise regional rainfall affecting agriculture across South America." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "oe-l2",
            level: 2,
            prompt: "According to Garrett Hardin (1968), why are shared natural resources often overexploited?",
            options: [
              { id: "a", text: "Because technology makes harvesting too easy" },
              { id: "b", text: "Because individuals each act in their own interest, depleting the shared resource", correct: true },
              { id: "c", text: "Because governments always encourage overexploitation" },
              { id: "d", text: "Because shared resources are always unlimited" },
            ],
            explanation: "The tragedy of the commons: each user gains the full benefit of taking more, but the costs of depletion are shared by everyone. Rational self-interest leads collectively to overexploitation without external regulation.",
          },
          {
            type: "fill",
            id: "oe-l4",
            level: 4,
            prompt: "Maximum sustainable yield (MSY) occurs when the population is at ▁ of the carrying capacity K.",
            answers: ["half", "k/2", "1/2", "one half", "50%"],
            explanation: "At N = K/2, the logistic growth rate dN/dt is at its maximum, so the population can replace the largest possible harvest. Fishing below this level depletes the stock; fishing above it causes collapse.",
          },
          {
            type: "short",
            id: "oe-l6",
            level: 6,
            prompt: "Describe the collapse of the Grand Banks cod fishery. What does this case illustrate about the tragedy of the commons and the role of political action in preventing overexploitation?",
            keywords: ["grand banks", "cod", "1992", "collapse", "moratorium", "tragedy of the commons", "regulation", "quota", "overfishing", "stocks", "jobs", "political"],
            minKeywords: 2,
            sample: "The Grand Banks cod fishery off Canada collapsed in 1992 after decades of overfishing that exceeded the maximum sustainable yield. About 40,000 jobs were lost and stocks have only partially recovered despite a 30-year moratorium. This illustrates the tragedy of the commons: each fishing company rationally maximised its catch, but the collective result was stock collapse. Political and regulatory failure — delaying catch limits despite scientific warnings — accelerated the crash.",
          },
          {
            type: "short",
            id: "oe-l8",
            level: 8,
            prompt: "Explain the concept of the Allee effect and how it creates an extinction vortex. How does this affect conservation management decisions when a population is already small?",
            keywords: ["allee effect", "extinction vortex", "threshold", "reproductive success", "mates", "group defence", "non-linear", "decline", "minimum viable population", "conservation", "management", "accelerates"],
            minKeywords: 3,
            sample: "The Allee effect describes reduced fitness at low population density — below a critical threshold, individuals struggle to find mates, cooperative defences break down, and inbreeding increases. This creates an extinction vortex: each decline reduces reproductive success, which drives further decline in an accelerating feedback. Conservation managers must identify the minimum viable population (MVP) above which the Allee threshold lies, and must act before the population crosses it — since below the threshold, even removing all harvest pressure may not prevent extinction. This makes early intervention essential.",
          },
        ],
      },
    },
    {
      id: "mitigation",
      name: "Mitigation strategies",
      descriptor: "Evaluate conservation strategies designed to achieve sustainable use of biodiversity.",
      guided: [
        { level: 2, body: "Humans use several strategies to prevent species extinction: protected areas (national parks), sustainable fishing rules, seed banks, and rewilding. Each targets a different aspect of biodiversity loss." },
        { level: 4, body: "30×30: the global target is to protect 30% of Earth's land and ocean by 2030; currently only 17% of land and 10% of ocean is protected. Sustainable fisheries use MSC (Marine Stewardship Council) certification, fishing quotas based on stock assessments, and seasonal closures. The Svalbard Global Seed Vault (Norway) holds 1.3 million seed samples from 98% of countries, opened in 2008 — a backup for the world's seed banks." },
        { level: 6, body: "Rewilding: reintroducing keystone species triggers trophic cascades. Wolves reintroduced to Yellowstone in 1995 reduced elk grazing pressure, allowing riparian vegetation to recover, which stabilised river banks and changed river meander patterns — demonstrating a top-down ecological cascade. CITES (Convention on International Trade in Endangered Species) has 183 member states and regulates trade in 38,000 species. Effectiveness of protected areas depends on corridor connectivity, enforcement, and whether they encompass the full range of a species — fragmented reserves may not sustain viable populations." },
        { level: 8, body: "Evidence-based evaluation of strategies: MSC-certified sustainable fisheries show 10–20% higher stock biomass than uncertified equivalents in studies, but certification can be gamed and small-scale fisheries are underrepresented. The Svalbard Vault's limitation is that seeds need periodic regeneration — it does not protect wild populations or ecosystem services. Rewilding has strongest evidence for large intact landscapes (boreal Europe, sub-Saharan Africa); in fragmented European landscapes, evidence for trophic cascade benefits is contested. 30×30 faces political resistance (overlap with indigenous land rights, agriculture, mining). The most cost-effective strategy appears to be protecting tropical forest, which sequesters carbon and harbours >50% of terrestrial species simultaneously." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "ms-l2",
            level: 2,
            prompt: "What is the global '30×30' conservation target?",
            options: [
              { id: "a", text: "Protect 30 species by 2030" },
              { id: "b", text: "Reduce carbon emissions by 30% by 2030" },
              { id: "c", text: "Protect 30% of the Earth's land and ocean by 2030", correct: true },
              { id: "d", text: "Plant 30 billion trees by 2030" },
            ],
            explanation: "30×30 is the international biodiversity target: protect 30% of Earth's land and oceans by the year 2030. Currently only 17% of land and 10% of ocean are formally protected.",
          },
          {
            type: "fill",
            id: "ms-l4",
            level: 4,
            prompt: "The Svalbard Global Seed Vault, opened in 2008, holds approximately ▁ million seed samples.",
            answers: ["1.3", "1.3 million"],
            explanation: "The Svalbard vault holds 1.3 million accessions (seed samples) from 98% of the world's countries, serving as a backup for national seed banks in case of disaster, war, or climate change.",
          },
          {
            type: "short",
            id: "ms-l6",
            level: 6,
            prompt: "Explain how the reintroduction of wolves to Yellowstone National Park in 1995 produced a trophic cascade. What does this example demonstrate about rewilding as a conservation strategy?",
            keywords: ["wolves", "yellowstone", "1995", "elk", "grazing", "riparian", "vegetation", "river", "trophic cascade", "rewilding", "keystone", "top-down"],
            minKeywords: 2,
            sample: "Wolves reintroduced to Yellowstone preyed on elk and changed their grazing behaviour, reducing overgrazing of streamside vegetation. Recovering plants stabilised river banks, reducing erosion and causing rivers to meander differently. This trophic cascade — predator affecting plants via herbivore — illustrates that rewilding with keystone species can restore ecosystem structure and function, going far beyond simply preventing predator extinction.",
          },
          {
            type: "short",
            id: "ms-l8",
            level: 8,
            prompt: "Evaluate the effectiveness of two conservation strategies (protected areas and sustainable fisheries certification). What evidence exists for and against each, and what conditions determine their success?",
            keywords: ["protected areas", "msc", "sustainable fisheries", "evidence", "stock biomass", "certification", "fragmentation", "corridor", "enforcement", "viable population", "rewilding", "effective", "limitation"],
            minKeywords: 3,
            sample: "MSC-certified sustainable fisheries show 10–20% higher stock biomass than uncertified fisheries in some studies, but certification can be gamed and small-scale fisheries are underrepresented in the scheme — reducing its global reach. Protected areas are most effective when large, connected by corridors, and well-enforced; fragmented reserves often cannot sustain minimum viable populations of wide-ranging species. Both strategies require governance and enforcement to work — without those, designation alone achieves little. A combination of strategies targeting both in-situ protection and sustainable use gives the best evidence base for long-term biodiversity outcomes.",
          },
        ],
      },
    },
    {
      id: "biotech-conservation",
      name: "3D bioprinting and biotechnology",
      descriptor: "Evaluate biotechnological approaches to conservation and sustainability.",
      guided: [
        { level: 2, body: "New biotechnologies offer novel tools for conservation. 3D bioprinting uses living cells to print tissues and organs. Lab-grown (cultivated) meat grows animal muscle in a bioreactor rather than from a farmed animal. De-extinction projects aim to bring back extinct species using genetic technology." },
        { level: 4, body: "3D bioprinting: bioink is a mixture of living cells suspended in a hydrogel scaffold; the printer deposits layers to build three-dimensional tissue. Printed cartilage and skin grafts are already in clinical use; a prototype printed kidney was produced in 2023. Lab-grown meat: cultivated from animal muscle stem cells; uses 95% less land and 96% less water than conventional beef. Cost fell from $330,000 to approximately $10 per burger between 2013 and 2023." },
        { level: 6, body: "De-extinction: Colossal Biosciences is using CRISPR gene editing to insert cold-resistance genes from woolly mammoth genomes into Asian elephant cells, targeting 2028 for a viable embryo. This raises ethical and ecological questions: does reintroducing the mammoth restore a lost ecosystem function, or divert resources from living endangered species? Synthetic biology: engineered microorganisms are being developed to degrade plastics (e.g. engineered Ideonella sakaiensis for PET degradation) and to synthesise medicines. These technologies blurs the line between conservation and technological substitution for nature." },
        { level: 8, body: "Critical evaluation of biotechnological conservation: 3D bioprinting for conservation (e.g. printed Northern white rhino embryos — Biorescue project) remains experimental, with scale-up and epigenetic hurdles. Lab-grown meat's environmental footprint depends critically on the energy source — if powered by fossil fuels, life-cycle emissions may exceed conventional beef in some models. De-extinction resources argument: the $15 million woolly mammoth project could alternatively fund protection of 1,500 km² of habitat for 50 living endangered species. Opportunity cost must be weighed explicitly. Synthetic biology offers high potential but carries ecological risk from release of engineered organisms — containment and reversibility are key safety requirements." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "bt-l2",
            level: 2,
            prompt: "What is 'bioink' in 3D bioprinting?",
            options: [
              { id: "a", text: "A type of synthetic plastic used to make medical devices" },
              { id: "b", text: "A mixture of living cells suspended in a hydrogel scaffold", correct: true },
              { id: "c", text: "A dye used to colour biological samples for microscopy" },
              { id: "d", text: "A growth hormone added to lab-grown meat cultures" },
            ],
            explanation: "Bioink is the printable material in 3D bioprinting — living cells mixed into a hydrogel that keeps them alive and in position as the printer builds up layers of tissue.",
          },
          {
            type: "fill",
            id: "bt-l4",
            level: 4,
            prompt: "The company Colossal Biosciences is using ▁ gene editing to insert woolly mammoth cold-resistance genes into the Asian elephant genome.",
            answers: ["crispr", "CRISPR", "CRISPR-Cas9", "crispr-cas9"],
            explanation: "CRISPR-Cas9 allows precise editing of specific DNA sequences. Colossal Biosciences is using it to insert mammoth traits — including cold-resistance genes — into the Asian elephant genome in a de-extinction project targeting 2028.",
          },
          {
            type: "short",
            id: "bt-l6",
            level: 6,
            prompt: "Describe two environmental benefits of lab-grown (cultivated) meat. What concern remains about its environmental footprint even if it reaches commercial scale?",
            keywords: ["lab-grown", "cultivated", "land", "water", "95%", "96%", "emissions", "energy", "fossil fuels", "conventional beef", "environmental", "footprint", "scale"],
            minKeywords: 2,
            sample: "Lab-grown meat uses approximately 95% less land and 96% less water than conventional beef production, potentially relieving pressure on agricultural land and freshwater resources. However, its climate footprint depends heavily on the energy source used to power bioreactors — if electricity comes from fossil fuels, life-cycle greenhouse gas emissions may not be significantly lower than, or could even exceed, conventional beef. So energy transition must accompany adoption of cultured meat for the climate benefit to be realised.",
          },
          {
            type: "short",
            id: "bt-l8",
            level: 8,
            prompt: "Evaluate the opportunity cost argument against de-extinction projects like the woolly mammoth. Do you think biotechnology resources should be prioritised for de-extinction or for protecting living endangered species? Justify using evidence.",
            keywords: ["opportunity cost", "woolly mammoth", "colossal", "15 million", "1500 km", "habitat", "endangered", "living species", "de-extinction", "resources", "crispr", "evidence", "justify", "prioritise"],
            minKeywords: 3,
            sample: "The $15 million invested in the woolly mammoth de-extinction project could alternatively fund protection of approximately 1,500 km² of habitat for living endangered species. The opportunity cost argument is compelling: de-extinction restores one extinct species, while habitat protection can preserve hundreds of species simultaneously. Against this, de-extinction advocates argue that restoring lost ecosystem engineers (like mammoths in arctic grasslands) could deliver disproportionate ecological benefits. The scientific consensus is that preventing current extinctions is a higher priority, given that living species face immediate threats and de-extinction technology remains unproven at scale. However, both approaches should ideally operate with separate funding streams rather than competing for the same conservation budget.",
          },
        ],
      },
    },
  ],
}
