import type { StrandhootPack } from "../engine/types"

export const enzymesCritA: StrandhootPack = {
  slug: "enzymes-crit-a",
  title: "Enzymes & Biochemistry",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Structure, activity and denaturation",
  accent: "#1b7888",
  icon: "🔬",
  statementOfInquiry: "Science is applied to mitigate the transformations associated with aging but sometimes anti-aging science is misrepresented.",
  estMinutes: 25,
  intro:
    "Explore the molecular machines that drive life — from the precise fit of enzyme and substrate to the irreversible unravelling of denaturation. Each strand targets a core concept from Chapter 2: Transformation, levelling up from recall to analysis.",
  badges: [
    { id: "structure", label: "Active Site Expert", icon: "🔑", description: "Reach Level 8 on Enzyme structure", strandId: "structure", atLevel: 8 },
    { id: "temperature", label: "Temperature Analyst", icon: "🌡️", description: "Reach Level 8 on Temperature effects", strandId: "temperature", atLevel: 8 },
    { id: "ph", label: "pH Investigator", icon: "⚗️", description: "Reach Level 8 on pH effects", strandId: "ph", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 2: Transformation", blurb: "Enzyme structure, temperature, pH and inhibitors", icon: "🔬" }],
  strands: [
    {
      id: "structure",
      name: "Enzyme structure",
      descriptor: "Describe enzyme structure and the mechanism of enzyme-substrate interaction.",
      guided: [
        { level: 2, body: "Enzymes are globular proteins with a special region called the active site. The active site has a specific 3D shape that matches the substrate — the molecule the enzyme acts on. The enzyme is not consumed in the reaction." },
        { level: 4, body: "The active site binds the substrate to form an enzyme-substrate complex. The lock-and-key model says the substrate fits the active site exactly like a key fits a lock. Enzyme specificity means one enzyme acts on only one substrate — because the shapes must match precisely." },
        { level: 6, body: "The induced-fit model refines the lock-and-key model: the active site changes shape slightly when the substrate binds, improving the fit. This explains why some enzymes can act on structurally similar substrates. The enzyme is not consumed — after the reaction, the products leave and the enzyme is free to catalyse again, making enzymes very efficient (a single enzyme molecule can process thousands of substrate molecules per second)." },
        { level: 8, body: "The 3D shape of the active site is maintained by non-covalent interactions (hydrogen bonds, ionic interactions, hydrophobic effects) within the protein's tertiary structure. If the amino acid sequence changes (mutation) or bonds are disrupted (denaturation), the active site shape changes and activity is lost. This explains enzyme specificity at the molecular level: the precise electrostatic complementarity between active site residues and substrate functional groups determines which substrates bind — and with what affinity (Km)." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "str-l2",
            level: 2,
            prompt: "What type of molecule is an enzyme?",
            options: [
              { id: "a", text: "Carbohydrate" },
              { id: "b", text: "Lipid" },
              { id: "c", text: "Globular protein", correct: true },
              { id: "d", text: "Nucleic acid" },
            ],
            explanation: "Enzymes are globular proteins — their spherical 3D shape places the active site in a precise configuration to bind the substrate.",
          },
          {
            type: "fill",
            id: "str-l4",
            level: 4,
            prompt: "The region of an enzyme that binds the substrate is called the ▁.",
            answers: ["active site"],
            explanation: "The active site has a specific 3D shape complementary to the substrate. When substrate binds, an enzyme-substrate complex forms and the reaction proceeds.",
          },
          {
            type: "short",
            id: "str-l6",
            level: 6,
            prompt: "Compare the lock-and-key model and the induced-fit model of enzyme action. Why does the induced-fit model better explain enzyme behaviour?",
            keywords: ["lock-and-key", "induced-fit", "active site", "substrate", "shape", "changes", "complex", "fits", "rigid"],
            minKeywords: 2,
            sample: "The lock-and-key model says the substrate fits the active site exactly, like a key in a lock — the shapes are rigid and complementary. The induced-fit model improves on this: the active site changes shape slightly when the substrate binds, creating a tighter fit. This better explains why some enzymes can act on structurally similar substrates, and why binding energy is used to strain the substrate and lower the activation energy.",
          },
          {
            type: "short",
            id: "str-l8",
            level: 8,
            prompt: "Explain, at a molecular level, why an enzyme is specific to one substrate. Include the role of tertiary structure and non-covalent bonds in maintaining active site shape.",
            keywords: ["tertiary structure", "non-covalent", "hydrogen bonds", "ionic", "active site", "complementary", "specificity", "electrostatic", "amino acid", "shape"],
            minKeywords: 3,
            sample: "The active site is a precise 3D pocket formed by specific amino acid residues in the protein's tertiary structure. Hydrogen bonds, ionic interactions, and hydrophobic effects between these residues maintain the active site's exact shape. Only a substrate with a complementary shape and charge distribution can bind — making the enzyme specific to that substrate. If any non-covalent bonds are disrupted (by heat or extreme pH), the active site shape changes and specificity is lost.",
          },
        ],
      },
    },
    {
      id: "temperature",
      name: "Temperature effects on enzymes",
      descriptor: "Explain how temperature affects enzyme activity, including the role of denaturation.",
      guided: [
        { level: 2, body: "Warming an enzyme solution speeds up the reaction — more collisions occur between enzyme and substrate. But above a certain temperature, the enzyme stops working. Human enzymes work best at around 37°C (body temperature)." },
        { level: 4, body: "For every 10°C rise in temperature, the reaction rate roughly doubles (Q10 = 2). This is because higher temperature gives molecules more kinetic energy, increasing the frequency of successful enzyme-substrate collisions. At the optimum temperature, the rate is at its maximum. Above the optimum, the rate falls sharply because the enzyme denatures." },
        { level: 6, body: "Denaturation occurs when hydrogen bonds maintaining the enzyme's 3D tertiary structure break at high temperatures. This changes the shape of the active site permanently — the substrate can no longer bind. Denaturation is irreversible: unlike slowing at low temperature (where kinetic energy simply decreases and activity resumes on warming), a denatured enzyme cannot regain its original shape." },
        { level: 8, body: "The bell-shaped rate-vs-temperature curve results from two competing effects: below optimum, reaction rate increases exponentially with temperature (Arrhenius equation, Q10 ≈ 2); above optimum, the fraction of active enzyme molecules falls rapidly as thermal energy overcomes the non-covalent interactions (H-bonds, hydrophobic, ionic) stabilising the active site. The net rate is the product of both effects, producing a sharp optimum. In organisms adapted to extreme environments (thermophiles, psychrophiles), different amino acid compositions alter the balance of these two forces, shifting the optimum accordingly." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "temp-l2",
            level: 2,
            prompt: "What happens to enzyme activity when temperature rises above the optimum?",
            options: [
              { id: "a", text: "Activity doubles" },
              { id: "b", text: "Activity remains the same" },
              { id: "c", text: "Activity increases then stays high" },
              { id: "d", text: "Activity decreases because the enzyme denatures", correct: true },
            ],
            explanation: "Above the optimum temperature, the enzyme's active site changes shape permanently (denaturation) and substrate can no longer bind, so activity falls sharply.",
          },
          {
            type: "fill",
            id: "temp-l4",
            level: 4,
            prompt: "For every 10°C rise in temperature, the rate of an enzyme-controlled reaction roughly ▁.",
            answers: ["doubles", "double"],
            explanation: "The Q10 value for enzyme reactions is approximately 2 — each 10°C increase doubles the rate, because molecules have more kinetic energy and collide more frequently and successfully.",
          },
          {
            type: "short",
            id: "temp-l6",
            level: 6,
            prompt: "Explain the difference between an enzyme working slowly at low temperature and an enzyme being denatured at high temperature. Why is one reversible and the other is not?",
            keywords: ["kinetic energy", "denaturation", "hydrogen bonds", "active site", "shape", "reversible", "irreversible", "low temperature", "high temperature"],
            minKeywords: 2,
            sample: "At low temperature, enzymes slow down because molecules have less kinetic energy and fewer successful collisions occur — but the active site shape is unchanged. Warm the enzyme and activity returns (reversible). At high temperature, the hydrogen bonds maintaining the active site shape break — the enzyme denatures. The active site loses its specific shape permanently; warming back down cannot restore it (irreversible).",
          },
          {
            type: "short",
            id: "temp-l8",
            level: 8,
            prompt: "The rate-vs-temperature graph for an enzyme is bell-shaped with a sharp optimum. Explain the two competing processes that produce this shape, and why denaturation is irreversible.",
            keywords: ["arrhenius", "q10", "kinetic energy", "denaturation", "non-covalent", "hydrogen bonds", "active site", "optimum", "bell-shaped", "competing", "thermophile"],
            minKeywords: 3,
            sample: "Below the optimum, increasing temperature increases kinetic energy, raising the frequency of productive enzyme-substrate collisions (Q10 ≈ 2, Arrhenius relationship) — rate rises. Above the optimum, thermal energy breaks the non-covalent bonds (H-bonds, ionic, hydrophobic) stabilising the active site's tertiary structure, distorting it — denaturation reduces the fraction of functional enzymes. The net rate peaks where these two effects balance. Denaturation is irreversible because the unfolded polypeptide chain re-forms random aggregates rather than returning to its precise native conformation — the information about original folding is not lost but re-folding requires chaperone proteins and specific conditions.",
          },
        ],
      },
    },
    {
      id: "ph",
      name: "pH effects on enzymes",
      descriptor: "Explain how pH affects enzyme activity and why each enzyme has an optimal pH.",
      guided: [
        { level: 2, body: "Every enzyme has a pH at which it works best — called its optimal pH. Changing the pH above or below this optimum reduces enzyme activity. Pepsin in the stomach works at pH 2; salivary amylase works at pH 7." },
        { level: 4, body: "Extreme pH values denature enzymes by breaking ionic bonds and hydrogen bonds in the active site. Acids provide H⁺ ions that disrupt ionic bonds; alkalis (bases) remove H⁺ ions. Buffers are used in experiments to maintain a constant pH so only one variable is changing." },
        { level: 6, body: "Different enzymes are adapted to the pH of their environment: pepsin (stomach protease) has an optimal pH of about 2 because the stomach environment is highly acidic; salivary amylase works optimally at pH 7 (mouth); pancreatic lipase has an optimum around pH 8 (small intestine, which is slightly alkaline due to bile secretions). This shows how enzyme structure is shaped by natural selection to suit its working environment." },
        { level: 8, body: "pH alters the ionisation of amino acid side chains in and around the active site — particularly the R-groups of aspartate, glutamate (negatively charged), lysine, arginine (positively charged), and histidine (pH-sensitive). These charges help maintain active site shape through ionic interactions and are often directly involved in catalysis (acid-base catalysis). Changing pH shifts the equilibrium of these ionisations, altering charge distribution and disrupting the precise electrostatic complementarity between active site and substrate. Extreme pH also breaks the hydrogen bonds of secondary structure (alpha-helices, beta-sheets) — contributing to full denaturation." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "ph-l2",
            level: 2,
            prompt: "At what pH does pepsin, the protease in the stomach, work best?",
            options: [
              { id: "a", text: "pH 7 (neutral)" },
              { id: "b", text: "pH 8 (slightly alkaline)" },
              { id: "c", text: "pH 2 (strongly acidic)", correct: true },
              { id: "d", text: "pH 14 (strongly alkaline)" },
            ],
            explanation: "Pepsin works in the stomach, which is highly acidic (pH 1–3). Its active site is adapted to function optimally at pH 2 — the active site would change shape (denature) at higher pH values.",
          },
          {
            type: "fill",
            id: "ph-l4",
            level: 4,
            prompt: "In enzyme experiments, a ▁ is used to maintain a constant pH so that pH is not an uncontrolled variable.",
            answers: ["buffer", "buffer solution"],
            explanation: "A buffer solution resists changes in pH by absorbing or releasing H⁺ ions. This ensures that pH stays constant during the experiment, making pH a controlled variable.",
          },
          {
            type: "short",
            id: "ph-l6",
            level: 6,
            prompt: "Explain why pepsin and pancreatic lipase have very different optimal pH values. What does this tell us about their environments?",
            keywords: ["pepsin", "lipase", "stomach", "small intestine", "acidic", "alkaline", "active site", "adapted", "environment", "optimal"],
            minKeywords: 2,
            sample: "Pepsin (optimal pH 2) works in the highly acidic stomach — its active site is adapted to function where H⁺ concentration is very high. Pancreatic lipase (optimal pH 8) acts in the slightly alkaline small intestine, where bile salts have neutralised the stomach acid. Each enzyme's active site shape is adapted by natural selection to match the pH of its specific environment — a different pH would distort the active site and reduce activity.",
          },
          {
            type: "short",
            id: "ph-l8",
            level: 8,
            prompt: "Explain, at a molecular level, how changing pH alters enzyme activity. Include the role of amino acid side-chain ionisation and its effect on the active site.",
            keywords: ["ionisation", "amino acid", "side chain", "ionic bonds", "active site", "charge", "hydrogen bonds", "catalysis", "denaturation", "electrostatic", "ph"],
            minKeywords: 3,
            sample: "pH alters the ionisation state of amino acid side chains — for example, aspartate and glutamate carry negative charges at neutral pH, while lysine and arginine carry positive charges. These charged groups form ionic interactions that maintain active site shape and are often directly involved in acid-base catalysis. Changing pH shifts the ionisation equilibria of these residues, disrupting the precise charge distribution the active site needs for substrate binding and catalysis. Extreme pH also breaks hydrogen bonds in secondary structure (alpha-helices, beta-sheets), leading to denaturation and irreversible loss of active site shape.",
          },
        ],
      },
    },
    {
      id: "inhibitors",
      name: "Enzyme inhibitors",
      descriptor: "Compare competitive and non-competitive inhibition and explain their effects on enzyme activity.",
      guided: [
        { level: 2, body: "An inhibitor is a molecule that reduces enzyme activity. Some inhibitors block the active site, preventing the substrate from binding. Cyanide is a dangerous example — it blocks an enzyme in our cells and stops respiration." },
        { level: 4, body: "Competitive inhibitors have a similar shape to the substrate. They compete with the substrate for the active site — if the inhibitor is there, the substrate cannot bind. Increasing the substrate concentration reduces competitive inhibition (more substrate 'wins' the competition). Non-competitive inhibitors bind to a different site on the enzyme (not the active site), changing the active site shape so the substrate cannot fit." },
        { level: 6, body: "Competitive inhibition is often reversible — the inhibitor and substrate keep competing. At high [substrate], the proportion of enzymes occupied by inhibitor decreases, so activity approaches its uninhibited maximum (Vmax is unchanged, but Km appears higher). Non-competitive inhibition is not overcome by increasing [substrate] because the inhibitor does not compete for the active site — instead, it changes the shape of the active site permanently (or semi-permanently), reducing Vmax." },
        { level: 8, body: "Kinetically: competitive inhibition increases the apparent Km (more substrate needed to reach half-maximal rate) but leaves Vmax unchanged. Non-competitive inhibition decreases Vmax but leaves Km unchanged — because every enzyme molecule affected has a reduced catalytic rate regardless of [substrate]. Some non-competitive inhibitors are irreversible (e.g. nerve agents that phosphorylate the serine residue in acetylcholinesterase's active site, making the enzyme permanently inactive). Feedback inhibition is a biological example of non-competitive (allosteric) inhibition — the end-product of a metabolic pathway inhibits an enzyme early in the pathway, preventing wasteful overproduction." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "inh-l2",
            level: 2,
            prompt: "Cyanide kills cells by permanently blocking cytochrome oxidase, an enzyme in respiration. This is an example of which type of inhibition?",
            options: [
              { id: "a", text: "Competitive inhibition (reversed by adding more substrate)" },
              { id: "b", text: "Irreversible non-competitive inhibition", correct: true },
              { id: "c", text: "Reversible competitive inhibition" },
              { id: "d", text: "Feedback inhibition" },
            ],
            explanation: "Cyanide binds permanently to cytochrome oxidase at a site other than the active site, permanently inactivating it. This is irreversible non-competitive inhibition — increasing substrate concentration cannot overcome it.",
          },
          {
            type: "fill",
            id: "inh-l4",
            level: 4,
            prompt: "Increasing the substrate concentration can reduce the effect of a ▁ inhibitor, because substrate and inhibitor compete for the active site.",
            answers: ["competitive"],
            explanation: "A competitive inhibitor has a shape similar to the substrate and competes for the active site. With more substrate molecules available, the chance that substrate rather than inhibitor occupies the active site increases — reducing the inhibitor's effect.",
          },
          {
            type: "short",
            id: "inh-l6",
            level: 6,
            prompt: "Compare competitive and non-competitive inhibition. How does each affect the active site, and why does increasing substrate concentration overcome only one of them?",
            keywords: ["competitive", "non-competitive", "active site", "substrate", "shape", "allosteric", "concentration", "overcome", "different site", "vmax"],
            minKeywords: 2,
            sample: "A competitive inhibitor has a similar shape to the substrate and binds the active site, blocking substrate entry. Increasing substrate concentration overwhelms the inhibitor by giving more substrate molecules to compete — the enzyme's maximum rate (Vmax) is unchanged. A non-competitive inhibitor binds elsewhere on the enzyme (an allosteric site) and changes the active site shape so substrate cannot bind properly. Increasing substrate concentration does not help because the active site shape is already altered — Vmax decreases.",
          },
          {
            type: "short",
            id: "inh-l8",
            level: 8,
            prompt: "Explain how competitive and non-competitive inhibition affect Km and Vmax differently. Give a biological example of non-competitive (allosteric) inhibition and explain its metabolic significance.",
            keywords: ["km", "vmax", "competitive", "non-competitive", "allosteric", "feedback inhibition", "metabolic pathway", "end-product", "reversible", "irreversible", "phosphorylate"],
            minKeywords: 3,
            sample: "Competitive inhibition increases apparent Km (more substrate needed to reach half-maximal rate) but leaves Vmax unchanged — at very high [substrate], inhibitor is outcompeted and full activity is restored. Non-competitive inhibition decreases Vmax but leaves Km unchanged — affected enzyme molecules are less catalytically active regardless of [substrate]. A biological example is feedback inhibition: in an amino acid biosynthesis pathway, the final amino acid (end-product) allosterically inhibits the first enzyme in the pathway, preventing wasteful overproduction when the amino acid is plentiful. This is non-competitive allosteric inhibition — the product binds a regulatory site, not the active site.",
          },
        ],
      },
    },
  ],
}
