import type { StrandhootPack } from "../engine/types"

export const enzymesCritC: StrandhootPack = {
  slug: "enzymes-crit-c",
  title: "Temperature & Amylase Activity",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Amylase rate dataset",
  accent: "#0984b5",
  icon: "🔬",
  statementOfInquiry: "Science is applied to mitigate the transformations associated with aging but sometimes anti-aging science is misrepresented.",
  estMinutes: 30,
  intro:
    "A student measured the reaction rate of amylase at eight temperatures. Use the data tool to plot, transform and analyse — then draw a conclusion about the optimum temperature and the Q10 relationship. Each written strand levels up with the depth of your scientific reasoning.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Rate Analyst", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Enzyme Expert", icon: "🔬", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Amylase dataset", blurb: "Reaction rate vs temperature for salivary amylase", icon: "🔬" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the rate vs temperature data clearly and apply a linearising transform for the rising phase.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with data values but missing headings or units." },
        { level: 4, body: "Level 3–4: A clear table with column headings (Temperature (°C); Reaction rate (s⁻¹)) and a graph with both axes labelled including units. Points plotted as a scatter graph." },
        { level: 6, body: "Level 5–6: Axes labelled with units, a sensible scale that fills the grid, a smooth bell-shaped curve of best fit. The peak at 37°C is clearly visible; data points above 40°C showing the drop towards zero are distinguished from the rising phase." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised graph of ln(rate) vs temperature for the 10–37°C range. If the Q10 relationship holds, this gives a straight line — showing that the logarithm of rate increases linearly with temperature in the pre-denaturation range. The slope of ln(rate) vs T gives the rate constant for the exponential increase." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Effect of temperature on amylase reaction rate (rate = 1/time for starch disappearance)",
        xLabel: "Temperature (°C)",
        yLabel: "Reaction rate (s⁻¹)",
        editable: true,
        initialRows: [
          { x: 10, y: 0.0021 },
          { x: 20, y: 0.0048 },
          { x: 30, y: 0.0100 },
          { x: 37, y: 0.0172 },
          { x: 40, y: 0.0118 },
          { x: 45, y: 0.0055 },
          { x: 50, y: 0.0011 },
          { x: 55, y: 0.0002 },
        ],
        transforms: [
          { id: "raw", label: "Rate vs temperature", x: "x", y: "y", xLabel: "Temperature (°C)", yLabel: "Reaction rate (s⁻¹)" },
          { id: "ln", label: "ln(rate) vs temperature (linear region 10-37°C)", x: "x", y: "ln(y)", xLabel: "Temperature (°C)", yLabel: "ln(rate)" },
        ],
        derive: { kind: "gradient", label: "Rate constant (linear region 10–37°C)", unit: "s⁻¹ per °C" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted reaction rate on the y-axis against temperature on...",
          "The graph shows a... trend because...",
          "I linearised the data by plotting ln(rate) vs temperature because...",
          "The straight line in the 10–37°C region confirms...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "rate", "temperature", "data"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "s⁻¹", "°c", "temperature", "rate"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth bell-shaped curve; optimum at 37°C identified.", keywords: ["bell-shaped", "curve", "best fit", "optimum", "37", "smooth", "decreases", "rises"], minKeywords: 2 },
          { level: 8, descriptor: "Linearised ln(rate) vs temperature described as straight line in rising phase.", keywords: ["ln", "linear", "straight line", "10-37", "transform", "slope", "gradient", "exponential"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the Q10 and determine the gradient of the linearised plot.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('The rate increases then decreases')." },
        { level: 4, body: "Level 3–4: Calculates the change in rate between two temperatures. For example, from 20°C to 30°C, rate increases from 0.0048 to 0.0100 s⁻¹ — approximately a doubling, consistent with Q10 = 2." },
        { level: 6, body: "Level 5–6: Calculates Q10 using the formula Q10 = (rate at T+10) / (rate at T). Example: Q10 from 10°C to 20°C = 0.0048 / 0.0021 ≈ 2.3. From the ln(rate) vs temperature graph, draws a line of best fit through the 10–37°C points and calculates gradient = Δln(rate) / ΔT." },
        { level: 8, body: "Level 7–8: Full Q10 calculations at multiple intervals (10–20°C, 20–30°C) and average. Calculates gradient of ln(rate) vs T: using T=10 (ln(0.0021) = −6.17) and T=37 (ln(0.0172) = −4.06): gradient = (−4.06 − (−6.17)) / (37 − 10) = 2.11/27 ≈ 0.078 °C⁻¹. Notes the sharp drop above 37°C (rate falls from 0.0172 to 0.0002 between 37°C and 55°C) as evidence of denaturation, not a simple rate decrease." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Effect of temperature on amylase reaction rate (rate = 1/time for starch disappearance)",
        xLabel: "Temperature (°C)",
        yLabel: "Reaction rate (s⁻¹)",
        editable: true,
        initialRows: [
          { x: 10, y: 0.0021 },
          { x: 20, y: 0.0048 },
          { x: 30, y: 0.0100 },
          { x: 37, y: 0.0172 },
          { x: 40, y: 0.0118 },
          { x: 45, y: 0.0055 },
          { x: 50, y: 0.0011 },
          { x: 55, y: 0.0002 },
        ],
        transforms: [
          { id: "raw", label: "Rate vs temperature", x: "x", y: "y", xLabel: "Temperature (°C)", yLabel: "Reaction rate (s⁻¹)" },
          { id: "ln", label: "ln(rate) vs temperature (linear region 10-37°C)", x: "x", y: "ln(y)", xLabel: "Temperature (°C)", yLabel: "ln(rate)" },
        ],
        derive: { kind: "gradient", label: "Rate constant (linear region 10–37°C)", unit: "s⁻¹ per °C" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the Q10 for the rising phase and determine the gradient of the ln(rate) vs temperature graph.",
        scaffolds: [
          "The trend shows that the rate...",
          "Q10 from ___°C to ___°C = rate at (T+10) / rate at T = ___ / ___ = ___",
          "This means that for every 10°C rise, the rate...",
          "From the ln(rate) vs T graph, gradient = Δln(rate) / ΔT = ___ / ___ = ___°C⁻¹",
          "The sharp fall above 37°C is explained by...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes rate increases then decreases.", keywords: ["increases", "decreases", "temperature", "rate", "falls", "rises"], minKeywords: 1 },
          { level: 4, descriptor: "Approximate doubling per 10°C noted; Q10 term used.", keywords: ["q10", "doubles", "10°c", "2", "ratio", "increase"], minKeywords: 1 },
          { level: 6, descriptor: "Q10 calculated numerically; ln(rate) gradient calculation attempted.", keywords: ["q10", "0.0048", "0.0021", "0.0100", "2.3", "gradient", "ln", "best fit", "two points"], minKeywords: 2 },
          { level: 8, descriptor: "Multiple Q10 values; ln(rate) gradient calculated with values; denaturation above 37°C noted.", keywords: ["0.0172", "0.0002", "denaturation", "gradient", "0.078", "ln", "−6.17", "−4.06", "27", "average q10", "sharp fall"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about the optimum temperature and the mechanism of the rate increase and fall.",
      guided: [
        { level: 2, body: "Level 1–2: 'The rate increased then decreased as temperature increased.'" },
        { level: 4, body: "Level 3–4: 'The rate increased from 10°C to 37°C and then decreased above 37°C. The optimum temperature for amylase appears to be around 37°C. This is consistent with amylase being a human enzyme adapted to body temperature.'" },
        { level: 6, body: "Level 5–6: 'Rate increased from 0.0021 s⁻¹ at 10°C to a maximum of 0.0172 s⁻¹ at 37°C, consistent with a Q10 of approximately 2 (rate doubles per 10°C rise). Above 37°C, rate falls sharply — to 0.0002 s⁻¹ at 55°C — due to denaturation breaking hydrogen bonds in the active site, preventing substrate binding. This is consistent with the hypothesis.'" },
        { level: 8, body: "Level 7–8: 'Rate increased exponentially from 10°C to 37°C (Q10 ≈ 2.3 per 10°C; ln(rate) vs T is approximately linear with gradient ≈ 0.078°C⁻¹), confirming the Arrhenius relationship. The optimum at 37°C matches human body temperature — evolutionary adaptation. Above 37°C, the rate fell sharply: a 100-fold decrease between 37°C and 55°C, consistent with rapid denaturation rather than a simple decrease in kinetic energy. The asymmetric bell shape (slower rise, very steep fall) confirms that two different processes operate on either side of the optimum. These data support the hypothesis.'" },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Effect of temperature on amylase reaction rate (rate = 1/time for starch disappearance)",
        xLabel: "Temperature (°C)",
        yLabel: "Reaction rate (s⁻¹)",
        editable: true,
        initialRows: [
          { x: 10, y: 0.0021 },
          { x: 20, y: 0.0048 },
          { x: 30, y: 0.0100 },
          { x: 37, y: 0.0172 },
          { x: 40, y: 0.0118 },
          { x: 45, y: 0.0055 },
          { x: 50, y: 0.0011 },
          { x: 55, y: 0.0002 },
        ],
        transforms: [
          { id: "raw", label: "Rate vs temperature", x: "x", y: "y", xLabel: "Temperature (°C)", yLabel: "Reaction rate (s⁻¹)" },
          { id: "ln", label: "ln(rate) vs temperature (linear region 10-37°C)", x: "x", y: "ln(y)", xLabel: "Temperature (°C)", yLabel: "ln(rate)" },
        ],
        derive: { kind: "gradient", label: "Rate constant (linear region 10–37°C)", unit: "s⁻¹ per °C" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. What is the optimum temperature for amylase? Explain the rise and the fall using enzyme theory, and reference specific data values.",
        scaffolds: [
          "The optimum temperature for amylase appears to be ___°C because...",
          "From 10°C to 37°C, rate increased from ___ to ___ s⁻¹ because...",
          "Above 37°C, rate fell sharply because...",
          "Q10 for the rising phase was approximately ___, indicating...",
          "These results support / partially support the hypothesis because...",
        ],
        rubric: [
          { level: 2, descriptor: "States optimum temperature and basic trend.", keywords: ["optimum", "37", "increases", "decreases", "temperature", "rate"], minKeywords: 1 },
          { level: 4, descriptor: "Optimum identified; body temperature link made; denaturation mentioned.", keywords: ["37°c", "body temperature", "denaturation", "optimum", "human", "fall", "rise"], minKeywords: 2 },
          { level: 6, descriptor: "Specific data values used; Q10 stated; denaturation mechanism explained.", keywords: ["0.0021", "0.0172", "q10", "denaturation", "hydrogen bonds", "active site", "37°c", "hypothesis", "consistent"], minKeywords: 3 },
          { level: 8, descriptor: "Arrhenius/ln(rate) referenced; 100-fold fall quantified; asymmetric bell shape explained.", keywords: ["exponential", "0.0002", "100-fold", "arrhenius", "gradient", "0.078", "asymmetric", "denaturation", "two processes", "evolutionary"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the iodine spot plate method and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could be improved by repeating the experiment.'" },
        { level: 4, body: "Level 3–4: 'Only one trial was done at each temperature, reducing reliability. The endpoint (iodine colour change) is subjective — different people may judge the colour change differently, introducing human error.'" },
        { level: 6, body: "Level 5–6: Key weaknesses: (1) Subjective colourimetric endpoint — different students may judge 'colourless' differently, causing systematic error. Improvement: use a standardised colour reference card or a colorimeter to measure light absorbance at 580 nm. (2) Temperature not fully equilibrated before mixing — enzyme may react at a different temperature. Improvement: equilibrate separately for 5 minutes before mixing. (3) Only one repeat — reducing reliability. Improvement: repeat 3 times and calculate mean rate and standard deviation.'" },
        { level: 8, body: "Level 7–8: Specific additional weaknesses: (1) Very low rates at 10°C and 55°C are measured with high uncertainty — if starch takes >30 minutes to disappear, small errors in timing have proportionally large effects on rate. A continuous colorimetric method (spectrophotometer reading absorbance every second) would give more reliable data at extremes. (2) Iodine itself is mildly inhibitory to amylase at high concentrations — using dilute iodine reduces this systematic error. (3) Enzyme may lose activity during the experiment (especially at 37°C) due to gradual denaturation — fresh enzyme should be prepared for each temperature. Each weakness links to a specific, reasoned improvement and its effect on accuracy or reliability." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Effect of temperature on amylase reaction rate (rate = 1/time for starch disappearance)",
        xLabel: "Temperature (°C)",
        yLabel: "Reaction rate (s⁻¹)",
        editable: true,
        initialRows: [
          { x: 10, y: 0.0021 },
          { x: 20, y: 0.0048 },
          { x: 30, y: 0.0100 },
          { x: 37, y: 0.0172 },
          { x: 40, y: 0.0118 },
          { x: 45, y: 0.0055 },
          { x: 50, y: 0.0011 },
          { x: 55, y: 0.0002 },
        ],
        transforms: [
          { id: "raw", label: "Rate vs temperature", x: "x", y: "y", xLabel: "Temperature (°C)", yLabel: "Reaction rate (s⁻¹)" },
          { id: "ln", label: "ln(rate) vs temperature (linear region 10-37°C)", x: "x", y: "ln(y)", xLabel: "Temperature (°C)", yLabel: "ln(rate)" },
        ],
        derive: { kind: "gradient", label: "Rate constant (linear region 10–37°C)", unit: "s⁻¹ per °C" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the iodine spot plate method used to collect these data. What are the main weaknesses and how would you improve them?",
        scaffolds: [
          "A key weakness of the iodine spot plate method is...",
          "This affects the results because...",
          "To improve this, I would...",
          "Reliability could be improved by...",
          "At extreme temperatures (10°C and 55°C), an additional problem is...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem", "repeat"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned with improvement.", keywords: ["subjective", "endpoint", "colour", "repeat", "human error", "reliable", "one trial"], minKeywords: 1 },
          { level: 6, descriptor: "Subjective endpoint and equilibration weakness with matched improvements.", keywords: ["colorimeter", "colour reference", "equilibrate", "5 min", "subjective", "systematic error", "repeat", "3 times", "mean", "standard deviation"], minKeywords: 3 },
          { level: 8, descriptor: "Extreme temperature uncertainty; iodine inhibition; enzyme degradation identified.", keywords: ["spectrophotometer", "absorbance", "dilute iodine", "inhibitory", "fresh enzyme", "30 minutes", "timing uncertainty", "proportional", "reliability", "accuracy"], minKeywords: 3 },
        ],
      },
    },
  ],
}
