import type { StrandhootPack } from "../engine/types"

export const evolutionCritA: StrandhootPack = {
  slug: "evolution-crit-a",
  title: "Inheritance & Evolution",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Genetics, natural selection and speciation",
  accent: "#1b7888",
  icon: "🦕",
  statementOfInquiry: "Scientific and technical innovations can change the impacts that we have on the world.",
  estMinutes: 25,
  intro:
    "From Mendel's pea plants to CRISPR gene editing, genetics and evolution reveal how traits are inherited, how species change over time, and how humans are now shaping the very code of life. Each strand targets a core concept from Chapter 10: Consequences, levelling up from recall to analysis.",
  badges: [
    { id: "mendel", label: "Mendel's Protégé", icon: "🧬", description: "Reach Level 8 on Mendelian genetics", strandId: "mendelian", atLevel: 8 },
    { id: "selector", label: "Natural Selector", icon: "🦋", description: "Reach Level 8 on Natural selection", strandId: "natural-selection", atLevel: 8 },
    { id: "speciation", label: "Species Splitter", icon: "🌍", description: "Reach Level 8 on Speciation", strandId: "speciation", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 10: Consequences", blurb: "Genetics, evolution, speciation and genetic engineering", icon: "🦕" }],
  strands: [
    {
      id: "mendelian",
      name: "Mendelian genetics",
      descriptor: "Understand genes, alleles, dominance and monohybrid crosses including codominance.",
      guided: [
        { level: 2, body: "A gene is a sequence of DNA that codes for a protein. Alleles are alternative forms of a gene — for example, the gene for pea seed colour has a yellow allele and a green allele. An organism has two alleles for each gene, one inherited from each parent." },
        { level: 4, body: "Genotype describes the alleles an organism has (e.g. AA, Aa, or aa); phenotype is the observable trait. Dominant alleles (written as capital letters) are expressed in the heterozygote (Aa). Recessive alleles (lowercase) are only expressed when homozygous (aa). A monohybrid cross between two heterozygotes (Aa × Aa) gives a 3:1 phenotype ratio: 1 AA : 2 Aa : 1 aa, but 3 dominant phenotype : 1 recessive phenotype." },
        { level: 6, body: "Codominance occurs when both alleles contribute equally to the phenotype — neither is dominant or recessive. In ABO blood groups, alleles I^A and I^B are both codominant: an individual with genotype I^A I^B expresses both A and B antigens and has blood group AB. The allele I^O is recessive to both. This produces four blood groups: A, B, AB, O." },
        { level: 8, body: "A full Punnett square for Aa × Aa predicts offspring in the ratio 1 AA : 2 Aa : 1 aa (genotype) and 3 dominant : 1 recessive (phenotype). The ratio arises because the dominant allele masks the recessive in Aa individuals. Codominance in blood groups contrasts sharply: I^A I^B individuals show both phenotypes simultaneously because both proteins are produced. This illustrates that dominance is not absolute — it depends on the molecular effect of the allele product at the cellular level." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "mg-l2",
            level: 2,
            prompt: "What is a gene?",
            options: [
              { id: "a", text: "A chromosome made of protein" },
              { id: "b", text: "A sequence of DNA that codes for a protein", correct: true },
              { id: "c", text: "An alternative form of an allele" },
              { id: "d", text: "The observable trait of an organism" },
            ],
            explanation: "A gene is a specific sequence of DNA that carries the instructions to make a protein. Alleles are the alternative versions of a gene.",
          },
          {
            type: "fill",
            id: "mg-l4",
            level: 4,
            prompt: "A monohybrid cross between two heterozygotes (Aa × Aa) produces a dominant to recessive phenotype ratio of ▁.",
            answers: ["3:1", "3 to 1", "three to one"],
            explanation: "The Punnett square for Aa × Aa gives 1 AA, 2 Aa, 1 aa. The three individuals with at least one A allele express the dominant phenotype, giving a 3:1 ratio.",
          },
          {
            type: "short",
            id: "mg-l6",
            level: 6,
            prompt: "Explain what is meant by codominance, using ABO blood groups as an example. What phenotype does the genotype I^A I^B produce, and why?",
            keywords: ["codominance", "both", "expressed", "alleles", "blood group", "ab", "antigens", "phenotype", "dominant", "recessive"],
            minKeywords: 2,
            sample: "Codominance is when both alleles are expressed equally in the heterozygote — neither is dominant or recessive. In the ABO blood group system, alleles I^A and I^B are codominant. An individual with genotype I^A I^B produces both A and B antigens on their red blood cells, giving blood group AB. Both alleles contribute to the phenotype simultaneously.",
          },
          {
            type: "short",
            id: "mg-l8",
            level: 8,
            prompt: "Construct the full Punnett square for a monohybrid cross between two heterozygotes (Aa × Aa). State the genotype and phenotype ratios and explain why the 3:1 phenotype ratio arises. How does codominance in I^A I^B blood group contrast with this pattern of dominance?",
            keywords: ["punnett", "1aa", "2aa", "1aa", "genotype", "phenotype", "3:1", "dominant", "masks", "recessive", "codominance", "i^a i^b", "both", "protein"],
            minKeywords: 3,
            sample: "Punnett square: gametes A and a from each parent give offspring AA : Aa : Aa : aa = 1:2:1 genotype ratio. Phenotype ratio = 3 dominant : 1 recessive because A is dominant and masks a in the Aa heterozygotes. Codominance in blood groups contrasts sharply: I^A I^B individuals express both A and B antigens because both allele products (glycoproteins) are made and present on red blood cells — dominance here is not about one allele being silenced but about the molecular products of both alleles being independently functional.",
          },
        ],
      },
    },
    {
      id: "natural-selection",
      name: "Natural selection",
      descriptor: "Explain Darwin's mechanism of natural selection with reference to variation, competition and allele frequency.",
      guided: [
        { level: 2, body: "Darwin's theory of natural selection has four key ideas: (1) variation exists within a population, (2) there is competition for limited resources, (3) individuals with advantageous traits are more likely to survive and reproduce ('survival of the fittest'), (4) these advantageous traits are passed on to offspring." },
        { level: 4, body: "Variation arises from mutation (random changes in DNA) and sexual reproduction (new allele combinations). Individuals with alleles giving them an advantage in their environment are more likely to survive and reproduce — so those alleles become more frequent in the population over generations. This is a change in allele frequency, the mechanism of microevolution." },
        { level: 6, body: "The peppered moth (Biston betularia) illustrates industrial melanism: before industrialisation, pale moths were camouflaged on pale tree bark and survived predation better than dark moths. After pollution darkened bark with soot, dark moths survived better. The frequency of the dark (melanic) allele increased dramatically in industrial areas — the environment changed the selection pressure." },
        { level: 8, body: "Antibiotic resistance in bacteria is natural selection operating in real time: a population of bacteria contains rare individuals with a resistance allele (from random mutation). Antibiotic treatment kills sensitive bacteria but the resistant ones survive and reproduce — rapidly shifting allele frequency toward resistance. Darwin's finches on the Galápagos demonstrate adaptive radiation: geographic isolation on different islands, combined with different food sources, drove beak shape variation via natural selection — thick beaks for cracking seeds, thin beaks for probing flowers. Together these examples confirm variation + selection pressure + inheritance → directional change in allele frequency over time." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "ns-l2",
            level: 2,
            prompt: "According to Darwin's theory of natural selection, which individuals are most likely to survive and reproduce?",
            options: [
              { id: "a", text: "The largest individuals in the population" },
              { id: "b", text: "The oldest individuals in the population" },
              { id: "c", text: "Individuals with advantageous traits for their environment", correct: true },
              { id: "d", text: "Individuals that reproduce the slowest" },
            ],
            explanation: "Natural selection favours individuals with traits that give them an advantage in their specific environment — they survive and pass on those traits to offspring.",
          },
          {
            type: "fill",
            id: "ns-l4",
            level: 4,
            prompt: "In natural selection, advantageous alleles become more frequent in a population over time because individuals carrying them are more likely to survive and ▁.",
            answers: ["reproduce", "breed", "pass on their genes", "pass on their alleles"],
            explanation: "Survival alone is not enough — individuals must reproduce to pass advantageous alleles to the next generation. Over many generations, this shifts allele frequencies.",
          },
          {
            type: "short",
            id: "ns-l6",
            level: 6,
            prompt: "Explain how the peppered moth (Biston betularia) provides evidence for natural selection. Why did the frequency of dark moths change in industrial areas?",
            keywords: ["peppered moth", "melanis", "dark", "pale", "camouflage", "bark", "predation", "soot", "pollution", "allele", "frequency", "survived"],
            minKeywords: 2,
            sample: "Before industrialisation, pale-coloured moths were camouflaged against pale tree bark and were less likely to be eaten by birds. Dark moths were more visible and more often predated, so the dark allele was rare. After industrial pollution coated bark with soot, the dark moths became better camouflaged and survived longer to reproduce. The frequency of the dark allele increased in industrial areas — a direct result of the changed selection pressure from the environment.",
          },
          {
            type: "short",
            id: "ns-l8",
            level: 8,
            prompt: "Use antibiotic resistance in bacteria AND Darwin's finches to explain how natural selection produces directional change in allele frequency. What is the role of variation, selection pressure, and inheritance in each example?",
            keywords: ["variation", "mutation", "resistance", "allele", "frequency", "selection pressure", "antibiotic", "survive", "reproduce", "finches", "beak", "adaptive", "inheritance", "directional"],
            minKeywords: 3,
            sample: "In bacteria: variation arises from random mutations giving some individuals a resistance allele. Antibiotic treatment is a selection pressure — sensitive bacteria die, resistant ones survive and reproduce, rapidly shifting allele frequency toward resistance over many generations. In Darwin's finches: variation in beak shape (from genetic variation) was acted on by different food availability on each island (selection pressure). Birds with beak shapes suited to available food survived and reproduced; others did not. Over generations, allele frequencies for beak genes shifted on each island independently. Both examples show: variation (existing genetic differences) + selection pressure (environmental challenge) + inheritance (passing alleles to offspring) = directional change in allele frequency = evolution by natural selection.",
          },
        ],
      },
    },
    {
      id: "speciation",
      name: "Speciation",
      descriptor: "Explain allopatric speciation through geographic isolation, divergence and reproductive isolation.",
      guided: [
        { level: 2, body: "Speciation is the formation of a new species. A species is defined as a group of organisms that can interbreed and produce fertile offspring. New species form when populations become reproductively isolated — unable to interbreed." },
        { level: 4, body: "Allopatric speciation occurs when a geographic barrier (mountain range, sea level rise, river) splits a population into two isolated groups. The two populations can no longer interbreed and gene flow stops. They evolve separately under different selection pressures and accumulate different mutations. Eventually they become so different they cannot interbreed even if the barrier is removed — a new species has formed." },
        { level: 6, body: "Reproductive isolation can occur in several ways: different mating seasons (temporal isolation), incompatible gametes (gametic isolation), or chromosomal changes preventing viable offspring (post-zygotic isolation). Ring species demonstrate speciation in progress — the herring gull (Larus argentatus) and lesser black-backed gull (Larus fuscus) are two species that cannot interbreed at the ends of their range, but are connected by a chain of interbreeding populations forming a ring around the Arctic." },
        { level: 8, body: "Molecular evidence strongly supports the fossil and morphological evidence for speciation: cytochrome c is a mitochondrial protein. The more similar the cytochrome c amino acid sequence between two species, the more recently they shared a common ancestor. Humans and chimpanzees share 99% identity in cytochrome c; humans and yeast share about 66% identity — quantifying the divergence time and evolutionary distance. Sympatric speciation (without geographic isolation) can occur through polyploidy in plants — chromosome number doubles in a hybrid, creating a new species reproductively isolated from both parents (e.g. allotetraploid bread wheat, Triticum aestivum, has 6 chromosome sets from three ancestral species)." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "sp-l2",
            level: 2,
            prompt: "What is the biological definition of a species?",
            options: [
              { id: "a", text: "A group of organisms that look identical" },
              { id: "b", text: "A group of organisms that live in the same habitat" },
              { id: "c", text: "A group of organisms that can interbreed and produce fertile offspring", correct: true },
              { id: "d", text: "A group of organisms with the same number of chromosomes" },
            ],
            explanation: "The biological species concept defines a species as a group of organisms that can interbreed with each other to produce fertile offspring, but cannot interbreed with members of other species.",
          },
          {
            type: "fill",
            id: "sp-l4",
            level: 4,
            prompt: "Allopatric speciation begins when a population is split by a ▁ barrier, preventing the two groups from interbreeding.",
            answers: ["geographic", "geographical", "physical"],
            explanation: "Allopatric speciation requires a geographic barrier (mountain range, sea, river) that stops gene flow between populations, allowing them to evolve independently.",
          },
          {
            type: "short",
            id: "sp-l6",
            level: 6,
            prompt: "Explain the difference between geographic isolation and reproductive isolation. Why is reproductive isolation the key step in speciation?",
            keywords: ["geographic", "isolation", "reproductive", "gene flow", "interbreed", "barrier", "speciation", "fertile", "mating", "gametes"],
            minKeywords: 2,
            sample: "Geographic isolation is a physical barrier (mountain, sea) that prevents two populations from meeting and interbreeding — it stops gene flow. Reproductive isolation means the two populations cannot successfully interbreed even if the geographic barrier is removed, because of differences in mating behaviour, gamete compatibility, or chromosome number. Reproductive isolation is the key step because it is the permanent split — once populations cannot interbreed, they cannot exchange genes and will diverge indefinitely into separate species.",
          },
          {
            type: "short",
            id: "sp-l8",
            level: 8,
            prompt: "Explain how molecular evidence from cytochrome c supports the theory of evolution. How does ring species evidence differ from this? What does polyploidy demonstrate about speciation without geographic isolation?",
            keywords: ["cytochrome c", "amino acid", "sequence", "similarity", "common ancestor", "divergence", "molecular", "ring species", "interbreed", "herring gull", "polyploidy", "chromosome", "sympatric", "wheat"],
            minKeywords: 3,
            sample: "Cytochrome c is a mitochondrial protein present in almost all eukaryotes. Species that share a more recent common ancestor have more similar cytochrome c amino acid sequences — e.g. humans and chimpanzees share ~99% identity, while humans and yeast share ~66%. The greater the sequence difference, the longer ago the evolutionary split occurred. This molecular evidence independently confirms divergence predicted by fossil records. Ring species (e.g. herring gull / lesser black-backed gull) show speciation in progress — a chain of interbreeding populations forms a ring, with the terminal populations unable to interbreed, demonstrating reproductive isolation emerging gradually. Polyploidy (e.g. bread wheat) shows sympatric speciation without geographic isolation: chromosome doubling in a hybrid instantly produces a reproductively isolated new species.",
          },
        ],
      },
    },
    {
      id: "genetic-modification",
      name: "Genetic modification and cloning",
      descriptor: "Describe the techniques of GMO production, CRISPR-Cas9 gene editing and reproductive/therapeutic cloning.",
      guided: [
        { level: 2, body: "Genetic modification (GM) means changing the DNA of an organism. Scientists can insert a gene from one organism into another — for example, inserting the human insulin gene into bacteria so the bacteria produce human insulin for diabetics." },
        { level: 4, body: "The process of making a GMO: (1) restriction enzymes cut the target gene from donor DNA; (2) the same enzyme cuts the vector (usually a plasmid — circular bacterial DNA); (3) DNA ligase joins the gene into the plasmid; (4) the recombinant plasmid is inserted into host cells (transformation); (5) host cells that have taken up the plasmid produce the protein. Examples: insulin from E. coli, golden rice (producing provitamin A), Bt crops (producing Bacillus thuringiensis insect toxin)." },
        { level: 6, body: "CRISPR-Cas9 is a precise gene editing tool: a guide RNA (gRNA) matches the target DNA sequence; the Cas9 enzyme (a molecular 'scissors') cuts both strands of DNA at that site; the cell's repair mechanisms can then delete, correct, or insert a gene. Reproductive cloning (somatic cell nuclear transfer) involves removing the nucleus from an egg cell, replacing it with the nucleus from an adult body cell, stimulating the egg to divide, and implanting it into a surrogate — Dolly the sheep (1996) was the first mammal cloned this way. Therapeutic cloning uses the same technique to produce embryonic stem cells genetically matched to the patient — avoiding immune rejection." },
        { level: 8, body: "Each technique presents specific ethical dimensions: GM crops (e.g. golden rice prevents Vitamin A deficiency in 250 million at-risk children) vs ecological risks of gene flow to wild relatives creating herbicide-resistant 'superweeds'. CRISPR-Cas9: Casgevy (2023) is the first approved CRISPR treatment for sickle cell disease (cost $2.2 million per patient) — uses CRISPR to restore fetal haemoglobin production. Therapeutic cloning avoids immune rejection because the patient's own nuclear DNA is used. Reproductive cloning has high failure rates and premature aging risks (Dolly showed early arthritis and lung disease, euthanised at 6 years vs typical 11–12 years for sheep). Each technique illustrates how genetic innovations alter our impacts on the living world — the central statement of inquiry." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "gm-l2",
            level: 2,
            prompt: "Which enzyme is used to join a gene into a plasmid vector during the production of a GMO?",
            options: [
              { id: "a", text: "Restriction enzyme" },
              { id: "b", text: "DNA polymerase" },
              { id: "c", text: "DNA ligase", correct: true },
              { id: "d", text: "RNA polymerase" },
            ],
            explanation: "DNA ligase is the 'joining enzyme' — it bonds the gene into the cut plasmid by forming phosphodiester bonds. Restriction enzymes cut the DNA; ligase seals the join.",
          },
          {
            type: "fill",
            id: "gm-l4",
            level: 4,
            prompt: "In CRISPR-Cas9 gene editing, the ▁ RNA guides the Cas9 enzyme to the correct target sequence in the genome.",
            answers: ["guide", "gRNA", "guide RNA"],
            explanation: "The guide RNA (gRNA) is a short RNA sequence complementary to the target DNA. It forms a complex with Cas9 and directs it precisely to the correct location in the genome.",
          },
          {
            type: "short",
            id: "gm-l6",
            level: 6,
            prompt: "Outline the steps in making a genetically modified bacterium to produce human insulin. Name the enzymes involved at each stage.",
            keywords: ["restriction enzyme", "ligase", "plasmid", "vector", "transformation", "insulin gene", "dna", "recombinant", "host", "bacteria"],
            minKeywords: 2,
            sample: "Step 1: Use a restriction enzyme to cut the human insulin gene from human DNA, and the same enzyme to cut a bacterial plasmid (vector) — both cuts produce complementary sticky ends. Step 2: Mix the gene and plasmid together; DNA ligase joins them by forming phosphodiester bonds, creating a recombinant plasmid. Step 3: Introduce the recombinant plasmid into E. coli bacteria (transformation). Step 4: Select bacteria that have taken up the plasmid; these bacteria now transcribe and translate the human insulin gene, producing human insulin protein.",
          },
          {
            type: "short",
            id: "gm-l8",
            level: 8,
            prompt: "Compare reproductive cloning and therapeutic cloning. Why does therapeutic cloning avoid immune rejection? What ethical issues arise from each?",
            keywords: ["reproductive", "therapeutic", "cloning", "somatic cell", "nuclear transfer", "stem cells", "immune rejection", "dolly", "embryo", "nucleus", "surrogate", "patient", "ethical"],
            minKeywords: 3,
            sample: "Both use somatic cell nuclear transfer (SCNT): the nucleus from an adult body cell is inserted into an enucleated egg cell. In reproductive cloning (e.g. Dolly the sheep, 1996), the embryo is implanted into a surrogate and a cloned animal is born. In therapeutic cloning, the embryo is grown in vitro and embryonic stem cells are harvested — the embryo is not implanted. Therapeutic cloning avoids immune rejection because the stem cells carry the patient's own nuclear DNA (genetically identical to the recipient). Ethical issues: reproductive cloning involves high failure rates and health risks (premature aging); for humans it raises issues of identity and exploitation. Therapeutic cloning requires destroying a human embryo for stem cell harvest, which many regard as ethically unacceptable. Both challenge the view that humans should not interfere with fundamental biological processes.",
          },
        ],
      },
    },
  ],
}
