import type { StrandhootPack } from "../engine/types"

export const evolutionCritC: StrandhootPack = {
  slug: "evolution-crit-c",
  title: "Natural Selection Dataset",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Allele frequency over generations",
  accent: "#0984b5",
  icon: "🦕",
  statementOfInquiry: "Scientific and technical innovations can change the impacts that we have on the world.",
  estMinutes: 30,
  intro:
    "A population genetics model tracks how the frequency of a deleterious recessive allele (q) declines over 35 generations of directional natural selection. Use the data tool to plot, transform and analyse — then draw a conclusion about microevolution and evaluate the model. Each written strand levels up with the depth of your scientific reasoning.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Evolution Analyst", icon: "🧬", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "evaluator", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Allele frequency dataset", blurb: "Decline of a deleterious recessive allele under natural selection", icon: "📉" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the allele frequency data and apply the 1/q linearising transform.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with generation and allele frequency values, but missing headings or units." },
        { level: 4, body: "Level 3–4: A clear table with column headings (Generation; Recessive allele frequency q) and a graph with both axes labelled correctly. The graph shows allele frequency falling from 0.50 to 0.11 over 35 generations." },
        { level: 6, body: "Level 5–6: Axes labelled with units, a sensible scale filling the grid, points accurately plotted with a smooth curve of best fit showing the decelerating decline. The rate of decrease slows over time — the curve flattens as q gets smaller." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised 1/q vs generation plot. Selection theory predicts that 1/q should change linearly with generation (selection equation: 1/q_t = 1/q_0 + s·t, where s is the selection coefficient). A straight line confirms directional selection; the gradient gives the selection coefficient s — the rate of change of 1/q per generation." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Decline in frequency of a deleterious recessive allele (q) under directional natural selection",
        xLabel: "Generation",
        yLabel: "Recessive allele frequency (q)",
        editable: true,
        initialRows: [
          { x: 0, y: 0.50 },
          { x: 5, y: 0.40 },
          { x: 10, y: 0.32 },
          { x: 15, y: 0.26 },
          { x: 20, y: 0.21 },
          { x: 25, y: 0.17 },
          { x: 30, y: 0.14 },
          { x: 35, y: 0.11 },
        ],
        transforms: [
          { id: "raw", label: "Allele frequency vs generation", x: "x", y: "y", xLabel: "Generation", yLabel: "Recessive allele frequency (q)" },
          { id: "inv", label: "1/q vs generation (linearise selection dynamics)", x: "x", y: "1/y", xLabel: "Generation", yLabel: "1/q" },
        ],
        derive: { kind: "gradient", label: "Selection rate (change in 1/q per generation)", unit: "per generation" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid? What does the shape of the raw curve tell you?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted recessive allele frequency (q) on the y-axis against...",
          "The graph shows a... trend because...",
          "I linearised the data by plotting 1/q vs generation because...",
          "The straight line on the 1/q plot confirms...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "data", "allele", "generation", "frequency"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "generation", "frequency", "q"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve of best fit; decelerating decline described.", keywords: ["curve", "best fit", "decreases", "smooth", "decelerating", "flattens", "slower", "scale"], minKeywords: 2 },
          { level: 8, descriptor: "1/q linearisation described as straight line; gradient interpretation stated.", keywords: ["1/q", "straight line", "linear", "selection coefficient", "gradient", "transform", "s·t", "selection equation"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient of the 1/q vs generation plot and determine the selection coefficient.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('allele frequency decreases over generations')." },
        { level: 4, body: "Level 3–4: Notes the total change in q (from 0.50 to 0.11 over 35 generations) and that the decrease is not constant — the rate slows over time as the recessive allele becomes rarer." },
        { level: 6, body: "Level 5–6: From the 1/q vs generation graph, draws a line of best fit and reads off two widely-spaced points to calculate gradient = Δ(1/q) / Δgeneration. At generation 0: 1/q = 1/0.50 = 2.0. At generation 35: 1/q = 1/0.11 ≈ 9.09. Gradient ≈ (9.09 − 2.0) / (35 − 0) = 7.09 / 35 ≈ 0.20 per generation. States the unit of gradient as per generation." },
        { level: 8, body: "Level 7–8: Full calculation shown — gradient ≈ 0.20 per generation represents the selection coefficient s. The selection equation predicts 1/q_t = 1/q_0 + s·t: check: 1/0.50 + 0.20 × 35 = 2.0 + 7.0 = 9.0 ≈ observed 1/0.11 = 9.09. The close agreement confirms the model. The selection coefficient s ≈ 0.20 means homozygous recessive individuals (qq) have a 20% lower reproductive fitness than the dominant class. Note: the decline decelerates because rare recessive alleles are 'hidden' in heterozygotes (Qq), which are phenotypically normal and not selected against." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Decline in frequency of a deleterious recessive allele (q) under directional natural selection",
        xLabel: "Generation",
        yLabel: "Recessive allele frequency (q)",
        editable: true,
        initialRows: [
          { x: 0, y: 0.50 },
          { x: 5, y: 0.40 },
          { x: 10, y: 0.32 },
          { x: 15, y: 0.26 },
          { x: 20, y: 0.21 },
          { x: 25, y: 0.17 },
          { x: 30, y: 0.14 },
          { x: 35, y: 0.11 },
        ],
        transforms: [
          { id: "raw", label: "Allele frequency vs generation", x: "x", y: "y", xLabel: "Generation", yLabel: "Recessive allele frequency (q)" },
          { id: "inv", label: "1/q vs generation (linearise selection dynamics)", x: "x", y: "1/y", xLabel: "Generation", yLabel: "1/q" },
        ],
        derive: { kind: "gradient", label: "Selection rate (change in 1/q per generation)", unit: "per generation" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the 1/q vs generation graph and use it to find the selection coefficient s. Show full working.",
        scaffolds: [
          "The trend shows that allele frequency q...",
          "From the 1/q plot I chose two points: at generation 0, 1/q = ... and at generation 35, 1/q = ...",
          "Gradient = Δ(1/q) / Δgeneration = ... / ... = ... per generation",
          "This gradient equals the selection coefficient s ≈ ...",
          "This means homozygous recessive individuals have a ___% lower reproductive fitness because...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes allele frequency decreases with generation.", keywords: ["decreases", "generation", "allele", "frequency", "q", "trend", "falls"], minKeywords: 1 },
          { level: 4, descriptor: "Notes rate of decrease slows; total change quantified.", keywords: ["slows", "decelerates", "0.50", "0.11", "35 generations", "rate", "not constant"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated from 1/q plot with working shown.", keywords: ["gradient", "1/q", "2.0", "9.09", "0.20", "per generation", "two points", "best fit", "δ(1/q)"], minKeywords: 2 },
          { level: 8, descriptor: "Selection coefficient named; model verified; heterozygote protection explained.", keywords: ["selection coefficient", "s = 0.20", "20%", "fitness", "heterozygote", "hidden", "qq", "qq", "model", "verify", "1/q_0 + s·t"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about microevolution by natural selection and explain why q never reaches zero.",
      guided: [
        { level: 2, body: "Level 1–2: 'The recessive allele frequency decreased over 35 generations.'" },
        { level: 4, body: "Level 3–4: 'The recessive allele frequency fell from 0.50 to 0.11 over 35 generations, showing that natural selection reduced the frequency of the deleterious allele. However, it did not reach zero.'" },
        { level: 6, body: "Level 5–6: 'The allele frequency decreased from q = 0.50 to q = 0.11, confirming that directional natural selection reduces the frequency of a deleterious recessive allele over time. The 1/q vs generation plot is approximately linear (gradient ≈ 0.20 per generation), consistent with the selection equation. The allele declines but never reaches zero — this is because rare recessive alleles are protected from selection when hidden in heterozygotes (Qq), who have a normal phenotype and are not selected against.'" },
        { level: 8, body: "Level 7–8: Full conclusion using model and data: the gradient of the 1/q plot (≈ 0.20 per generation) gives the selection coefficient s, meaning qq individuals have 20% lower reproductive fitness. The model accurately predicts observed q values (predicted q₃₅ ≈ 0.11). The fundamental asymptote — why q can never reach zero — is explained by heterozygote protection: rare deleterious recessive alleles are sheltered from selection in Qq heterozygotes. This is why recessive genetic diseases (e.g. cystic fibrosis, sickle cell) persist at low frequencies in human populations even under strong selection against the homozygous phenotype." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Decline in frequency of a deleterious recessive allele (q) under directional natural selection",
        xLabel: "Generation",
        yLabel: "Recessive allele frequency (q)",
        editable: true,
        initialRows: [
          { x: 0, y: 0.50 },
          { x: 5, y: 0.40 },
          { x: 10, y: 0.32 },
          { x: 15, y: 0.26 },
          { x: 20, y: 0.21 },
          { x: 25, y: 0.17 },
          { x: 30, y: 0.14 },
          { x: 35, y: 0.11 },
        ],
        transforms: [
          { id: "raw", label: "Allele frequency vs generation", x: "x", y: "y", xLabel: "Generation", yLabel: "Recessive allele frequency (q)" },
          { id: "inv", label: "1/q vs generation (linearise selection dynamics)", x: "x", y: "1/y", xLabel: "Generation", yLabel: "1/q" },
        ],
        derive: { kind: "gradient", label: "Selection rate (change in 1/q per generation)", unit: "per generation" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. Does the data support the theory of natural selection? Why does the recessive allele frequency never reach zero? Use specific data values and explain the role of heterozygotes.",
        scaffolds: [
          "The data show that from generation 0 to generation 35, the allele frequency q...",
          "This supports the theory of natural selection because...",
          "The 1/q vs generation plot is (approximately) linear, which confirms...",
          "The allele frequency never reaches zero because...",
          "This explains why recessive genetic diseases persist at low frequencies — for example...",
        ],
        rubric: [
          { level: 2, descriptor: "States allele frequency decreased with generation.", keywords: ["decreases", "frequency", "generation", "allele", "selection", "q"], minKeywords: 1 },
          { level: 4, descriptor: "Quantified decrease; did not reach zero stated.", keywords: ["0.50", "0.11", "35 generations", "not zero", "deleterious", "natural selection", "direction"], minKeywords: 1 },
          { level: 6, descriptor: "1/q linearity cited; heterozygote protection explained.", keywords: ["1/q", "linear", "gradient", "0.20", "heterozygote", "hidden", "qq", "phenotype", "selection equation"], minKeywords: 3 },
          { level: 8, descriptor: "Selection coefficient interpreted; real-world genetic disease example; asymptote explained.", keywords: ["selection coefficient", "s = 0.20", "20%", "fitness", "heterozygote protection", "cystic fibrosis", "sickle cell", "persist", "low frequency", "asymptote"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify limitations of the population genetics model and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The model is not completely accurate.'" },
        { level: 4, body: "Level 3–4: 'The model assumes a large, ideal population where mating is random. Real populations are smaller and mating may not be random, which could cause genetic drift.'" },
        { level: 6, body: "Level 5–6: 'The model assumes: (1) infinite population size — in reality, small populations experience genetic drift (random fluctuations in allele frequency independent of selection), which could cause the allele to drift to extinction or fixation by chance. (2) Random mating — assortative mating or inbreeding alters Hardy-Weinberg equilibrium. (3) No mutation — new deleterious alleles arise constantly by mutation, providing an input that counteracts selection.'" },
        { level: 8, body: "Level 7–8: Comprehensive evaluation: (1) Genetic drift: in small populations (N < 100), drift can overwhelm selection — the allele could fix or be lost by chance regardless of fitness. This is why conservation genetics faces the 'bottleneck' problem. (2) Mutation-selection balance: at equilibrium, deleterious alleles persist at frequency q = √(μ/s), where μ is the mutation rate and s the selection coefficient. For cystic fibrosis: s ≈ 0.02 (reduced fitness of CF homozygotes), μ ≈ 6.7 × 10⁻⁷ → q ≈ 0.006, close to observed ~0.02 (heterozygote advantage may also contribute). (3) Environmental change: the model assumes constant selection pressure, but selection coefficients change if the environment changes." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Decline in frequency of a deleterious recessive allele (q) under directional natural selection",
        xLabel: "Generation",
        yLabel: "Recessive allele frequency (q)",
        editable: true,
        initialRows: [
          { x: 0, y: 0.50 },
          { x: 5, y: 0.40 },
          { x: 10, y: 0.32 },
          { x: 15, y: 0.26 },
          { x: 20, y: 0.21 },
          { x: 25, y: 0.17 },
          { x: 30, y: 0.14 },
          { x: 35, y: 0.11 },
        ],
        transforms: [
          { id: "raw", label: "Allele frequency vs generation", x: "x", y: "y", xLabel: "Generation", yLabel: "Recessive allele frequency (q)" },
          { id: "inv", label: "1/q vs generation (linearise selection dynamics)", x: "x", y: "1/y", xLabel: "Generation", yLabel: "1/q" },
        ],
        derive: { kind: "gradient", label: "Selection rate (change in 1/q per generation)", unit: "per generation" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the population genetics model. What assumptions does it make? What are the main limitations and how would you improve or extend the model?",
        scaffolds: [
          "A key assumption of the model is...",
          "In reality, this assumption fails because...",
          "This limitation affects the result because...",
          "Genetic drift would be significant if...",
          "To improve the model, I would...",
        ],
        rubric: [
          { level: 2, descriptor: "States the model has limitations or assumptions.", keywords: ["assumption", "limitation", "model", "real", "population", "accurate"], minKeywords: 1 },
          { level: 4, descriptor: "One specific assumption named with effect.", keywords: ["infinite population", "random mating", "genetic drift", "small population", "assumption", "real"], minKeywords: 1 },
          { level: 6, descriptor: "Multiple limitations including drift, mutation and mating.", keywords: ["genetic drift", "small population", "mutation", "random mating", "hardy-weinberg", "assortative", "inbreeding", "constant selection"], minKeywords: 2 },
          { level: 8, descriptor: "Quantified drift threshold; mutation-selection balance; environmental change.", keywords: ["n < 100", "drift", "mutation-selection balance", "μ/s", "cystic fibrosis", "s = 0.02", "heterozygote advantage", "environmental change", "bottleneck", "fixation"], minKeywords: 3 },
        ],
      },
    },
  ],
}
