import type { StrandhootPack } from "../engine/types"

// Crit C data: DNA fragment size vs migration distance in agarose gel electrophoresis.
// Larger fragments migrate shorter distances; the relationship is exponential.
// Linearising with ln(size) vs distance gives a straight line — the van't Hoff of gel electrophoresis.
// Gradient = ln(bp) per mm; used to calculate sizes of unknown fragments.
export const geneticsCritC: StrandhootPack = {
  slug: "genetics-crit-c",
  title: "DNA Gel Electrophoresis",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Fragment size vs migration distance dataset",
  accent: "#0984b5",
  icon: "🧬",
  statementOfInquiry: "Observing patterns allows scientists to propose new theories that explain how the living world works.",
  estMinutes: 30,
  intro:
    "A DNA ladder was run through an agarose gel. Use the data tool to plot the migration distances against fragment sizes, linearise the exponential relationship, and calculate the gradient — then draw a conclusion about gel electrophoresis and evaluate the method. Each written strand levels up with the depth of your scientific reasoning.",
  badges: [
    { id: "presenter", label: "Gel Grapher", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "DNA Detective", icon: "🔬", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Gel electrophoresis dataset", blurb: "Fragment size vs migration distance in agarose gel", icon: "🧬" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the gel electrophoresis data and apply a linearising transform.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with data values, but missing headings or units. A graph plotted without axis labels." },
        { level: 4, body: "Level 3–4: A clear table with column headings (migration distance in mm; DNA fragment size in base pairs) and a graph with both axes labelled including units. Points plotted accurately." },
        { level: 6, body: "Level 5–6: Axes labelled with units, a sensible scale that fills the grid, points accurately plotted with a smooth curve of best fit showing the exponential decrease in fragment size with migration distance. Trend described: larger fragments migrate shorter distances." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised graph of ln(size) vs migration distance. If the relationship is exponential, this transform gives a straight line — confirming the exponential model. The gradient of the ln(size) vs distance line gives the rate of size decrease per mm and is used to calculate the size of unknown DNA fragments in forensic or medical applications." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "DNA fragment size vs migration distance in agarose gel electrophoresis (DNA ladder)",
        xLabel: "Migration distance (mm)",
        yLabel: "DNA fragment size (base pairs)",
        editable: true,
        initialRows: [
          { x: 10, y: 5000 },
          { x: 15, y: 2000 },
          { x: 20, y: 1000 },
          { x: 25, y: 500 },
          { x: 30, y: 250 },
          { x: 35, y: 125 },
          { x: 40, y: 65 },
          { x: 45, y: 32 },
        ],
        transforms: [
          { id: "raw", label: "Fragment size vs migration distance", x: "x", y: "y", xLabel: "Distance (mm)", yLabel: "Size (bp)" },
          { id: "ln", label: "ln(size) vs migration distance (linearise exponential relationship)", x: "x", y: "ln(y)", xLabel: "Distance (mm)", yLabel: "ln(size)" },
        ],
        derive: { kind: "gradient", label: "Size decrease per mm migration", unit: "ln(bp) per mm" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted fragment size on the y-axis against migration distance on...",
          "The graph shows a... trend because...",
          "I linearised the data by plotting ln(size) vs distance because...",
          "The straight line on the linearised plot confirms...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "data", "size", "distance", "fragment"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "base pairs", "mm", "distance", "size"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve of best fit; exponential trend described.", keywords: ["curve", "best fit", "decreases", "exponential", "smooth", "larger", "shorter", "migrate"], minKeywords: 2 },
          { level: 8, descriptor: "Linearised ln(size) vs distance plot described as a straight line.", keywords: ["ln", "straight line", "linear", "transform", "gradient", "exponential", "confirm", "model"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient of the linearised plot and interpret the size decrease per mm.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('larger fragments moved less far')." },
        { level: 4, body: "Level 3–4: Notes that fragment size drops from 5000 bp at 10 mm to 32 bp at 45 mm — a very large and non-linear (exponential) decrease across a 35 mm range." },
        { level: 6, body: "Level 5–6: From the ln(size) vs distance graph, draws a line of best fit and reads off two widely-spaced points to calculate gradient = Δln(size) / Δ(distance). States the unit of gradient as ln(bp) per mm. The negative gradient confirms that size decreases exponentially with distance." },
        { level: 8, body: "Level 7–8: Full calculation shown — using two points from the linearised plot, e.g. (10, ln 5000) = (10, 8.52) and (45, ln 32) = (45, 3.47). Gradient = (3.47 − 8.52) / (45 − 10) = −5.05 / 35 ≈ −0.144 ln(bp) per mm. This means for each additional mm of migration, ln(size) decreases by 0.144, i.e. fragment size decreases by a factor of e⁰·¹⁴⁴ ≈ 1.15× per mm. This gradient can be used to calculate unknown fragment sizes: size = e^(intercept + gradient × distance)." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "DNA fragment size vs migration distance in agarose gel electrophoresis (DNA ladder)",
        xLabel: "Migration distance (mm)",
        yLabel: "DNA fragment size (base pairs)",
        editable: true,
        initialRows: [
          { x: 10, y: 5000 },
          { x: 15, y: 2000 },
          { x: 20, y: 1000 },
          { x: 25, y: 500 },
          { x: 30, y: 250 },
          { x: 35, y: 125 },
          { x: 40, y: 65 },
          { x: 45, y: 32 },
        ],
        transforms: [
          { id: "raw", label: "Fragment size vs migration distance", x: "x", y: "y", xLabel: "Distance (mm)", yLabel: "Size (bp)" },
          { id: "ln", label: "ln(size) vs migration distance (linearise exponential relationship)", x: "x", y: "ln(y)", xLabel: "Distance (mm)", yLabel: "ln(size)" },
        ],
        derive: { kind: "gradient", label: "Size decrease per mm migration", unit: "ln(bp) per mm" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the ln(size) vs migration distance graph and interpret what it tells you about the rate of size decrease.",
        scaffolds: [
          "The trend shows that as migration distance increases, fragment size...",
          "From the linearised plot I chose two points: (distance₁, ln size₁) = ... and (distance₂, ln size₂) = ...",
          "Gradient = Δln(size) / Δ(distance) = ... / ... = ... ln(bp) per mm",
          "This means for each additional mm of migration, the fragment size...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes that fragment size decreases with distance.", keywords: ["decreases", "distance", "size", "further", "smaller", "fragment"], minKeywords: 1 },
          { level: 4, descriptor: "Describes exponential decrease; range noted.", keywords: ["exponential", "5000", "32", "35 mm", "large", "non-linear", "range"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated from linearised graph with working.", keywords: ["gradient", "ln", "two points", "best fit", "delta", "slope", "ln(bp) per mm", "negative"], minKeywords: 2 },
          { level: 8, descriptor: "Full gradient calculation shown with interpretation and use for unknown sizing.", keywords: ["8.52", "3.47", "0.144", "−5.05", "35", "unknown", "intercept", "e^", "factor", "per mm"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about the relationship between fragment size and migration distance and link to DNA profiling applications.",
      guided: [
        { level: 2, body: "Level 1–2: 'Larger DNA fragments moved less far on the gel.'" },
        { level: 4, body: "Level 3–4: 'Fragment size decreased as migration distance increased. The relationship was non-linear — larger fragments showed a much smaller decrease in migration distance for each increase in size.'" },
        { level: 6, body: "Level 5–6: 'Fragment size decreased exponentially as migration distance increased. Plotting ln(size) vs distance gave a straight line, confirming the exponential relationship. The gradient of −0.14 ln(bp) per mm shows size decreases rapidly at first and then more slowly. This is because larger fragments experience more resistance as they move through the agarose gel matrix. This principle allows unknown fragment sizes to be determined from their migration distance.'" },
        { level: 8, body: "Level 7–8: Full conclusion: gradient = −0.144 ln(bp) per mm. The exponential relationship arises because agarose gel acts as a molecular sieve — smaller fragments thread through pores more easily, covering greater distances in the same time under the same electric field. The linear ln(size) vs distance relationship allows construction of a standard curve for sizing unknown fragments. This is the basis of forensic DNA profiling (STR analysis), paternity testing, and medical diagnosis of genetic conditions such as cystic fibrosis — where the size of amplified PCR fragments identifies the allele present." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "DNA fragment size vs migration distance in agarose gel electrophoresis (DNA ladder)",
        xLabel: "Migration distance (mm)",
        yLabel: "DNA fragment size (base pairs)",
        editable: true,
        initialRows: [
          { x: 10, y: 5000 },
          { x: 15, y: 2000 },
          { x: 20, y: 1000 },
          { x: 25, y: 500 },
          { x: 30, y: 250 },
          { x: 35, y: 125 },
          { x: 40, y: 65 },
          { x: 45, y: 32 },
        ],
        transforms: [
          { id: "raw", label: "Fragment size vs migration distance", x: "x", y: "y", xLabel: "Distance (mm)", yLabel: "Size (bp)" },
          { id: "ln", label: "ln(size) vs migration distance (linearise exponential relationship)", x: "x", y: "ln(y)", xLabel: "Distance (mm)", yLabel: "ln(size)" },
        ],
        derive: { kind: "gradient", label: "Size decrease per mm migration", unit: "ln(bp) per mm" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. What is the relationship between DNA fragment size and migration distance? Use values from the data and link to the applications of gel electrophoresis.",
        scaffolds: [
          "As migration distance increases from 10 mm to 45 mm, fragment size...",
          "Plotting ln(size) vs distance gave a straight line, which confirms...",
          "The gradient is approximately... ln(bp) per mm, meaning...",
          "This relationship explains how gel electrophoresis is used in...",
        ],
        rubric: [
          { level: 2, descriptor: "States that larger fragments migrate less far.", keywords: ["larger", "less", "distance", "smaller", "further", "migrate"], minKeywords: 1 },
          { level: 4, descriptor: "Exponential relationship identified; data range quoted.", keywords: ["exponential", "5000", "32", "10 mm", "45 mm", "non-linear", "decreases"], minKeywords: 1 },
          { level: 6, descriptor: "Specific data values used; linearisation described; application mentioned.", keywords: ["ln", "straight line", "gradient", "−0.14", "sieve", "matrix", "application", "unknown", "standard curve"], minKeywords: 3 },
          { level: 8, descriptor: "Gradient calculated; molecular sieve mechanism explained; forensic/medical applications cited.", keywords: ["0.144", "sieve", "pores", "pcr", "str", "forensic", "paternity", "cystic fibrosis", "allele", "standard curve", "sizing"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the gel electrophoresis method and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could be improved.'" },
        { level: 4, body: "Level 3–4: 'Only one lane was used per fragment size, so the results may not be reliable.'" },
        { level: 6, body: "Level 5–6: 'A key limitation is that migration distance was measured by eye from the photograph, which introduces a reading uncertainty of ±1–2 mm. Also, only one run was performed, so reliability cannot be assessed. Improvement: repeat the gel run 3 times and use digital image analysis software to measure migration distances more precisely.'" },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses: (1) Band smearing — if voltage is too high or gel concentration incorrect, bands broaden and migration distance is hard to read precisely (solution: optimise voltage and agarose % for the fragment size range). (2) Lane-to-lane variation — samples may not be loaded perfectly, causing slight differences between lanes (solution: run triplicate lanes and average). (3) Temperature affects mobility — gel temperature rises during electrophoresis, altering pore size and fragment speed (solution: run in buffer with ice cooling). (4) Only 8 data points — adding more ladder bands between 500 and 1000 bp (where the linearised graph changes fastest) would improve the precision of the standard curve. Each weakness linked to a specific, reasoned improvement." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "DNA fragment size vs migration distance in agarose gel electrophoresis (DNA ladder)",
        xLabel: "Migration distance (mm)",
        yLabel: "DNA fragment size (base pairs)",
        editable: true,
        initialRows: [
          { x: 10, y: 5000 },
          { x: 15, y: 2000 },
          { x: 20, y: 1000 },
          { x: 25, y: 500 },
          { x: 30, y: 250 },
          { x: 35, y: 125 },
          { x: 40, y: 65 },
          { x: 45, y: 32 },
        ],
        transforms: [
          { id: "raw", label: "Fragment size vs migration distance", x: "x", y: "y", xLabel: "Distance (mm)", yLabel: "Size (bp)" },
          { id: "ln", label: "ln(size) vs migration distance (linearise exponential relationship)", x: "x", y: "ln(y)", xLabel: "Distance (mm)", yLabel: "ln(size)" },
        ],
        derive: { kind: "gradient", label: "Size decrease per mm migration", unit: "ln(bp) per mm" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect this gel electrophoresis data. What are the main weaknesses and how would you improve them?",
        scaffolds: [
          "A key weakness is...",
          "This affects the result because...",
          "To improve this, I would...",
          "Reliability could be improved by...",
          "A systematic error in this method is...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned.", keywords: ["repeat", "reliable", "measurement", "one run", "only once", "reading"], minKeywords: 1 },
          { level: 6, descriptor: "Relevant limitation with matching improvement.", keywords: ["±1", "±2", "reading", "digital", "image analysis", "3 times", "repeat", "reliable", "improve"], minKeywords: 2 },
          { level: 8, descriptor: "Multiple specific weaknesses with reasoned improvements.", keywords: ["smearing", "voltage", "agarose", "lane", "triplicate", "temperature", "ice", "cooling", "8 data points", "500", "1000", "standard curve", "precision"], minKeywords: 3 },
        ],
      },
    },
  ],
}
