import type { StrandhootPack } from "../engine/types"

export const geneticsCritA: StrandhootPack = {
  slug: "genetics-crit-a",
  title: "Genetics & Cell Division",
  subject: "MYP Biology",
  criterion: "A",
  topic: "DNA, mitosis and meiosis",
  accent: "#1b7888",
  icon: "🧬",
  statementOfInquiry: "Observing patterns allows scientists to propose new theories that explain how the living world works.",
  estMinutes: 25,
  intro:
    "From Watson and Crick's double helix to the dance of chromosomes in mitosis and meiosis, genetics reveals the patterns behind inheritance and variation. Each strand levels up from recall to analysis — exploring DNA structure, cell division, and how reproduction drives diversity.",
  badges: [
    { id: "dna", label: "Double Helix Expert", icon: "🧬", description: "Reach Level 8 on DNA structure", strandId: "dna", atLevel: 8 },
    { id: "mitosis", label: "Mitosis Master", icon: "🔬", description: "Reach Level 8 on Mitosis", strandId: "mitosis", atLevel: 8 },
    { id: "meiosis", label: "Meiosis Marvel", icon: "🎲", description: "Reach Level 8 on Meiosis and genetic variation", strandId: "meiosis", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 9: Patterns", blurb: "DNA, cell division, and the patterns of inheritance", icon: "🧬" }],
  strands: [
    {
      id: "dna",
      name: "DNA structure",
      descriptor: "Describe the structure of DNA and explain how genetic information is encoded.",
      guided: [
        { level: 2, body: "DNA is a double helix — two strands twisted around each other, discovered by Watson and Crick in 1953. It is made of four bases: adenine (A), thymine (T), cytosine (C), and guanine (G). The bases pair up: A with T, and C with G." },
        { level: 4, body: "DNA has a deoxyribose-phosphate backbone that runs along the outside of the helix. The four bases sit on the inside and pair via hydrogen bonds: A–T (two hydrogen bonds) and C–G (three hydrogen bonds). The two strands run antiparallel — one runs 5'→3' and the other 3'→5'. A gene is a sequence of bases that codes for one protein (one gene → one polypeptide)." },
        { level: 6, body: "The genetic code is universal: the same codons (triplets of bases) code for the same amino acids in all organisms from bacteria to humans — evidence of common ancestry. The antiparallel nature of DNA is essential for replication and transcription. Complementary base pairing means the sequence on one strand precisely determines the sequence on the other — the basis for accurate DNA copying. A change in the base sequence (mutation) can alter the protein produced." },
        { level: 8, body: "The deoxyribose-phosphate backbone provides structural stability while the bases are protected inside the helix. The hydrogen bonds holding base pairs together are individually weak but collectively strong across millions of base pairs — and must be broken during replication. Watson and Crick's 1953 model (built using X-ray crystallography data from Franklin and Wilkins) explained how genetic information could be both stable (stored in base sequences) and copied (via complementary base pairing). The universality of the genetic code (triplet codons → amino acids, the same across all domains of life) is the molecular basis of the tree of life." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "dna-l2",
            level: 2,
            prompt: "Which bases are complementary pairs in DNA?",
            options: [
              { id: "a", text: "A–C and T–G" },
              { id: "b", text: "A–T and C–G", correct: true },
              { id: "c", text: "A–G and C–T" },
              { id: "d", text: "A–T and C–T" },
            ],
            explanation: "In DNA, adenine (A) pairs with thymine (T), and cytosine (C) pairs with guanine (G) via hydrogen bonds. This is complementary base pairing.",
          },
          {
            type: "fill",
            id: "dna-l4",
            level: 4,
            prompt: "A sequence of bases that codes for one protein is called a ▁.",
            answers: ["gene"],
            explanation: "One gene = one sequence of bases coding for one polypeptide (protein). This is the 'one gene → one polypeptide' principle.",
          },
          {
            type: "short",
            id: "dna-l6",
            level: 6,
            prompt: "Explain what is meant by the genetic code being 'universal'. Why is this significant for our understanding of evolution?",
            keywords: ["universal", "codons", "amino acids", "all organisms", "bacteria", "common ancestry", "same", "evolution"],
            minKeywords: 2,
            sample: "The genetic code is universal because the same three-base codons (triplets) code for the same amino acids in all organisms, from bacteria to humans. This is significant because it provides evidence for common ancestry — all life evolved from a common ancestor that used this same molecular code. It also makes genetic engineering possible, since genes from one organism can be expressed in another.",
          },
          {
            type: "short",
            id: "dna-l8",
            level: 8,
            prompt: "Explain how the structure of DNA — specifically the antiparallel strands, complementary base pairing, and deoxyribose-phosphate backbone — makes it suitable for both storing and copying genetic information.",
            keywords: ["antiparallel", "complementary", "base pairing", "hydrogen bonds", "backbone", "replication", "copying", "stable", "sequence", "template"],
            minKeywords: 3,
            sample: "The deoxyribose-phosphate backbone provides structural stability, running antiparallel on the outside of the helix. The bases are protected inside and held together by hydrogen bonds (A–T, C–G). For storage, the base sequence encodes genetic information stably. For copying, complementary base pairing means each strand acts as a template — the sequence of one strand precisely determines the other. The antiparallel orientation allows replication to proceed in opposite directions on each strand. The hydrogen bonds are individually weak enough to be broken by helicase during replication, yet collectively strong across millions of base pairs to maintain structure.",
          },
        ],
      },
    },
    {
      id: "mitosis",
      name: "Mitosis",
      descriptor: "Describe the stages and purpose of mitosis in eukaryotic cells.",
      guided: [
        { level: 2, body: "Mitosis is cell division for growth, repair, and asexual reproduction. It produces two daughter cells that are genetically identical to the parent cell and to each other. The stages are remembered as PMAT: Prophase, Metaphase, Anaphase, Telophase." },
        { level: 4, body: "In Prophase, chromosomes condense and become visible, the nuclear envelope breaks down, and the spindle fibres form. In Metaphase, chromosomes align at the equatorial plate (middle of the cell) and spindle fibres attach to centromeres. In Anaphase, sister chromatids are pulled to opposite poles by the spindle. In Telophase, nuclear envelopes re-form, chromosomes decondense, and cytokinesis divides the cytoplasm. Result: 2 genetically identical diploid daughter cells." },
        { level: 6, body: "Mitosis maintains the chromosome number: a diploid (2n) cell divides to produce two diploid (2n) daughter cells. This is essential — if mitosis produced haploid cells, each subsequent division would halve the chromosome number until no chromosomes remained. The spindle fibres attach at the centromere of each chromosome, pulling sister chromatids apart in Anaphase. Cytokinesis (cytoplasm division) follows Telophase but is distinct from mitosis itself. Mitosis is the basis of asexual reproduction — producing genetically identical clones." },
        { level: 8, body: "During Prophase, the nuclear envelope breaks down as chromosomes condense, allowing spindle microtubules access to chromosomes. In Metaphase, the spindle assembly checkpoint ensures all chromosomes are correctly attached to spindle fibres before division proceeds — failure triggers apoptosis (programmed cell death) or causes aneuploidy (wrong chromosome number), associated with cancer. Anaphase depends on degradation of cohesins (proteins holding sister chromatids) by separase, triggered by the cell cycle regulatory cascade. The result — two diploid, genetically identical cells — is the molecular basis of growth, tissue repair, and clonal asexual reproduction." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "mit-l2",
            level: 2,
            prompt: "What is the primary purpose of mitosis?",
            options: [
              { id: "a", text: "To produce haploid gametes for sexual reproduction" },
              { id: "b", text: "To produce two genetically identical diploid cells for growth and repair", correct: true },
              { id: "c", text: "To increase genetic variation in a population" },
              { id: "d", text: "To reduce the chromosome number by half" },
            ],
            explanation: "Mitosis produces two genetically identical diploid daughter cells. It is used for growth, repair, and asexual reproduction — not for producing gametes (that is meiosis).",
          },
          {
            type: "fill",
            id: "mit-l4",
            level: 4,
            prompt: "During ▁ (stage of mitosis), chromosomes align at the equatorial plate and spindle fibres attach to centromeres.",
            answers: ["Metaphase", "metaphase"],
            explanation: "In Metaphase, chromosomes are aligned at the cell's equator (equatorial plate) and spindle fibres from opposite poles attach to the centromere of each chromosome, preparing to pull sister chromatids apart.",
          },
          {
            type: "short",
            id: "mit-l6",
            level: 6,
            prompt: "Describe what happens in each stage of mitosis (PMAT) and explain why it is important that the chromosome number is maintained.",
            keywords: ["prophase", "metaphase", "anaphase", "telophase", "diploid", "chromosomes", "identical", "spindle", "centromere", "cytokinesis"],
            minKeywords: 2,
            sample: "Prophase: chromosomes condense, nuclear envelope breaks down, spindle forms. Metaphase: chromosomes align at the equatorial plate, spindle fibres attach to centromeres. Anaphase: sister chromatids pulled to opposite poles. Telophase: nuclear envelopes re-form, chromosomes decondense, cytokinesis divides cytoplasm. Maintaining the diploid chromosome number is important so that every daughter cell has a full set of genetic information. If the chromosome number were halved at each division, cells would quickly lose essential genes.",
          },
          {
            type: "short",
            id: "mit-l8",
            level: 8,
            prompt: "Explain how failures in the spindle assembly checkpoint during Metaphase can lead to aneuploidy. Why is this clinically significant?",
            keywords: ["spindle assembly checkpoint", "aneuploidy", "chromosome number", "cancer", "apoptosis", "metaphase", "cohesins", "wrong", "attachment", "separase"],
            minKeywords: 3,
            sample: "The spindle assembly checkpoint in Metaphase ensures all chromosomes are correctly attached to spindle fibres from both poles before division proceeds. If a chromosome is unattached or incorrectly attached, the checkpoint pauses the cycle. If this checkpoint fails, cells with incorrect chromosome numbers (aneuploidy) are produced — extra or missing chromosomes. Aneuploidy is clinically significant: most aneuploid embryos are non-viable, but some cause conditions (e.g. trisomy 21 / Down syndrome). Uncontrolled aneuploidy in somatic cells is a hallmark of cancer, as cells accumulate chromosomal abnormalities that drive tumour progression.",
          },
        ],
      },
    },
    {
      id: "meiosis",
      name: "Meiosis and genetic variation",
      descriptor: "Explain how meiosis produces haploid gametes and generates genetic variation.",
      guided: [
        { level: 2, body: "Meiosis produces four haploid gametes (egg and sperm cells) from one diploid cell. Unlike mitosis, meiosis involves two rounds of division. The resulting gametes are genetically unique — not identical to the parent or to each other." },
        { level: 4, body: "Meiosis I separates homologous chromosome pairs (2n→n): in Prophase I, crossing over occurs between non-sister chromatids of homologous chromosomes, exchanging segments and creating new allele combinations. In Metaphase I, homologous pairs align randomly (independent assortment). Meiosis II separates chromatids (like mitosis but on haploid cells). Final result: 4 genetically unique haploid cells." },
        { level: 6, body: "Two sources of genetic variation in meiosis: (1) Crossing over — during Prophase I, non-sister chromatids exchange segments at chiasmata, producing new allele combinations that did not exist in either parent. (2) Independent assortment — in Metaphase I, homologous pairs align randomly; either chromosome of each pair can go to either pole. In humans (23 pairs of chromosomes), this alone gives 2²³ ≈ 8.4 million possible combinations per gamete. Fertilisation then combines gametes from two individuals, generating enormous diversity." },
        { level: 8, body: "Crossing over during Prophase I occurs at chiasmata — points where non-sister chromatids physically exchange segments via a process of breakage and reunion. This recombination produces chromosomes with new combinations of alleles not present in either parent. Independent assortment gives 2²³ combinations per gamete; crossing over with multiple chiasmata per chromosome pair multiplies this further, making each gamete genetically unique. This combinatorial variation is the molecular basis for the diversity within sexual populations, enabling natural selection to act on a wider range of phenotypes — a key adaptive advantage of sexual reproduction." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "mei-l2",
            level: 2,
            prompt: "What is the result of meiosis?",
            options: [
              { id: "a", text: "Two genetically identical diploid cells" },
              { id: "b", text: "Two genetically unique diploid cells" },
              { id: "c", text: "Four genetically identical haploid cells" },
              { id: "d", text: "Four genetically unique haploid cells", correct: true },
            ],
            explanation: "Meiosis produces four haploid (n) gametes, each genetically unique due to crossing over and independent assortment. This is distinct from mitosis, which produces two identical diploid cells.",
          },
          {
            type: "fill",
            id: "mei-l4",
            level: 4,
            prompt: "The exchange of segments between non-sister chromatids during Prophase I of meiosis is called ▁.",
            answers: ["crossing over", "crossover", "recombination"],
            explanation: "Crossing over occurs in Prophase I when non-sister chromatids of homologous chromosomes exchange segments at chiasmata. This creates new allele combinations and is a major source of genetic variation.",
          },
          {
            type: "short",
            id: "mei-l6",
            level: 6,
            prompt: "Describe two ways in which meiosis generates genetic variation. Explain why this is important for a species.",
            keywords: ["crossing over", "independent assortment", "variation", "alleles", "chiasmata", "combinations", "2n", "23", "haploid", "selection"],
            minKeywords: 2,
            sample: "Two sources of variation: (1) Crossing over in Prophase I — non-sister chromatids exchange segments at chiasmata, producing new allele combinations not present in either parent chromosome. (2) Independent assortment in Metaphase I — homologous pairs align randomly; either chromosome can go to either pole, giving 2²³ ≈ 8.4 million possible gamete combinations in humans. This variation is important because it provides the raw material for natural selection — a population with diverse genotypes can adapt to changing environments, whereas a genetically uniform population may be wiped out by a single disease or environmental change.",
          },
          {
            type: "short",
            id: "mei-l8",
            level: 8,
            prompt: "Compare the processes and outcomes of meiosis I and meiosis II. Explain at a molecular level why crossing over in Prophase I is such a powerful source of new allele combinations.",
            keywords: ["meiosis i", "meiosis ii", "homologous", "chromatids", "chiasmata", "breakage", "reunion", "alleles", "recombination", "diploid", "haploid"],
            minKeywords: 3,
            sample: "Meiosis I separates homologous chromosomes — the cell goes from diploid (2n) to haploid (n). Prophase I is when crossing over occurs: non-sister chromatids of homologous chromosomes physically break and rejoin at chiasmata, exchanging segments. Metaphase I features independent assortment of homologous pairs. Meiosis II then separates sister chromatids, similar to mitosis but starting from haploid cells. Crossing over is so powerful because it can break up linked alleles (alleles on the same chromosome that would otherwise always be inherited together) and create new combinations — for example, placing a beneficial allele from one parent alongside another beneficial allele from the other parent onto the same chromosome, potentially producing an offspring with greater fitness than either parent.",
          },
        ],
      },
    },
    {
      id: "reproduction",
      name: "Reproduction and life cycles",
      descriptor: "Compare sexual and asexual reproduction and describe the plant alternation of generations.",
      guided: [
        { level: 2, body: "There are two main types of reproduction. Asexual reproduction uses mitosis and produces genetically identical offspring (clones). Sexual reproduction involves fertilisation of haploid gametes and produces offspring with genetic variation." },
        { level: 4, body: "Asexual reproduction (e.g. binary fission, budding, vegetative propagation): faster, no mate needed, offspring identical to parent — advantageous in stable environments. Sexual reproduction: fertilisation combines haploid gametes from two parents, creating genetic variation — enables adaptation to changing environments, but is slower and requires a mate. Plants show alternation of generations: the sporophyte (2n) produces haploid spores (n) by meiosis → spores grow into the gametophyte (n) → gametophyte produces gametes → fertilisation gives a new sporophyte (2n)." },
        { level: 6, body: "Advantages of asexual reproduction: rapid population growth, no energy cost of producing male gametes, all offspring can reproduce. Disadvantage: no genetic variation — one pathogen or environmental change can eliminate the whole population. Advantages of sexual reproduction: variation enables natural selection and adaptation. Disadvantage: slower, energy-intensive, requires finding a mate. Plant alternation of generations: in mosses the gametophyte (n) is dominant; in ferns and flowering plants the sporophyte (2n) is dominant. The haploid gametophyte produces gametes by mitosis (not meiosis). The genetic diversity introduced at fertilisation is maintained through the sporophyte generation." },
        { level: 8, body: "The evolutionary balance between sexual and asexual reproduction is shaped by environment. The Red Queen hypothesis proposes that sexual reproduction persists because it generates variation that helps populations 'keep up' with evolving parasites and pathogens. Asexual lineages are vulnerable to mutational meltdown (accumulation of harmful mutations without recombination) — Muller's ratchet. In plant life cycles, alternation of generations means meiosis and mitosis each play distinct roles: meiosis generates spores (from the sporophyte), while mitosis grows the gametophyte and produces gametes. In bryophytes (mosses), the gametophyte is the dominant photosynthetic generation; in angiosperms (flowering plants), the sporophyte dominates and the gametophyte is reduced to a few cells (e.g. pollen grain)." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "rep-l2",
            level: 2,
            prompt: "Which statement correctly describes asexual reproduction?",
            options: [
              { id: "a", text: "It involves fertilisation of two gametes" },
              { id: "b", text: "It produces offspring with genetic variation" },
              { id: "c", text: "It produces genetically identical offspring using mitosis", correct: true },
              { id: "d", text: "It always requires two parent organisms" },
            ],
            explanation: "Asexual reproduction uses mitosis to produce genetically identical copies (clones) of the parent. No gametes or fertilisation are involved.",
          },
          {
            type: "fill",
            id: "rep-l4",
            level: 4,
            prompt: "In the plant life cycle, the diploid (2n) generation is called the ▁, and it produces haploid spores by meiosis.",
            answers: ["sporophyte"],
            explanation: "The sporophyte (2n) is the diploid generation. It produces haploid spores via meiosis. The spores grow into the gametophyte (n) which produces gametes. Fertilisation produces a new sporophyte.",
          },
          {
            type: "short",
            id: "rep-l6",
            level: 6,
            prompt: "Compare the advantages and disadvantages of sexual and asexual reproduction. Under what environmental conditions is each strategy more beneficial?",
            keywords: ["variation", "asexual", "sexual", "adaptation", "clones", "faster", "stable", "changing", "selection", "fertilisation"],
            minKeywords: 2,
            sample: "Asexual reproduction (mitosis) is faster, requires no mate, and all offspring can reproduce — advantageous in stable, favourable environments where the parent's genotype is already well-suited. However, no variation means a single pathogen can destroy the whole population. Sexual reproduction generates genetic variation through meiosis and fertilisation, enabling natural selection and adaptation to changing environments. It is slower and energy-intensive. Sexual reproduction is therefore favoured in changing environments with unpredictable challenges such as disease or climate fluctuation.",
          },
          {
            type: "short",
            id: "rep-l8",
            level: 8,
            prompt: "Explain the alternation of generations in plants. How do the roles of mitosis and meiosis differ in the sporophyte and gametophyte generations? Give an example of a plant where each generation is dominant.",
            keywords: ["sporophyte", "gametophyte", "meiosis", "mitosis", "spores", "gametes", "diploid", "haploid", "moss", "fern", "angiosperm", "dominant"],
            minKeywords: 3,
            sample: "Plants alternate between two multicellular generations: the sporophyte (2n, diploid) and the gametophyte (n, haploid). The sporophyte produces haploid spores via meiosis. Spores grow by mitosis into the gametophyte, which then produces gametes by mitosis (not meiosis). Fertilisation of gametes gives a new diploid sporophyte. In mosses (bryophytes), the gametophyte is the dominant photosynthetic generation — the familiar green mat. In ferns, sporophyte and gametophyte are both independent. In flowering plants (angiosperms), the sporophyte completely dominates — the gametophyte is reduced to just a few cells (the pollen grain is the male gametophyte; the embryo sac inside the ovule is the female gametophyte).",
          },
        ],
      },
    },
  ],
}
