import type { StrandhootPack } from "../engine/types"

export const habitatCritA: StrandhootPack = {
  slug: "habitat-crit-a",
  title: "Habitats & Ecosystems",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Abiotic factors, biodiversity and succession",
  accent: "#1b7888",
  icon: "🌍",
  statementOfInquiry: "Environments provide aesthetic benefits and influence human cultural expression, but human induced changes undermine these benefits.",
  estMinutes: 25,
  intro:
    "Explore how abiotic and biotic factors shape habitats, how scientists measure biodiversity, how ecosystems develop through succession, and how pollution indicators reveal environmental health. Each strand levels up from recall to analysis.",
  badges: [
    { id: "abiotic", label: "Factor Expert", icon: "🌡️", description: "Reach Level 8 on Abiotic and biotic factors", strandId: "factors", atLevel: 8 },
    { id: "biodiversity", label: "Diversity Analyst", icon: "📊", description: "Reach Level 8 on Biodiversity and sampling", strandId: "biodiversity", atLevel: 8 },
    { id: "succession", label: "Succession Mapper", icon: "🌱", description: "Reach Level 8 on Succession", strandId: "succession", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 8: Environment", blurb: "Abiotic factors, biodiversity, succession and pollution indicators", icon: "🌍" }],
  strands: [
    {
      id: "factors",
      name: "Abiotic and biotic factors",
      descriptor: "Identify abiotic and biotic factors and explain how they affect distribution and abundance.",
      guided: [
        { level: 2, body: "Abiotic factors are non-living factors in a habitat: temperature, light intensity, water availability, pH, salinity, wind speed, and humidity. Biotic factors are living factors: competition, predation, disease, mutualism, and parasitism. Both types affect where organisms live and how many there are." },
        { level: 4, body: "Abiotic factors set the physical limits for life. Temperature affects enzyme activity; light intensity limits photosynthesis; salinity affects osmosis. Biotic competition can be intraspecific (between same species, e.g. red squirrels competing for nuts) or interspecific (between different species, e.g. red vs grey squirrels). Predation reduces prey populations but also controls them." },
        { level: 6, body: "Limiting factors: whichever factor is in the shortest supply limits population growth — even if all other factors are ideal. For example, plants in a dense forest may have sufficient water and nutrients but be light-limited. The concept of limiting factors applies to both abiotic (e.g. light, temperature) and biotic (e.g. food availability from competitors) factors." },
        { level: 8, body: "Interactions between factors create complex outcomes. Mutualism (e.g. nitrogen-fixing bacteria in root nodules of legumes) benefits both species, altering soil abiotic conditions for the whole community. Parasitism (e.g. Plasmodium in mosquitoes) weakens hosts and changes competitive outcomes. A single change in one abiotic factor (e.g. acidification of a lake by acid rain lowering pH) cascades through biotic relationships — altering competition, disease susceptibility, and predator-prey dynamics simultaneously." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "fac-l2",
            level: 2,
            prompt: "Which of the following is an abiotic factor?",
            options: [
              { id: "a", text: "Predation by foxes" },
              { id: "b", text: "Competition between plants" },
              { id: "c", text: "Light intensity", correct: true },
              { id: "d", text: "Disease caused by bacteria" },
            ],
            explanation: "Light intensity is a non-living (abiotic) factor. Predation, competition, and disease are all biotic factors — they involve living organisms.",
          },
          {
            type: "fill",
            id: "fac-l4",
            level: 4,
            prompt: "Competition between individuals of the same species is called ▁ competition.",
            answers: ["intraspecific"],
            explanation: "Intraspecific competition occurs between individuals of the same species (intra = within). Interspecific competition occurs between different species (inter = between).",
          },
          {
            type: "short",
            id: "fac-l6",
            level: 6,
            prompt: "Explain the concept of a limiting factor and give one abiotic and one biotic example of how a limiting factor can restrict population growth.",
            keywords: ["limiting", "factor", "supply", "shortest", "population", "growth", "light", "temperature", "food", "competition"],
            minKeywords: 2,
            sample: "A limiting factor is the factor in shortest supply that restricts population growth, even when all other conditions are suitable. An abiotic example: light is a limiting factor for plants on the forest floor — even with adequate water and nutrients, low light prevents photosynthesis and growth. A biotic example: food availability limited by competitors restricts a population of rabbits if hares compete for the same grass.",
          },
          {
            type: "short",
            id: "fac-l8",
            level: 8,
            prompt: "Explain how a change in one abiotic factor can cascade through biotic relationships in an ecosystem. Use a specific example to support your answer.",
            keywords: ["abiotic", "biotic", "cascade", "ph", "acid", "competition", "predator", "prey", "disease", "relationship", "interaction"],
            minKeywords: 3,
            sample: "A change in one abiotic factor can trigger a cascade of biotic effects. For example, acid rain lowering lake pH below 5 kills acid-sensitive invertebrates (e.g. mayfly nymphs), reducing food availability for fish — a biotic effect. This weakens fish populations, reducing prey for predatory birds such as ospreys. Simultaneously, acid conditions favour tolerant species like certain algae, altering competition between algal species. A single abiotic change therefore ripples through predator-prey relationships, competition and disease susceptibility across the entire community.",
          },
        ],
      },
    },
    {
      id: "biodiversity",
      name: "Biodiversity and sampling",
      descriptor: "Describe methods for sampling habitats and calculating species diversity.",
      guided: [
        { level: 2, body: "Biodiversity has two components: species richness (the number of different species present) and species evenness (how equally individuals are distributed among species). Scientists use sampling methods to estimate biodiversity without counting every organism." },
        { level: 4, body: "Random sampling uses quadrats (frames of known area, e.g. 0.25 m²) thrown randomly to avoid bias; organisms inside are counted. Systematic sampling uses transects — a line or belt across a habitat at regular intervals — to show how species change across an environmental gradient. Mark-recapture estimates total population: N = MC/R (N = total, M = marked first catch, C = total second catch, R = recaptured marked)." },
        { level: 6, body: "Simpson's diversity index D = 1 − Σ(n/N)², where n = number of individuals of each species and N = total individuals. D ranges from 0 (no diversity — one species only) to approaching 1 (maximum diversity). A higher D means a more diverse, stable ecosystem. Percentage cover is used for plants that cannot be counted individually — the proportion of the quadrat area occupied by each species." },
        { level: 8, body: "Choice of sampling method depends on the question. Transects reveal zonation (gradual change in species composition across a gradient, e.g. from sea to inland). The mark-recapture formula assumes: marks do not affect survival, marks are permanent, the population is closed (no immigration or emigration), and marked individuals mix randomly. Violation of these assumptions introduces bias. Simpson's D weights evenness heavily — a community with 5 species equally distributed has a higher D than one with 5 species where 90% of individuals belong to one species." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "bio-l2",
            level: 2,
            prompt: "What does species richness measure?",
            options: [
              { id: "a", text: "The total number of individuals in a habitat" },
              { id: "b", text: "The number of different species present", correct: true },
              { id: "c", text: "The evenness of distribution among species" },
              { id: "d", text: "The size of the largest species in the habitat" },
            ],
            explanation: "Species richness is simply the count of different species present. Species evenness measures how equally the individuals are spread among those species.",
          },
          {
            type: "fill",
            id: "bio-l4",
            level: 4,
            prompt: "In a mark-recapture study, 40 beetles were caught and marked (M). In a second catch of 50 beetles (C), 10 were found to be marked (R). The estimated population size N = ▁.",
            answers: ["200"],
            explanation: "N = MC/R = (40 × 50) / 10 = 2000 / 10 = 200 beetles. This assumes marks are retained, the population is closed, and marked individuals mix randomly.",
          },
          {
            type: "short",
            id: "bio-l6",
            level: 6,
            prompt: "A student counts plants in 10 quadrats. In habitat A there are 3 species with 30, 28 and 32 individuals respectively. In habitat B there are 3 species with 80, 10 and 0 individuals respectively. Without calculating D, explain which habitat will have the higher Simpson's diversity index and why.",
            keywords: ["evenness", "distribution", "dominant", "equal", "diversity", "simpson", "higher", "habitat a", "species"],
            minKeywords: 2,
            sample: "Habitat A will have the higher Simpson's D. Although both habitats have the same species richness (3 species), habitat A has a much more even distribution of individuals across species (roughly 30:30:30). Habitat B is dominated by one species (80 individuals) with very few of the second and none of the third — poor evenness. Simpson's D penalises dominance, so habitat B's uneven distribution gives a lower D value.",
          },
          {
            type: "short",
            id: "bio-l8",
            level: 8,
            prompt: "Evaluate the mark-recapture method for estimating beetle population size. State three assumptions and explain what would happen to the estimate if each assumption were violated.",
            keywords: ["assumption", "closed", "immigration", "emigration", "mix", "random", "marked", "survival", "bias", "overestimate", "underestimate"],
            minKeywords: 3,
            sample: "Mark-recapture assumes: (1) marks do not affect survival — if marks make beetles more visible to predators, marked beetles die at a higher rate, reducing R and causing N to be overestimated; (2) the population is closed — if new unmarked beetles immigrate between catches, C rises without increasing R, inflating N; (3) marked individuals mix randomly — if marked beetles aggregate rather than dispersing, they are more likely to be recaptured, increasing R and causing N to be underestimated. Each violation introduces systematic bias in a specific direction.",
          },
        ],
      },
    },
    {
      id: "succession",
      name: "Succession",
      descriptor: "Describe and compare primary and secondary succession and the role of pioneer species.",
      guided: [
        { level: 2, body: "Succession is the gradual change in a community over time. Primary succession starts on bare rock where no soil exists — pioneer species such as lichens are the first to colonise. Secondary succession occurs after a habitat has been destroyed (e.g. by fire or flood) but the soil remains, so it is faster." },
        { level: 4, body: "In primary succession on bare rock: lichens → mosses → grasses → shrubs → woodland → climax community. Pioneer species (lichens) tolerate extreme conditions (no soil, temperature extremes, desiccation). As they die and weather rock, they create the first thin layer of soil. Each seral stage (stage in succession) makes conditions more suitable for the next community, which then out-competes and replaces the previous one." },
        { level: 6, body: "Pioneer species modify the environment for subsequent species: lichens weather rock (releasing minerals) and fix nitrogen, allowing mosses to establish. Each seral stage increases soil depth, organic matter, and water-holding capacity. Biodiversity increases through succession as more niches become available. The climax community is stable and self-sustaining — though exactly which species form it depends on climate (the 'climax' in a temperate UK environment is typically oak woodland)." },
        { level: 8, body: "Primary vs secondary succession differ in starting conditions and rate. Secondary succession is faster because soil (with dormant seeds, nutrients and microorganisms) already exists — e.g. abandoned fields progress from annuals to woodland in decades, whereas bare rock takes centuries. Both converge on the same climax community for a given climate. The facilitation model of succession proposes that early species actively make conditions better for later species (not just tolerate and modify passively). The inhibition model proposes that each species resists replacement and only a disturbance removes them. Real successions show elements of both." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "suc-l2",
            level: 2,
            prompt: "Which organisms are typically the pioneer species in primary succession on bare rock?",
            options: [
              { id: "a", text: "Oak trees" },
              { id: "b", text: "Grasses" },
              { id: "c", text: "Lichens", correct: true },
              { id: "d", text: "Shrubs" },
            ],
            explanation: "Lichens are pioneer species — they can colonise bare rock where no soil exists, tolerating extreme conditions. They break down the rock surface and contribute organic matter, starting the soil formation process.",
          },
          {
            type: "fill",
            id: "suc-l4",
            level: 4,
            prompt: "Secondary succession is faster than primary succession because the ▁ is already present.",
            answers: ["soil", "soil layer"],
            explanation: "In secondary succession (after fire, flood, or farming) the soil remains, along with dormant seeds and soil microorganisms. In primary succession, soil must be built from bare rock — a much slower process.",
          },
          {
            type: "short",
            id: "suc-l6",
            level: 6,
            prompt: "Explain how pioneer species prepare the environment for later seral stages in primary succession. Include at least two specific ways they modify conditions.",
            keywords: ["lichen", "nitrogen", "weathering", "soil", "organic", "moisture", "pioneer", "seral", "conditions", "minerals"],
            minKeywords: 2,
            sample: "Pioneer species such as lichens modify the abiotic environment to allow later species to establish. Lichens secrete acids that weather rock, releasing mineral ions and creating the first particles of soil. When lichens die, their organic matter adds to the soil, increasing its depth and water-holding capacity. Some pioneers (e.g. cyanobacteria within lichens) fix atmospheric nitrogen, adding nutrients that later species such as mosses and grasses need. These changes create conditions suitable for the next seral stage, increasing biodiversity over time.",
          },
          {
            type: "short",
            id: "suc-l8",
            level: 8,
            prompt: "Compare the facilitation and inhibition models of succession. Which model do you think better explains real successions, and why?",
            keywords: ["facilitation", "inhibition", "pioneer", "replace", "modify", "resist", "disturbance", "real", "both", "seral", "conditions", "out-compete"],
            minKeywords: 3,
            sample: "The facilitation model proposes that early species actively improve conditions for later species — for example, lichens building soil for mosses. The inhibition model proposes that each established species resists replacement and only dies when a disturbance creates a gap. Real successions show elements of both: early pioneer stages often show facilitation (lichen to moss to grass), while later stages can show inhibition (mature woodland resists invasion by later successional species). Neither model alone fully explains the complexity of real community change over time.",
          },
        ],
      },
    },
    {
      id: "pollution",
      name: "Pollution and indicators",
      descriptor: "Describe types of pollution and explain how indicator species reveal pollution levels.",
      guided: [
        { level: 2, body: "Pollution is the addition of harmful substances to the environment. Air pollution includes SO₂ (causes acid rain), NOx, particulates, and CO₂ (greenhouse gas). Water pollution includes eutrophication, oil spills, heavy metals, and plastic microbeads. Soil pollution includes DDT and other persistent pesticides. Indicator species are organisms sensitive to pollution — their presence or absence reveals pollution levels." },
        { level: 4, body: "Air pollution indicators: lichens are highly sensitive to SO₂. Where SO₂ pollution is high, lichens are absent. The number of lichen species (or the density per m²) decreases with increasing SO₂ levels — making them a reliable pollution index. Water pollution indicators: stonefly nymphs (Plecoptera) require high dissolved oxygen and are absent in polluted water; tubifex worms tolerate very low oxygen and indicate heavily polluted water. Their presence or absence provides a rapid biological assessment." },
        { level: 6, body: "Eutrophication sequence: excess nitrogen and phosphorus (from fertiliser runoff) → rapid algal growth (algal bloom) → algae block light reaching submerged plants → plants die → bacteria decompose dead organic matter, consuming oxygen → oxygen levels fall (deoxygenation/hypoxia) → fish and invertebrates die → 'dead zone'. DDT is a persistent organochlorine pesticide that accumulates through trophic levels (biomagnification): plankton → small fish → large fish → birds of prey. Concentrations can be millions of times higher in apex predators, causing eggshell thinning and reproductive failure." },
        { level: 8, body: "Indicator species are used because they integrate pollution over time, unlike one-off chemical measurements. The biotic index (e.g. BMWP score) assigns species different sensitivity scores — clean water has a high BMWP score, polluted water a low score. Bioaccumulation of microplastics: ingested by zooplankton, then fish, then seabirds — 90% of seabirds have plastic in their gut. Microplastics also enter human blood. Chemical indicators (SO₂ concentration in ppb) give point-in-time data; biological indicators give time-integrated evidence of chronic exposure, making them complementary tools for environmental monitoring." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "pol-l2",
            level: 2,
            prompt: "What does the absence of lichens from trees in a city centre indicate?",
            options: [
              { id: "a", text: "High water pollution" },
              { id: "b", text: "Healthy clean air" },
              { id: "c", text: "High SO₂ air pollution", correct: true },
              { id: "d", text: "High CO₂ concentration" },
            ],
            explanation: "Lichens are very sensitive to SO₂. Their absence from trees typically indicates high SO₂ pollution from burning fossil fuels. They are used as biological indicators of air quality.",
          },
          {
            type: "fill",
            id: "pol-l4",
            level: 4,
            prompt: "The process by which excess fertiliser in waterways causes algal blooms, oxygen depletion and death of aquatic organisms is called ▁.",
            answers: ["eutrophication"],
            explanation: "Eutrophication: nutrients (nitrates and phosphates) enter water → rapid algal growth → algae block light → submerged plants die → bacteria decompose dead matter → oxygen depleted → aquatic organisms suffocate.",
          },
          {
            type: "short",
            id: "pol-l6",
            level: 6,
            prompt: "Explain why indicator species are useful for monitoring pollution. Include an example of an air pollution indicator and a water pollution indicator in your answer.",
            keywords: ["indicator", "sensitive", "lichen", "stonefly", "tubifex", "absence", "presence", "pollution", "biological", "time"],
            minKeywords: 2,
            sample: "Indicator species are useful because they reflect pollution levels over time — unlike chemical measurements taken at a single moment. Lichens are air pollution indicators: their absence or low density indicates high SO₂ pollution from burning fossil fuels. Stonefly nymphs are clean water indicators: they require high dissolved oxygen and are absent in polluted rivers. Conversely, tubifex worms tolerate very low oxygen and indicate severely polluted water. Together, the presence or absence of these species gives a time-integrated picture of pollution levels.",
          },
          {
            type: "short",
            id: "pol-l8",
            level: 8,
            prompt: "Explain why chemical indicators (e.g. measured SO₂ concentration) and biological indicators (e.g. lichen density per m²) are considered complementary rather than interchangeable tools for environmental monitoring.",
            keywords: ["chemical", "biological", "point-in-time", "integrated", "chronic", "acute", "bmwp", "lichen", "time", "complementary", "exposure", "monitoring"],
            minKeywords: 3,
            sample: "Chemical indicators (e.g. SO₂ concentration in ppb) give precise, quantitative, point-in-time measurements — useful for detecting acute pollution events. However, they may miss chronic, low-level pollution between sampling dates. Biological indicators (e.g. lichen density per m²) integrate pollution exposure over the organism's lifetime, revealing cumulative effects that a single chemical measurement would miss. A BMWP biotic index scores the diversity of invertebrates to give a long-term picture of water quality. The two approaches are complementary: chemical monitoring identifies what pollutants are present and at what concentration right now, while biological monitoring reveals the cumulative ecological impact over time.",
          },
        ],
      },
    },
  ],
}
