import type { StrandhootPack } from "../engine/types"

// Crit C data: species-area relationship for bird species in woodland patches.
// S = cA^z (power law). √area linearises the relationship when z ≈ 0.5.
// Gradient of species richness vs √area gives species-area coefficient.
export const habitatCritC: StrandhootPack = {
  slug: "habitat-crit-c",
  title: "Species-Area Relationship",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Habitat area and biodiversity dataset",
  accent: "#0984b5",
  icon: "🌍",
  statementOfInquiry: "Environments provide aesthetic benefits and influence human cultural expression, but human induced changes undermine these benefits.",
  estMinutes: 30,
  intro:
    "A field ecologist recorded bird species richness in eight woodland patches of different areas. Use the data tool to plot, transform and analyse the species-area relationship — then draw a conclusion about how habitat area affects biodiversity and what this means for conservation. Each strand levels up with the depth of your scientific reasoning.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Ecology Analyst", icon: "🌿", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Woodland bird survey", blurb: "Bird species richness vs woodland patch area", icon: "🌍" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the species-area data clearly and apply the √area transform to linearise it.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with the data values but missing headings, units, or a graph." },
        { level: 4, body: "Level 3–4: A clear table with column headings (woodland area in km²; number of bird species) and a scatter graph with both axes labelled and including units." },
        { level: 6, body: "Level 5–6: Axes labelled with units, a sensible scale that fills most of the grid, points accurately plotted, and a smooth curve of best fit showing the non-linear (power-law) increase of species richness with area. The curve rises steeply at small areas and flattens at large areas." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised graph of species richness vs √area (km). If the species-area relationship S = cA^z holds with z ≈ 0.5, plotting S against √A gives a straight line — far easier to extrapolate and analyse. The gradient of the straight line is the species-area coefficient (species gained per √km)." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Number of bird species recorded vs woodland patch area (species-area relationship)",
        xLabel: "Woodland area (km²)",
        yLabel: "Number of bird species",
        editable: true,
        initialRows: [
          { x: 1, y: 4 },
          { x: 5, y: 8 },
          { x: 10, y: 11 },
          { x: 25, y: 15 },
          { x: 50, y: 19 },
          { x: 100, y: 23 },
          { x: 250, y: 28 },
          { x: 500, y: 32 },
        ],
        transforms: [
          { id: "raw", label: "Species richness vs area", x: "x", y: "y", xLabel: "Area (km²)", yLabel: "Species richness" },
          { id: "sqrt", label: "Species richness vs √area (linearise power law)", x: "√x", y: "y", xLabel: "√area (km)", yLabel: "Species richness" },
        ],
        derive: { kind: "gradient", label: "Species-area coefficient (species per √km)", unit: "species per √km" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the species-area data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted species richness on the y-axis against woodland area on...",
          "The graph shows a... trend because...",
          "I linearised the data by plotting species richness vs √area because...",
          "The straight line on the transformed graph confirms...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "data", "species", "area", "woodland"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "km²", "species", "woodland", "area"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve of best fit; non-linear trend described.", keywords: ["curve", "best fit", "non-linear", "smooth", "increases", "flattens", "power", "accurate", "scale"], minKeywords: 2 },
          { level: 8, descriptor: "Linearised √area plot described as a straight line.", keywords: ["√area", "straight line", "linear", "transform", "gradient", "species-area", "sqrt", "km", "linearise"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient of the linearised species-area plot and interpret the species-area coefficient.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend: 'More bird species are found in larger woodland patches.'" },
        { level: 4, body: "Level 3–4: Calculates the increase in species richness across the range: from 4 species at 1 km² to 32 species at 500 km², an increase of 28 species. Notes the increase is not linear — doubling the area does not double the species count." },
        { level: 6, body: "Level 5–6: From the species richness vs √area graph, draws a line of best fit and reads off two widely-spaced points to calculate gradient = Δ(species) / Δ(√area). States the unit of gradient as species per √km. Notes that the relationship is closer to linear on the transformed plot, supporting a power law with z ≈ 0.5." },
        { level: 8, body: "Level 7–8: Full calculation shown. √1 = 1, S = 4; √500 ≈ 22.4, S = 32. Gradient ≈ (32 − 4) / (22.4 − 1) = 28 / 21.4 ≈ 1.31 species per √km. This means roughly 1.3 more bird species are recorded for each additional √km of woodland. Extrapolate: a 1000 km² patch gives √1000 ≈ 31.6, predicted S ≈ 4 + 1.31 × 31.6 ≈ 45 species. Note: extrapolation beyond the data range has greater uncertainty." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Number of bird species recorded vs woodland patch area (species-area relationship)",
        xLabel: "Woodland area (km²)",
        yLabel: "Number of bird species",
        editable: true,
        initialRows: [
          { x: 1, y: 4 },
          { x: 5, y: 8 },
          { x: 10, y: 11 },
          { x: 25, y: 15 },
          { x: 50, y: 19 },
          { x: 100, y: 23 },
          { x: 250, y: 28 },
          { x: 500, y: 32 },
        ],
        transforms: [
          { id: "raw", label: "Species richness vs area", x: "x", y: "y", xLabel: "Area (km²)", yLabel: "Species richness" },
          { id: "sqrt", label: "Species richness vs √area (linearise power law)", x: "√x", y: "y", xLabel: "√area (km)", yLabel: "Species richness" },
        ],
        derive: { kind: "gradient", label: "Species-area coefficient (species per √km)", unit: "species per √km" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the species richness vs √area graph and state what it means.",
        scaffolds: [
          "The overall trend shows that species richness...",
          "From the √area graph I chose two points: (√area₁, species₁) = ... and (√area₂, species₂) = ...",
          "Gradient = Δ(species) / Δ(√area) = ... / ... = ... species per √km",
          "This means that for every additional √km of woodland area, the number of bird species...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes species richness increases with area.", keywords: ["increases", "larger", "more", "species", "area", "woodland"], minKeywords: 1 },
          { level: 4, descriptor: "Non-linear increase noted; overall range described.", keywords: ["non-linear", "not double", "28", "range", "4 species", "32 species", "500", "1 km"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated from linearised graph with working.", keywords: ["gradient", "√area", "two points", "best fit", "species per", "slope", "delta"], minKeywords: 2 },
          { level: 8, descriptor: "Full gradient calculation with values; extrapolation attempted; uncertainty noted.", keywords: ["1.31", "22.4", "28", "21.4", "species per √km", "extrapolate", "1000", "45", "uncertainty"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about the species-area relationship and its conservation implications.",
      guided: [
        { level: 2, body: "Level 1–2: 'Larger woodlands have more bird species.'" },
        { level: 4, body: "Level 3–4: 'Species richness increased with woodland area. Doubling the area does not double the number of species — the relationship follows a curve, not a straight line.'" },
        { level: 6, body: "Level 5–6: 'Species richness follows a power-law relationship (S = cA^z) with woodland area. Plotting S vs √area linearises the data, giving a gradient of approximately 1.3 species per √km. This means you need to multiply the area by 10 (not 2) to approximately double the species count — a key conservation implication: fragmentation into small patches greatly reduces biodiversity.'" },
        { level: 8, body: "Level 7–8: Data support the species-area relationship S = cA^z with z ≈ 0.5. Gradient ≈ 1.3 species per √km, meaning species accumulate with the square root of area. To double species richness from 4 to 8, you need to increase area from 1 km² to approximately 25 km² — a 25-fold increase, not a 2-fold increase. Conservation implication: connecting fragmented woodland patches via wildlife corridors effectively increases 'functional area', raising the species-area curve. This data directly supports the case for habitat connectivity over multiple small reserves." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Number of bird species recorded vs woodland patch area (species-area relationship)",
        xLabel: "Woodland area (km²)",
        yLabel: "Number of bird species",
        editable: true,
        initialRows: [
          { x: 1, y: 4 },
          { x: 5, y: 8 },
          { x: 10, y: 11 },
          { x: 25, y: 15 },
          { x: 50, y: 19 },
          { x: 100, y: 23 },
          { x: 250, y: 28 },
          { x: 500, y: 32 },
        ],
        transforms: [
          { id: "raw", label: "Species richness vs area", x: "x", y: "y", xLabel: "Area (km²)", yLabel: "Species richness" },
          { id: "sqrt", label: "Species richness vs √area (linearise power law)", x: "√x", y: "y", xLabel: "√area (km)", yLabel: "Species richness" },
        ],
        derive: { kind: "gradient", label: "Species-area coefficient (species per √km)", unit: "species per √km" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. What is the relationship between woodland area and bird species richness? What does this mean for conservation?",
        scaffolds: [
          "As woodland area increases from 1 km² to 500 km², species richness...",
          "The relationship follows a... because plotting S vs √area gives a...",
          "The gradient of approximately... species per √km means...",
          "To double the species richness you would need to increase the area by a factor of...",
          "A conservation implication of this is...",
        ],
        rubric: [
          { level: 2, descriptor: "States species richness increases with woodland area.", keywords: ["increases", "larger", "more", "species", "area"], minKeywords: 1 },
          { level: 4, descriptor: "Non-linear relationship described; doubling area does not double species.", keywords: ["non-linear", "not double", "power", "curve", "relationship", "does not"], minKeywords: 1 },
          { level: 6, descriptor: "Power law described; gradient used; conservation link made.", keywords: ["power law", "s = ca", "gradient", "1.3", "fragmentation", "conservation", "√area", "linearise"], minKeywords: 3 },
          { level: 8, descriptor: "Quantified: 25-fold area increase to double species; corridors link.", keywords: ["25 km²", "25-fold", "1 km²", "double", "wildlife corridor", "connectivity", "functional area", "fragments", "1.3", "gradient"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the bird survey method and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could be improved.'" },
        { level: 4, body: "Level 3–4: 'Only one survey was done at each woodland, which reduces reliability. Bird surveys may also be affected by weather and time of day.'" },
        { level: 6, body: "Level 5–6: 'A key limitation is that woodland shape is not controlled — two patches with the same area but different edge:interior ratios will have different species richness (edge effect). Also, only one survey per woodland reduces reliability. Improvement: standardise shape by using circular survey plots, and repeat surveys 3 times per season.'" },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses: (1) The survey method (point count vs transect) is not specified — inconsistent methods between woodlands would introduce bias. (2) Woodland shape confounds area — a long, thin woodland has more edge habitat (with different species) per unit area than a circular one; edge effect inflates species richness in thin patches. (3) Seasonal surveys in spring (breeding season) sample more species than winter, but the data do not specify when surveys were done. (4) Observer bias — different ornithologists have different detection abilities. Each weakness is linked to a specific, reasoned improvement, e.g. single observer conducting all surveys in May during the dawn chorus." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Number of bird species recorded vs woodland patch area (species-area relationship)",
        xLabel: "Woodland area (km²)",
        yLabel: "Number of bird species",
        editable: true,
        initialRows: [
          { x: 1, y: 4 },
          { x: 5, y: 8 },
          { x: 10, y: 11 },
          { x: 25, y: 15 },
          { x: 50, y: 19 },
          { x: 100, y: 23 },
          { x: 250, y: 28 },
          { x: 500, y: 32 },
        ],
        transforms: [
          { id: "raw", label: "Species richness vs area", x: "x", y: "y", xLabel: "Area (km²)", yLabel: "Species richness" },
          { id: "sqrt", label: "Species richness vs √area (linearise power law)", x: "√x", y: "y", xLabel: "√area (km)", yLabel: "Species richness" },
        ],
        derive: { kind: "gradient", label: "Species-area coefficient (species per √km)", unit: "species per √km" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect this species-area data. What are the main weaknesses and how would you improve them?",
        scaffolds: [
          "A key weakness is...",
          "This affects the result because...",
          "To improve this, I would...",
          "The shape of the woodland patch could confound the results because...",
          "Reliability could be improved by...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem", "bias"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned.", keywords: ["repeat", "weather", "time", "season", "reliable", "once", "survey"], minKeywords: 1 },
          { level: 6, descriptor: "Edge effect or shape confound identified; specific improvement given.", keywords: ["edge", "shape", "interior", "confound", "repeat", "3 times", "circular", "standardise", "bias"], minKeywords: 2 },
          { level: 8, descriptor: "Multiple specific weaknesses with reasoned improvements; season and observer bias addressed.", keywords: ["point count", "transect", "edge effect", "thin", "season", "spring", "dawn chorus", "observer", "detection", "may", "confound", "shape"], minKeywords: 3 },
        ],
      },
    },
  ],
}
