import type { StrandhootPack } from "../engine/types"

export const healthCritA: StrandhootPack = {
  slug: "health-crit-a",
  title: "Health Evidence & Vaccination",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Risk factors, epidemiology and immunity",
  accent: "#1b7888",
  icon: "💉",
  statementOfInquiry: "Healthy lifestyles can be based on evidence of relationships between types of behaviour and risks of disease.",
  estMinutes: 25,
  intro:
    "From Doll & Hill's landmark smoking study to the immunology of vaccination, this chapter is about using scientific evidence to understand health. Each strand targets a core concept — levelling up from recall to critical analysis of epidemiological evidence.",
  badges: [
    { id: "risk", label: "Risk Detective", icon: "🔍", description: "Reach Level 8 on Lifestyle risk factors", strandId: "risk-factors", atLevel: 8 },
    { id: "bmi", label: "Screening Expert", icon: "📏", description: "Reach Level 8 on BMI and health screening", strandId: "bmi-screening", atLevel: 8 },
    { id: "immune", label: "Immunity Expert", icon: "🛡️", description: "Reach Level 8 on Immune system", strandId: "immune-system", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 11: Evidence", blurb: "Risk factors, immunity and the science of vaccination", icon: "💉" }],
  strands: [
    {
      id: "risk-factors",
      name: "Lifestyle risk factors",
      descriptor: "Distinguish correlation from causation and evaluate evidence linking lifestyle to disease.",
      guided: [
        { level: 2, body: "A risk factor is something that increases the chance of developing a disease. Smoking, poor diet, physical inactivity, alcohol and obesity are all lifestyle risk factors. The Doll & Hill 1950 study was the first large study to link smoking to lung cancer." },
        { level: 4, body: "Correlation means two variables change together — it does not prove one causes the other. Causation means one variable directly causes a change in another. In the Doll & Hill study, 40,000 UK doctors were followed over many years (a prospective cohort study). Heavy smokers had a 25× higher risk of lung cancer. Other risk factors: alcohol → liver cirrhosis and cancer; physical inactivity → Type 2 diabetes and cardiovascular disease; poor diet → obesity and deficiency diseases." },
        { level: 6, body: "Confounding variables can create false correlations. For example, smokers may also have poor diets, making it harder to separate the effect of smoking alone. Doll & Hill controlled for age and gender. Modern evidence now shows causation for smoking → lung cancer because: (1) dose–response relationship (more cigarettes = higher risk), (2) biological mechanism identified (carcinogens in tar mutate p53 tumour suppressor gene), (3) risk decreases when people stop smoking. Obesity increases risk of joint damage, sleep apnoea, Type 2 diabetes, and multiple cancers." },
        { level: 8, body: "Establishing causation requires Bradford Hill criteria: strength of association, consistency across studies, dose–response gradient, biological plausibility, temporality (cause precedes effect), and coherence with known biology. Doll & Hill satisfied all of these — heavy smokers had 25× lung cancer risk, the relationship was dose–dependent, carcinogens are mutagenic in vitro, and risk reverses on cessation. Confounders (age, genetics, socioeconomic status) must be statistically controlled using multivariate regression. A residual confounder is one not measured in the study — this is a key limitation of all epidemiological research." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "rf-l2",
            level: 2,
            prompt: "What is the difference between correlation and causation?",
            options: [
              { id: "a", text: "Correlation means one thing directly causes another" },
              { id: "b", text: "Causation means two variables change together without a direct link" },
              { id: "c", text: "Correlation is a statistical association; causation means one directly causes the other", correct: true },
              { id: "d", text: "They are the same thing in scientific research" },
            ],
            explanation: "Correlation shows two variables change together (e.g. smoking and lung cancer both increase). Causation means smoking directly causes lung cancer — established through additional evidence including mechanism and dose–response.",
          },
          {
            type: "fill",
            id: "rf-l4",
            level: 4,
            prompt: "The Doll & Hill 1950 study found that heavy smokers had a ▁ higher risk of developing lung cancer compared to non-smokers.",
            answers: ["25×", "25 times", "25x", "twenty-five times"],
            explanation: "Doll & Hill's prospective cohort study of 40,000 UK doctors found heavy smokers had a 25× higher risk of lung cancer — one of the strongest statistical associations in epidemiology.",
          },
          {
            type: "short",
            id: "rf-l6",
            level: 6,
            prompt: "Explain why a correlation between two variables does not automatically prove causation. Use one named example and describe what additional evidence would be needed.",
            keywords: ["correlation", "causation", "confounding", "mechanism", "dose-response", "smoking", "lung cancer", "evidence", "control"],
            minKeywords: 2,
            sample: "Correlation shows that two variables increase together — for example, smoking and lung cancer both increase — but this could be due to a confounding variable such as diet or stress. To establish causation, researchers need a biological mechanism (e.g. carcinogens in tar mutate the p53 gene), a dose–response relationship (more cigarettes = higher risk), and evidence that the risk decreases when the cause is removed (risk falls after quitting smoking).",
          },
          {
            type: "short",
            id: "rf-l8",
            level: 8,
            prompt: "Using the Bradford Hill criteria, explain how scientists established that smoking causes lung cancer rather than merely correlating with it. Discuss the role of confounding variables.",
            keywords: ["bradford hill", "dose-response", "strength", "consistency", "biological plausibility", "temporality", "confounding", "multivariate", "p53", "carcinogen", "residual"],
            minKeywords: 3,
            sample: "The Bradford Hill criteria require: strength (25× risk for heavy smokers), consistency (multiple independent studies agree), dose–response (more cigarettes = more risk), biological plausibility (carcinogens in tar mutate the p53 tumour suppressor gene), and temporality (smoking precedes cancer). Confounders — variables that correlate with both smoking and cancer such as age or socioeconomic status — must be controlled by multivariate regression. Residual confounders (unmeasured variables) remain a limitation of all observational studies, but the weight of evidence firmly establishes causation.",
          },
        ],
      },
    },
    {
      id: "bmi-screening",
      name: "Body mass index and health screening",
      descriptor: "Calculate and interpret BMI, identify its limitations, and describe health screening programmes.",
      guided: [
        { level: 2, body: "BMI (Body Mass Index) is calculated as mass (kg) divided by height (m) squared: BMI = mass/height². Ranges: below 18.5 = underweight, 18.5–24.9 = healthy, 25–29.9 = overweight, 30 or above = obese." },
        { level: 4, body: "BMI is a quick screening tool used by health services to identify people at risk of weight-related diseases such as Type 2 diabetes and cardiovascular disease. Limitations include: BMI overestimates body fat in muscular individuals (e.g. athletes), underestimates fat in elderly people with muscle wasting, and does not account for fat distribution. Waist-to-hip ratio is an alternative measure that captures abdominal (visceral) fat more accurately." },
        { level: 6, body: "Metabolic syndrome is a cluster of conditions that together increase cardiovascular disease risk: central obesity (waist circumference >102 cm in men, >88 cm in women), high triglycerides, high blood pressure, and high fasting blood glucose. A person can have a normal BMI but still have metabolic syndrome if they carry fat predominantly around the abdomen (an 'apple' shape). Ethnicity-specific BMI thresholds are needed — South Asian populations have higher cardiovascular risk at a lower BMI (threshold ≥23 recommended by WHO)." },
        { level: 8, body: "BMI was designed as a population-level epidemiological tool, not an individual clinical diagnostic. Its limitations are systematic: in a sample of 1,000 people, DEXA scanning (dual-energy X-ray absorptiometry, the gold standard for body composition) would reclassify ~20% of those labelled 'healthy BMI' as having excess body fat. Central adiposity measured by waist-to-hip ratio or waist circumference is a better predictor of visceral fat and metabolic risk. The NICE guidelines in the UK now recommend using BMI as a first screen, then waist circumference as a second measure, and applying ethnicity-specific cut-offs for people of South Asian, Chinese, Japanese, and Black African or Caribbean origin." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "bmi-l2",
            level: 2,
            prompt: "A person has a mass of 80 kg and a height of 2.0 m. What is their BMI and which category does it fall into?",
            options: [
              { id: "a", text: "BMI = 20; healthy weight" },
              { id: "b", text: "BMI = 40; obese" },
              { id: "c", text: "BMI = 20; underweight" },
              { id: "d", text: "BMI = 160; overweight" },
            ],
            explanation: "BMI = 80 / (2.0)² = 80 / 4 = 20. A BMI of 20 falls in the healthy range (18.5–24.9).",
          },
          {
            type: "fill",
            id: "bmi-l4",
            level: 4,
            prompt: "BMI overestimates body fat in ▁ individuals because muscle is denser than fat.",
            answers: ["muscular", "athletic", "athletes", "heavily muscled"],
            explanation: "Muscle is denser than fat, so a muscular person can have a high BMI while actually having a healthy or low body fat percentage. BMI cannot distinguish between muscle mass and fat mass.",
          },
          {
            type: "short",
            id: "bmi-l6",
            level: 6,
            prompt: "Explain what metabolic syndrome is and why waist-to-hip ratio may be a better health screening measure than BMI for some individuals.",
            keywords: ["metabolic syndrome", "waist", "central obesity", "triglycerides", "blood pressure", "glucose", "visceral", "fat distribution", "bmi", "limitation"],
            minKeywords: 2,
            sample: "Metabolic syndrome is a cluster of conditions including central obesity, high triglycerides, high blood pressure, and high fasting blood glucose, which together greatly increase cardiovascular disease risk. BMI does not measure where fat is stored — a person with a normal BMI may carry excess visceral fat around the abdomen, which is more metabolically dangerous. Waist-to-hip ratio directly measures abdominal fat distribution and is a better predictor of metabolic risk than BMI alone.",
          },
          {
            type: "short",
            id: "bmi-l8",
            level: 8,
            prompt: "Critically evaluate BMI as a clinical screening tool. In your answer, refer to DEXA scanning, ethnicity-specific thresholds, and NICE guidelines.",
            keywords: ["dexa", "reclassify", "ethnicity", "south asian", "waist circumference", "nice", "visceral", "population-level", "diagnostic", "threshold", "23"],
            minKeywords: 3,
            sample: "BMI was designed as a population-level tool, not an individual diagnostic. DEXA scanning — the gold standard for body composition — would reclassify approximately 20% of 'healthy BMI' individuals as having excess fat. Ethnicity-specific thresholds are required: South Asian populations face higher cardiovascular risk at a BMI that would be classified as healthy for European populations, so WHO recommends a threshold of ≥23 for these groups. NICE guidelines recommend using BMI as a first screen, then adding waist circumference as a second measure, combining both for a more accurate assessment of metabolic risk.",
          },
        ],
      },
    },
    {
      id: "immune-system",
      name: "Immune system",
      descriptor: "Compare innate and adaptive immunity and explain the basis of immunological memory.",
      guided: [
        { level: 2, body: "The immune system has two main branches: innate immunity (immediate, non-specific) and adaptive immunity (slower, specific, and permanent). Innate defences include the skin barrier, mucus, cilia, phagocytes, and fever. Adaptive immunity involves B-lymphocytes and T-lymphocytes." },
        { level: 4, body: "Innate immunity: skin blocks pathogens physically; mucus traps pathogens in the respiratory tract; cilia sweep mucus away; phagocytes (neutrophils and macrophages) engulf and destroy pathogens by phagocytosis; complement proteins punch holes in bacterial membranes; fever inhibits pathogen reproduction. Adaptive immunity: B-lymphocytes produce antibodies with antigen-specific binding sites that neutralise pathogens; T-helper cells activate B-cells; T-cytotoxic (killer) T-cells destroy infected body cells; natural killer cells destroy cells that lack self-markers." },
        { level: 6, body: "Clonal selection: when a B-cell encounters its matching antigen, it is selected and divides rapidly (clonal expansion) to produce many identical antibody-secreting plasma cells. After the infection, most plasma cells die but some differentiate into memory B-cells. On second exposure to the same antigen, memory cells enable a faster and much stronger secondary immune response — so fast the pathogen is eliminated before symptoms appear. T-helper cells are central coordinators: without them, B-cells cannot mount a full antibody response (this is why HIV, which destroys T-helper cells, is so devastating)." },
        { level: 8, body: "Immunological memory operates via two mechanisms: (1) memory B-cells have lower activation thresholds and proliferate faster than naïve B-cells; (2) memory T-cells persist for decades at higher frequencies than naïve T-cells and re-activate more rapidly. Affinity maturation during the secondary response also produces antibodies with higher antigen-binding affinity (somatic hypermutation in germinal centres). Natural killer (NK) cells bridge innate and adaptive immunity — they kill cells without prior sensitisation using 'missing self' recognition: they attack cells lacking MHC class I molecules, which viruses and tumours often downregulate to hide from cytotoxic T-cells." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "imm-l2",
            level: 2,
            prompt: "Which of the following is part of the innate immune response?",
            options: [
              { id: "a", text: "B-lymphocytes producing antibodies" },
              { id: "b", text: "Phagocytes engulfing pathogens", correct: true },
              { id: "c", text: "Clonal expansion of memory cells" },
              { id: "d", text: "T-helper cells activating B-cells" },
            ],
            explanation: "Phagocytes (neutrophils and macrophages) engulf and destroy pathogens by phagocytosis — this is immediate and non-specific, making it part of innate immunity. Antibodies, clonal expansion, and T-helper cell activation are all part of adaptive immunity.",
          },
          {
            type: "fill",
            id: "imm-l4",
            level: 4,
            prompt: "After a first infection, some B-cells differentiate into ▁ cells, which allow a faster and stronger immune response on second exposure to the same pathogen.",
            answers: ["memory", "memory B", "memory b"],
            explanation: "Memory B-cells persist after an infection. On second exposure to the same antigen, they proliferate rapidly and produce antibodies so quickly that the infection is usually cleared before symptoms develop.",
          },
          {
            type: "short",
            id: "imm-l6",
            level: 6,
            prompt: "Explain clonal selection and expansion. Why does the secondary immune response produce a faster and stronger reaction than the primary response?",
            keywords: ["clonal selection", "clonal expansion", "memory", "antigen", "b-cell", "antibody", "plasma cells", "secondary", "faster", "stronger"],
            minKeywords: 2,
            sample: "Clonal selection occurs when a B-cell with a matching receptor encounters its specific antigen — this activates the B-cell, which then divides rapidly (clonal expansion) to produce many identical plasma cells secreting the specific antibody. Some B-cells become memory cells. In a secondary exposure, memory cells recognise the antigen immediately and expand faster than naïve B-cells, producing a larger antibody response before symptoms develop.",
          },
          {
            type: "short",
            id: "imm-l8",
            level: 8,
            prompt: "Explain affinity maturation and the role of natural killer cells. How do NK cells use 'missing self' recognition to complement the actions of cytotoxic T-cells?",
            keywords: ["affinity maturation", "somatic hypermutation", "germinal centre", "natural killer", "missing self", "mhc class i", "cytotoxic", "virus", "tumour", "downregulate", "bridge"],
            minKeywords: 3,
            sample: "Affinity maturation occurs in germinal centres during a secondary response: B-cells undergo somatic hypermutation in their antibody genes, and those producing higher-affinity antibodies are selected — resulting in antibodies that bind the antigen more tightly than in the primary response. Natural killer (NK) cells use 'missing self' recognition: they attack cells lacking MHC class I surface proteins, which viruses and tumour cells often downregulate to escape cytotoxic T-cells. NK cells therefore complement cytotoxic T-cells by targeting the very cells that have evaded the adaptive response.",
          },
        ],
      },
    },
    {
      id: "vaccination",
      name: "Vaccination and herd immunity",
      descriptor: "Compare vaccine types and calculate herd immunity thresholds using R₀.",
      guided: [
        { level: 2, body: "Vaccination introduces antigens into the body to stimulate the immune system and produce memory cells without causing disease. Types of vaccine: live attenuated (weakened pathogen — e.g. MMR); inactivated (killed pathogen — e.g. flu); subunit (just antigens — e.g. hepatitis B, HPV); mRNA (codes for an antigen — e.g. COVID-19 Pfizer/Moderna)." },
        { level: 4, body: "Live attenuated vaccines (MMR, yellow fever) use a weakened form of the pathogen — they produce strong, long-lasting immunity, often with a single dose, but are not safe for immunocompromised individuals. Inactivated vaccines (seasonal flu, polio IPV) use a killed pathogen — safe for immunocompromised patients but may need booster doses. Subunit vaccines (hepatitis B, HPV) contain only specific antigen proteins — very safe but may require boosters. mRNA vaccines (COVID-19 Pfizer/Moderna) deliver mRNA that instructs cells to make the spike protein; they never enter the cell nucleus and cannot alter DNA." },
        { level: 6, body: "Herd immunity: if enough of the population is immune, the pathogen cannot find susceptible hosts to spread through, protecting even unvaccinated individuals. The herd immunity threshold = 1 − 1/R₀ (where R₀ is the basic reproduction number, the average number of people one infected person infects in a fully susceptible population). For measles (R₀ ≈ 15): threshold = 1 − 1/15 = 93%. For COVID-19 (R₀ ≈ 3): threshold = 1 − 1/3 = 67%. Active immunity (vaccination or natural infection) is long-lasting because memory cells are formed. Passive immunity (maternal antibodies across the placenta, antivenom, immunoglobulin injections) is immediate but temporary — no memory cells are produced." },
        { level: 8, body: "The mRNA vaccine platform: mRNA is delivered in lipid nanoparticles that protect it from degradation and facilitate cell entry. The ribosomes translate the mRNA into spike protein; the protein is displayed on the cell surface; the immune system mounts an adaptive response. mRNA is degraded within days and never enters the nucleus. The Pfizer–BioNTech BNT162b2 vaccine was 95% efficacious against COVID-19 in Phase III trials. The herd immunity threshold calculation assumes a homogeneous population — in reality, superspreader events, population heterogeneity, and waning immunity all complicate the estimate. Measles R₀ ≈ 15 requires ≥93% vaccination coverage — any community coverage below this creates a pathway for the virus to reach unvaccinated or immunocompromised individuals, which is why the Wakefield MMR-autism fraud had such devastating consequences for measles resurgence." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "vax-l2",
            level: 2,
            prompt: "Which type of vaccine uses mRNA to instruct cells to produce a viral protein?",
            options: [
              { id: "a", text: "Live attenuated vaccine" },
              { id: "b", text: "Inactivated vaccine" },
              { id: "c", text: "Subunit vaccine" },
              { id: "d", text: "mRNA vaccine", correct: true },
            ],
            explanation: "mRNA vaccines (such as the Pfizer and Moderna COVID-19 vaccines) deliver mRNA that instructs the body's ribosomes to make a viral protein (e.g. the SARS-CoV-2 spike protein), triggering an immune response.",
          },
          {
            type: "fill",
            id: "vax-l4",
            level: 4,
            prompt: "The herd immunity threshold for measles (R₀ = 15) is ▁ %.",
            answers: ["93", "93%", "93.3", "93.3%"],
            explanation: "Herd immunity threshold = 1 − 1/R₀ = 1 − 1/15 = 0.933 = 93.3%. At least 93% of the population must be immune to prevent measles spreading through a community.",
          },
          {
            type: "short",
            id: "vax-l6",
            level: 6,
            prompt: "Distinguish between active and passive immunity. Give one example of each and explain why passive immunity does not provide long-term protection.",
            keywords: ["active", "passive", "memory", "antibodies", "maternal", "temporary", "vaccination", "antivenom", "long-lasting", "no memory cells"],
            minKeywords: 2,
            sample: "Active immunity results from the immune system producing its own antibodies and memory cells — either through infection or vaccination (e.g. MMR vaccine). It is long-lasting because memory B-cells and T-cells persist. Passive immunity involves receiving antibodies made by another organism — for example, maternal antibodies passed across the placenta or antivenom. It provides immediate protection but is temporary because no memory cells are formed; once the transferred antibodies are degraded, protection is lost.",
          },
          {
            type: "short",
            id: "vax-l8",
            level: 8,
            prompt: "Explain how mRNA vaccines work and why they cannot alter a person's DNA. Calculate the herd immunity threshold for COVID-19 (R₀ = 3) and explain why the threshold for measles is so much higher.",
            keywords: ["mrna", "ribosome", "spike protein", "lipid nanoparticle", "nucleus", "dna", "threshold", "r0", "67%", "93%", "measles", "heterogeneity", "waning"],
            minKeywords: 3,
            sample: "mRNA vaccines deliver mRNA inside lipid nanoparticles into the cytoplasm of cells. Ribosomes translate the mRNA into a viral protein (e.g. the SARS-CoV-2 spike protein), which is displayed on the cell surface and triggers an adaptive immune response. The mRNA never enters the nucleus and is degraded within days, so it cannot alter DNA. Herd immunity threshold for COVID-19: 1 − 1/3 = 67%. For measles (R₀ ≈ 15): 1 − 1/15 = 93%. Measles is far more infectious (R₀ = 15 vs 3), so each infected person spreads it to 15 others — the firebreak of immunity must be proportionally larger to stop transmission.",
          },
        ],
      },
    },
  ],
}
