import type { StrandhootPack } from "../engine/types"

// Crit C data: Measles incidence vs MMR vaccination coverage across 8 countries (WHO data 2019).
// ln(incidence) vs coverage gives a straight line (exponential decline model).
// Gradient ≈ −0.085 ln(cases) per % coverage, confirming exponential decline.
// Herd immunity for measles achieved at ~95% (R₀=15, threshold=1−1/15=93.3%).
export const healthCritC: StrandhootPack = {
  slug: "health-crit-c",
  title: "Vaccination Coverage Dataset",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Vaccine coverage vs disease incidence",
  accent: "#0984b5",
  icon: "💉",
  statementOfInquiry: "Healthy lifestyles can be based on evidence of relationships between types of behaviour and risks of disease.",
  estMinutes: 30,
  intro:
    "WHO data from 8 countries shows how measles incidence drops as MMR vaccination coverage rises. Use the data tool to plot, transform, and analyse — then conclude whether the exponential decline model holds, and evaluate the quality of the dataset. Each written strand levels up with the depth of your scientific reasoning.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Epidemiologist", icon: "🔬", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "evaluator", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Vaccination dataset", blurb: "Measles incidence vs MMR coverage across 8 countries", icon: "💉" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the vaccination coverage vs disease incidence data clearly and apply a linearising transform.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with numbers but missing column headings or units." },
        { level: 4, body: "Level 3–4: A clear table with headings (MMR vaccination coverage %; measles incidence cases per 100,000) and a graph with both axes labelled including units." },
        { level: 6, body: "Level 5–6: Axes labelled with units, a sensible scale filling the grid, points accurately plotted with a smooth curve of best fit showing the exponential decrease in incidence as coverage rises." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised graph of ln(incidence) vs coverage (%). If incidence declines exponentially with coverage, this transform should give a straight line — far easier to calculate a gradient from. A straight line on the ln plot confirms the exponential model. The gradient of the ln plot gives the rate of incidence decline per percentage point of vaccination coverage." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Measles incidence vs vaccination coverage across 8 countries (WHO data 2019)",
        xLabel: "MMR vaccination coverage (%)",
        yLabel: "Measles incidence (cases per 100,000 population)",
        editable: true,
        initialRows: [
          { x: 20, y: 850 },
          { x: 30, y: 620 },
          { x: 40, y: 430 },
          { x: 50, y: 280 },
          { x: 60, y: 160 },
          { x: 70, y: 80 },
          { x: 80, y: 30 },
          { x: 90, y: 5 },
        ],
        transforms: [
          { id: "raw", label: "Disease incidence vs vaccination coverage", x: "x", y: "y", xLabel: "Coverage (%)", yLabel: "Incidence (cases/100,000)" },
          { id: "ln", label: "ln(incidence) vs vaccination coverage (exponential decline model)", x: "x", y: "ln(y)", xLabel: "Coverage (%)", yLabel: "ln(incidence)" },
        ],
        derive: { kind: "gradient", label: "Rate of incidence decline per % vaccination coverage", unit: "ln(cases) per %" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted incidence on the y-axis against vaccination coverage on...",
          "The graph shows a... trend because...",
          "I linearised the data by plotting ln(incidence) vs coverage (%) because...",
          "The straight line on the ln plot confirms...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data, graph, or table.", keywords: ["table", "graph", "data", "incidence", "vaccination", "coverage"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "cases", "per 100,000", "percentage", "coverage"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve of best fit; exponential trend described.", keywords: ["curve", "best fit", "decreases", "exponential", "smooth", "accurate", "scale", "sharp"], minKeywords: 2 },
          { level: 8, descriptor: "Linearised ln plot described as a straight line confirming exponential model.", keywords: ["ln", "straight line", "linear", "logarithm", "transform", "gradient", "exponential model", "confirms"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient of the ln(incidence) vs coverage graph and interpret its meaning.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('Incidence gets smaller as vaccination coverage increases')." },
        { level: 4, body: "Level 3–4: Calculates the change in incidence over the range (850 to 5 cases per 100,000) and notes the decrease is very large and non-linear (exponential)." },
        { level: 6, body: "Level 5–6: From the ln(incidence) vs coverage (%) graph, draws a line of best fit and reads off two widely-spaced points to calculate gradient = Δln(incidence) / Δcoverage (%). States the unit of the gradient as ln(cases) per %." },
        { level: 8, body: "Level 7–8: Full calculation shown using two points — e.g. (20%, 850 cases) and (90%, 5 cases): ln(850) = 6.75, ln(5) = 1.61. Gradient = (1.61 − 6.75) / (90 − 20) = −5.14 / 70 ≈ −0.073 ln(cases) per %. This means each 1% increase in vaccination coverage reduces ln(incidence) by approximately 0.073 — corresponding to incidence multiplied by e^(−0.073) ≈ 0.93 (a ~7% reduction in absolute incidence per percentage point of vaccination coverage). Herd immunity for measles is predicted at ≥93% coverage (R₀ = 15): above this, the data predict incidence would approach zero." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Measles incidence vs vaccination coverage across 8 countries (WHO data 2019)",
        xLabel: "MMR vaccination coverage (%)",
        yLabel: "Measles incidence (cases per 100,000 population)",
        editable: true,
        initialRows: [
          { x: 20, y: 850 },
          { x: 30, y: 620 },
          { x: 40, y: 430 },
          { x: 50, y: 280 },
          { x: 60, y: 160 },
          { x: 70, y: 80 },
          { x: 80, y: 30 },
          { x: 90, y: 5 },
        ],
        transforms: [
          { id: "raw", label: "Disease incidence vs vaccination coverage", x: "x", y: "y", xLabel: "Coverage (%)", yLabel: "Incidence (cases/100,000)" },
          { id: "ln", label: "ln(incidence) vs vaccination coverage (exponential decline model)", x: "x", y: "ln(y)", xLabel: "Coverage (%)", yLabel: "ln(incidence)" },
        ],
        derive: { kind: "gradient", label: "Rate of incidence decline per % vaccination coverage", unit: "ln(cases) per %" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the ln(incidence) vs coverage graph and state what it means in terms of disease decline per percentage of vaccination coverage.",
        scaffolds: [
          "The trend shows that incidence...",
          "From the ln plot I chose two points: (coverage₁, ln(incidence₁)) = ... and (coverage₂, ln(incidence₂)) = ...",
          "Gradient = Δln(incidence) / Δcoverage = ... / ... = ... ln(cases) per %",
          "This means each 1% increase in coverage reduces incidence by approximately...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes incidence decreases as coverage increases.", keywords: ["decreases", "increases", "coverage", "incidence", "falls", "trend"], minKeywords: 1 },
          { level: 4, descriptor: "Describes exponential decrease; range noted.", keywords: ["exponential", "decrease", "850", "5", "range", "large", "non-linear"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated from ln plot with working.", keywords: ["gradient", "ln", "delta", "slope", "two points", "best fit", "ln(cases) per %"], minKeywords: 2 },
          { level: 8, descriptor: "Full gradient calculation with interpretation; herd immunity threshold noted.", keywords: ["6.75", "1.61", "−0.073", "0.93", "7%", "93%", "herd immunity", "e^", "r0", "15", "zero"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about the relationship between vaccination coverage and measles incidence, with reference to herd immunity.",
      guided: [
        { level: 2, body: "Level 1–2: 'Measles incidence decreased as vaccination coverage increased.'" },
        { level: 4, body: "Level 3–4: 'Measles incidence fell as MMR vaccination coverage rose, showing vaccination reduces disease spread in the population — this supports the idea that vaccination protects communities, not just individuals.'" },
        { level: 6, body: "Level 5–6: 'Incidence fell from 850 to 5 cases per 100,000 as coverage rose from 20% to 90%. The ln(incidence) vs coverage graph is approximately linear, confirming an exponential decline model. The gradient of approximately −0.073 per % coverage means each additional 1% of coverage reduces incidence by ~7%. This demonstrates population-level protection: as coverage approaches the measles herd immunity threshold (~93%, calculated from R₀ = 15), incidence approaches zero — even unvaccinated individuals are protected.'" },
        { level: 8, body: "Level 7–8: Full conclusion with quantified gradient, herd immunity threshold derived and justified, and link to R₀ = 15. At 90% coverage, incidence has already dropped to 5 per 100,000 — a 99.4% reduction from 850. The data suggest the exponential decline model holds well up to 90% coverage. Above 93% (herd immunity threshold for measles, derived from 1 − 1/R₀ = 1 − 1/15), theory predicts incidence should drop to near zero — these data cannot test this as the maximum coverage in the dataset is only 90%. The finding is consistent with WHO data showing measles resurgence in European countries where coverage dropped below 95% (e.g. 2018–2019: 83,000 cases in Europe)." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Measles incidence vs vaccination coverage across 8 countries (WHO data 2019)",
        xLabel: "MMR vaccination coverage (%)",
        yLabel: "Measles incidence (cases per 100,000 population)",
        editable: true,
        initialRows: [
          { x: 20, y: 850 },
          { x: 30, y: 620 },
          { x: 40, y: 430 },
          { x: 50, y: 280 },
          { x: 60, y: 160 },
          { x: 70, y: 80 },
          { x: 80, y: 30 },
          { x: 90, y: 5 },
        ],
        transforms: [
          { id: "raw", label: "Disease incidence vs vaccination coverage", x: "x", y: "y", xLabel: "Coverage (%)", yLabel: "Incidence (cases/100,000)" },
          { id: "ln", label: "ln(incidence) vs vaccination coverage (exponential decline model)", x: "x", y: "ln(y)", xLabel: "Coverage (%)", yLabel: "ln(incidence)" },
        ],
        derive: { kind: "gradient", label: "Rate of incidence decline per % vaccination coverage", unit: "ln(cases) per %" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. Does the data support the exponential decline model? Use values from the dataset and link to herd immunity for measles (R₀ = 15).",
        scaffolds: [
          "As vaccination coverage increased from 20% to 90%, measles incidence...",
          "The ln(incidence) vs coverage graph shows... which confirms...",
          "The gradient of approximately −0.073 per % means...",
          "The herd immunity threshold for measles is ___% because R₀ = 15...",
          "The data are consistent with / limited in testing this because...",
        ],
        rubric: [
          { level: 2, descriptor: "States incidence decreases with coverage.", keywords: ["decreases", "incidence", "coverage", "vaccination", "falls"], minKeywords: 1 },
          { level: 4, descriptor: "Population-level protection mentioned; community immunity stated.", keywords: ["community", "population", "protection", "herd", "unvaccinated", "spread", "decline"], minKeywords: 1 },
          { level: 6, descriptor: "Specific values used; gradient interpreted; herd immunity threshold calculated.", keywords: ["850", "5", "20%", "90%", "−0.073", "93%", "herd immunity", "r0", "15", "ln", "exponential"], minKeywords: 3 },
          { level: 8, descriptor: "Full conclusion with limitation on 90% ceiling and reference to European resurgence.", keywords: ["99.4%", "93%", "threshold", "1−1/r0", "2018", "83000", "europe", "resurgence", "90% coverage", "cannot test", "above"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in this cross-sectional dataset and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could be improved.'" },
        { level: 4, body: "Level 3–4: 'Only 8 countries are included, which makes it hard to generalise the findings globally.'" },
        { level: 6, body: "Level 5–6: 'A key limitation is that this is cross-sectional — it is a snapshot in time and cannot show whether vaccination caused the change in incidence (only a longitudinal study tracking the same countries over time could demonstrate causation). Also, only 8 countries are included — more data points would increase reliability and allow outliers to be identified. A systematic error: wealthier countries may have both higher vaccination coverage and better healthcare systems, which independently reduce incidence (confounding variable).'" },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses with quantified improvements: (1) Cross-sectional design cannot establish causation — improvement: track the same 50 countries over 20 years (longitudinal cohort). (2) Only 8 data points — this limits the power of the regression analysis; a minimum of 30–50 countries is needed for a statistically robust correlation. (3) No data above 90% coverage — this is exactly the range where herd immunity effects would be most visible; improvement: include countries with >93% coverage. (4) GDP/healthcare quality as a confounding variable — higher-income countries have both better vaccination programmes and better nutrition and medical care, which independently reduce measles severity; improvement: stratify analysis by income group. (5) Self-reported incidence data: countries with weak surveillance systems may underreport cases — use WHO-standardised reporting protocols." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Measles incidence vs vaccination coverage across 8 countries (WHO data 2019)",
        xLabel: "MMR vaccination coverage (%)",
        yLabel: "Measles incidence (cases per 100,000 population)",
        editable: true,
        initialRows: [
          { x: 20, y: 850 },
          { x: 30, y: 620 },
          { x: 40, y: 430 },
          { x: 50, y: 280 },
          { x: 60, y: 160 },
          { x: 70, y: 80 },
          { x: 80, y: 30 },
          { x: 90, y: 5 },
        ],
        transforms: [
          { id: "raw", label: "Disease incidence vs vaccination coverage", x: "x", y: "y", xLabel: "Coverage (%)", yLabel: "Incidence (cases/100,000)" },
          { id: "ln", label: "ln(incidence) vs vaccination coverage (exponential decline model)", x: "x", y: "ln(y)", xLabel: "Coverage (%)", yLabel: "ln(incidence)" },
        ],
        derive: { kind: "gradient", label: "Rate of incidence decline per % vaccination coverage", unit: "ln(cases) per %" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect this vaccination coverage dataset. What are the main weaknesses and how would you improve them?",
        scaffolds: [
          "A key weakness is that this is a cross-sectional study, which means...",
          "This affects the result because...",
          "To improve this, I would...",
          "A confounding variable is...",
          "Reliability could be improved by including more countries because...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem", "small"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned.", keywords: ["8 countries", "few", "cross-sectional", "causation", "generalise", "small sample"], minKeywords: 1 },
          { level: 6, descriptor: "Cross-sectional limitation explained; confounding variable named.", keywords: ["cross-sectional", "causation", "longitudinal", "confounding", "healthcare", "gdp", "wealth", "improve", "more countries"], minKeywords: 2 },
          { level: 8, descriptor: "Multiple specific weaknesses with quantified improvements; surveillance bias mentioned.", keywords: ["30", "50 countries", "longitudinal", "stratify", "income", "underreport", "surveillance", "93%", "no data above 90", "who-standardised", "regression", "power"], minKeywords: 3 },
        ],
      },
    },
  ],
}
