import type { StrandhootPack } from "../engine/types"

export const homeostasisCritA: StrandhootPack = {
  slug: "homeostasis-crit-a",
  title: "Homeostasis & Biogeochemical Cycles",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Regulation and nutrient cycling",
  accent: "#1b7888",
  icon: "⚖️",
  statementOfInquiry: "Development is only sustainable if systems remain in balance.",
  estMinutes: 25,
  intro:
    "From the hypothalamus sensing your core temperature to bacteria fixing nitrogen in root nodules, living systems use feedback loops to maintain balance. Each strand targets a core concept from Chapter 7: Homeostasis and Biogeochemical Cycles, levelling up from recall to analysis.",
  badges: [
    { id: "thermo", label: "Thermostat Expert", icon: "🌡️", description: "Reach Level 8 on Thermoregulation", strandId: "thermoregulation", atLevel: 8 },
    { id: "glucose", label: "Glucose Guardian", icon: "🍬", description: "Reach Level 8 on Blood glucose regulation", strandId: "blood-glucose", atLevel: 8 },
    { id: "nitrogen", label: "Nitrogen Ninja", icon: "🌿", description: "Reach Level 8 on Nitrogen cycle", strandId: "nitrogen-cycle", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 7: Balance", blurb: "Thermoregulation, blood glucose, carbon and nitrogen cycles", icon: "⚖️" }],
  strands: [
    {
      id: "thermoregulation",
      name: "Thermoregulation",
      descriptor: "Explain the negative feedback mechanisms that maintain body temperature at 37°C.",
      guided: [
        { level: 2, body: "Normal human core body temperature is 37°C. The hypothalamus in the brain acts as the body's thermostat — thermoreceptors detect if temperature rises above or falls below the set point, and it triggers corrective responses." },
        { level: 4, body: "Too hot responses: vasodilation (blood vessels near the skin widen → more blood to skin surface → more heat lost by radiation), sweating (evaporation removes heat from the skin), hair erector muscles relax (hairs lie flat). Too cold responses: vasoconstriction (blood vessels near skin narrow → less blood at surface → less heat lost), shivering (rapid muscle contractions generate heat), piloerection (hairs stand up → trap insulating air layer)." },
        { level: 6, body: "These are negative feedback loops: a deviation from the set point (37°C) triggers a response that opposes the deviation and returns the body to normal. The hypothalamus receives signals from thermoreceptors in the skin (peripheral) and in itself (central). The response reduces the stimulus — when temperature returns to 37°C, the response switches off." },
        { level: 8, body: "Vasodilation increases surface area of blood capillaries near the skin and shunts more blood through arteriovenous anastomoses, maximising heat loss by conduction, convection, and radiation. Sweating is particularly efficient at high temperatures because the latent heat of vaporisation of water is high (~2260 J/g). In very cold conditions, peripheral vasoconstriction can reduce skin temperature to near ambient without dropping core temperature — a counter-current heat exchange mechanism in limb blood vessels further reduces heat loss. This compartmentalisation of core and shell temperatures is what allows humans to survive in extreme cold while maintaining the enzymatic conditions of 37°C for core organ function." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "thermo-l2",
            level: 2,
            prompt: "Which part of the brain detects changes in body temperature and coordinates the response?",
            options: [
              { id: "a", text: "Cerebellum" },
              { id: "b", text: "Hypothalamus", correct: true },
              { id: "c", text: "Medulla oblongata" },
              { id: "d", text: "Cerebral cortex" },
            ],
            explanation: "The hypothalamus contains thermoreceptors and acts as the body's thermostat, coordinating responses to maintain core temperature at 37°C.",
          },
          {
            type: "fill",
            id: "thermo-l4",
            level: 4,
            prompt: "When the body is too hot, blood vessels near the skin surface widen — a process called ▁ — which increases heat loss.",
            answers: ["vasodilation"],
            explanation: "Vasodilation widens superficial blood vessels, bringing more warm blood to the skin surface where heat can be lost to the environment by radiation and convection.",
          },
          {
            type: "short",
            id: "thermo-l6",
            level: 6,
            prompt: "Explain why thermoregulation is described as a negative feedback loop. Use the example of the body's response to overheating.",
            keywords: ["negative feedback", "set point", "hypothalamus", "vasodilation", "sweating", "opposes", "deviation", "returns", "response", "37"],
            minKeywords: 2,
            sample: "Negative feedback means the response opposes the original change. When body temperature rises above 37°C (the set point), thermoreceptors signal the hypothalamus, which triggers vasodilation and sweating. These responses cool the body, reducing the deviation from the set point. Once temperature returns to 37°C, the response switches off — the feedback is negative because it opposes the stimulus.",
          },
          {
            type: "short",
            id: "thermo-l8",
            level: 8,
            prompt: "Compare the mechanisms of vasodilation and sweating as heat-loss responses. Explain why sweating is particularly effective at high temperatures, using the concept of latent heat of vaporisation.",
            keywords: ["vasodilation", "radiation", "conduction", "convection", "sweating", "evaporation", "latent heat", "vaporisation", "efficient", "water", "heat loss", "temperature"],
            minKeywords: 3,
            sample: "Vasodilation increases blood flow to the skin surface, increasing heat loss by radiation, conduction, and convection. Sweating is particularly effective because it uses the latent heat of vaporisation of water (~2260 J/g) — evaporating sweat removes large amounts of thermal energy from the skin even when the air temperature is close to body temperature. At very high ambient temperatures, radiation and convection become ineffective (or even add heat), making sweating the primary cooling mechanism.",
          },
        ],
      },
    },
    {
      id: "blood-glucose",
      name: "Blood glucose regulation",
      descriptor: "Describe how insulin and glucagon maintain blood glucose within the normal range.",
      guided: [
        { level: 2, body: "After eating, blood glucose rises. Between meals, blood glucose falls. The pancreas releases hormones to correct both deviations and keep blood glucose within the normal range of approximately 4–7 mmol/L." },
        { level: 4, body: "After eating (high blood glucose): β-cells of the pancreas release insulin → liver and muscle cells take up glucose and convert it to glycogen (glycogenesis) → blood glucose falls back to normal. Between meals (low blood glucose): α-cells of the pancreas release glucagon → liver converts glycogen back to glucose (glycogenolysis) → blood glucose rises back to normal. This is another negative feedback system." },
        { level: 6, body: "The two hormones work antagonistically (opposite effects). Insulin is the 'store it' hormone: it also increases glucose uptake by body cells for respiration and stimulates fat storage. Glucagon is the 'release it' hormone: it also stimulates gluconeogenesis (making new glucose from amino acids and fats). The set point is ~4–7 mmol/L. In Type 1 diabetes, β-cells are destroyed by an autoimmune response, so no insulin is produced and blood glucose cannot be lowered." },
        { level: 8, body: "Insulin acts via a receptor tyrosine kinase cascade: binding insulin to its receptor on target cells triggers phosphorylation of GLUT4 transporter vesicles, causing them to fuse with the plasma membrane and insert glucose transporters — increasing glucose uptake by ~10-fold. The liver's dual role is central: in the absorptive state (post-meal), it acts as a buffer by storing glucose as glycogen (up to ~100g); in the post-absorptive state (fasting), it exports glucose via glycogenolysis and gluconeogenesis. The brain requires a constant glucose supply (~120g/day) and cannot use fatty acids, making tight blood glucose regulation an existential priority." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "glucose-l2",
            level: 2,
            prompt: "Which hormone is released by the pancreas when blood glucose levels are too high?",
            options: [
              { id: "a", text: "Glucagon" },
              { id: "b", text: "Adrenaline" },
              { id: "c", text: "Insulin", correct: true },
              { id: "d", text: "Thyroxine" },
            ],
            explanation: "Insulin is released by the β-cells of the pancreas when blood glucose rises (e.g. after eating). It causes cells to take up glucose and the liver to store it as glycogen.",
          },
          {
            type: "fill",
            id: "glucose-l4",
            level: 4,
            prompt: "When the liver converts glucose to glycogen for storage, this process is called ▁.",
            answers: ["glycogenesis"],
            explanation: "Glycogenesis is the synthesis of glycogen from glucose, stimulated by insulin. The reverse process — breaking glycogen back down to glucose — is glycogenolysis, stimulated by glucagon.",
          },
          {
            type: "short",
            id: "glucose-l6",
            level: 6,
            prompt: "Explain how insulin and glucagon work antagonistically to regulate blood glucose. Include the roles of both the pancreas and the liver.",
            keywords: ["insulin", "glucagon", "beta", "alpha", "pancreas", "liver", "glycogen", "glycogenesis", "glycogenolysis", "antagonistic", "negative feedback", "blood glucose"],
            minKeywords: 2,
            sample: "Insulin (from β-cells) and glucagon (from α-cells) are antagonistic hormones. When blood glucose rises, insulin causes liver and muscle cells to convert glucose to glycogen (glycogenesis) — lowering blood glucose. When blood glucose falls, glucagon causes the liver to convert glycogen back to glucose (glycogenolysis) — raising blood glucose. Together they form a negative feedback system keeping blood glucose at ~4–7 mmol/L.",
          },
          {
            type: "short",
            id: "glucose-l8",
            level: 8,
            prompt: "Explain how insulin increases glucose uptake in target cells at the molecular level. Why is the brain particularly dependent on tight blood glucose regulation?",
            keywords: ["receptor", "glut4", "transporter", "membrane", "phosphorylation", "uptake", "brain", "glucose", "fatty acids", "constant", "supply", "120g", "gluconeogenesis"],
            minKeywords: 3,
            sample: "Insulin binds to a receptor tyrosine kinase on target cells, triggering a phosphorylation cascade that causes GLUT4 transporter vesicles to fuse with the plasma membrane, inserting glucose transporters that increase glucose uptake ~10-fold. The brain is entirely dependent on glucose for energy (~120g/day) because neurons cannot use fatty acids as fuel. A drop in blood glucose (hypoglycaemia) rapidly impairs brain function, making blood glucose regulation an existential priority — hence why both insulin and glucagon operate on a minute-by-minute basis.",
          },
        ],
      },
    },
    {
      id: "carbon-cycle",
      name: "Carbon cycle",
      descriptor: "Trace the movement of carbon through the atmosphere, living organisms, and Earth's crust.",
      guided: [
        { level: 2, body: "Carbon moves between the atmosphere, living organisms, and the Earth. Plants remove CO₂ from the atmosphere during photosynthesis. Respiration by all living organisms returns CO₂ to the atmosphere." },
        { level: 4, body: "Key processes: photosynthesis (atmospheric CO₂ → organic compounds in plants), respiration (organic compounds → CO₂ in all organisms), decomposition (dead organic matter → CO₂ released by decomposers and detritivores), combustion (fossil fuels and wood burned → CO₂ released). Carbon sinks store carbon for long periods: peat bogs, limestone/CaCO₃ in shells and rock, and the deep ocean." },
        { level: 6, body: "The carbon cycle was roughly balanced before industrialisation — carbon released by respiration, decomposition and natural combustion equalled carbon fixed by photosynthesis. Burning fossil fuels releases carbon that was fixed millions of years ago and locked underground, creating a net transfer from a geological store to the atmosphere. This breaks the short-term balance, increasing atmospheric CO₂ from ~280 ppm (pre-industrial) to ~420 ppm today, driving climate change." },
        { level: 8, body: "Carbon reservoirs and residence times: atmosphere (~800 Gt C, decadal), terrestrial biosphere (~600 Gt C, years–centuries), soils and peat (~2000 Gt C, centuries–millennia), oceans (~38 000 Gt C, centuries–millennia), and geological carbon (fossil fuels ~4000 Gt, limestone ~60 000 000 Gt, timescales millions of years). Fossil fuel combustion adds ~10 Gt C/year to the atmosphere — roughly equal to all terrestrial biosphere carbon in 60 years. Ocean acidification (CO₂ + H₂O → H₂CO₃) threatens marine calcifiers (coral, molluscs) whose CaCO₃ shells dissolve as pH falls — a feedback that could weaken one of the largest long-term carbon sinks." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "carbon-l2",
            level: 2,
            prompt: "Which process removes CO₂ from the atmosphere and incorporates it into organic compounds in plants?",
            options: [
              { id: "a", text: "Respiration" },
              { id: "b", text: "Decomposition" },
              { id: "c", text: "Combustion" },
              { id: "d", text: "Photosynthesis", correct: true },
            ],
            explanation: "Photosynthesis uses light energy to convert atmospheric CO₂ into organic compounds (glucose) stored in plant tissue, removing carbon from the atmosphere.",
          },
          {
            type: "fill",
            id: "carbon-l4",
            level: 4,
            prompt: "Peat bogs, deep ocean water, and limestone rocks are examples of carbon ▁ — places where carbon is stored for long periods.",
            answers: ["sinks", "carbon sinks"],
            explanation: "Carbon sinks are reservoirs that absorb and store more carbon than they release. Peat, limestone (CaCO₃), and the deep ocean lock carbon away for centuries or millions of years.",
          },
          {
            type: "short",
            id: "carbon-l6",
            level: 6,
            prompt: "Explain why burning fossil fuels disrupts the carbon cycle in a way that respiration does not.",
            keywords: ["fossil fuels", "millions of years", "geological", "locked", "atmosphere", "respiration", "balance", "photosynthesis", "net transfer", "co2", "ppm", "stored"],
            minKeywords: 2,
            sample: "Respiration releases carbon that was recently fixed by photosynthesis, so the carbon stays within the short-term cycle — it is balanced by ongoing photosynthesis. Fossil fuels, however, contain carbon that was fixed millions of years ago and locked in geological stores underground. Burning them releases this ancient carbon as CO₂, creating a net transfer into the atmosphere with no equivalent removal process. This is why atmospheric CO₂ has risen from ~280 ppm to ~420 ppm since industrialisation.",
          },
          {
            type: "short",
            id: "carbon-l8",
            level: 8,
            prompt: "Compare the sizes of different carbon reservoirs and their residence times. Explain how ocean acidification could create a positive feedback loop that amplifies climate change.",
            keywords: ["atmosphere", "ocean", "fossil fuels", "limestone", "reservoir", "residence time", "acidification", "carbonic acid", "ph", "calcium carbonate", "coral", "calcifiers", "feedback", "sink", "dissolve"],
            minKeywords: 3,
            sample: "The geological carbon reservoir (limestone ~60 million Gt, fossil fuels ~4000 Gt) vastly exceeds the atmosphere (~800 Gt) and biosphere (~600 Gt). Oceans (~38 000 Gt) have intermediate capacity with residence times of centuries to millennia. Ocean acidification occurs when CO₂ dissolves to form carbonic acid, lowering pH. This threatens marine calcifiers (coral, molluscs) whose CaCO₃ shells dissolve in acidic conditions. If coral reefs and shell-forming organisms decline, their capacity to sequester carbon into limestone decreases — weakening this long-term carbon sink, leaving more CO₂ in the atmosphere, and amplifying warming in a positive feedback loop.",
          },
        ],
      },
    },
    {
      id: "nitrogen-cycle",
      name: "Nitrogen cycle",
      descriptor: "Describe the processes and organisms that cycle nitrogen through ecosystems.",
      guided: [
        { level: 2, body: "Nitrogen makes up 78% of the atmosphere as N₂ gas, but most organisms cannot use it directly. It must be 'fixed' — converted into usable forms like ammonium (NH₄⁺) or nitrate (NO₃⁻). Plants absorb nitrate from the soil; animals get nitrogen by eating plants or other animals." },
        { level: 4, body: "Four key processes: (1) Nitrogen fixation — Rhizobium bacteria in legume root nodules convert N₂ → NH₄⁺; also done by lightning and the industrial Haber process. (2) Nitrification — soil bacteria convert NH₃/NH₄⁺ → NO₂⁻ (Nitrosomonas) → NO₃⁻ (Nitrobacter). (3) Denitrification — anaerobic bacteria in waterlogged soil convert NO₃⁻ → N₂ gas (returns to atmosphere). (4) Decomposition/ammonification — dead organisms and waste are broken down by decomposers releasing NH₃/NH₄⁺ back to the soil." },
        { level: 6, body: "The nitrogen cycle involves mutualistic relationships: Rhizobium bacteria live in root nodules of legumes (peas, beans, clover) in a mutualistic symbiosis — the bacteria receive photosynthate (sugars) from the plant and in return fix N₂ into NH₄⁺ that the plant can use. Nitrification is an aerobic process (requires O₂), while denitrification is anaerobic (occurs in waterlogged, low-O₂ soils). Farmers use legume rotation crops to naturally enrich soil nitrogen without synthetic fertilizer." },
        { level: 8, body: "Rhizobium contains the enzyme nitrogenase, which reduces N₂ to NH₄⁺ at the high energy cost of 16 ATP per N₂ molecule — a highly endothermic process. Leghemoglobin in root nodules maintains low O₂ levels to protect nitrogenase (which is irreversibly denatured by O₂) while still allowing aerobic respiration to provide ATP. Denitrification is driven by facultative anaerobes using NO₃⁻ as the terminal electron acceptor in anaerobic respiration. Human disruption: the Haber process fixes ~120 Tg N/year (more than all biological fixation combined), massively exceeding the system's natural denitrification capacity, so excess NO₃⁻ accumulates, causing eutrophication of rivers, lakes, and coastal zones — a global biogeochemical imbalance." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "nitrogen-l2",
            level: 2,
            prompt: "Which type of bacteria, found in legume root nodules, converts atmospheric N₂ into ammonium (NH₄⁺) that plants can use?",
            options: [
              { id: "a", text: "Nitrosomonas" },
              { id: "b", text: "Nitrobacter" },
              { id: "c", text: "Clostridium" },
              { id: "d", text: "Rhizobium", correct: true },
            ],
            explanation: "Rhizobium bacteria live in root nodules of leguminous plants. They fix atmospheric nitrogen (N₂) into ammonium (NH₄⁺), making nitrogen available to the plant in a mutualistic relationship.",
          },
          {
            type: "fill",
            id: "nitrogen-l4",
            level: 4,
            prompt: "The conversion of NH₃/NH₄⁺ in the soil first to nitrite (NO₂⁻) and then to nitrate (NO₃⁻) by soil bacteria is called ▁.",
            answers: ["nitrification"],
            explanation: "Nitrification is a two-step aerobic process: Nitrosomonas converts ammonium to nitrite, then Nitrobacter converts nitrite to nitrate. Plants absorb nitrate from the soil for protein synthesis.",
          },
          {
            type: "short",
            id: "nitrogen-l6",
            level: 6,
            prompt: "Explain the mutualistic relationship between Rhizobium bacteria and leguminous plants. Why are legumes used in crop rotation?",
            keywords: ["rhizobium", "root nodules", "mutualism", "nitrogen fixation", "sugars", "photosynthate", "ammonium", "legumes", "crop rotation", "soil nitrogen", "symbiosis"],
            minKeywords: 2,
            sample: "Rhizobium bacteria live in root nodules of leguminous plants (peas, beans, clover) in a mutualistic relationship. The bacteria receive carbohydrates (photosynthate/sugars) from the plant as an energy source, and in return they fix atmospheric N₂ into NH₄⁺ that the plant can use to make proteins. Farmers use legumes in crop rotation because these plants naturally enrich the soil with fixed nitrogen — reducing the need for synthetic nitrogen fertilizers for the following crop.",
          },
          {
            type: "short",
            id: "nitrogen-l8",
            level: 8,
            prompt: "Explain why nitrogenase in Rhizobium must be protected from oxygen, and describe the mechanism used to achieve this. How has human nitrogen fixation disrupted the natural nitrogen cycle?",
            keywords: ["nitrogenase", "oxygen", "denatured", "leghemoglobin", "anaerobic", "atp", "haber process", "denitrification", "eutrophication", "nitrate", "accumulate", "imbalance", "fixing", "tg"],
            minKeywords: 3,
            sample: "Nitrogenase is irreversibly denatured by oxygen, yet Rhizobium needs aerobic respiration to supply the 16 ATP per N₂ molecule required for fixation. Leghemoglobin in root nodules binds free oxygen, maintaining very low O₂ tension while still supplying enough for respiration — a finely tuned balance. Human disruption: the Haber process now fixes more nitrogen annually (~120 Tg N/year) than all biological fixation combined, far exceeding the rate at which denitrifying bacteria can return NO₃⁻ to N₂. The surplus accumulates in soil and water, driving eutrophication of rivers, lakes, and coastal zones — a massive disruption to the global nitrogen cycle.",
          },
        ],
      },
    },
  ],
}
