import type { StrandhootPack } from "../engine/types"

export const homeostasisCritC: StrandhootPack = {
  slug: "homeostasis-crit-c",
  title: "Blood Glucose Over Time",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Glucose regulation dataset",
  accent: "#0984b5",
  icon: "⚖️",
  statementOfInquiry: "Development is only sustainable if systems remain in balance.",
  estMinutes: 30,
  intro:
    "A healthy participant ate a standard meal and had their blood glucose measured every 30 minutes for 3.5 hours. Use the data tool to plot, transform and analyse — then draw a conclusion about the insulin response and evaluate the method.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Glucose Expert", icon: "🍬", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "evaluator", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Blood glucose dataset", blurb: "Blood glucose concentration after a meal in a healthy individual", icon: "⚖️" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the blood glucose data clearly and apply a 1/y transform to show rate of glucose clearance.",
      guided: [
        { level: 2, body: "A basic table with data values but missing headings or units." },
        { level: 4, body: "A clear table with column headings (Time in minutes; Blood glucose in mmol/L) and a graph with both axes labelled including units." },
        { level: 6, body: "Axes labelled with units, a sensible scale that fills the grid, points accurately plotted, and a smooth curve of best fit. The graph shows blood glucose rising to a peak at 60 minutes and declining back towards baseline — describing a characteristic post-meal glucose response curve." },
        { level: 8, body: "As Level 5–6, plus a 1/y transform (1/blood glucose vs time) to show the rate of glucose clearance. After the peak at 60 min, as insulin drives glucose clearance, 1/y increases linearly — a straight section on the 1/y graph indicates a constant fractional clearance rate, consistent with first-order kinetics of insulin-mediated glucose uptake." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Blood glucose concentration after a meal in a healthy individual",
        xLabel: "Time after meal (minutes)",
        yLabel: "Blood glucose (mmol/L)",
        editable: true,
        initialRows: [
          { x: 0, y: 4.5 },
          { x: 30, y: 6.8 },
          { x: 60, y: 8.2 },
          { x: 90, y: 7.1 },
          { x: 120, y: 5.8 },
          { x: 150, y: 4.9 },
          { x: 180, y: 4.6 },
          { x: 210, y: 4.5 },
        ],
        transforms: [
          { id: "raw", label: "Blood glucose vs time", x: "x", y: "y", xLabel: "Time (min)", yLabel: "Blood glucose (mmol/L)" },
          { id: "inv", label: "1/glucose vs time (rate of clearance)", x: "x", y: "1/y", xLabel: "Time (min)", yLabel: "1/blood glucose" },
        ],
        derive: { kind: "gradient", label: "Glucose rise rate (0-60 min)", unit: "mmol/L per min" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted blood glucose on the y-axis against time on the x-axis...",
          "The graph shows a... trend because...",
          "I applied the 1/y transform to show...",
          "The curve of best fit shows...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "data", "blood glucose", "time"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "mmol", "minutes", "time", "blood glucose"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve of best fit; peak at 60 min described; scale fills grid.", keywords: ["curve", "best fit", "peak", "60 min", "8.2", "smooth", "accurate", "scale", "rises", "falls"], minKeywords: 2 },
          { level: 8, descriptor: "1/y transform described and its scientific meaning explained.", keywords: ["1/y", "transform", "clearance", "rate", "linear", "first-order", "insulin", "straight", "kinetics", "increasing"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient of the rising phase and interpret the data quantitatively.",
      guided: [
        { level: 2, body: "Describes the overall trend: 'Blood glucose went up after the meal and then came back down.'" },
        { level: 4, body: "Identifies the peak (8.2 mmol/L at 60 min) and notes the return towards baseline (4.5 mmol/L at 210 min). Notes that the rise is faster than the fall." },
        { level: 6, body: "From the graph, draws a line of best fit through the rising phase (0–60 min) and calculates the gradient: rise = 8.2 − 4.5 = 3.7 mmol/L; run = 60 − 0 = 60 min; gradient ≈ 0.062 mmol/L per min. States the unit correctly as mmol/L per min." },
        { level: 8, body: "Full calculation shown for the rising phase gradient (0–60 min): gradient = (8.2 − 4.5) / (60 − 0) = 3.7 / 60 ≈ 0.062 mmol/L per min. Also calculates the gradient of the declining phase (60–210 min): gradient = (4.5 − 8.2) / (210 − 60) = −3.7 / 150 ≈ −0.025 mmol/L per min. Compares the two: the rising phase is 2.5× faster than the decline, reflecting rapid glucose absorption followed by slower insulin-mediated clearance. Notes that a diabetic patient would show a peak above 11 mmol/L and a much shallower decline due to absence or reduced effectiveness of insulin." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Blood glucose concentration after a meal in a healthy individual",
        xLabel: "Time after meal (minutes)",
        yLabel: "Blood glucose (mmol/L)",
        editable: true,
        initialRows: [
          { x: 0, y: 4.5 },
          { x: 30, y: 6.8 },
          { x: 60, y: 8.2 },
          { x: 90, y: 7.1 },
          { x: 120, y: 5.8 },
          { x: 150, y: 4.9 },
          { x: 180, y: 4.6 },
          { x: 210, y: 4.5 },
        ],
        transforms: [
          { id: "raw", label: "Blood glucose vs time", x: "x", y: "y", xLabel: "Time (min)", yLabel: "Blood glucose (mmol/L)" },
          { id: "inv", label: "1/glucose vs time (rate of clearance)", x: "x", y: "1/y", xLabel: "Time (min)", yLabel: "1/blood glucose" },
        ],
        derive: { kind: "gradient", label: "Glucose rise rate (0-60 min)", unit: "mmol/L per min" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the rising phase (0–60 min). How does this compare to the rate of decline? What does this tell you about glucose absorption versus clearance?",
        scaffolds: [
          "The peak blood glucose was ___ mmol/L at ___ minutes...",
          "Gradient of rising phase (0–60 min) = (y₂ − y₁) / (x₂ − x₁) = ... / ... = ... mmol/L per min",
          "Gradient of declining phase (60–210 min) = ... mmol/L per min",
          "The rising phase is ___ times faster than the declining phase because...",
          "In a diabetic patient, the graph would differ because...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes blood glucose rises then falls.", keywords: ["rises", "falls", "peak", "time", "blood glucose", "goes up", "comes down"], minKeywords: 1 },
          { level: 4, descriptor: "Peak value and time identified; rise faster than fall noted.", keywords: ["8.2", "60 min", "peak", "rise", "fall", "faster", "return", "baseline", "4.5"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient of rising phase calculated with working and correct unit.", keywords: ["gradient", "0.062", "3.7", "60", "mmol/l per min", "rise", "run", "calculation", "working"], minKeywords: 2 },
          { level: 8, descriptor: "Both gradients calculated and compared; diabetic contrast given.", keywords: ["0.062", "0.025", "rising", "declining", "2.5", "faster", "diabetic", "11 mmol", "insulin", "clearance", "absorption", "slower", "decline"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about the insulin response and link the data to the negative feedback mechanism.",
      guided: [
        { level: 2, body: "Level 1–2: 'Blood glucose rose after eating and then came back down.'" },
        { level: 4, body: "Level 3–4: 'Blood glucose peaked at 8.2 mmol/L at 60 minutes and returned to baseline (~4.5 mmol/L) by 210 minutes. This shows the body successfully regulated blood glucose after the meal.'" },
        { level: 6, body: "Level 5–6: 'Blood glucose rose from 4.5 mmol/L (fasting) to a peak of 8.2 mmol/L at 60 minutes — a rise of 3.7 mmol/L at a rate of 0.062 mmol/L per min. This triggered insulin release from the β-cells of the pancreas. Insulin stimulated glycogenesis in the liver and glucose uptake by cells, causing blood glucose to fall back to baseline (4.5 mmol/L) by 210 minutes. This is consistent with the normal negative feedback regulation of blood glucose.'" },
        { level: 8, body: "Level 7–8: Full conclusion with values: peak 8.2 mmol/L at 60 min (rise rate 0.062 mmol/L/min); decline rate −0.025 mmol/L/min (indicating insulin-mediated clearance slower than absorption). Return to 4.5 mmol/L by 210 min — well within the normal range (4–7 mmol/L). This is consistent with a healthy insulin response. Contrast with Type 1 diabetic: no insulin → peak >11 mmol/L, prolonged hyperglycaemia, no return to baseline. Contrast with Type 2 diabetic: insulin present but reduced sensitivity → intermediate peak, delayed return. The 1/y transform shows a near-linear increase after 60 min, suggesting approximately first-order kinetics for insulin-mediated clearance. All values are within the expected physiological range." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Blood glucose concentration after a meal in a healthy individual",
        xLabel: "Time after meal (minutes)",
        yLabel: "Blood glucose (mmol/L)",
        editable: true,
        initialRows: [
          { x: 0, y: 4.5 },
          { x: 30, y: 6.8 },
          { x: 60, y: 8.2 },
          { x: 90, y: 7.1 },
          { x: 120, y: 5.8 },
          { x: 150, y: 4.9 },
          { x: 180, y: 4.6 },
          { x: 210, y: 4.5 },
        ],
        transforms: [
          { id: "raw", label: "Blood glucose vs time", x: "x", y: "y", xLabel: "Time (min)", yLabel: "Blood glucose (mmol/L)" },
          { id: "inv", label: "1/glucose vs time (rate of clearance)", x: "x", y: "1/y", xLabel: "Time (min)", yLabel: "1/blood glucose" },
        ],
        derive: { kind: "gradient", label: "Glucose rise rate (0-60 min)", unit: "mmol/L per min" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. Does this data show a healthy blood glucose response? Use specific values, link to insulin and negative feedback, and contrast with what a diabetic patient's graph would look like.",
        scaffolds: [
          "Blood glucose rose from ___ mmol/L to a peak of ___ mmol/L at ___ minutes...",
          "This triggered the release of insulin from the ___ cells of the pancreas...",
          "Insulin stimulated... causing blood glucose to fall back to...",
          "This is consistent with / inconsistent with normal regulation because...",
          "In a Type 1 diabetic patient, the graph would show... because...",
        ],
        rubric: [
          { level: 2, descriptor: "States blood glucose rose then fell.", keywords: ["rose", "fell", "peak", "blood glucose", "returns", "baseline"], minKeywords: 1 },
          { level: 4, descriptor: "Peak value and return to baseline stated; regulation mentioned.", keywords: ["8.2", "60 min", "4.5", "210 min", "normal", "regulated", "healthy"], minKeywords: 1 },
          { level: 6, descriptor: "Insulin, glycogenesis, and negative feedback named; specific values used.", keywords: ["insulin", "beta cells", "glycogenesis", "negative feedback", "4.5 mmol", "8.2 mmol", "60 minutes", "210 minutes", "normal range", "4-7 mmol"], minKeywords: 3 },
          { level: 8, descriptor: "Rise and decline gradients compared; Type 1 and Type 2 contrast; 1/y kinetics discussed.", keywords: ["0.062", "0.025", "type 1", "type 2", "11 mmol", "hyperglycaemia", "insulin sensitivity", "first-order", "1/y", "physiological", "clearance", "consistent"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the blood glucose data collection and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could be improved.'" },
        { level: 4, body: "Level 3–4: 'Only one participant was tested, so we cannot generalise. Repeating with more participants would improve reliability.'" },
        { level: 6, body: "Level 5–6: 'Key limitations: (1) only one participant — results may not be representative of the population. (2) The fasting state was not confirmed — if the participant had eaten recently, the baseline would be elevated. (3) Glucometers have an accuracy of ±15% at high glucose concentrations, introducing measurement uncertainty. Improvements: test 10+ participants and report mean ± SD; confirm fasting with written record; use laboratory blood tests (hexokinase method, more accurate than glucometer).'" },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses: (1) Single participant — cannot assess population variability in insulin sensitivity. (2) Glucometer uncertainty (±15% at high concentrations) could mean a reading of 8.2 mmol/L could be as low as 7.0 or as high as 9.4 mmol/L — this uncertainty is large enough to affect the conclusion about peak glucose. (3) Food composition is variable (glycaemic response also depends on meal size, fat and protein content, and participant's gut microbiome). (4) Time intervals of 30 min may miss a very early peak (some high-GI foods peak at 45 min). (5) Only one meal tested — cannot compare high vs low GI from this data alone. Each weakness linked to a specific, reasoned improvement." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Blood glucose concentration after a meal in a healthy individual",
        xLabel: "Time after meal (minutes)",
        yLabel: "Blood glucose (mmol/L)",
        editable: true,
        initialRows: [
          { x: 0, y: 4.5 },
          { x: 30, y: 6.8 },
          { x: 60, y: 8.2 },
          { x: 90, y: 7.1 },
          { x: 120, y: 5.8 },
          { x: 150, y: 4.9 },
          { x: 180, y: 4.6 },
          { x: 210, y: 4.5 },
        ],
        transforms: [
          { id: "raw", label: "Blood glucose vs time", x: "x", y: "y", xLabel: "Time (min)", yLabel: "Blood glucose (mmol/L)" },
          { id: "inv", label: "1/glucose vs time (rate of clearance)", x: "x", y: "1/y", xLabel: "Time (min)", yLabel: "1/blood glucose" },
        ],
        derive: { kind: "gradient", label: "Glucose rise rate (0-60 min)", unit: "mmol/L per min" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect this blood glucose data. What are the main weaknesses and how would you specifically improve each one?",
        scaffolds: [
          "A key weakness is...",
          "This affects the result because...",
          "To improve this, I would...",
          "The glucometer has an uncertainty of ±15%, which means the reading of 8.2 mmol/L could actually be between...",
          "Reliability could be improved by...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem", "only one"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned with improvement.", keywords: ["one participant", "fasting", "repeat", "more participants", "generalise", "representative", "mean"], minKeywords: 1 },
          { level: 6, descriptor: "Three relevant limitations with matched improvements.", keywords: ["one participant", "fasting confirmed", "glucometer", "±15%", "laboratory", "hexokinase", "mean", "standard deviation", "10 participants", "written record"], minKeywords: 3 },
          { level: 8, descriptor: "Multiple specific weaknesses with quantified impact; meal composition variability; 30-min intervals limitation.", keywords: ["±15%", "7.0", "9.4", "meal composition", "fat", "protein", "microbiome", "30 min", "45 min", "peak", "compare", "gi", "weakness", "improvement", "specific"], minKeywords: 3 },
        ],
      },
    },
  ],
}
