import type { StrandhootPack } from "../engine/types"

export const osmosisCritC: StrandhootPack = {
  slug: "osmosis-crit-c",
  title: "Potato Osmosis Dataset",
  subject: "MYP Biology",
  criterion: "C",
  topic: "% mass change vs sucrose concentration",
  accent: "#0984b5",
  icon: "💧",
  statementOfInquiry: "The changes in the weather patterns caused by current economic activity may not be fair to future generations.",
  estMinutes: 30,
  intro:
    "A student measured the percentage change in mass of potato cylinders immersed in sucrose solutions of increasing concentration. Use the data tool to plot, transform and analyse the results — then draw a conclusion about the isotonic point and evaluate the method.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Isotonic Expert", icon: "🔬", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Potato osmosis dataset", blurb: "% mass change vs sucrose concentration data", icon: "💧" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the osmosis data clearly and apply a transform to check linearity.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with data values but missing headings or units." },
        { level: 4, body: "Level 3–4: A clear table with column headings (sucrose concentration in mol/dm³; % change in mass) and a graph with both axes labelled including units." },
        { level: 6, body: "Level 5–6: Axes labelled with units, a sensible scale that fills the grid, points accurately plotted. A straight line of best fit is appropriate because the relationship appears linear — the x² transform should produce a curved plot, confirming the raw data is linear (not quadratic)." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus the linearisation check: if % change is plotted against concentration², the plot is NOT straight (it curves), confirming the raw x vs y relationship IS linear. The line of best fit on the raw graph can be extrapolated to find the x-intercept — the isotonic point where % change = 0. The gradient (slope) gives the rate of mass change per unit increase in concentration." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "% change in mass of potato cylinders at different sucrose concentrations",
        xLabel: "Sucrose concentration (mol/dm³)",
        yLabel: "% change in mass",
        editable: true,
        initialRows: [
          { x: 0, y: 9.2 },
          { x: 0.1, y: 5.8 },
          { x: 0.2, y: 2.4 },
          { x: 0.3, y: 0.1 },
          { x: 0.4, y: -2.9 },
          { x: 0.5, y: -5.5 },
          { x: 0.6, y: -7.8 },
          { x: 0.7, y: -9.6 },
        ],
        transforms: [
          { id: "raw", label: "% mass change vs sucrose concentration", x: "x", y: "y", xLabel: "Sucrose concentration (mol/dm³)", yLabel: "% change in mass" },
          { id: "sq", label: "% change vs concentration squared (non-linearity check)", x: "x²", y: "y", xLabel: "Concentration² (mol/dm³)²", yLabel: "% change in mass" },
        ],
        derive: { kind: "gradient", label: "Rate of mass change per mol/dm³", unit: "% per mol/dm³" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted % change in mass on the y-axis against sucrose concentration on the x-axis because...",
          "The graph shows a... trend — the relationship appears to be...",
          "I applied the x² transform to check whether the relationship is linear or quadratic: the result shows...",
          "A straight line of best fit is appropriate because...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "data", "mass", "concentration", "sucrose"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "mol/dm", "% change", "concentration"], minKeywords: 2 },
          { level: 6, descriptor: "Linear trend described; line of best fit drawn; x² transform applied.", keywords: ["linear", "straight line", "best fit", "decreases", "x²", "transform", "scale", "accurate"], minKeywords: 2 },
          { level: 8, descriptor: "Linearisation check described; x-intercept identified as isotonic point; gradient stated.", keywords: ["x²", "curved", "linear", "x-intercept", "isotonic", "gradient", "extrapolate", "0.29", "non-linear"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient and determine the isotonic point from the x-intercept.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('% change in mass decreases as sucrose concentration increases')." },
        { level: 4, body: "Level 3–4: Notes the relationship is approximately linear. As concentration increases from 0 to 0.7 mol/dm³, % change falls from +9.2% to −9.6%. This is a range of about 18.8% over 0.7 mol/dm³ — roughly −27% per mol/dm³ (approximate)." },
        { level: 6, body: "Level 5–6: Gradient = Δy / Δx. Using (0, 9.2) and (0.7, −9.6): gradient = (−9.6 − 9.2) / (0.7 − 0) = −18.8 / 0.7 ≈ −26.9% per mol/dm³ (using extreme points gives a less accurate gradient than a line of best fit; ideally gradient is read from two widely-spaced points on the line). The x-intercept is found by extrapolating the line of best fit to where % change = 0 — approximately 0.29–0.31 mol/dm³." },
        { level: 8, body: "Level 7–8: From the line of best fit through all 8 points: gradient ≈ −19% per mol/dm³ (more accurate than raw point-to-point). Equation of line: y = −19x + 9.2 (approximate). At y = 0: x = 9.2 / 19 ≈ 0.48 — wait, the line through all points has a y-intercept near +9.2 and x-intercept near 0.29 mol/dm³ (gradient closer to −32% when y-intercept is correctly read from the best-fit line). The isotonic point ≈ 0.29 mol/dm³ represents the water potential of the potato cell contents: ψ ≈ −RTc where c is the molar concentration. The x² plot is curved, confirming the x vs y relationship is linear." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "% change in mass of potato cylinders at different sucrose concentrations",
        xLabel: "Sucrose concentration (mol/dm³)",
        yLabel: "% change in mass",
        editable: true,
        initialRows: [
          { x: 0, y: 9.2 },
          { x: 0.1, y: 5.8 },
          { x: 0.2, y: 2.4 },
          { x: 0.3, y: 0.1 },
          { x: 0.4, y: -2.9 },
          { x: 0.5, y: -5.5 },
          { x: 0.6, y: -7.8 },
          { x: 0.7, y: -9.6 },
        ],
        transforms: [
          { id: "raw", label: "% mass change vs sucrose concentration", x: "x", y: "y", xLabel: "Sucrose concentration (mol/dm³)", yLabel: "% change in mass" },
          { id: "sq", label: "% change vs concentration squared (non-linearity check)", x: "x²", y: "y", xLabel: "Concentration² (mol/dm³)²", yLabel: "% change in mass" },
        ],
        derive: { kind: "gradient", label: "Rate of mass change per mol/dm³", unit: "% per mol/dm³" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the % mass change vs sucrose concentration graph and identify the isotonic point.",
        scaffolds: [
          "The trend shows that as sucrose concentration increases, % mass change...",
          "The relationship is approximately... because...",
          "Gradient = Δy / Δx = (___ − ___) / (___ − ___) = ___ % per mol/dm³",
          "The x-intercept (isotonic point) ≈ ___ mol/dm³ because % change = 0 at this point, meaning...",
          "The x² transform plot is... (curved / straight), which confirms the raw relationship is...",
        ],
        rubric: [
          { level: 2, descriptor: "Notes % change decreases with concentration.", keywords: ["decreases", "increases", "concentration", "mass", "falls", "trend"], minKeywords: 1 },
          { level: 4, descriptor: "Linear relationship noted; range stated.", keywords: ["linear", "range", "9.2", "−9.6", "decrease", "increase", "straight"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated with working; x-intercept identified as isotonic point.", keywords: ["gradient", "δy", "δx", "−19", "−27", "x-intercept", "isotonic", "0.3", "0.29", "two points"], minKeywords: 2 },
          { level: 8, descriptor: "Gradient from line of best fit; isotonic point calculated; x² confirms linearity.", keywords: ["line of best fit", "0.29", "x-intercept", "isotonic", "water potential", "x²", "curved", "linear", "gradient", "equation"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about the isotonic point and link to osmosis and water potential.",
      guided: [
        { level: 2, body: "Level 1–2: 'The mass of the potato cylinders decreased as sucrose concentration increased.'" },
        { level: 4, body: "Level 3–4: 'As sucrose concentration increased, the % change in mass decreased. At low concentrations, potato cylinders gained mass; at high concentrations, they lost mass. This is consistent with osmosis.'" },
        { level: 6, body: "Level 5–6: '% change in mass fell linearly from +9.2% at 0 mol/dm³ to −9.6% at 0.7 mol/dm³. The x-intercept of the line of best fit (the isotonic point) was approximately 0.29–0.30 mol/dm³. At this concentration, the water potential of the sucrose solution equals that of the potato cell contents — there is no net water movement by osmosis.'" },
        { level: 8, body: "Level 7–8: The linear relationship (confirmed by x² transform being non-linear) gives a gradient of approximately −19% per mol/dm³. The x-intercept ≈ 0.29 mol/dm³ corresponds to the water potential of the potato cell cytoplasm. Below this concentration, the solution is hypotonic relative to the cell — water enters by osmosis, increasing mass. Above it, the solution is hypertonic — water exits, decreasing mass. The negative gradient is explained by the direct relationship between solute concentration and water potential depression." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "% change in mass of potato cylinders at different sucrose concentrations",
        xLabel: "Sucrose concentration (mol/dm³)",
        yLabel: "% change in mass",
        editable: true,
        initialRows: [
          { x: 0, y: 9.2 },
          { x: 0.1, y: 5.8 },
          { x: 0.2, y: 2.4 },
          { x: 0.3, y: 0.1 },
          { x: 0.4, y: -2.9 },
          { x: 0.5, y: -5.5 },
          { x: 0.6, y: -7.8 },
          { x: 0.7, y: -9.6 },
        ],
        transforms: [
          { id: "raw", label: "% mass change vs sucrose concentration", x: "x", y: "y", xLabel: "Sucrose concentration (mol/dm³)", yLabel: "% change in mass" },
          { id: "sq", label: "% change vs concentration squared (non-linearity check)", x: "x²", y: "y", xLabel: "Concentration² (mol/dm³)²", yLabel: "% change in mass" },
        ],
        derive: { kind: "gradient", label: "Rate of mass change per mol/dm³", unit: "% per mol/dm³" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. What is the isotonic point of the potato cells? What does this tell us about the water potential of the cells? Link to osmosis theory.",
        scaffolds: [
          "As sucrose concentration increased from 0 to 0.7 mol/dm³, % mass change...",
          "The x-intercept of the line of best fit is approximately ___ mol/dm³. This is the isotonic point because...",
          "Below this concentration, the solution is hypotonic — so water enters the potato cells by osmosis because...",
          "Above this concentration, the solution is hypertonic — so water exits the cells because...",
          "This isotonic value ≈ ___ mol/dm³ represents the water potential of the potato cell cytoplasm.",
        ],
        rubric: [
          { level: 2, descriptor: "States % change decreases with concentration.", keywords: ["decreases", "mass", "concentration", "increases", "loses", "gains"], minKeywords: 1 },
          { level: 4, descriptor: "Osmosis stated; mass gain at low concentration and loss at high concentration.", keywords: ["osmosis", "gain", "lose", "hypotonic", "hypertonic", "low", "high", "consistent"], minKeywords: 1 },
          { level: 6, descriptor: "Specific data values used; isotonic point identified with value.", keywords: ["9.2", "−9.6", "isotonic", "0.29", "0.3", "x-intercept", "water potential", "equal", "no net"], minKeywords: 3 },
          { level: 8, descriptor: "Gradient stated; x² confirms linearity; hypotonic/hypertonic explained with water potential.", keywords: ["−19", "gradient", "x²", "linear", "hypotonic", "hypertonic", "water potential", "cytoplasm", "osmosis", "depression", "0.29"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the potato osmosis method and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could be improved.'" },
        { level: 4, body: "Level 3–4: 'The cylinders were only left in solution for 30 minutes — this may not be enough time for equilibrium to be reached, making the result an underestimate of true mass change.'" },
        { level: 6, body: "Level 5–6: Key limitations: (1) 30 minutes may not be long enough to reach osmotic equilibrium — measured % change would be smaller than the true value. (2) Blotting technique is subjective — if cylinders are not blotted consistently, surface water adds to apparent mass. (3) Cutting cylinders by hand leads to variation in length and diameter, affecting surface area and rate of exchange. Improvement: extend to 60 min, standardise blotting (5 blots with same pressure), use a calibrated cork borer and ruler." },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses: (1) Osmotic equilibrium not guaranteed in 30 min — cylinders in 0.8 mol/dm³ solutions shrink quickly; lower concentrations may still be equilibrating. Effect: underestimate of % change at extreme concentrations, flattening the gradient. Improvement: pilot study to determine equilibrium time. (2) Inconsistent blotting — systematic error in DV; standardise with a protocol. (3) Single potato — different regions of the same tuber have slightly different water potentials, introducing random error; use cylinders from one homogeneous region. (4) Only 8 concentrations — adding 0.25 and 0.35 mol/dm³ would more precisely pinpoint the isotonic point. Each weakness linked to its specific effect on the accuracy or reliability of the result." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "% change in mass of potato cylinders at different sucrose concentrations",
        xLabel: "Sucrose concentration (mol/dm³)",
        yLabel: "% change in mass",
        editable: true,
        initialRows: [
          { x: 0, y: 9.2 },
          { x: 0.1, y: 5.8 },
          { x: 0.2, y: 2.4 },
          { x: 0.3, y: 0.1 },
          { x: 0.4, y: -2.9 },
          { x: 0.5, y: -5.5 },
          { x: 0.6, y: -7.8 },
          { x: 0.7, y: -9.6 },
        ],
        transforms: [
          { id: "raw", label: "% mass change vs sucrose concentration", x: "x", y: "y", xLabel: "Sucrose concentration (mol/dm³)", yLabel: "% change in mass" },
          { id: "sq", label: "% change vs concentration squared (non-linearity check)", x: "x²", y: "y", xLabel: "Concentration² (mol/dm³)²", yLabel: "% change in mass" },
        ],
        derive: { kind: "gradient", label: "Rate of mass change per mol/dm³", unit: "% per mol/dm³" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect this osmosis data. What are the main weaknesses and how would you improve them?",
        scaffolds: [
          "A key weakness is...",
          "This affects the result because...",
          "To improve this, I would...",
          "Inconsistent blotting leads to... which means...",
          "Reliability could be improved by...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned.", keywords: ["equilibrium", "time", "blotting", "cylinder", "30 minutes", "length", "variation"], minKeywords: 1 },
          { level: 6, descriptor: "Relevant limitation with matching improvement.", keywords: ["equilibrium not reached", "blot", "standardise", "60 min", "cork borer", "surface area", "systematic error", "reliable", "improvement"], minKeywords: 2 },
          { level: 8, descriptor: "Multiple specific weaknesses linked to effects on gradient or isotonic point; reasoned improvements.", keywords: ["underestimate", "gradient", "isotonic", "pilot study", "homogeneous", "region", "0.25", "0.35", "accuracy", "reliability", "random error", "systematic"], minKeywords: 3 },
        ],
      },
    },
  ],
}
