import type { StrandhootPack } from "../engine/types"

export const osmosisCritA: StrandhootPack = {
  slug: "osmosis-crit-a",
  title: "Movement in Living Organisms",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Diffusion, osmosis and transport",
  accent: "#1b7888",
  icon: "💧",
  statementOfInquiry: "The changes in the weather patterns caused by current economic activity may not be fair to future generations.",
  estMinutes: 25,
  intro:
    "Explore how substances move in and out of cells — from the passive drift of diffusion to the energy-driven pumps of active transport, and from the gas-exchange surfaces of alveoli to the double circulatory system of the heart. Each strand levels up from recall to analysis.",
  badges: [
    { id: "diffuser", label: "Diffusion Expert", icon: "🌊", description: "Reach Level 8 on Diffusion and osmosis", strandId: "diffusion", atLevel: 8 },
    { id: "pump", label: "Active Transporter", icon: "⚡", description: "Reach Level 8 on Active transport", strandId: "active-transport", atLevel: 8 },
    { id: "gas-ace", label: "Gas Exchange Ace", icon: "🫁", description: "Reach Level 8 on Gas exchange structures", strandId: "gas-exchange", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 5: Movement", blurb: "Diffusion, osmosis, active transport, gas exchange, and circulation", icon: "💧" }],
  strands: [
    {
      id: "diffusion",
      name: "Diffusion and osmosis",
      descriptor: "Distinguish diffusion and osmosis; explain water potential and plasmolysis.",
      guided: [
        { level: 2, body: "Diffusion is the passive movement of particles from a region of high concentration to a region of low concentration. It requires no energy (no ATP). Examples: oxygen diffuses from the air into blood in the lungs; carbon dioxide diffuses out of cells; glucose diffuses from the gut into the bloodstream." },
        { level: 4, body: "Osmosis is a special type of diffusion — only water molecules move, across a partially (semi-)permeable membrane, from a region of high water potential to a region of low water potential. A cell in a hypertonic solution (more solute outside) loses water and the vacuole shrinks (plasmolysis). A cell in a hypotonic solution (less solute outside) gains water and becomes turgid." },
        { level: 6, body: "Water potential (ψ) is the measure of the tendency of water to move. Pure water has a water potential of 0 kPa — the maximum possible. Adding solute lowers water potential to negative values (e.g. −500 kPa). Water always moves from the less negative (higher) water potential to the more negative (lower) water potential. So water moves by osmosis from dilute solutions to concentrated solutions, following the water potential gradient." },
        { level: 8, body: "The water potential of a solution is the sum of two components: osmotic potential (lowered by solute) and pressure potential (raised by cell wall pushing back). In a turgid plant cell, the negative osmotic potential is partly offset by the positive pressure potential (turgor). When cells are plasmolysed, the cell membrane pulls away from the cell wall (incipient plasmolysis is the point just before this occurs). At osmotic equilibrium, the water potential of the cell exactly matches the water potential of the surrounding solution — there is no net water movement." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "d-l2",
            level: 2,
            prompt: "Which statement correctly describes diffusion?",
            options: [
              { id: "a", text: "Movement of water only, across a semi-permeable membrane" },
              { id: "b", text: "Passive movement of particles from high to low concentration", correct: true },
              { id: "c", text: "Movement of particles against the concentration gradient using ATP" },
              { id: "d", text: "Movement of particles from low to high concentration" },
            ],
            explanation: "Diffusion is passive (no ATP required) and moves particles down their concentration gradient — from regions of high concentration to regions of low concentration.",
          },
          {
            type: "fill",
            id: "d-l4",
            level: 4,
            prompt: "When a plant cell is placed in a concentrated salt solution, water leaves the cell by osmosis and the vacuole shrinks. This is called ▁.",
            answers: ["plasmolysis", "plasmolised"],
            explanation: "Plasmolysis occurs when a cell loses water by osmosis in a hypertonic solution. The cell membrane pulls away from the cell wall as the vacuole shrinks.",
          },
          {
            type: "short",
            id: "d-l6",
            level: 6,
            prompt: "Explain what is meant by water potential. Why does osmosis always move water from a dilute solution to a concentrated solution?",
            keywords: ["water potential", "negative", "solute", "osmosis", "gradient", "dilute", "concentrated", "high", "low"],
            minKeywords: 2,
            sample: "Water potential measures the tendency of water to move. Pure water has a water potential of 0; adding solute lowers it to negative values. Osmosis moves water from a higher (less negative) water potential to a lower (more negative) water potential — meaning from a dilute solution into a concentrated solution, because the concentrated solution has the lower water potential.",
          },
          {
            type: "short",
            id: "d-l8",
            level: 8,
            prompt: "A plant cell is at incipient plasmolysis. Explain what this means, using the concepts of osmotic potential, pressure potential and water potential equilibrium.",
            keywords: ["incipient plasmolysis", "osmotic potential", "pressure potential", "water potential", "equilibrium", "cell wall", "membrane", "turgor", "zero"],
            minKeywords: 3,
            sample: "Incipient plasmolysis is the point just before the cell membrane starts to pull away from the cell wall. At this point, turgor pressure (pressure potential) has fallen to zero — the cell is flaccid. The water potential of the cell equals the water potential of the surrounding solution, so there is no net movement of water. The osmotic potential is still negative (solute is present inside), but with no pressure potential to add, the total water potential matches the external solution exactly.",
          },
        ],
      },
    },
    {
      id: "active-transport",
      name: "Active transport",
      descriptor: "Explain how active transport moves particles against concentration gradients using ATP and carrier proteins.",
      guided: [
        { level: 2, body: "Active transport moves particles from a region of low concentration to a region of high concentration — against the concentration gradient. Unlike diffusion, active transport requires energy in the form of ATP. It uses specific carrier proteins embedded in the cell membrane." },
        { level: 4, body: "Active transport is essential where cells need to absorb substances that are already more concentrated inside than outside. Root hair cells absorb potassium ions (K⁺) and nitrate ions (NO₃⁻) from the soil even when those ions are already more concentrated inside the cell. In the kidney, glucose is actively reabsorbed from the filtrate in the proximal convoluted tubule back into the blood." },
        { level: 6, body: "The sodium-potassium pump in neurones (nerve cells) is a classic example: it actively pumps 3 Na⁺ ions out of the cell and 2 K⁺ ions into the cell with each cycle, using one ATP molecule. This maintains the electrical gradient across the neurone membrane needed for nerve impulse transmission. The pump works against the concentration gradients of both ions simultaneously." },
        { level: 8, body: "Active transport and facilitated diffusion both use carrier proteins, but they differ fundamentally: facilitated diffusion moves particles down their concentration gradient (no ATP needed), while active transport moves particles against their gradient (ATP required). In the gut epithelium, glucose absorption from the intestinal lumen uses a secondary active transport mechanism: a sodium-glucose co-transporter exploits the Na⁺ gradient (maintained by the Na⁺/K⁺ ATPase) to drive glucose into the cell against its gradient — no ATP is directly used for glucose, but ATP powers the Na⁺/K⁺ pump that creates the gradient in the first place." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "at-l2",
            level: 2,
            prompt: "Which feature distinguishes active transport from diffusion?",
            options: [
              { id: "a", text: "Active transport requires ATP and moves particles against the concentration gradient", correct: true },
              { id: "b", text: "Active transport moves particles from high to low concentration" },
              { id: "c", text: "Active transport does not use carrier proteins" },
              { id: "d", text: "Active transport only moves water molecules" },
            ],
            explanation: "Active transport requires ATP (energy) and uses carrier proteins to move particles against their concentration gradient — from low to high concentration. Diffusion is passive and moves down the concentration gradient.",
          },
          {
            type: "fill",
            id: "at-l4",
            level: 4,
            prompt: "Root hair cells absorb potassium ions from the soil by ▁ transport, because the ions are already more concentrated inside the cell than in the soil.",
            answers: ["active"],
            explanation: "When the substance is already more concentrated inside the cell, moving more in requires active transport — energy from ATP is used to pump ions against their concentration gradient through carrier proteins.",
          },
          {
            type: "short",
            id: "at-l6",
            level: 6,
            prompt: "Describe how the sodium-potassium pump works and explain why neurones depend on it.",
            keywords: ["sodium", "potassium", "pump", "atp", "concentration gradient", "neurone", "nerve impulse", "carrier", "gradient"],
            minKeywords: 2,
            sample: "The sodium-potassium pump uses one ATP molecule per cycle to actively transport 3 Na⁺ ions out of the neurone and 2 K⁺ ions in. Both movements are against concentration gradients. This creates and maintains the electrical potential difference across the membrane that is essential for generating and transmitting nerve impulses.",
          },
          {
            type: "short",
            id: "at-l8",
            level: 8,
            prompt: "Explain how glucose is absorbed from the gut lumen into intestinal epithelial cells. Why is this described as secondary active transport?",
            keywords: ["sodium-glucose", "co-transporter", "sodium", "gradient", "atp", "na+/k+ pump", "secondary", "active transport", "epithelium", "facilitated diffusion"],
            minKeywords: 3,
            sample: "Glucose absorption in the gut is secondary active transport. The Na⁺/K⁺ ATPase pump uses ATP to maintain a low Na⁺ concentration inside the epithelial cell. A sodium-glucose co-transporter then uses the energy stored in this Na⁺ gradient to drive glucose into the cell against its own concentration gradient — no ATP is used directly for glucose. This is secondary because the energy comes indirectly via the Na⁺ gradient rather than directly from ATP hydrolysis.",
          },
        ],
      },
    },
    {
      id: "gas-exchange",
      name: "Gas exchange structures",
      descriptor: "Compare gas exchange adaptations in alveoli, fish gills and insect tracheal systems.",
      guided: [
        { level: 2, body: "In the lungs, gas exchange takes place in millions of tiny air sacs called alveoli. Their structure is adapted for efficient exchange: enormous total surface area, thin walls (just one cell thick), a moist surface, and a dense network of blood capillaries surrounding each alveolus. Breathing (ventilation) maintains the concentration gradient." },
        { level: 4, body: "Fish exchange gases across gills. Each gill is made of gill lamellae, and each lamella has many secondary lamellae to increase surface area. Fish use counter-current blood flow: blood and water flow in opposite directions across the secondary lamellae. This keeps a diffusion gradient across the entire length of the gill, allowing fish to extract up to 80% of the dissolved oxygen from water — far more than if they used a parallel-flow system." },
        { level: 6, body: "Insects do not use lungs or gills. Instead, they have a tracheal system: a network of air tubes (tracheae) that branch into tiny tracheoles, delivering oxygen directly to cells. Air enters and leaves through small openings called spiracles in the exoskeleton. Spiracles can open and close to reduce water loss. The tracheal system bypasses the circulatory system entirely for gas transport — oxygen diffuses directly from tracheoles to respiring cells." },
        { level: 8, body: "All gas exchange surfaces share four key adaptations: (1) large surface area:volume ratio, (2) thin diffusion distance, (3) maintenance of a steep concentration gradient (by ventilation or circulation), (4) moist surface. The counter-current system in fish gills is the most efficient: mathematical modelling shows that counter-current exchange maintains a concentration gradient over the entire length, whereas co-current (parallel) flow reaches equilibrium halfway along the lamella and exchange stops. In insects, the tracheal system is efficient only for small body sizes — larger insects would need an impossibly dense tracheal network, which is why insects remain small." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "ge-l2",
            level: 2,
            prompt: "Which adaptation of alveoli increases the efficiency of gas exchange?",
            options: [
              { id: "a", text: "Thick walls to protect against damage" },
              { id: "b", text: "Large surface area and thin walls one cell thick", correct: true },
              { id: "c", text: "Dry surface to prevent water loss" },
              { id: "d", text: "No blood capillaries to keep gas exchange area clear" },
            ],
            explanation: "Alveoli have an enormous total surface area, walls just one cell thick (minimising diffusion distance), a moist surface, and surrounding capillaries. These adaptations together maximise the rate of gas exchange.",
          },
          {
            type: "fill",
            id: "ge-l4",
            level: 4,
            prompt: "In fish gills, blood and water flow in opposite directions across the secondary lamellae. This arrangement is called ▁ flow.",
            answers: ["counter-current", "countercurrent"],
            explanation: "Counter-current flow ensures the blood always encounters water with a higher oxygen concentration than itself, maintaining a diffusion gradient across the entire gill and maximising oxygen uptake.",
          },
          {
            type: "short",
            id: "ge-l6",
            level: 6,
            prompt: "Describe how the insect tracheal system delivers oxygen to cells without using the circulatory system.",
            keywords: ["trachea", "tracheoles", "spiracles", "diffusion", "cells", "oxygen", "network", "exoskeleton", "circulatory"],
            minKeywords: 2,
            sample: "Insects breathe through spiracles — pores in the exoskeleton that can open and close. Air enters the spiracles and travels along branching tracheae, then into finer tracheoles that reach individual cells. Oxygen diffuses directly from the tracheoles into respiring cells. The insect circulatory system plays no role in oxygen transport — the tracheal system delivers gas directly.",
          },
          {
            type: "short",
            id: "ge-l8",
            level: 8,
            prompt: "Explain why counter-current flow in fish gills is more efficient than co-current (parallel) flow. Use the concept of concentration gradient to support your answer.",
            keywords: ["counter-current", "co-current", "parallel", "concentration gradient", "equilibrium", "maintained", "entire length", "oxygen", "efficient", "blood", "water"],
            minKeywords: 3,
            sample: "In counter-current flow, blood and water move in opposite directions. This means blood always encounters water that has a higher oxygen concentration than itself, maintaining a concentration gradient across the entire length of the gill lamella. In co-current (parallel) flow, blood and water move in the same direction and rapidly reach equilibrium — the concentration gradient drops to zero halfway along, and exchange stops. Counter-current flow therefore extracts far more oxygen from the water passing over the gills.",
          },
        ],
      },
    },
    {
      id: "circulation",
      name: "Circulation and heart",
      descriptor: "Describe the double circulatory system and the structure of the heart, arteries, veins and capillaries.",
      guided: [
        { level: 2, body: "Humans have a double circulatory system: blood travels through the heart twice for each complete circuit. The pulmonary circuit carries blood from the heart to the lungs and back; the systemic circuit carries oxygenated blood from the heart to the body and returns deoxygenated blood. The heart has four chambers: left atrium, right atrium, left ventricle, right ventricle." },
        { level: 4, body: "Arteries carry blood away from the heart — they have thick, elastic walls to withstand high pressure. Veins carry blood toward the heart — they have thinner walls and valves to prevent backflow. Capillaries are just one cell thick, forming dense networks in tissues where substances (oxygen, glucose, CO₂, waste) exchange between the blood and cells. Valves in the heart prevent backflow between chambers." },
        { level: 6, body: "The left side of the heart pumps oxygenated blood around the entire body (systemic circuit) at high pressure — the left ventricle has the thickest, most muscular wall. The right side pumps deoxygenated blood only to the lungs (pulmonary circuit, shorter distance) — so the right ventricle wall is thinner. Atrioventricular valves (mitral and tricuspid) prevent backflow from ventricles to atria; semilunar valves (aortic and pulmonary) prevent backflow from arteries into ventricles." },
        { level: 8, body: "The advantage of the double circulation is that it allows the pressure to be boosted before blood enters the systemic circuit — giving enough force to reach the extremities. In fish, which have single circulation, blood loses much of its pressure when it passes through the gill capillaries, so it flows sluggishly to the body. In the systemic circuit, the arterioles (small arteries with muscular walls) can regulate blood flow to different organs by vasoconstriction or vasodilation. At the capillary level, exchange is maximised: the capillary wall is just one endothelial cell thick (≈1 μm diffusion distance); the capillary network provides an enormous surface area; and slow blood flow maximises contact time." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "c-l2",
            level: 2,
            prompt: "What is the correct path of blood in the pulmonary circuit?",
            options: [
              { id: "a", text: "Heart → body → heart" },
              { id: "b", text: "Lungs → body → heart" },
              { id: "c", text: "Heart → lungs → heart", correct: true },
              { id: "d", text: "Heart → liver → heart" },
            ],
            explanation: "The pulmonary circuit carries deoxygenated blood from the right side of the heart to the lungs, where it is oxygenated, and then back to the left side of the heart.",
          },
          {
            type: "fill",
            id: "c-l4",
            level: 4,
            prompt: "Arteries carry blood ▁ from the heart and have thick, elastic walls to withstand high pressure.",
            answers: ["away", "away from"],
            explanation: "Arteries carry blood AWAY from the heart (remember: Arteries = Away). Their thick, muscular, elastic walls allow them to withstand and absorb the high pressure pulse created by the heart's contractions.",
          },
          {
            type: "short",
            id: "c-l6",
            level: 6,
            prompt: "Explain why the left ventricle of the heart has a much thicker, more muscular wall than the right ventricle.",
            keywords: ["left ventricle", "systemic", "body", "pressure", "right ventricle", "pulmonary", "lungs", "oxygenated", "distance", "thick"],
            minKeywords: 2,
            sample: "The left ventricle pumps oxygenated blood into the systemic circuit — around the entire body, including the legs, arms and brain. This is a long circuit requiring very high pressure. The right ventricle only pumps blood to the lungs (pulmonary circuit), which is a much shorter distance and requires lower pressure. Therefore the left ventricle has a thicker, more muscular wall to generate the greater force needed.",
          },
          {
            type: "short",
            id: "c-l8",
            level: 8,
            prompt: "Explain the advantage of a double circulatory system over the single circulation found in fish. In your answer, refer to blood pressure and the efficiency of oxygen delivery to body tissues.",
            keywords: ["double", "single", "pressure", "fish", "gills", "boost", "systemic", "oxygenated", "capillaries", "slow", "efficient", "extremities"],
            minKeywords: 3,
            sample: "In a double circulatory system, blood returns to the heart after passing through the lungs and is pumped again at high pressure into the systemic circuit. This ensures oxygenated blood reaches the extremities at sufficient pressure. In fish (single circulation), blood loses most of its pressure as it passes through the gill capillaries. It then flows slowly and at low pressure to the body tissues, limiting oxygen delivery. The double circuit allows mammals and birds to sustain high metabolic rates by delivering oxygenated blood at high pressure efficiently throughout the body.",
          },
        ],
      },
    },
  ],
}
