import type { StrandhootPack } from "../engine/types"

export const pathogensCritA: StrandhootPack = {
  slug: "pathogens-crit-a",
  title: "Biological Interactions",
  subject: "MYP Biology",
  criterion: "A",
  topic: "Pathogens, immunity and ecology",
  accent: "#1b7888",
  icon: "🦠",
  statementOfInquiry: "When two or more individuals interact, they form relationships that, over time, impact and contribute to their identity.",
  estMinutes: 25,
  intro:
    "From the reflex arc to rainforest food webs, biological interactions shape the living world. Each strand targets a core concept from Chapter 6: Interaction — levelling up from recall to deep analysis of nervous systems, pathogens, immunity and ecology.",
  badges: [
    { id: "neuro", label: "Neuro Navigator", icon: "🧠", description: "Reach Level 8 on Nervous system", strandId: "nervous", atLevel: 8 },
    { id: "pathogen", label: "Pathogen Profiler", icon: "🦠", description: "Reach Level 8 on Pathogens", strandId: "pathogens", atLevel: 8 },
    { id: "immune", label: "Immune Expert", icon: "🛡️", description: "Reach Level 8 on Immune response", strandId: "immunity", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 6: Interaction", blurb: "Nerves, pathogens, immunity and ecological relationships", icon: "🦠" }],
  strands: [
    {
      id: "nervous",
      name: "Nervous system",
      descriptor: "Describe the structure and function of neurons and the reflex arc.",
      guided: [
        { level: 2, body: "The nervous system has three types of neuron: sensory neurons carry signals from receptors to the CNS; relay neurons pass signals within the CNS; motor neurons carry signals from the CNS to effectors (muscles or glands). A reflex is a rapid, automatic response to a stimulus." },
        { level: 4, body: "The reflex arc pathway: stimulus → receptor → sensory neuron → relay neuron (in CNS) → motor neuron → effector → response. Because the signal bypasses the brain (uses the spinal cord only), the response is faster than a voluntary action. Example: touching a hot surface → hand withdrawal before pain is consciously felt." },
        { level: 6, body: "At a synapse, the electrical signal cannot jump the gap directly. Instead: the action potential reaches the presynaptic membrane → neurotransmitter is released from vesicles → it diffuses across the synaptic gap → binds to complementary receptor proteins on the postsynaptic membrane → triggers a new electrical signal in the next neuron. The synaptic delay is about 0.5 ms. Voluntary actions differ from reflexes: they involve conscious decision-making in the cerebral cortex." },
        { level: 8, body: "Synaptic transmission is directional (vesicles are only in the presynaptic knob, receptors only on the postsynaptic membrane), amplifiable (multiple synaptic inputs summate on one neuron), and modulatable (drugs such as SSRIs block neurotransmitter reuptake; beta-blockers compete with adrenaline at receptors). In a reflex arc, the signal travels at up to 120 m/s in myelinated fibres; the myelin sheath (Schwann cells) increases conduction speed by saltatory conduction (signal jumps between nodes of Ranvier). Damage to relay neurons in the spinal cord can abolish reflexes below the injury level while voluntary pathways through the brain remain intact — explaining the different functional losses seen in spinal cord injuries." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "ns-l2",
            level: 2,
            prompt: "Which type of neuron carries nerve impulses from a receptor to the central nervous system (CNS)?",
            options: [
              { id: "a", text: "Motor neuron" },
              { id: "b", text: "Relay neuron" },
              { id: "c", text: "Sensory neuron", correct: true },
              { id: "d", text: "Effector neuron" },
            ],
            explanation: "Sensory neurons carry signals from receptors (e.g. in the skin) to the CNS. Motor neurons carry signals from the CNS to effectors; relay neurons connect neurons within the CNS.",
          },
          {
            type: "fill",
            id: "ns-l4",
            level: 4,
            prompt: "In the reflex arc, the order of structures is: stimulus → receptor → sensory neuron → relay neuron → motor neuron → ▁ → response.",
            answers: ["effector", "muscle", "effector (muscle or gland)"],
            explanation: "The effector (a muscle or gland) produces the response — for example, a muscle contracts to withdraw a hand from heat. The effector is the final link before the visible response.",
          },
          {
            type: "short",
            id: "ns-l6",
            level: 6,
            prompt: "Explain how a nerve signal is transmitted across a synapse. Name the key structures involved.",
            keywords: ["neurotransmitter", "vesicles", "diffuses", "receptor", "postsynaptic", "presynaptic", "gap", "membrane", "signal"],
            minKeywords: 2,
            sample: "When an action potential reaches the presynaptic membrane, neurotransmitter molecules are released from vesicles. They diffuse across the synaptic gap and bind to complementary receptor proteins on the postsynaptic membrane, triggering a new electrical signal in the next neuron. Transmission is one-directional because vesicles and receptors are on opposite sides.",
          },
          {
            type: "short",
            id: "ns-l8",
            level: 8,
            prompt: "Explain why reflex arcs are faster than voluntary responses, and describe how drugs can interfere with synaptic transmission. Use specific examples.",
            keywords: ["spinal cord", "brain", "delay", "myelinated", "saltatory", "synapse", "neurotransmitter", "drug", "ssri", "reuptake", "receptor", "voluntary"],
            minKeywords: 3,
            sample: "Reflex arcs bypass the brain, using only the spinal cord, which reduces the number of synapses and the total path length — cutting response time significantly. Myelinated fibres transmit impulses at up to 120 m/s via saltatory conduction between nodes of Ranvier. At synapses, drugs can interfere: SSRIs block reuptake of serotonin, prolonging its effect; beta-blockers competitively bind adrenaline receptors. Voluntary actions require conscious processing in the cerebral cortex, adding synaptic delays through multiple brain regions.",
          },
        ],
      },
    },
    {
      id: "pathogens",
      name: "Pathogens",
      descriptor: "Compare bacteria, viruses, fungi and parasites as pathogens.",
      guided: [
        { level: 2, body: "Pathogens are disease-causing microorganisms. There are four main types: bacteria (e.g. tuberculosis, cholera), viruses (e.g. influenza, COVID-19), fungi (e.g. athlete's foot), and parasites (e.g. malaria)." },
        { level: 4, body: "Bacteria are living cells that reproduce rapidly in the host and produce toxins that damage tissues. They can be killed by antibiotics. Viruses are not cells — they consist of nucleic acid (DNA or RNA) surrounded by a protein coat. They inject their genetic material into host cells and use the host's machinery to replicate. Antibiotics do not work on viruses because viruses have no cell wall or metabolism to target." },
        { level: 6, body: "Fungi are heterotrophic organisms that reproduce by spores; examples include athlete's foot (Tinea pedis) and thrush (Candida albicans). Parasites live on or inside a host and cause harm: Plasmodium (malaria) is transmitted by the Anopheles mosquito and invades red blood cells; the tapeworm (Taenia) lives in the intestine and absorbs digested nutrients. Each pathogen type differs in structure, reproduction mode, and treatment — antibiotics target bacterial cell walls and metabolism but cannot affect viruses or eukaryotic parasites." },
        { level: 8, body: "Bacterial virulence depends on toxin production (exotoxins secreted by living cells, e.g. cholera toxin; endotoxins from gram-negative cell walls, e.g. salmonella LPS) and host invasion mechanisms. Viruses evolve rapidly through mutation and reassortment (e.g. influenza antigenic shift), enabling immune evasion. HIV targets CD4+ T-helper lymphocytes, destroying the adaptive immune response itself. Plasmodium has a complex life cycle (liver → red blood cells → mosquito → new host), with different stage-specific antigens making vaccine development difficult. Drug resistance is a cross-cutting challenge: MRSA (bacteria), antifungal-resistant Candida auris, and drug-resistant Plasmodium all illustrate how selective pressure drives pathogen evolution." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "p-l2",
            level: 2,
            prompt: "Which type of pathogen is NOT a living cell?",
            options: [
              { id: "a", text: "Bacterium" },
              { id: "b", text: "Virus", correct: true },
              { id: "c", text: "Fungus" },
              { id: "d", text: "Parasite" },
            ],
            explanation: "Viruses are not cells. They consist of nucleic acid (DNA or RNA) enclosed in a protein coat, and can only replicate inside a living host cell.",
          },
          {
            type: "fill",
            id: "p-l4",
            level: 4,
            prompt: "Antibiotics are effective against bacteria but NOT against viruses because viruses have no ▁ or metabolism to target.",
            answers: ["cell wall", "cell walls"],
            explanation: "Antibiotics work by disrupting bacterial structures such as cell walls (e.g. penicillin) or ribosomes. Viruses lack these structures — they are not cells — so antibiotics have no target to attack.",
          },
          {
            type: "short",
            id: "p-l6",
            level: 6,
            prompt: "Compare bacteria and viruses as pathogens. Include their structure, how they cause disease, and which treatments work against each.",
            keywords: ["cell", "nucleic acid", "protein coat", "toxins", "replicate", "host", "antibiotic", "antiviral", "bacteria", "virus"],
            minKeywords: 2,
            sample: "Bacteria are living cells that reproduce rapidly, produce toxins, and can be treated with antibiotics that target their cell walls and metabolism. Viruses are not cells — they consist only of nucleic acid and a protein coat. They inject their genetic material into host cells and use the host's machinery to replicate. Antibiotics cannot treat viral infections; antivirals (e.g. oseltamivir for flu) or vaccines are used instead.",
          },
          {
            type: "short",
            id: "p-l8",
            level: 8,
            prompt: "Explain how HIV and Plasmodium each evade or defeat the immune system. What makes these pathogens particularly difficult to treat or vaccinate against?",
            keywords: ["hiv", "cd4", "t-helper", "plasmodium", "life cycle", "antigen", "mutation", "immune", "vaccine", "drug resistance", "liver", "red blood cells"],
            minKeywords: 3,
            sample: "HIV targets CD4+ T-helper lymphocytes — the cells that coordinate the adaptive immune response — progressively destroying immunity itself. Vaccination is extremely difficult because HIV mutates rapidly and is integrated into the host genome. Plasmodium has a complex multi-stage life cycle (liver, red blood cells, mosquito), with different antigens expressed at each stage, so the immune system must respond to a moving target. Drug-resistant strains of both pathogens evolve under treatment pressure, making long-term management a major challenge.",
          },
        ],
      },
    },
    {
      id: "immunity",
      name: "Immune response",
      descriptor: "Distinguish innate and adaptive immunity and explain the role of lymphocytes and antibodies.",
      guided: [
        { level: 2, body: "The immune system has two main lines of defence. Innate immunity (non-specific) responds immediately to any pathogen: skin acts as a barrier, mucus traps pathogens, and phagocytes engulf and destroy them. Adaptive immunity (specific) responds to a particular antigen and creates memory." },
        { level: 4, body: "Innate defences: skin barrier (intact skin prevents entry), mucus and cilia in the respiratory tract, phagocytosis by neutrophils and macrophages, and inflammation (increased blood flow brings more immune cells). Adaptive response: B-lymphocytes produce antibodies that are complementary in shape to a specific antigen; T-helper lymphocytes activate B-cells; after infection, memory B and T cells remain, enabling a faster and stronger secondary response." },
        { level: 6, body: "Antibody-antigen binding is based on complementary shapes — an antibody's variable region matches only one antigen (like a lock and key). Antibodies can: neutralise pathogens (block attachment), opsonise (coat pathogens to make phagocytosis easier), and activate complement proteins. Vaccines exploit immunological memory: they introduce antigens (as weakened/killed pathogens, proteins, or mRNA instructions) to generate memory cells without causing disease. The secondary immune response produces 10–100× more antibodies, more rapidly." },
        { level: 8, body: "Clonal selection theory: when an antigen enters the body, the lymphocyte with the matching receptor is selected and proliferates — clonal expansion — producing plasma cells (antibody factories) and memory cells. T-helper cells (CD4+) coordinate the response by releasing cytokines that activate both B-cells (humoral immunity) and cytotoxic T-cells (cell-mediated immunity). Cytotoxic T-cells kill host cells displaying foreign antigens (e.g. virus-infected cells). MHC class I proteins on all nucleated cells present viral peptides for T-cell surveillance. Monoclonal antibodies (e.g. trastuzumab for breast cancer, adalimumab for autoimmune disease) are engineered versions of this specificity used as targeted therapies." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "im-l2",
            level: 2,
            prompt: "Which of the following is an example of innate (non-specific) immunity?",
            options: [
              { id: "a", text: "B-lymphocytes producing antibodies" },
              { id: "b", text: "Memory cells enabling faster secondary response" },
              { id: "c", text: "Phagocytes engulfing pathogens", correct: true },
              { id: "d", text: "Vaccines generating immune memory" },
            ],
            explanation: "Phagocytosis by neutrophils and macrophages is a non-specific innate defence — it attacks any foreign material immediately, without needing to recognise a specific antigen.",
          },
          {
            type: "fill",
            id: "im-l4",
            level: 4,
            prompt: "Antibodies are produced by ▁ and bind to antigens on the surface of pathogens in a complementary, lock-and-key manner.",
            answers: ["b-lymphocytes", "b lymphocytes", "b cells", "b-cells"],
            explanation: "B-lymphocytes (B-cells) differentiate into plasma cells that secrete antibodies specific to a particular antigen. Each antibody's variable region is complementary in shape to one antigen.",
          },
          {
            type: "short",
            id: "im-l6",
            level: 6,
            prompt: "Explain why a person recovers from a second exposure to the same pathogen much more rapidly. Use the terms antigen, memory cells and antibodies.",
            keywords: ["memory", "antigen", "antibodies", "secondary", "faster", "lymphocytes", "response", "b-cells", "plasma"],
            minKeywords: 2,
            sample: "After the first infection, memory B and T lymphocytes remain in the body. When the same pathogen enters again, its antigens are recognised by these memory cells. They rapidly proliferate and differentiate into plasma cells, producing large quantities of antibodies far more quickly than the primary response. The pathogen is neutralised before symptoms develop, which is why the person recovers faster — or does not become ill at all.",
          },
          {
            type: "short",
            id: "im-l8",
            level: 8,
            prompt: "Describe the roles of T-helper cells and cytotoxic T-cells in the adaptive immune response. How do vaccines exploit clonal selection to provide long-term protection?",
            keywords: ["t-helper", "cytokines", "b-cells", "cytotoxic", "mhc", "clonal selection", "plasma cells", "memory", "vaccine", "antigen", "proliferate", "cd4"],
            minKeywords: 3,
            sample: "T-helper cells (CD4+) release cytokines that activate B-cells to produce antibodies (humoral immunity) and stimulate cytotoxic T-cells to kill infected host cells displaying viral peptides on MHC class I proteins (cell-mediated immunity). Clonal selection theory explains how vaccines work: the vaccine introduces an antigen (from killed/weakened pathogen or mRNA), which selects and activates the matching lymphocyte, triggering clonal expansion into plasma cells and long-lived memory cells. On real infection, memory cells respond with rapid clonal expansion and massive antibody production, neutralising the pathogen before disease develops.",
          },
        ],
      },
    },
    {
      id: "ecology",
      name: "Ecological interactions",
      descriptor: "Classify ecological relationships and explain population dynamics.",
      guided: [
        { level: 2, body: "Organisms interact in many ways. Competition occurs when organisms fight for the same resource. Predators eat prey. In mutualism both organisms benefit (e.g. clownfish and sea anemone). In parasitism one organism benefits at the other's expense (e.g. tapeworm in the human intestine)." },
        { level: 4, body: "Competition types: intraspecific (same species competing for territory, mates, or food) and interspecific (different species competing for the same food or space). Predator-prey relationships create oscillating population cycles: when prey is plentiful, predator numbers rise; as predators eat more prey, prey numbers fall; predators then decline, allowing prey to recover. Classic example: snowshoe hare and Canadian lynx, with roughly 10-year oscillation cycles." },
        { level: 6, body: "Mutualism: clownfish live among sea anemone tentacles (protection) and in return deter butterfly fish that eat anemones; nitrogen-fixing bacteria (Rhizobium) live in root nodules of legumes — bacteria gain sugar, plant gains ammonium ions. Commensalism: barnacles on a whale's skin are carried to new feeding grounds (barnacle benefits, whale is unaffected). Parasitism: Plasmodium falciparum destroys red blood cells; the tapeworm (Taenia) absorbs nutrients from the host intestine. Distinguishing these categories depends on identifying whether each partner benefits (+), is harmed (−), or unaffected (0): mutualism (+/+), predation (+/−), parasitism (+/−), commensalism (+/0)." },
        { level: 8, body: "Population dynamics are governed by density-dependent factors (competition intensifies as density rises; predation becomes proportionally greater; disease spreads more easily in crowded populations) and density-independent factors (extreme temperature, flood, drought). The lynx-hare cycle shows a lagged response: hare numbers peak, then lynx numbers peak roughly 1–2 years later, then both crash. Mathematical models (Lotka-Volterra equations) predict these oscillations but real cycles are influenced by third factors (vegetation availability, other predators). Trophic cascades demonstrate indirect interactions: wolf reintroduction to Yellowstone reduced deer overgrazing, rivers stabilised and biodiversity increased — a cascade effect through the food web." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "ec-l2",
            level: 2,
            prompt: "What type of ecological interaction do clownfish and sea anemones share?",
            options: [
              { id: "a", text: "Parasitism" },
              { id: "b", text: "Commensalism" },
              { id: "c", text: "Competition" },
              { id: "d", text: "Mutualism", correct: true },
            ],
            explanation: "Clownfish gain protection from the anemone's stinging tentacles; the anemone benefits from the clownfish deterring butterfly fish. Both organisms benefit — this is mutualism (+/+).",
          },
          {
            type: "fill",
            id: "ec-l4",
            level: 4,
            prompt: "When members of the SAME species compete for the same resources (e.g. territory or mates), this is called ▁ competition.",
            answers: ["intraspecific"],
            explanation: "Intraspecific means 'within the same species'. Interspecific competition is between different species. Intraspecific competition can limit population growth by reducing survival and reproductive success.",
          },
          {
            type: "short",
            id: "ec-l6",
            level: 6,
            prompt: "Explain why predator and prey populations oscillate. Use the lynx and hare as an example.",
            keywords: ["prey", "predator", "hare", "lynx", "oscillation", "population", "increase", "decrease", "cycle", "food", "lag"],
            minKeywords: 2,
            sample: "When hare numbers are high, lynx have abundant food and their population increases. As more lynx eat more hares, hare numbers decline. With fewer hares, lynx face food shortage and their numbers fall too. This allows hare populations to recover, and the cycle repeats — roughly every 10 years. The lynx population lags behind the hare by 1–2 years because it takes time for predator numbers to respond to changes in prey abundance.",
          },
          {
            type: "short",
            id: "ec-l8",
            level: 8,
            prompt: "Explain what a trophic cascade is, using the wolf reintroduction to Yellowstone as an example. What does this reveal about how species interact within ecosystems?",
            keywords: ["trophic cascade", "wolf", "yellowstone", "deer", "overgrazing", "river", "vegetation", "indirect", "biodiversity", "ecosystem", "food web", "density-dependent"],
            minKeywords: 3,
            sample: "A trophic cascade is an indirect effect that ripples through a food web when a top predator is added or removed. In Yellowstone, reintroducing wolves reduced deer numbers and changed their grazing behaviour (deer avoided open areas near rivers). This reduced overgrazing of riparian vegetation; rivers stabilised and biodiversity increased across the ecosystem. The cascade illustrates that species interact not just directly (predation) but indirectly through behaviour modification and habitat change — removal of one predator can cause ecosystem-wide collapse across multiple trophic levels.",
          },
        ],
      },
    },
  ],
}
