import type { StrandhootPack } from "../engine/types"

// Crit C data: zone of inhibition diameter vs disinfectant concentration.
// The x values are powers of 2 (1,2,4,8,16,32,64,128 μg/ml) to produce a clean
// log-linear relationship. Plotting zone (mm) vs √concentration linearises the
// diminishing-returns curve, allowing gradient extraction.
export const pathogensCritC: StrandhootPack = {
  slug: "pathogens-crit-c",
  title: "Disinfectant Effectiveness Dataset",
  subject: "MYP Biology",
  criterion: "C",
  topic: "Zone of inhibition vs concentration",
  accent: "#0984b5",
  icon: "🦠",
  statementOfInquiry: "When two or more individuals interact, they form relationships that, over time, impact and contribute to their identity.",
  estMinutes: 30,
  intro:
    "A student measured the diameter of the zone of inhibition at eight disinfectant concentrations. Use the data tool to plot, transform and analyse — then draw a conclusion about the minimum inhibitory concentration and evaluate the reliability of the method. Each written strand levels up with the depth of your scientific reasoning.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Zone Analyst", icon: "🔬", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "evaluator", label: "Method Critic", icon: "⚖️", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Inhibition zone dataset", blurb: "Zone of inhibition diameter vs disinfectant concentration", icon: "🦠" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the zone of inhibition data clearly and apply a linearising √x transform.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with some data values but missing headings or units." },
        { level: 4, body: "Level 3–4: A clear table with column headings (Concentration in μg/ml; Zone diameter in mm) and a graph with both axes labelled including units." },
        { level: 6, body: "Level 5–6: Axes labelled with units; scale fills the graph paper; points accurately plotted with a smooth curve of best fit, showing that zone diameter increases with concentration but with diminishing returns (a curve, not a straight line)." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised graph of zone diameter (mm) vs √concentration (√(μg/ml)). If the relationship is log-like, √x should give an approximately straight line, allowing gradient calculation. A straight line on the transformed plot confirms the √x relationship, and the x-intercept can be used to estimate the minimum inhibitory concentration (MIC)." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Diameter of zone of inhibition at different disinfectant concentrations",
        xLabel: "Disinfectant concentration (μg/ml)",
        yLabel: "Zone of inhibition diameter (mm)",
        editable: true,
        initialRows: [
          { x: 1, y: 5.2 },
          { x: 2, y: 7.8 },
          { x: 4, y: 10.5 },
          { x: 8, y: 13.2 },
          { x: 16, y: 16.0 },
          { x: 32, y: 18.8 },
          { x: 64, y: 21.0 },
          { x: 128, y: 22.5 },
        ],
        transforms: [
          { id: "raw", label: "Inhibition zone vs concentration", x: "x", y: "y", xLabel: "Concentration (μg/ml)", yLabel: "Zone (mm)" },
          { id: "sqrt", label: "Inhibition zone vs √concentration (linearise log-like relationship)", x: "√x", y: "y", xLabel: "√concentration", yLabel: "Zone (mm)" },
        ],
        derive: { kind: "gradient", label: "Effectiveness increase per unit √concentration", unit: "mm per √(μg/ml)" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted zone diameter on the y-axis against concentration on...",
          "The graph shows a... trend because...",
          "I linearised the data by plotting zone diameter vs √concentration because...",
          "The approximately straight line on the transformed plot confirms...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "data", "zone", "concentration", "diameter"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "mm", "μg/ml", "concentration", "diameter"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve of best fit; diminishing returns trend described.", keywords: ["curve", "best fit", "diminishing", "smooth", "accurate", "scale", "non-linear", "increases"], minKeywords: 2 },
          { level: 8, descriptor: "Linearised √x plot described as approximately straight; MIC discussed.", keywords: ["√x", "sqrt", "straight line", "linear", "transform", "slope", "gradient", "mic", "minimum inhibitory", "intercept"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient of the √x vs zone diameter plot and interpret the result.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('the zone of inhibition gets larger as concentration increases')." },
        { level: 4, body: "Level 3–4: Calculates the change in zone diameter from 5.2 mm (1 μg/ml) to 22.5 mm (128 μg/ml) — a difference of 17.3 mm — and notes the rate of increase slows at higher concentrations." },
        { level: 6, body: "Level 5–6: From the zone diameter vs √concentration graph, draws a line of best fit and reads off two widely-spaced points to calculate gradient = Δzone / Δ√concentration. States the unit of gradient as mm per √(μg/ml)." },
        { level: 8, body: "Level 7–8: Full calculation shown — picks two points on the linearised graph, e.g. (√1=1, 5.2 mm) and (√128≈11.3, 22.5 mm). Gradient = (22.5 − 5.2) / (11.3 − 1) = 17.3 / 10.3 ≈ 1.68 mm per √(μg/ml). The gradient represents how much the zone diameter increases for each unit increase in √concentration. Extrapolates to find the concentration at which zone diameter = 6 mm (disc diameter) = the theoretical MIC." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Diameter of zone of inhibition at different disinfectant concentrations",
        xLabel: "Disinfectant concentration (μg/ml)",
        yLabel: "Zone of inhibition diameter (mm)",
        editable: true,
        initialRows: [
          { x: 1, y: 5.2 },
          { x: 2, y: 7.8 },
          { x: 4, y: 10.5 },
          { x: 8, y: 13.2 },
          { x: 16, y: 16.0 },
          { x: 32, y: 18.8 },
          { x: 64, y: 21.0 },
          { x: 128, y: 22.5 },
        ],
        transforms: [
          { id: "raw", label: "Inhibition zone vs concentration", x: "x", y: "y", xLabel: "Concentration (μg/ml)", yLabel: "Zone (mm)" },
          { id: "sqrt", label: "Inhibition zone vs √concentration (linearise log-like relationship)", x: "√x", y: "y", xLabel: "√concentration", yLabel: "Zone (mm)" },
        ],
        derive: { kind: "gradient", label: "Effectiveness increase per unit √concentration", unit: "mm per √(μg/ml)" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient of the zone diameter vs √concentration graph and explain what it represents.",
        scaffolds: [
          "The trend shows that zone diameter...",
          "From the √concentration plot I chose two points: (√c₁, zone₁) = ... and (√c₂, zone₂) = ...",
          "Gradient = Δzone / Δ√concentration = ... / ... = ... mm per √(μg/ml)",
          "This gradient tells us that for every unit increase in √concentration, the zone diameter...",
          "To estimate the MIC, I extrapolate to where zone diameter = 6 mm, giving √c = ..., so c ≈ ... μg/ml",
        ],
        rubric: [
          { level: 2, descriptor: "Notes zone diameter increases with concentration.", keywords: ["increases", "larger", "concentration", "zone", "diameter", "trend"], minKeywords: 1 },
          { level: 4, descriptor: "Describes diminishing returns; range of zone noted.", keywords: ["diminishing", "range", "5.2", "22.5", "slows", "non-linear", "change"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated from linearised √x graph with working.", keywords: ["gradient", "√", "sqrt", "two points", "best fit", "mm per", "unit", "slope"], minKeywords: 2 },
          { level: 8, descriptor: "Full gradient calculation with values; MIC extrapolated with working.", keywords: ["1.68", "17.3", "10.3", "11.3", "mic", "minimum inhibitory", "extrapolate", "6 mm", "disc", "gradient", "calculation"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about the relationship between disinfectant concentration and inhibition, with reference to data.",
      guided: [
        { level: 2, body: "Level 1–2: 'The zone of inhibition increased as concentration increased.'" },
        { level: 4, body: "Level 3–4: 'Zone diameter increased from 5.2 mm to 22.5 mm as concentration rose from 1 to 128 μg/ml, but the rate of increase slowed at higher concentrations — a diminishing returns pattern.'" },
        { level: 6, body: "Level 5–6: 'Zone diameter increased with disinfectant concentration in a diminishing-returns (log-like) pattern. Plotting zone diameter vs √concentration gave an approximately straight line with gradient ≈ 1.68 mm per √(μg/ml). This supports the hypothesis that doubling concentration gives progressively smaller additional inhibition — consistent with diffusion theory (Fick's law: diffusion rate is proportional to concentration gradient, but zone area grows geometrically).'" },
        { level: 8, body: "Level 7–8: 'Zone diameter increased with concentration following a √x relationship (gradient ≈ 1.68 mm per √(μg/ml)), consistent with diffusion-controlled inhibition. Extrapolating the line to zone diameter = 6 mm (disc diameter) suggests MIC ≈ (6 − y-intercept) / gradient)² ≈ estimated value μg/ml. This supports the hypothesis of logarithmic diminishing returns. However, the relationship may begin to plateau at very high concentrations as the agar becomes saturated. The data confirm that disinfectant concentration positively affects antibacterial effectiveness, but with diminishing returns that limit the practical benefit of using very high concentrations.'" },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Diameter of zone of inhibition at different disinfectant concentrations",
        xLabel: "Disinfectant concentration (μg/ml)",
        yLabel: "Zone of inhibition diameter (mm)",
        editable: true,
        initialRows: [
          { x: 1, y: 5.2 },
          { x: 2, y: 7.8 },
          { x: 4, y: 10.5 },
          { x: 8, y: 13.2 },
          { x: 16, y: 16.0 },
          { x: 32, y: 18.8 },
          { x: 64, y: 21.0 },
          { x: 128, y: 22.5 },
        ],
        transforms: [
          { id: "raw", label: "Inhibition zone vs concentration", x: "x", y: "y", xLabel: "Concentration (μg/ml)", yLabel: "Zone (mm)" },
          { id: "sqrt", label: "Inhibition zone vs √concentration (linearise log-like relationship)", x: "√x", y: "y", xLabel: "√concentration", yLabel: "Zone (mm)" },
        ],
        derive: { kind: "gradient", label: "Effectiveness increase per unit √concentration", unit: "mm per √(μg/ml)" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. Does the data support the hypothesis that higher disinfectant concentration produces a larger zone of inhibition? Use specific values and explain the pattern.",
        scaffolds: [
          "As concentration increased from 1 to 128 μg/ml, zone diameter...",
          "The relationship is... because the rate of increase...",
          "The √concentration vs zone plot gave a gradient of approximately...",
          "This is consistent with / differs from the hypothesis because...",
          "The estimated MIC from extrapolation is approximately...",
        ],
        rubric: [
          { level: 2, descriptor: "States zone diameter increases with concentration.", keywords: ["increases", "zone", "concentration", "larger", "diameter"], minKeywords: 1 },
          { level: 4, descriptor: "Specific data values cited; diminishing returns noted.", keywords: ["5.2", "22.5", "1 μg/ml", "128 μg/ml", "diminishing", "slows", "non-linear"], minKeywords: 1 },
          { level: 6, descriptor: "√x relationship described; gradient calculated; Fick's law or diffusion mentioned.", keywords: ["√x", "gradient", "1.68", "diffusion", "fick", "logarithmic", "diminishing returns", "linear", "hypothesis"], minKeywords: 3 },
          { level: 8, descriptor: "MIC extrapolated; plateau effect discussed; hypothesis evaluated with evidence.", keywords: ["mic", "extrapolate", "6 mm", "disc", "saturated", "plateau", "gradient", "1.68", "hypothesis", "evidence", "practical"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the zone of inhibition method and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could be improved by doing it more carefully.'" },
        { level: 4, body: "Level 3–4: 'Only one trial was done at each concentration, which reduces reliability. Repeating each concentration 3 times would give a mean and allow identification of anomalous results.'" },
        { level: 6, body: "Level 5–6: 'A key limitation is that the agar may not have been inoculated uniformly — patches of higher or lower bacterial density would affect the zone size independently of concentration. Improvement: use a calibrated bacterial suspension (e.g. 0.5 McFarland standard) and flood-and-drain technique. Another limitation: zones were measured with a ruler (±0.5 mm), which introduces significant random error at small zone diameters. Improvement: use digital callipers or image analysis software.'" },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses: (1) Uneven inoculation — standardise with McFarland 0.5 turbidity standard. (2) Measurement error — zones are not perfectly circular; measuring in only one direction overestimates or underestimates; measure in two perpendicular directions and average. (3) Disc placement — pressing too hard compresses agar and alters diffusion; use sterile forceps and consistent light pressure. (4) Evaporation of disinfectant — more volatile at higher concentrations; seal plates with Parafilm immediately. (5) Only 8 concentrations tested — adding intermediate values would improve curve resolution and MIC accuracy. Each weakness is linked to how it specifically affects the DV and how the improvement addresses that effect." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Diameter of zone of inhibition at different disinfectant concentrations",
        xLabel: "Disinfectant concentration (μg/ml)",
        yLabel: "Zone of inhibition diameter (mm)",
        editable: true,
        initialRows: [
          { x: 1, y: 5.2 },
          { x: 2, y: 7.8 },
          { x: 4, y: 10.5 },
          { x: 8, y: 13.2 },
          { x: 16, y: 16.0 },
          { x: 32, y: 18.8 },
          { x: 64, y: 21.0 },
          { x: 128, y: 22.5 },
        ],
        transforms: [
          { id: "raw", label: "Inhibition zone vs concentration", x: "x", y: "y", xLabel: "Concentration (μg/ml)", yLabel: "Zone (mm)" },
          { id: "sqrt", label: "Inhibition zone vs √concentration (linearise log-like relationship)", x: "√x", y: "y", xLabel: "√concentration", yLabel: "Zone (mm)" },
        ],
        derive: { kind: "gradient", label: "Effectiveness increase per unit √concentration", unit: "mm per √(μg/ml)" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect this zone of inhibition data. What are the main weaknesses and how would you improve them?",
        scaffolds: [
          "A key weakness is...",
          "This affects the zone diameter measurement because...",
          "To improve this, I would...",
          "A second weakness is...",
          "Reliability could be improved by...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness with a matching improvement.", keywords: ["repeat", "reliable", "3 times", "ruler", "measurement", "trial", "once"], minKeywords: 1 },
          { level: 6, descriptor: "Two relevant limitations with matching improvements; measurement error and inoculation mentioned.", keywords: ["uniform", "mcfarland", "callipers", "image analysis", "±0.5", "inoculation", "bacterial density", "perpendicular", "ruler", "improve"], minKeywords: 2 },
          { level: 8, descriptor: "4+ specific weaknesses with linked improvements; each weakness tied to effect on DV.", keywords: ["mcfarland", "perpendicular", "evaporation", "parafilm", "forceps", "intermediate", "resolution", "mic", "disc placement", "volatile", "compress", "affects the dv"], minKeywords: 3 },
        ],
      },
    },
  ],
}
