import type { StrandhootPack } from "../engine/types"

// Crit C data: rate of O₂ production by Elodea at different light intensities.
// The rate increases roughly linearly at low light then plateaus near 2 500 lux.
// Plotting 1/rate vs 1/light intensity (Lineweaver-Burk style) linearises the
// saturation kinetics — analogous to enzyme kinetics.
export const respirationCritC: StrandhootPack = {
  slug: "respiration-crit-c",
  title: "Light Intensity & Photosynthesis",
  subject: "MYP Biology",
  criterion: "C",
  topic: "O₂ production dataset",
  accent: "#0984b5",
  icon: "🌿",
  statementOfInquiry: "Humans need to find sources of energy that do not cause harmful and irreversible changes to ecosystems and the environment.",
  estMinutes: 30,
  intro:
    "A student measured O₂ bubble production in Elodea at eight light intensities. Use the data tool to plot, transform and analyse the results — then write a conclusion linking to limiting factors and evaluate the method. Each strand levels up with the depth of your scientific reasoning.",
  badges: [
    { id: "presenter", label: "Data Display", icon: "📊", description: "Reach Level 8 on Presenting data", strandId: "present", atLevel: 8 },
    { id: "processor", label: "Gradient Finder", icon: "📐", description: "Reach Level 8 on Processing data", strandId: "process", atLevel: 8 },
    { id: "concluder", label: "Photosynthesis Analyst", icon: "🌱", description: "Reach Level 8 on Conclusion", strandId: "conclude", atLevel: 8 },
    { id: "evaluator", label: "Method Critic", icon: "⚖️", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "O₂ production dataset", blurb: "Rate of O₂ production by Elodea vs light intensity", icon: "🌿" }],
  strands: [
    {
      id: "present",
      name: "Presenting the data",
      descriptor: "Display the O₂ bubble rate vs light intensity data clearly and apply the Lineweaver-Burk transform.",
      guided: [
        { level: 2, body: "Level 1–2: A basic table with data values but missing headings or units." },
        { level: 4, body: "Level 3–4: A clear table with column headings (Light intensity in lux; O₂ bubble rate in bubbles/min) and a graph with both axes labelled including units." },
        { level: 6, body: "Level 5–6: Axes labelled with units, a sensible scale that fills the grid, points accurately plotted with a smooth curve of best fit showing the initial linear increase and plateau (light saturation) at around 2 500 lux." },
        { level: 8, body: "Level 7–8: As Level 5–6, plus a linearised graph of 1/rate vs 1/light intensity (Lineweaver-Burk). If saturation kinetics hold, this gives a straight line — far easier to analyse. The intercept and slope of the 1/rate vs 1/light plot reveal maximum rate (Vmax) and the half-saturation constant (analogous to Km in enzyme kinetics)." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Rate of O₂ production by Elodea at different light intensities",
        xLabel: "Light intensity (lux)",
        yLabel: "O₂ bubble rate (bubbles/min)",
        editable: true,
        initialRows: [
          { x: 0, y: 0 },
          { x: 500, y: 3 },
          { x: 1000, y: 8 },
          { x: 1500, y: 13 },
          { x: 2000, y: 17 },
          { x: 2500, y: 20 },
          { x: 3000, y: 22 },
          { x: 3500, y: 22.5 },
        ],
        transforms: [
          { id: "raw", label: "Bubble rate vs light intensity", x: "x", y: "y", xLabel: "Light intensity (lux)", yLabel: "Bubble rate (bubbles/min)" },
          { id: "inv", label: "1/rate vs 1/intensity (Lineweaver-Burk)", x: "1/x", y: "1/y", xLabel: "1/light intensity", yLabel: "1/bubble rate" },
        ],
        derive: { kind: "gradient", label: "Rate of increase in linear region", unit: "bubbles/min per lux" },
      },
      response: {
        kind: "data",
        prompt: "Describe how you have presented the data. What makes your table and graph clear and scientifically valid?",
        scaffolds: [
          "My table includes headings and units for...",
          "I plotted O₂ bubble rate on the y-axis against light intensity on...",
          "The graph shows a... trend because...",
          "I linearised the data by plotting 1/rate vs 1/light intensity because...",
          "The straight line on the Lineweaver-Burk plot confirms...",
        ],
        rubric: [
          { level: 2, descriptor: "Mentions the data or graph.", keywords: ["table", "graph", "data", "bubbles", "light", "intensity"], minKeywords: 1 },
          { level: 4, descriptor: "Headings and units on table and axes.", keywords: ["units", "heading", "labelled", "axes", "lux", "bubbles per minute", "light intensity"], minKeywords: 2 },
          { level: 6, descriptor: "Smooth curve of best fit; plateau described; saturation named.", keywords: ["curve", "best fit", "plateau", "saturation", "smooth", "increases", "linear", "scale"], minKeywords: 2 },
          { level: 8, descriptor: "Lineweaver-Burk linearised plot described as a straight line.", keywords: ["1/rate", "1/intensity", "straight line", "linear", "lineweaver", "transform", "slope", "intercept", "vmax"], minKeywords: 2 },
        ],
      },
    },
    {
      id: "process",
      name: "Processing the data",
      descriptor: "Calculate the gradient in the linear region and identify the light saturation point.",
      guided: [
        { level: 2, body: "Level 1–2: Describes the overall trend ('the bubble rate increases with light intensity')." },
        { level: 4, body: "Level 3–4: Notes that the rate increases steeply at low light then levels off. Identifies the approximate saturation point as around 2 500–3 000 lux where the rate stops increasing." },
        { level: 6, body: "Level 5–6: From the linear region (0–1 500 lux), draws a line of best fit and calculates the gradient = Δ(bubble rate) / Δ(light intensity). For example: (13 − 0) / (1 500 − 0) ≈ 0.0087 bubbles min⁻¹ per lux. States the light compensation point as the intensity at which photosynthesis rate equals respiration rate (here: x = 0, since data starts at 0 bubbles)." },
        { level: 8, body: "Level 7–8: Full gradient calculation in linear region: using (0, 0) and (1 500, 13): gradient = 13/1500 ≈ 0.0087 bubbles min⁻¹ per lux. From 2 500 lux onward, rate plateaus at ~22–22.5 bubbles/min — the maximum rate (Vmax). The 1/rate vs 1/intensity Lineweaver-Burk plot linearises the curve; the y-intercept = 1/Vmax ≈ 1/22.5 ≈ 0.044 min/bubble, confirming the plateau value. Notes uncertainty: each data point is a single trial — repeat measurements needed to calculate error bars." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Rate of O₂ production by Elodea at different light intensities",
        xLabel: "Light intensity (lux)",
        yLabel: "O₂ bubble rate (bubbles/min)",
        editable: true,
        initialRows: [
          { x: 0, y: 0 },
          { x: 500, y: 3 },
          { x: 1000, y: 8 },
          { x: 1500, y: 13 },
          { x: 2000, y: 17 },
          { x: 2500, y: 20 },
          { x: 3000, y: 22 },
          { x: 3500, y: 22.5 },
        ],
        transforms: [
          { id: "raw", label: "Bubble rate vs light intensity", x: "x", y: "y", xLabel: "Light intensity (lux)", yLabel: "Bubble rate (bubbles/min)" },
          { id: "inv", label: "1/rate vs 1/intensity (Lineweaver-Burk)", x: "1/x", y: "1/y", xLabel: "1/light intensity", yLabel: "1/bubble rate" },
        ],
        derive: { kind: "gradient", label: "Rate of increase in linear region", unit: "bubbles/min per lux" },
      },
      response: {
        kind: "data",
        prompt: "Process the data: calculate the gradient in the linear region, identify the saturation point, and use the Lineweaver-Burk transform to confirm the maximum rate.",
        scaffolds: [
          "The trend shows that the bubble rate...",
          "In the linear region (0–1 500 lux): gradient = Δy / Δx = ___ / ___ = ___ bubbles min⁻¹ per lux",
          "The light saturation point is approximately ___ lux because...",
          "From the Lineweaver-Burk plot, the y-intercept = 1/Vmax ≈ ___, so Vmax ≈ ___ bubbles/min",
        ],
        rubric: [
          { level: 2, descriptor: "Notes rate increases with light intensity.", keywords: ["increases", "light intensity", "bubbles", "rate", "more light", "trend"], minKeywords: 1 },
          { level: 4, descriptor: "Saturation point identified; plateau described.", keywords: ["plateau", "saturation", "2500", "3000", "levels off", "maximum", "no longer increases"], minKeywords: 1 },
          { level: 6, descriptor: "Gradient calculated from linear region with working.", keywords: ["gradient", "linear", "0.0087", "1500", "13", "bubbles per lux", "best fit", "slope"], minKeywords: 2 },
          { level: 8, descriptor: "Full gradient calculation; Lineweaver-Burk y-intercept used to confirm Vmax; uncertainty noted.", keywords: ["0.0087", "vmax", "22.5", "1/vmax", "0.044", "y-intercept", "lineweaver", "error bar", "repeat", "uncertainty"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "conclude",
      name: "Conclusion",
      descriptor: "State a conclusion about limiting factors and link the plateau to CO₂ limitation.",
      guided: [
        { level: 2, body: "Level 1–2: 'The O₂ production increased as light intensity increased.'" },
        { level: 4, body: "Level 3–4: 'O₂ production increased with light intensity but stopped increasing at around 2 500 lux, suggesting the plant reached its maximum photosynthesis rate.'" },
        { level: 6, body: "Level 5–6: 'From 0 to 1 500 lux, rate increased linearly (gradient ≈ 0.0087 bubbles min⁻¹ per lux), confirming light was the limiting factor. Above 2 500 lux, rate plateaued at ~22 bubbles/min — light was no longer limiting. At this point CO₂ concentration became the limiting factor, as RuBisCO could not fix CO₂ any faster with the CO₂ and Elodea provided.'" },
        { level: 8, body: "Level 7–8: Linear phase (0–1 500 lux) rate = 0.0087 × intensity (r² close to 1). Saturation at ~2 500 lux; Vmax ≈ 22.5 bubbles/min. The plateau is explained by CO₂ limitation — at high light, the Calvin cycle is limited by CO₂ supply and RuBisCO activity, not photon availability. The 1/rate vs 1/intensity linearisation confirms Michaelis–Menten-type kinetics, with the y-intercept giving 1/Vmax ≈ 0.044 min/bubble. This is consistent with the hypothesis that rate would plateau at saturation. Quantitative agreement between linear gradient and literature values for Elodea supports the reliability of the method." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Rate of O₂ production by Elodea at different light intensities",
        xLabel: "Light intensity (lux)",
        yLabel: "O₂ bubble rate (bubbles/min)",
        editable: true,
        initialRows: [
          { x: 0, y: 0 },
          { x: 500, y: 3 },
          { x: 1000, y: 8 },
          { x: 1500, y: 13 },
          { x: 2000, y: 17 },
          { x: 2500, y: 20 },
          { x: 3000, y: 22 },
          { x: 3500, y: 22.5 },
        ],
        transforms: [
          { id: "raw", label: "Bubble rate vs light intensity", x: "x", y: "y", xLabel: "Light intensity (lux)", yLabel: "Bubble rate (bubbles/min)" },
          { id: "inv", label: "1/rate vs 1/intensity (Lineweaver-Burk)", x: "1/x", y: "1/y", xLabel: "1/light intensity", yLabel: "1/bubble rate" },
        ],
        derive: { kind: "gradient", label: "Rate of increase in linear region", unit: "bubbles/min per lux" },
      },
      response: {
        kind: "data",
        prompt: "Write a conclusion. What limited the rate of photosynthesis at low and at high light intensity? Use specific data values and link to limiting factors.",
        scaffolds: [
          "At low light intensity (0–1 500 lux), the rate increased because...",
          "The gradient in the linear region is approximately ___.",
          "Above 2 500 lux, the rate plateaued at ___ bubbles/min because...",
          "At this point the limiting factor changed from light to...",
          "This is consistent with / differs from my hypothesis because...",
        ],
        rubric: [
          { level: 2, descriptor: "States O₂ rate increases with light intensity.", keywords: ["increases", "light", "o2", "bubbles", "rate", "more"], minKeywords: 1 },
          { level: 4, descriptor: "Plateau identified; saturation point named.", keywords: ["plateau", "saturation", "2500", "maximum", "levels off", "no longer"], minKeywords: 1 },
          { level: 6, descriptor: "Specific data values used; limiting factor shift explained.", keywords: ["0.0087", "1500", "13", "2500", "22", "limiting factor", "co2", "rubisco", "light", "gradient"], minKeywords: 3 },
          { level: 8, descriptor: "Gradient and Vmax calculated; Lineweaver-Burk intercept cited; hypothesis referenced.", keywords: ["vmax", "22.5", "0.044", "lineweaver", "michaelis", "r²", "hypothesis", "co2 limiting", "consistent", "gradient"], minKeywords: 3 },
        ],
      },
    },
    {
      id: "evaluate",
      name: "Evaluating the method",
      descriptor: "Identify weaknesses in the Elodea bubble-counting method and suggest specific improvements.",
      guided: [
        { level: 2, body: "Level 1–2: 'The method could be improved.'" },
        { level: 4, body: "Level 3–4: 'Only one trial was done at each light intensity, which reduces reliability. The results might not be repeatable.'" },
        { level: 6, body: "Level 5–6: 'Key limitations: (1) bubbles vary in size — counting bubbles is not the same as measuring O₂ volume; larger bubbles contain more O₂, so bubble count is not a fully accurate DV. Better: use an inverted test tube to collect gas and measure volume with a syringe. (2) Only one trial per light intensity — need 3 repeats to calculate mean and identify outliers.'" },
        { level: 8, body: "Level 7–8: Multiple specific weaknesses: (1) Bubble size varies — use a gas syringe or O₂ electrode to measure O₂ volume directly. (2) No acclimatisation time stated — plant needs 3–5 min to adjust to each new light level, or residual chloroplast activity affects the first reading. (3) Light intensity was set by distance, not measured — use a light sensor (lux meter) for accurate x-axis values; 1/d² relationship assumes a point source. (4) Single trials only — need 3 repeats per intensity; calculate mean ± SD, draw error bars. (5) CO₂ may be depleted over time if a large volume of plant is used — refresh NaHCO₃ solution between readings." },
      ],
      artifactKey: "data-processor",
      artifactProps: {
        title: "Rate of O₂ production by Elodea at different light intensities",
        xLabel: "Light intensity (lux)",
        yLabel: "O₂ bubble rate (bubbles/min)",
        editable: true,
        initialRows: [
          { x: 0, y: 0 },
          { x: 500, y: 3 },
          { x: 1000, y: 8 },
          { x: 1500, y: 13 },
          { x: 2000, y: 17 },
          { x: 2500, y: 20 },
          { x: 3000, y: 22 },
          { x: 3500, y: 22.5 },
        ],
        transforms: [
          { id: "raw", label: "Bubble rate vs light intensity", x: "x", y: "y", xLabel: "Light intensity (lux)", yLabel: "Bubble rate (bubbles/min)" },
          { id: "inv", label: "1/rate vs 1/intensity (Lineweaver-Burk)", x: "1/x", y: "1/y", xLabel: "1/light intensity", yLabel: "1/bubble rate" },
        ],
        derive: { kind: "gradient", label: "Rate of increase in linear region", unit: "bubbles/min per lux" },
      },
      response: {
        kind: "data",
        prompt: "Evaluate the method used to collect this O₂ production data. What are the main weaknesses and how would you improve them?",
        scaffolds: [
          "A key weakness is...",
          "This affects the result because...",
          "To improve this, I would...",
          "Reliability could be improved by...",
          "A source of systematic error is...",
        ],
        rubric: [
          { level: 2, descriptor: "Vague evaluation.", keywords: ["improve", "better", "error", "weakness", "problem", "accurate"], minKeywords: 1 },
          { level: 4, descriptor: "One specific weakness mentioned.", keywords: ["repeat", "single trial", "bubble size", "reliable", "only once", "one trial"], minKeywords: 1 },
          { level: 6, descriptor: "Two relevant weaknesses with matching improvements.", keywords: ["bubble size", "gas syringe", "o2 electrode", "repeat", "3 times", "acclimatisation", "reliable", "mean", "improve"], minKeywords: 3 },
          { level: 8, descriptor: "Multiple specific weaknesses with reasoned improvements; error bars and light sensor named.", keywords: ["gas syringe", "o2 electrode", "acclimatisation", "lux meter", "light sensor", "1/d²", "point source", "error bar", "sd", "nahco3", "depleted", "co2"], minKeywords: 4 },
        ],
      },
    },
  ],
}
