import type { StrandhootPack } from "../engine/types"

export const respirationCritA: StrandhootPack = {
  slug: "respiration-crit-a",
  title: "Cell Respiration & Photosynthesis",
  subject: "MYP Biology",
  criterion: "A",
  topic: "ATP, aerobic & anaerobic respiration",
  accent: "#1b7888",
  icon: "🌿",
  statementOfInquiry: "Humans need to find sources of energy that do not cause harmful and irreversible changes to ecosystems and the environment.",
  estMinutes: 25,
  intro:
    "Every living cell needs energy. From the ATP molecule to fermentation in yeast, this pack traces how organisms capture, store and release energy — levelling up from basic recall to analysis of aerobic and anaerobic pathways.",
  badges: [
    { id: "atp-expert", label: "ATP Expert", icon: "⚡", description: "Reach Level 8 on ATP & energy", strandId: "atp", atLevel: 8 },
    { id: "photosynthesiser", label: "Photosynthesiser", icon: "☀️", description: "Reach Level 8 on Photosynthesis", strandId: "photosynthesis", atLevel: 8 },
    { id: "aerobic-ace", label: "Aerobic Ace", icon: "🫁", description: "Reach Level 8 on Aerobic respiration", strandId: "aerobic", atLevel: 8 },
    { id: "master", label: "Biology Master", icon: "🏆", description: "Reach Level 6+ on all strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 1: Energy", blurb: "ATP, photosynthesis, aerobic and anaerobic respiration", icon: "🌿" }],
  strands: [
    {
      id: "atp",
      name: "ATP & energy",
      descriptor: "Describe the role of ATP as the universal energy currency of the cell.",
      guided: [
        { level: 2, body: "ATP stands for adenosine triphosphate. It is the universal energy currency of the cell — all organisms use ATP to power their cellular activities. When ATP is broken down into ADP (adenosine diphosphate) and Pi (inorganic phosphate), energy is released." },
        { level: 4, body: "ATP ↔ ADP + Pi: energy is stored when ADP and Pi are joined to make ATP, and released when ATP is broken back down. ATP is used for active transport (moving molecules against a concentration gradient), protein synthesis (making enzymes and structural proteins), movement (muscle contraction), and cell division." },
        { level: 6, body: "ATP is the link between energy-releasing reactions (respiration) and energy-requiring reactions (active transport, biosynthesis, movement). Because ATP can be rapidly made and broken down, it allows precise control of energy delivery. The energy released per molecule (~30.5 kJ mol⁻¹ hydrolysis) is small enough to be used without overheating the cell — unlike a direct glucose burn." },
        { level: 8, body: "ATP is not a long-term energy store — it cycles continuously. A human uses roughly their body mass in ATP per day, regenerated from ADP + Pi by respiration. The tight coupling of ATP synthesis to proton gradients (chemiosmosis in mitochondria) means the cell only makes as much ATP as the proton-motive force and ADP availability allow — a self-regulating energy economy. This contrasts with glucose, which is a stable storage molecule but cannot directly drive cellular machines." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "atp-l2",
            level: 2,
            prompt: "What does ATP stand for?",
            options: [
              { id: "a", text: "Adenine triphosphate" },
              { id: "b", text: "Adenosine triphosphate", correct: true },
              { id: "c", text: "Adenosine two-phosphate" },
              { id: "d", text: "Amino triphosphate" },
            ],
            explanation: "ATP stands for adenosine triphosphate — it contains the base adenine, the sugar ribose, and three phosphate groups.",
          },
          {
            type: "fill",
            id: "atp-l4",
            level: 4,
            prompt: "When ATP releases energy it is broken down into ADP and ▁.",
            answers: ["Pi", "inorganic phosphate", "phosphate"],
            explanation: "ATP → ADP + Pi (inorganic phosphate). The energy stored in the bond between the second and third phosphate groups is released and used by the cell.",
          },
          {
            type: "short",
            id: "atp-l6",
            level: 6,
            prompt: "Give three uses of ATP energy in the cell and explain why ATP is described as the 'universal energy currency'.",
            keywords: ["active transport", "protein synthesis", "movement", "muscle", "cell division", "universal", "energy currency", "all organisms"],
            minKeywords: 2,
            sample: "ATP provides energy for active transport (moving molecules against concentration gradients), protein synthesis (building enzymes and structural proteins), and movement (muscle contraction). It is called the universal energy currency because every living organism — from bacteria to humans — uses ATP to power cellular reactions. ATP bridges energy-releasing (respiration) and energy-requiring processes.",
          },
          {
            type: "short",
            id: "atp-l8",
            level: 8,
            prompt: "Explain why ATP is not a long-term energy storage molecule, and how its continuous cycling is regulated by the cell's energy demand.",
            keywords: ["adp", "chemiosmosis", "proton gradient", "mitochondria", "cycling", "regenerated", "storage", "glucose", "self-regulating", "demand"],
            minKeywords: 3,
            sample: "ATP is not a long-term store because it is continuously broken down and regenerated — the pool is tiny but cycles rapidly (a human regenerates roughly their own body mass in ATP daily). Synthesis is regulated by chemiosmosis: proton gradients across the inner mitochondrial membrane drive ATP synthase, and the rate depends on ADP availability. When demand is low, ADP is scarce and ATP synthesis slows automatically — a self-regulating system. Glucose, by contrast, is a stable, compact long-term energy store that cannot directly power cellular machinery.",
          },
        ],
      },
    },
    {
      id: "photosynthesis",
      name: "Photosynthesis",
      descriptor: "Write and interpret the equation for photosynthesis and explain factors that limit its rate.",
      guided: [
        { level: 2, body: "Photosynthesis is the process by which plants make their own food using light energy. The equation is: 6H₂O + 6CO₂ → C₆H₁₂O₆ + 6O₂ (in the presence of light energy). Glucose is the food produced and oxygen is released as a by-product." },
        { level: 4, body: "Photosynthesis occurs in chloroplasts, which contain the green pigment chlorophyll. Chlorophyll absorbs red and blue light but reflects green light (which is why leaves appear green). The glucose produced is stored as starch in the plant. Carbon dioxide enters through tiny pores called stomata; water is absorbed through the roots." },
        { level: 6, body: "Limiting factors control the rate of photosynthesis. At low light intensity, increasing light increases the rate — light provides the energy to split water. At high light intensity, CO₂ concentration becomes limiting — more CO₂ means more substrate for the Calvin cycle. Temperature affects enzyme activity: too cold slows enzymes; too hot denatures them. A compensation point exists where photosynthesis rate equals respiration rate." },
        { level: 8, body: "The two stages: (1) light-dependent reactions in the thylakoid — chlorophyll absorbs photons, splits water (photolysis: 2H₂O → 4H⁺ + 4e⁻ + O₂), generates ATP and NADPH, releasing O₂. (2) Calvin cycle in the stroma — CO₂ fixed by RuBisCO into G3P, which requires ATP and NADPH. Limiting factors interact non-linearly: at light saturation, CO₂ becomes the sole limiter; at very high CO₂, light or RuBisCO activity limits. Temperature has a bell-shaped effect on enzyme efficiency." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "photo-l2",
            level: 2,
            prompt: "Which of the following is the correct equation for photosynthesis?",
            options: [
              { id: "a", text: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP" },
              { id: "b", text: "6H₂O + 6CO₂ → C₆H₁₂O₆ + 6O₂", correct: true },
              { id: "c", text: "6CO₂ + 6O₂ → C₆H₁₂O₆ + 6H₂O" },
              { id: "d", text: "6H₂O + 6O₂ → C₆H₁₂O₆ + 6CO₂" },
            ],
            explanation: "Photosynthesis converts water and carbon dioxide into glucose and oxygen using light energy: 6H₂O + 6CO₂ → C₆H₁₂O₆ + 6O₂.",
          },
          {
            type: "fill",
            id: "photo-l4",
            level: 4,
            prompt: "Photosynthesis takes place in the ▁, which contains the pigment chlorophyll.",
            answers: ["chloroplast", "chloroplasts"],
            explanation: "Chloroplasts are the organelles where photosynthesis occurs. They contain chlorophyll, which absorbs red and blue light to power the reaction.",
          },
          {
            type: "short",
            id: "photo-l6",
            level: 6,
            prompt: "Explain how light intensity, CO₂ concentration and temperature can each limit the rate of photosynthesis.",
            keywords: ["limiting factor", "light intensity", "co2", "temperature", "enzyme", "rate", "chlorophyll", "calvin cycle"],
            minKeywords: 2,
            sample: "At low light intensity, increasing light boosts the rate because light energy is needed to power the reaction. Once light is no longer limiting, CO₂ concentration becomes the limiting factor — more CO₂ provides more substrate for the Calvin cycle. Temperature affects enzyme activity: at low temperatures enzymes work slowly; above the optimum, enzymes denature and rate falls. Only one factor limits the rate at any given time.",
          },
          {
            type: "short",
            id: "photo-l8",
            level: 8,
            prompt: "Describe the two stages of photosynthesis and explain how limiting factors interact at light saturation and very high CO₂ concentration.",
            keywords: ["light-dependent", "calvin cycle", "thylakoid", "stroma", "atp", "nadph", "co2", "rubisco", "photolysis", "saturation", "limiting"],
            minKeywords: 3,
            sample: "Stage 1 (light-dependent, thylakoid): chlorophyll absorbs photons, splits water (photolysis), produces ATP and NADPH, releases O₂. Stage 2 (Calvin cycle, stroma): CO₂ is fixed by RuBisCO using ATP and NADPH to make G3P (glucose precursor). At light saturation, further increases in light have no effect — CO₂ becomes the sole limiting factor. At very high CO₂, RuBisCO activity or temperature (enzyme kinetics) limits the rate instead. Factors interact non-linearly, and all three must be near-optimal for maximum rate.",
          },
        ],
      },
    },
    {
      id: "aerobic",
      name: "Aerobic respiration",
      descriptor: "Write the equation for aerobic respiration and explain where and why it produces so much ATP.",
      guided: [
        { level: 2, body: "Aerobic respiration uses oxygen to release energy from glucose. The equation is: glucose + oxygen → carbon dioxide + water + ATP. It occurs in the mitochondria — the 'powerhouses' of the cell. Much more ATP is produced than in anaerobic respiration." },
        { level: 4, body: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. A simplified figure: up to 38 ATP molecules are produced per glucose molecule. Aerobic respiration requires a continuous supply of oxygen — which is why we breathe. The mitochondria are the site because they have a large inner membrane surface area (cristae) for the reactions to occur." },
        { level: 6, body: "Aerobic respiration has three stages: glycolysis (cytoplasm — glucose → pyruvate, nets 2 ATP), the Krebs cycle (mitochondrial matrix — pyruvate fully oxidised, releasing CO₂, producing NADH and FADH₂), and oxidative phosphorylation (inner mitochondrial membrane — electron carriers donate electrons to O₂, driving chemiosmosis, producing ~34 ATP). Oxygen is the final electron acceptor — without it, the chain stops." },
        { level: 8, body: "The high ATP yield (theoretical 38, practical ~30–32 due to membrane leakage) comes from chemiosmosis: NADH and FADH₂ donate electrons to the electron transport chain, pumping H⁺ ions across the inner membrane. The resulting proton-motive force drives ATP synthase. Each NADH yields ~2.5 ATP; each FADH₂ ~1.5 ATP. This contrasts sharply with the net 2 ATP from glycolysis alone. Mitochondrial cristae maximise surface area for ATP synthase complexes, directly linking organelle structure to function." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "aerobic-l2",
            level: 2,
            prompt: "Where does aerobic respiration mainly take place in eukaryotic cells?",
            options: [
              { id: "a", text: "The nucleus" },
              { id: "b", text: "The chloroplast" },
              { id: "c", text: "The mitochondria", correct: true },
              { id: "d", text: "The cell membrane" },
            ],
            explanation: "Aerobic respiration occurs mainly in the mitochondria — the organelles often called the powerhouses of the cell. Their large folded inner membrane (cristae) provides a surface for the electron transport chain.",
          },
          {
            type: "fill",
            id: "aerobic-l4",
            level: 4,
            prompt: "A simplified figure for the number of ATP molecules produced per glucose in aerobic respiration is ▁.",
            answers: ["38", "up to 38", "approximately 38"],
            explanation: "Aerobic respiration produces up to 38 ATP per glucose (theoretical maximum). In practice, around 30–32 ATP are generated due to membrane leakage and transport costs.",
          },
          {
            type: "short",
            id: "aerobic-l6",
            level: 6,
            prompt: "Explain why aerobic respiration produces so much more ATP than anaerobic respiration. Name the location and role of oxygen in the process.",
            keywords: ["mitochondria", "oxygen", "electron transport chain", "glycolysis", "krebs cycle", "chemiosmosis", "38", "2", "electron acceptor"],
            minKeywords: 2,
            sample: "Aerobic respiration produces up to 38 ATP per glucose because glucose is completely oxidised across three stages: glycolysis (2 ATP), the Krebs cycle (generating NADH and FADH₂), and oxidative phosphorylation (~34 ATP via chemiosmosis on the inner mitochondrial membrane). Oxygen is the final electron acceptor at the end of the electron transport chain — without it, the chain stops and only the 2 ATP from glycolysis are available (as in anaerobic respiration).",
          },
          {
            type: "short",
            id: "aerobic-l8",
            level: 8,
            prompt: "Describe how chemiosmosis generates ATP in the mitochondria, and explain how the structure of the mitochondrion is adapted for this process.",
            keywords: ["chemiosmosis", "proton gradient", "inner membrane", "cristae", "atp synthase", "nadh", "fadh2", "electron transport chain", "surface area", "structure"],
            minKeywords: 3,
            sample: "NADH and FADH₂ (produced in glycolysis and the Krebs cycle) donate electrons to protein complexes in the inner mitochondrial membrane. These complexes use the energy to pump H⁺ ions from the matrix into the intermembrane space, creating a proton-motive force (electrochemical gradient). H⁺ ions flow back through ATP synthase, driving the synthesis of ATP from ADP + Pi — this is chemiosmosis. The mitochondrion's folded inner membrane (cristae) maximises surface area, packing more ATP synthase complexes per cell, directly linking organelle structure to its high ATP output.",
          },
        ],
      },
    },
    {
      id: "anaerobic",
      name: "Anaerobic respiration",
      descriptor: "Compare anaerobic respiration in animals and yeast, and explain why less ATP is produced.",
      guided: [
        { level: 2, body: "Anaerobic respiration occurs without oxygen. In animals (including humans), glucose is broken down to lactic acid, releasing a small amount of ATP. In yeast and fungi, glucose is converted to ethanol and carbon dioxide — this process is called fermentation." },
        { level: 4, body: "Animals: glucose → lactic acid + ATP. The build-up of lactic acid causes muscle fatigue and pain. After exercise, extra oxygen (the 'oxygen debt') is needed to break down the lactic acid. Yeast: glucose → ethanol + CO₂ + ATP. This is used in baking (CO₂ makes bread rise) and brewing (ethanol in alcoholic drinks). Both pathways produce far less ATP than aerobic respiration." },
        { level: 6, body: "Less ATP is produced because glucose is not completely broken down. In both pathways only glycolysis occurs, netting 2 ATP per glucose (vs. up to 38 in aerobic). In animals, pyruvate is reduced to lactate by NADH, regenerating NAD⁺ so glycolysis can continue — but the carbon atoms remain in lactate, not fully oxidised to CO₂. In yeast, pyruvate is decarboxylated to acetaldehyde and then reduced to ethanol. The energy in the C–C and C–H bonds of lactate/ethanol is wasted (not captured as ATP)." },
        { level: 8, body: "The key constraint is NAD⁺ regeneration: glycolysis requires NAD⁺ as a hydrogen acceptor, but without O₂, the electron transport chain cannot reoxidise NADH. Anaerobic pathways (lactate in animals, ethanol in yeast) regenerate NAD⁺ from NADH, allowing glycolysis to keep running — but at the cost of only 2 ATP and incomplete glucose oxidation. The 'oxygen debt' (excess post-exercise oxygen consumption, EPOC) reflects the aerobic oxidation of lactate (via the liver converting lactate → glucose → CO₂ + H₂O) and replenishment of depleted creatine phosphate stores. Fermentation is exploited industrially because the CO₂ and ethanol by-products are commercially valuable." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "anaerobic-l2",
            level: 2,
            prompt: "What are the products of anaerobic respiration in yeast?",
            options: [
              { id: "a", text: "Lactic acid and ATP" },
              { id: "b", text: "Carbon dioxide and water" },
              { id: "c", text: "Ethanol, carbon dioxide and ATP", correct: true },
              { id: "d", text: "Glucose and oxygen" },
            ],
            explanation: "Yeast perform fermentation: glucose → ethanol + CO₂ + ATP. This is the basis of brewing and baking.",
          },
          {
            type: "fill",
            id: "anaerobic-l4",
            level: 4,
            prompt: "The build-up of ▁ during anaerobic respiration in animal muscles causes fatigue and pain.",
            answers: ["lactic acid", "lactate"],
            explanation: "In animal muscle cells, glucose is converted to lactic acid (lactate) when oxygen is insufficient. The accumulation of lactic acid causes the burning sensation and fatigue during intense exercise.",
          },
          {
            type: "short",
            id: "anaerobic-l6",
            level: 6,
            prompt: "Explain why anaerobic respiration produces much less ATP than aerobic respiration. Use the term 'glucose not fully broken down' in your answer.",
            keywords: ["glycolysis", "2 atp", "38 atp", "glucose not fully broken down", "lactic acid", "ethanol", "complete oxidation", "electron transport chain", "oxygen"],
            minKeywords: 2,
            sample: "Anaerobic respiration produces only 2 ATP per glucose because glucose is not fully broken down — it is only partially oxidised to lactic acid (in animals) or ethanol + CO₂ (in yeast). Only glycolysis occurs, netting 2 ATP. In aerobic respiration, glucose is completely oxidised to CO₂ and H₂O through glycolysis, the Krebs cycle, and oxidative phosphorylation, yielding up to 38 ATP. Without oxygen, the electron transport chain cannot run, so most of the energy in glucose remains locked in the products and is lost as heat.",
          },
          {
            type: "short",
            id: "anaerobic-l8",
            level: 8,
            prompt: "Explain the role of NAD⁺ regeneration in anaerobic respiration, and describe what happens to lactic acid after intense exercise (the oxygen debt).",
            keywords: ["nad+", "nadh", "glycolysis", "regenerate", "electron transport chain", "oxygen debt", "epoc", "lactate", "liver", "creatine phosphate", "aerobic"],
            minKeywords: 3,
            sample: "Glycolysis requires NAD⁺ as a hydrogen acceptor (glucose → pyruvate, reducing NAD⁺ to NADH). Without oxygen, the electron transport chain cannot reoxidise NADH back to NAD⁺. Anaerobic pathways solve this: in animals, pyruvate is reduced to lactate using NADH → NAD⁺ is regenerated, keeping glycolysis running. After intense exercise, elevated oxygen uptake (EPOC, or 'oxygen debt') is used to aerobically oxidise the accumulated lactate — mainly in the liver, which converts lactate back to pyruvate and then to glucose, and also to replenish creatine phosphate stores and restore O₂ levels in myoglobin.",
          },
        ],
      },
    },
  ],
}
