import type { StrandhootPack } from "../engine/types"

export const transferCritA: StrandhootPack = {
  slug: "transfer-crit-a",
  title: "Transfer: Moles, Concentration & Organic Chemistry",
  subject: "MYP Chemistry",
  criterion: "A",
  topic: "Concentration, titration, pH & esters",
  accent: "#1b7888",
  icon: "⚗️",
  statementOfInquiry:
    "Technological advances in analytical devices enhance the ability of scientists to monitor the transfer of matter when changes occur during chemical reactions.",
  estMinutes: 28,
  intro:
    "From calculating the concentration of a solution to naming esters from fruit fragrances, this pack tests your knowledge of the key quantitative and organic ideas in Chapter 12: Transfer. Each strand levels up from recall to analysis — see how far you can go.",
  badges: [
    { id: "mole-master", label: "Mole Master", icon: "🔢", description: "Reach Level 8 on Concentration calculations", strandId: "concentration", atLevel: 8 },
    { id: "titration-pro", label: "Titration Pro", icon: "🧪", description: "Reach Level 8 on Titration technique", strandId: "titration", atLevel: 8 },
    { id: "ph-expert", label: "pH Expert", icon: "📊", description: "Reach Level 8 on pH and indicators", strandId: "ph", atLevel: 8 },
    { id: "ester-architect", label: "Ester Architect", icon: "🍎", description: "Reach Level 8 on Carboxylic acids and esters", strandId: "esters", atLevel: 8 },
    { id: "transfer-master", label: "Transfer Master", icon: "🏆", description: "Reach Level 6+ on all four strands", atLevel: 6 },
  ],
  paths: [{ id: "default", label: "Chapter 12: Transfer", blurb: "Concentration, titration, pH curves and organic esters", icon: "⚗️" }],
  strands: [
    {
      id: "concentration",
      name: "Concentration calculations",
      descriptor: "Calculate and interpret concentration of solutions using the mole concept.",
      guided: [
        { level: 2, body: "Concentration is a measure of how much solute is dissolved in a given volume of solvent. It is measured in mol dm⁻³. The formula is: concentration (mol dm⁻³) = amount of solute (mol) ÷ volume of solution (dm³). Remember: 1 dm³ = 1 litre = 1000 cm³." },
        { level: 4, body: "To find the amount in moles from a mass: amount (mol) = mass (g) ÷ molar mass Mᵣ (g mol⁻¹). Combining both formulae: concentration (mol dm⁻³) = mass (g) ÷ [Mᵣ (g mol⁻¹) × volume (dm³)]. Example: 8.00 g of NaOH (Mᵣ = 40.00) in 0.80 dm³ → concentration = 8.00 ÷ (40.00 × 0.80) = 0.25 mol dm⁻³." },
        { level: 6, body: "Apply the method step by step: (1) calculate Mᵣ if not given; (2) convert cm³ to dm³ by dividing by 1000; (3) calculate moles; (4) calculate concentration. For 6.80 g of NH₃ (Mᵣ = 17.03) in 800 cm³ = 0.800 dm³: moles = 6.80 ÷ 17.03 = 0.3993 mol; concentration = 0.3993 ÷ 0.800 = 0.499 mol dm⁻³ ≈ 0.499 mol dm⁻³ (3 s.f.)." },
        { level: 8, body: "Significant figures matter: the answer must be expressed to the same number of significant figures as the measurement with fewest s.f. The cobalt(II) chloride example from the chapter shows that colour depth is a qualitative indicator of concentration — but quantitative work requires the formula. A spectrophotometer (Beer–Lambert law: A = εcl) uses absorbance to determine concentration accurately, directly linking technology to quantitative analysis of solutions." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "conc-l2",
            level: 2,
            prompt: "What are the SI units of concentration used in chemistry?",
            options: [
              { id: "a", text: "g dm⁻³" },
              { id: "b", text: "mol dm⁻³", correct: true },
              { id: "c", text: "mol cm⁻³" },
              { id: "d", text: "g L⁻¹" },
            ],
            explanation: "Concentration in chemistry is expressed as moles of solute per cubic decimetre of solution (mol dm⁻³). Note that 1 dm³ = 1 litre = 1000 cm³.",
          },
          {
            type: "fill",
            id: "conc-l4",
            level: 4,
            prompt: "8.00 g of sodium hydroxide NaOH (Mᵣ = 40.00 g mol⁻¹) is dissolved to make 0.80 dm³ of solution. The concentration of the solution is ▁ mol dm⁻³.",
            answers: ["0.25", "0.25 mol dm⁻³"],
            explanation: "Amount = 8.00 ÷ 40.00 = 0.200 mol. Concentration = 0.200 ÷ 0.80 = 0.25 mol dm⁻³.",
          },
          {
            type: "short",
            id: "conc-l6",
            level: 6,
            prompt: "Calculate the concentration, in mol dm⁻³, of a solution made by dissolving 0.45 mol of sulfuric acid H₂SO₄ in 0.75 dm³ of water. Show your working.",
            keywords: ["0.45", "0.75", "0.60", "concentration", "mol", "dm", "divide", "moles", "volume"],
            minKeywords: 3,
            sample: "Concentration = amount (mol) ÷ volume (dm³) = 0.45 ÷ 0.75 = 0.60 mol dm⁻³.",
          },
          {
            type: "short",
            id: "conc-l8",
            level: 8,
            prompt: "A student dissolves 58.80 g of sulfuric acid H₂SO₄ (Mᵣ = 98.09 g mol⁻¹) in water to make a 500 cm³ solution. Calculate the concentration in mol dm⁻³ to the correct number of significant figures. Explain why significant figures matter in this calculation.",
            keywords: ["0.5990", "1.198", "mol dm", "significant", "figures", "500", "0.500", "moles", "divide", "precision"],
            minKeywords: 3,
            sample: "Amount = 58.80 ÷ 98.09 = 0.5994 mol. Volume = 500 cm³ = 0.500 dm³. Concentration = 0.5994 ÷ 0.500 = 1.199 mol dm⁻³ (4 s.f., matching 58.80 which has 4 s.f.). Significant figures matter because they indicate the precision of the measurement — reporting extra digits would imply a level of accuracy the apparatus cannot achieve.",
          },
        ],
      },
    },
    {
      id: "titration",
      name: "Titration technique",
      descriptor: "Describe and calculate from acid–base titrations using mole ratios.",
      guided: [
        { level: 2, body: "Titration is a technique used to find the unknown concentration of a solution. A solution of known concentration (the standard solution) is added from a burette to a measured volume of the unknown solution. The equivalence point is reached when the exact same number of moles of acid and base have reacted." },
        { level: 4, body: "The four calculation steps are: (1) write the balanced equation; (2) calculate moles of the known solution using n = c × V; (3) use the mole ratio from the equation to find moles of the unknown; (4) calculate the unknown concentration = n ÷ V. In the chapter's worked example: 25.0 cm³ of 0.800 mol dm⁻³ HCl neutralises 21.5 cm³ of KOH — moles of HCl = 0.800 × 0.0250 = 0.0200 mol; mole ratio 1:1 → 0.0200 mol KOH in 0.0215 dm³ → c = 0.930 mol dm⁻³." },
        { level: 6, body: "Concordant results (within 0.10 cm³) are required for reliable titres. The rough titration identifies the approximate endpoint; subsequent titrations are precise. Phenolphthalein is the correct indicator for a weak acid (ethanoic acid) + strong base (NaOH): it changes from colourless (acid) to pink (alkali) at the equivalence point because the equivalence point pH is above 7 for this combination." },
        { level: 8, body: "The choice of indicator must match the pH at the equivalence point. Strong acid + strong base: equivalence at pH 7 → use litmus, bromothymol blue, or phenolphthalein. Weak acid + strong base: equivalence at pH > 7 → phenolphthalein is suitable; methyl orange is not. The pH probe is more accurate than indicators because it gives a continuous, precise pH reading (uncertainty ±0.01 pH units) without the ambiguity of subjective colour assessment." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "tit-l2",
            level: 2,
            prompt: "In an acid–base titration, what is the equivalence point?",
            options: [
              { id: "a", text: "When the indicator changes colour" },
              { id: "b", text: "When the exact same number of moles of acid and base have reacted", correct: true },
              { id: "c", text: "When the burette is empty" },
              { id: "d", text: "When the pH equals 7" },
            ],
            explanation: "The equivalence point is when moles of acid exactly equal moles of base (accounting for the mole ratio in the equation). For a strong acid–strong base titration this happens to be at pH 7, but not always.",
          },
          {
            type: "fill",
            id: "tit-l4",
            level: 4,
            prompt: "In the titration HCl(aq) + KOH(aq) → KCl(aq) + H₂O(l), if 25.0 cm³ of 0.800 mol dm⁻³ HCl is used, the number of moles of HCl is ▁ mol.",
            answers: ["0.0200", "0.020"],
            explanation: "n = c × V = 0.800 mol dm⁻³ × (25.0 ÷ 1000) dm³ = 0.800 × 0.0250 = 0.0200 mol.",
          },
          {
            type: "short",
            id: "tit-l6",
            level: 6,
            prompt: "A student titrates ethanoic acid CH₃COOH with 0.50 mol dm⁻³ sodium hydroxide NaOH. She finds that 22.4 cm³ of NaOH neutralises 25.0 cm³ of ethanoic acid. Calculate the concentration of the ethanoic acid. Show all steps.",
            keywords: ["0.50", "22.4", "0.0224", "0.0112", "moles", "ratio", "25.0", "0.448", "mol dm", "naoh"],
            minKeywords: 3,
            sample: "Step 1 — balanced equation: CH₃COOH + NaOH → CH₃COONa + H₂O (1:1 ratio). Step 2 — moles NaOH = 0.50 × (22.4 ÷ 1000) = 0.0112 mol. Step 3 — mole ratio 1:1, so moles CH₃COOH = 0.0112 mol. Step 4 — c = 0.0112 ÷ (25.0 ÷ 1000) = 0.0112 ÷ 0.0250 = 0.448 mol dm⁻³.",
          },
          {
            type: "short",
            id: "tit-l8",
            level: 8,
            prompt: "Explain why phenolphthalein is a suitable indicator for the titration of ethanoic acid (a weak acid) with sodium hydroxide (a strong base), but methyl orange is not. Your answer should refer to the pH at the equivalence point.",
            keywords: ["equivalence", "ph", "7", "alkaline", "weak acid", "strong base", "phenolphthalein", "methyl orange", "range", "colour", "indicator"],
            minKeywords: 4,
            sample: "For a weak acid–strong base titration, the equivalence point occurs at pH greater than 7 (approximately pH 8–9) because the salt formed (sodium ethanoate) is basic. Phenolphthalein changes colour in the pH range 8.2–10, which covers this equivalence point — it will change from colourless to pink at the right moment. Methyl orange changes colour at pH 3.1–4.4 (acidic range) — this is well before the equivalence point, giving a false early endpoint. Using the wrong indicator leads to systematic error in the calculated concentration.",
          },
        ],
      },
    },
    {
      id: "ph",
      name: "pH curves and indicators",
      descriptor: "Interpret pH curves and select appropriate indicators for acid–base titrations.",
      guided: [
        { level: 2, body: "pH is a measure of the concentration of hydrogen ions H⁺ in a solution. Acids have pH < 7; neutral solutions pH = 7; alkalis pH > 7. Indicators are chemicals that change colour depending on pH — for example, phenolphthalein is colourless in acid and pink in alkali." },
        { level: 4, body: "A pH curve (titration curve) shows how pH changes as base is added to acid. For a strong acid–strong base titration (e.g. HCl + NaOH), the curve starts at low pH (~1), rises slowly, then shows a very steep rise around the equivalence point (at pH 7). A burette has uncertainty ±0.05 cm³ in a 50 cm³ burette (0.10% uncertainty)." },
        { level: 6, body: "The shape of the pH curve depends on the strength of acid and base. For a weak acid + strong base (e.g. CH₃COOH + NaOH): the curve starts at a higher pH (~3), has a flatter buffer zone before the equivalence point, and the equivalence point is at pH > 7. The buffer zone occurs because the partially neutralised acid resists pH change. Different indicators are suited to different equivalence point pH values." },
        { level: 8, body: "A pH probe gives a continuous, precise reading (±0.01 pH units) compared with subjective indicator colour changes. From the summative assessment data (page 326): as NaOH is added to the weak acid HA, pH rises from ~2.95 to ~11.85. The steep rise occurs between 18.0 and 19.0 cm³ NaOH, giving an equivalence point near 18.5 cm³. The erroneous data point (18.0 cm³, pH 6.75 → then 18.20 cm³, pH 10.5) indicates the equivalence point was crossed abruptly — consistent with a weak acid–strong base system where the steep region is narrower than for strong–strong titrations." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "ph-l2",
            level: 2,
            prompt: "Phenolphthalein indicator is colourless in acid and turns light pink in alkali. At what pH does it change colour?",
            options: [
              { id: "a", text: "pH 3–5 (acidic range)" },
              { id: "b", text: "pH 5–7 (near neutral)" },
              { id: "c", text: "pH 8–10 (alkaline range)", correct: true },
              { id: "d", text: "pH 11–14 (strongly alkaline)" },
            ],
            explanation: "Phenolphthalein changes from colourless to light pink in the pH range 8.2–10. This makes it suitable for titrations with an equivalence point in the alkaline range, such as weak acid–strong base.",
          },
          {
            type: "fill",
            id: "ph-l4",
            level: 4,
            prompt: "In a strong acid–strong base titration, the pH at the equivalence point is ▁.",
            answers: ["7", "7.0", "pH 7"],
            explanation: "When a strong acid (fully dissociated) reacts exactly with a strong base, the resulting salt solution is neutral — pH = 7. This is because neither the cation nor anion of the salt reacts with water.",
          },
          {
            type: "short",
            id: "ph-l6",
            level: 6,
            prompt: "Describe the shape of the pH curve for the titration of hydrochloric acid (strong acid) with sodium hydroxide (strong base). Identify the equivalence point and explain what the steep section of the curve represents.",
            keywords: ["starts", "low", "ph", "steep", "equivalence", "7", "increases", "neutralisation", "moles", "equal", "rapid"],
            minKeywords: 3,
            sample: "The curve starts at a low pH (around pH 1 for a typical concentration of HCl). As NaOH is added from the burette, the pH rises slowly at first. Around the equivalence point (at pH 7), the curve shows a very steep vertical rise — a small additional drop of NaOH causes a large jump in pH. After the equivalence point the pH levels off at high values (~13). The steep section shows the transition from acid to base as the last traces of H⁺ ions are neutralised and OH⁻ ions begin to accumulate.",
          },
          {
            type: "short",
            id: "ph-l8",
            level: 8,
            prompt: "A student uses a pH probe to collect data during a weak acid–strong base titration. Explain why the pH probe is more suitable than a colour indicator for this titration, and why the equivalence point in this titration is at a pH greater than 7.",
            keywords: ["ph probe", "continuous", "precise", "indicator", "subjective", "colour", "weak acid", "strong base", "alkaline", "equivalence", "salt", "hydrolysis", "buffer"],
            minKeywords: 4,
            sample: "A pH probe gives a continuous, precise reading (±0.01 pH units) that can be logged digitally — it removes the subjectivity of judging a colour change, which is especially important when the colour transition is gradual. In a weak acid–strong base titration, the salt formed at the equivalence point (e.g. sodium ethanoate) is basic because the ethanoate ion is the conjugate base of a weak acid and undergoes partial hydrolysis in water, producing OH⁻ ions. This raises the pH above 7 at the equivalence point, making a colour indicator with an acid-range transition (like methyl orange) unsuitable.",
          },
        ],
      },
    },
    {
      id: "esters",
      name: "Carboxylic acids and esters",
      descriptor: "Name and explain the formation of carboxylic acids and esters from alcohols.",
      guided: [
        { level: 2, body: "Carboxylic acids are organic compounds with the functional group –COOH. They are formed by the oxidation of a primary alcohol using an oxidising agent such as potassium manganate(VII), KMnO₄. For example, ethanol (CH₃CH₂OH) is oxidised to ethanoic acid (CH₃COOH). The suffix changes from -ol to -oic acid." },
        { level: 4, body: "Naming carboxylic acids: the prefix is from the parent alcohol (unchanged); the suffix changes from -ol to -oic acid. Examples: propanol → propanoic acid; butanol → butanoic acid; heptanol → heptanoic acid. Esters are formed by a condensation reaction between a carboxylic acid and an alcohol, removing a water molecule. The reaction is catalysed by concentrated sulfuric acid and requires heating." },
        { level: 6, body: "Naming esters: the first part comes from the alcohol (suffix changes -ane to -yl); the second part comes from the carboxylic acid (suffix changes -oic to -oate). Example: butanoic acid + ethanol → ethyl butanoate + water; C₄H₈O₂ + C₂H₆O → C₆H₁₂O₂ + H₂O. Esters are volatile, sweet-smelling compounds — pentyl ethanoate smells of banana, ethyl butanoate of pineapple, methyl butanoate of apple, pentyl butanoate of strawberry." },
        { level: 8, body: "Structural formulae show the arrangement of atoms and bonds, revealing the connectivity (e.g. the –COO– ester linkage) rather than just the molecular formula. The ester linkage forms when the –OH of the acid combines with the –OH of the alcohol, losing H₂O (condensation). Concentrated H₂SO₄ is a catalyst — it protonates the carboxylic acid's –OH, making it a better leaving group. The reaction is reversible; the ester floats on the sodium carbonate solution used to neutralise excess acid after the reaction." },
      ],
      response: {
        kind: "questions",
        questions: [
          {
            type: "mcq",
            id: "est-l2",
            level: 2,
            prompt: "Which functional group is present in all carboxylic acids?",
            options: [
              { id: "a", text: "–OH (hydroxyl)" },
              { id: "b", text: "–CHO (aldehyde)" },
              { id: "c", text: "–COOH (carboxyl)", correct: true },
              { id: "d", text: "–COO– (ester linkage)" },
            ],
            explanation: "The –COOH carboxyl group defines carboxylic acids. It contains both a C=O and an –OH on the same carbon. All carboxylic acids have this group.",
          },
          {
            type: "fill",
            id: "est-l4",
            level: 4,
            prompt: "The ester formed by the reaction of propanoic acid with methanol is called methyl ▁.",
            answers: ["propanoate", "methyl propanoate"],
            explanation: "Ester naming: first part from alcohol (methanol → methyl), second part from acid (propanoic acid → propanoate). Together: methyl propanoate.",
          },
          {
            type: "short",
            id: "est-l6",
            level: 6,
            prompt: "Write the word equation and chemical equation for the formation of ethyl butanoate from butanoic acid and ethanol. Name the type of reaction and identify the role of concentrated sulfuric acid.",
            keywords: ["butanoic acid", "ethanol", "ethyl butanoate", "water", "condensation", "catalyst", "sulfuric acid", "c4h8o2", "c2h6o", "c6h12o2"],
            minKeywords: 4,
            sample: "Word equation: butanoic acid + ethanol → ethyl butanoate + water. Chemical equation: C₄H₈O₂ + C₂H₆O → C₆H₁₂O₂ + H₂O. This is a condensation reaction because two molecules combine and a small molecule (water) is removed. Concentrated sulfuric acid acts as a catalyst, speeding up the reaction without being consumed.",
          },
          {
            type: "short",
            id: "est-l8",
            level: 8,
            prompt: "Explain how a structural formula gives more information than a molecular formula for an ester. Use ethyl butanoate as your example, and explain why the structural formula is essential for identifying the ester linkage.",
            keywords: ["structural", "molecular", "ester linkage", "–coo–", "connectivity", "arrangement", "atoms", "bonds", "ethyl", "butanoate", "c6h12o2"],
            minKeywords: 4,
            sample: "The molecular formula C₆H₁₂O₂ for ethyl butanoate tells you only the total number of each type of atom. It does not show how the atoms are connected. The structural formula shows the –COO– ester linkage (a C=O bonded to a C–O–C), which is essential to confirm this is an ester rather than a carboxylic acid or an isomer. The structural formula also shows which part of the molecule came from the acid (butanoate, four-carbon chain with C=O) and which from the alcohol (ethyl, two-carbon chain from ethanol), explaining both the name and the mechanism of formation by condensation.",
          },
        ],
      },
    },
  ],
}
